### ISSUE TITLE
Handling wildcards in recipe for directory names (realgud)

### ISSUE THREAD

**Issue by rocky** [melpa/melpa#1602]
In the realgud package, I'll be adding another debugger for nodejs soon. (Its there right now in the nodejs branch). Rather than add this in the rather long list in recipe/realgud that has:  

``` lisp
            ("realgud/debugger/gdb"       "realgud/debugger/gdb/*.el")
            ("realgud/debugger/gub"       "realgud/debugger/gub/*.el")
            ("realgud/debugger/kshdb"     "realgud/debugger/kshdb/*.el")
```

I first tried `("realgud/debugger/*"  "realgud/*/gub/*.el")` and that doesn't work because presumably _package-build-archive_,  would need to have to notice that `*` is a wildcard and call  _package-build-package_, repeatedly.

So undaunted, my second try was to see if I could put some emacs lisp code inside _recipe/realgud_. Something like: 

``` lisp
(realgud :fetcher github :repo "rocky/emacs-dbgr"
     :files
     (append
      '("realgud.el"
        ("realgud/common"             "realgud/common/*.el")
        ("realgud/common/buffer"      "realgud/common/buffer/*.el")
        ("realgud/lang" "realgud/lang/*.el"))
      (mapcar (lambda(dir)
            (list (format "%s" dir)
              (format "%s/*.el" dir)))
          (file-expand-wildcards "realgud/debugger/*"))))
```

This gives me the error when I run 

```
EMACS=/usr/local/bin/emacs remake -x recipes/realgud
...
;;; realgud

Fetcher: github
Source: rocky/emacs-dbgr

Updating /src/external-vcs/github/melpa/working/realgud/
Wrong type argument: stringp, append
remake: [recipes/realgud] Error 255 (ignored)
```

Other than hard-coding another directory in there, any thoughts as to how to fix recipe/realgud once and for all so I don't need to issue a pull request every time a new debugger is added? 

Thanks!

**Comment by milkypostman** [comment]
for edts couldn't we just take `realgud/debuggers/*` ? i.e., the whole debuggers directory?

**Comment by rocky** [comment]
The problem was that I put Makefiles in each of the directories and it is not desired to have these in the final package.

**Comment by purcell** [comment]
Closed because the current mechanism seems fine in the vast majority of cases, and workable in the few remaining edge cases.
