### ISSUE TITLE
API for fetching download count

### ISSUE THREAD

**Issue by Malabarba** [melpa/melpa#1705]
Is there an API (or any sort of automated way) for getting the download counts displayed on the website?

I ask because I'm thinking of adding those counts to [paradox](https://github.com/Bruce-Connor/paradox/).

**Comment by ChillarAnand** [comment]
> There's also http://melpa.milkbox.net/recipes.json and http://melpa.milkbox.net/archive.json, by the way.

this is awesome. this should be documented somewhere!

**Comment by purcell** [comment]
> this is awesome. this should be documented somewhere!

It's not particularly supported - if I need to change it to help the front-end of the website, then I will do so freely. :-)
