### ISSUE TITLE
Web API - CORS support

### ISSUE THREAD

**Issue by pawelbx** [melpa/melpa#1908]
Any chance we can get CORS support for the following URL:
http://melpa.milkbox.net/download_counts.json

It would be nice if we can fetch download stats via an ajax request to the above URL. 

Two other URLs that others might find useful were mentioned here: https://github.com/milkypostman/melpa/issues/1705

**Comment by tarsius** [comment]
Given that @milkypostman offered to implement this (but then apparently didn't), and that despite this there was no follow up in nearly a decade, I take that to mean that there isn't any actual interest in this anymore.
