### ISSUE TITLE
Audit installability of MELPA Stable package dependencies

### ISSUE THREAD

**Issue by purcell** [melpa/melpa#1955]
Missing tags on upstream repos can cause broken dependencies in MELPA Stable, such that packages become uninstallable for those who use only MELPA Stable.

An example is #1954.

**Comment by Malabarba** [comment]
For what it's worth, package.el is getting the ability to detect uninstallable packages on Emacs 25.1. 
So one way to audit this installability is to just fire up emacs, add all melpa stable packages to `package-archive-contents`, and check if the package is `package--incompatible-p`. This would spare the nice Melpa maintainers from having to rewrite the functionality.

**Comment by ardumont** [comment]
org-trello is probably broken on melpa-stable since it depends on request which did not tag its latest version to 0.0.2. I opened a PR to ask for it 1 year ago https://github.com/tkf/emacs-request/issues/18 but never got a reply...
(related to #1994)

**Comment by plantarum** [comment]
Not sure if this is the same issue, but ESS depends on julia-mode, and julia-mode isn't in MELPA stable. Consequently ESS, is in stable but can't be installed from there.

**Comment by purcell** [comment]
Given modern `package.el` support for pinning and priorities of archives, I'm going to close this issue:

- It's not practical to ensure that packages will only be present in MELPA Stable if all their dependent packages are also available in MELPA Stable
- That's not necessary anyway, since pinning/priorities allows users to have both MELPA archives enabled but prefer packages from Stable if desired.
