### ISSUE TITLE
Commentaries sometimes contain the full code

### ISSUE THREAD

**Issue by purcell** [melpa/melpa#2033]
e.g. http://melpa.milkbox.net/#/clues-theme

We use `lm-commentary` to extract the commentary, and the latest version of that function (in Emacs HEAD) handles the above file contents just fine, so perhaps we need a newer Emacs on the server...

**Comment by tarsius** [comment]
I assume Melpa is using `>= 24.4` now and this can be closed?

**Comment by purcell** [comment]
We still have 24.3, I believe. Hey @milkypostman, any thoughts on `dist-upgrade`-ing the servers to a newer Ubuntu?

**Comment by purcell** [comment]
Will be resolved by #4113.

**Comment by tarsius** [comment]
Has been resolved by #4113.
