### ISSUE TITLE
elixir-yasnippets on melpa-stable returns 404

### ISSUE THREAD

**Issue by poppingtonic** [melpa/melpa#2093]
I'm trying to install `elixir-yasnippets`. I hadn't added the MELPA archive before this, so I followed the standard instructions, adding the following lines to my .emacs:

``` lisp
(require 'package)
(add-to-list 'package-archives
             '("melpa" . "http://melpa.milkbox.net/packages/") t)
(package-initialize)
```

Then:
`M-x eval-buffer`
`M-x package-refresh-contents`

I then attempted to install `elixir-yasnippets`: 
`M-x package-install elixir-yasnippets`, 
which failed. I also tried `M-x package-list-packages`, and selected `elixir-yasnippets`, but it failed with:  `Error during download request: Not Found`.

**Comment by hisea** [comment]
Sorry for the delay in response.


I've pushed a git version tag, hopefully it helps, let me know if there's anything else I need to do.

Thanks

**Comment by purcell** [comment]
Thanks @hisea. :-)
