### ISSUE TITLE
Failed to download `melpa' archive.

### ISSUE THREAD

**Issue by nevetS** [melpa/melpa#2139]
with the following line enabled in my init.el, I receive the message:
Failed to download `melpa' archive.

```
(add-to-list 'package-archives
             '("melpa" . "http://melpa.org/packages") t)
```

I can download the package list and install packages from melpa-stable.

**Comment by s-kostyaev** [comment]
I have the same issue just now.

**Comment by mfine** [comment]
@s-kostyaev seeing the same issue, too. Can't get the debugger to kick in, but have these messages:

```
Contacting host: melpa.org:80
Failed to download `melpa' archive.
```

No idea what the archive is supposed to look like - but this is showing up empty?

```
$ curl -i http://melpa.org/packages/archive-contents 
HTTP/1.1 200 OK
Server: nginx/1.4.6 (Ubuntu)
Date: Wed, 04 May 2016 06:29:09 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 0
Connection: keep-alive
Last-Modified: Wed, 04 May 2016 05:38:10 GMT
ETag: "57298ac2-0"
Accept-Ranges: bytes

```

Is that right? Compare with:

```
$ curl --silent -i http://elpa.gnu.org/packages/archive-contents | head -20
HTTP/1.1 200 OK
Date: Wed, 04 May 2016 06:37:48 GMT
Server: Apache/2.4.10 (Debian)
Last-Modified: Tue, 03 May 2016 21:03:59 GMT
ETag: "6d01-531f672b2ac6c"
Accept-Ranges: bytes
Content-Length: 27905

(1
 (ace-window .
	     [(0 9 0)
	      ((avy
		(0 2 0)))
	      "Quickly switch windows." single
	      ((:url . "https://github.com/abo-abo/ace-window")
	       (:keywords "window" "location"))])
 (ack .
      [(1 5)
       nil "interface to ack-like tools" tar
       ((:keywords "tools" "processes" "convenience")
(23) Failed writing body
```

**Comment by douglarek** [comment]
@mfine same error too

**Comment by Geod24** [comment]
I also had the same issues when I tried a couple of hours ago.
Couldn't use `melpa` but `melpa-stable` worked fine.

**Comment by eldamir** [comment]
Installed fresh Ubuntu 16.04 yesterday. Nightly build of GNU emacs 25.1.50.2 and installed emacs through the quick install (cloning repo into ~/.emacs.d).

It worked fine yesterday. Today, nothing has changed in my emacs version, the spacemacs version or anything else, but I get the error described in this thread. Something gone wrong the the melpa archive?

**Comment by eldamir** [comment]
**UPDATE**

Ran `apt-get upgrade` and found that there were patches to `libssl1.0.0` and  `openssl`.

Now it works

**Comment by douglarek** [comment]
@eldamir maybe, I upgraded openssl though homebrew today.

**Comment by mfine** [comment]
Looks like it's back up:

```
$ ➜  ~  curl -i http://melpa.org/packages/archive-contents 
HTTP/1.1 200 OK
Server: nginx/1.4.6 (Ubuntu)
Date: Wed, 04 May 2016 07:29:26 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 511433
Connection: keep-alive
Vary: Accept-Encoding
Last-Modified: Wed, 04 May 2016 07:28:47 GMT
ETag: "5729a4af-7cdc9"
Accept-Ranges: bytes


(1 (zzz-to-char . [(20160122 440) ((emacs (24 4)) (cl-lib (0 5)) (avy (0 3 0))) "Fancy version of `zap-to-char' command" single ((:url . "https://github.com/mrkkrp/zzz-to-char") (:keywords "convenience"))]) (zygospore . [(20140703 152) nil "reversible C-x 1 (delete-other-windows)" single ((:url . "https://github.com/louiskottmann/zygospore.el"))]) (ztree . [(20160127 1542) ((cl-lib (0))) "Text mode directory tree" tar ((:url . "https://github.com/fourier/ztree") (:keywords "files" "tools"))]) (zotxt . [(20160427 1922) ((request-deferred (0 2 0))) "Tools to integrate emacs with Zotero via the zotxt plugin." tar nil]) (zotelo . [(20160118 2045) ((cl-lib (0 5))) "Manage Zotero collections from emacs" single ((:url . "https://github.com/vitoshka/zotelo") (:keywords "zotero" "emacs" "reftex" "bibtex" "mozrepl" "bibliography manager"))]) (zossima . [(20121123 1635) ((inf-ruby (2 2 3))) "Ruby from Emacs" tar 
```

**Comment by milkypostman** [comment]
sorry for the downtime. the server is doing a full rebuild. i suspect that the issue with archive-contents may have been related to our server running low on disk space.

will spend some time soon working on making the maintenance more automated.

**Comment by purcell** [comment]
@milkypostman Thanks for sorting that out. Maybe we should put monit on the build servers and have it alert us when a certain threshold of disk usage is exceeded?

**Comment by lascott** [comment]
@milkypostman Same issue yesterday and today.  Any thoughts welcomed.  Thanks

**Comment by purcell** [comment]
@lascott This particular error message is generally not a problem with MELPA, but rather can result from a number of problems with your Emacs setup, most commonly with proxy settings or SSL setup (e.g. openssl version, gnutls). Please check out #3914, which is a more recent ticket about the same error message, and try some of the tests there in order to debug the issue on your machine.

**Comment by bd339** [comment]
Had this problem today in Windows 10 (...yeah, I know...) and folks having to update their ssl libraries gave me the idea of having Emacs connect to `http://melpa.org/packages/` instead of `https://melpa.org/packages/`. It works, it's of course also not ideal, but I don't know what else to do in Windows...

**Comment by achikin** [comment]
I see this right now. I'm trying to install `use-package` and following the instructions on their page. https://jwiegley.github.io/use-package/installation/
```
 Then add one of the archives to package-archives:

To use Melpa:
(require 'package)
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/") t)
To use Melpa-Stable:
(require 'package)
(add-to-list 'package-archives
             '("melpa-stable" . "https://stable.melpa.org/packages/") t)
Once you have added your preferred archive, you need to update the local package list using:

M-x package-refresh-contents RET
```

**Comment by achikin** [comment]
I'm trying to show my colleague how to set up emacs-based ide from scratch and following simple instructions from the melpa own page does not work. That's so embarrassing :(.

**Comment by milkypostman** [comment]
@achikin it would help if we knew what the error you’re seeing is.

**Comment by purcell** [comment]
@achikin You're not following *our* instructions, though. The problem is most likely that your Emacs doesn't support https, but seeing the error message would help.

**Comment by achikin** [comment]
@purcell @milkypostman you were right. I forgot `(package-initialize)`. Sorry about that.

**Comment by manojkumarlinux** [comment]
package refresh  contents

**Comment by vegvisirh2c** [comment]
> Update. I discovered the problem, and [this particular bug report](https://github.com/milkypostman/melpa/issues/268) was helpful in finding the solution. `toggle-debug-on-error` is very helpful. `http://melpa.org/packages` vs. `http://melpa.org/packages/`
> 
> It would be nice if emacs was more forgiving in this regard.
For anyone who might come across this thread because of the same error: I had the issue. In my init file it wasn't https instead of http though, that bit was missing completely , with the URL essentially being just  "://melpa.org/packages/". As soon as I prepended 'http' the error went away

**Comment by JulienPalard** [comment]
I'm hitting this, `Debugger entered--Lisp error: (file-error "https://melpa.org/packages/archive-contents" "Bad Request")`, while `curl` can get it cleanly, I don't understand why and have no idea how to debug it. I'm using `Emacs 26.1` from `emacs-nox` from `http://raspbian.raspberrypi.org/raspbian/ buster`.

**Comment by qorg11** [comment]
Same issue as above

**Comment by traumschule** [comment]
Why does gnu fail as well?

```
(package-initialize)
(require 'package)
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org") t)
```

```
Importing package-keyring.gpg...done
Contacting host: elpa.gnu.org:443
Failed to download ‘gnu’ archive.
Contacting host: melpa.orgarchive-contents:443
Package refresh done
Failed to download ‘melpa’ archive.
```

```
Debugger entered--Lisp error: (file-error "https://elpa.gnu.org/packages/archive-contents" "Bad Request")
  signal(file-error ("https://elpa.gnu.org/packages/archive-contents" "Bad Request"))
  package--download-one-archive(("gnu" . "https://elpa.gnu.org/packages/") "archive-contents" nil)
  package--download-and-read-archives(nil)
  package-refresh-contents()
  funcall-interactively(package-refresh-contents)
  call-interactively(package-refresh-contents record nil)
  command-execute(package-refresh-contents record)
  execute-extended-command(nil "package-refresh-contents" nil)
  funcall-interactively(execute-extended-command nil "package-refresh-contents" nil)
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

GNU Emacs 26.1

**Comment by dinolivanos** [comment]
I hit this problem on Rasberry Pi OS, Debian Buster. 
I did a 
`sudo apt install gnutls-bin`

and then added this to the top of my init.el file
`(setq gnutls-algorithm-priority "NORMAL:-VERS-TLS1.3")`

It fixed the issue. I followed the advice from here [https://emacs.stackexchange.com/a/51772](url)

**Comment by sshaw** [comment]
I had this problem as well and while I was not able to resolve it (😿)  some things that may help others: 

* Changing `network-security-level`'s value, see [Network Security](https://www.gnu.org/software/emacs/manual/html_node/emacs/Network-Security.html)
* Seeing if you can successfully make the request with cURL or wget with debug mode on and if so 
  * Toying around with `gnutls-algorithm-priority`'s [vast set of options](https://gnutls.org/manual/html_node/Priority-Strings.html) based on what cURL/wget successfully connected with

**Comment by ertpoi** [comment]
> Update. I discovered the problem, and [this particular bug report](https://github.com/milkypostman/melpa/issues/268) was helpful in finding the solution. `toggle-debug-on-error` is very helpful. `http://melpa.org/packages` vs. `http://melpa.org/packages/`
> 
> It would be nice if emacs was more forgiving in this regard.

Have the same issue, although using `https://melpa.org/packages/` !

**Comment by milkypostman** [comment]
@ertpoi could you provide a description of your particular problem?

**Comment by avatar-lavventura** [comment]
> I see this right now. I'm trying to install `use-package` and following the instructions on their page. https://jwiegley.github.io/use-package/installation/
> 
> ```
>  Then add one of the archives to package-archives:
> 
> To use Melpa:
> (require 'package)
> (add-to-list 'package-archives
>              '("melpa" . "https://melpa.org/packages/") t)
> To use Melpa-Stable:
> (require 'package)
> (add-to-list 'package-archives
>              '("melpa-stable" . "https://stable.melpa.org/packages/") t)
> Once you have added your preferred archive, you need to update the local package list using:
> 
> M-x package-refresh-contents RET
> ```
> 
> I can open 'https://melpa.org/packages/' and 'https://melpa.org/packages/archive-contents' in my browser.

Can I use both `melpa` and `melpa-stable`?

**Comment by artelse** [comment]
Had the same issue, removing the  trailing slash resolved it:
`(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages") t)`
