### ISSUE TITLE
ox-pandoc and org-pandoc conflict

### ISSUE THREAD

**Issue by tarsius** [melpa/melpa#2377]
Both packages provide the feature `ox-pandoc`.

/cc @kawabata @robtillotson

**Comment by tarsius** [comment]
@kawabata @robtillotson ping

**Comment by robtillotson** [comment]
I can change the feature name of mine but a quick glance tells me there are probably going to be function name overlaps which make them unusable in the same installation anyway.  Does the emacs packaging system not have a mechanism for mutually excluding conflicting packages?  (I'm not aware of one, but I'm far from an expert on the subject.)  If not, I'll remove mine, as it is not as comprehensive as the newer one.

**Comment by purcell** [comment]
> Does the emacs packaging system not have a mechanism for mutually excluding conflicting packages?

No, it doesn't. It's pretty simple-minded.

> If not, I'll remove mine, as it is not as comprehensive as the newer one.

If the newer one will suit *your* needs, then settling on a single authoritative implementation would likely be better for users.

**Comment by kawabata** [comment]
Dear Steve, Rob,

I've been considering to change all my file names and options to
"ox-pandoc-XXX" instead of "org-pandoc-XXX".  But it still conflicts
with file name "ox-pandoc.el", and as this prefix usage is unprecedented
in org world, so I was a bit hesitant.

Or, if it is O.K, I can incorporate the document options of "org-pandoc",
including the followings:

#+EPUB_STYLESHEET

Regards,

On Mon, Jan 19, 2015 at 2:21 AM, Steve Purcell <notifications@github.com>
wrote:

> Does the emacs packaging system not have a mechanism for mutually
> excluding conflicting packages?
>
> No, it doesn't. It's pretty simple-minded.
>
> If not, I'll remove mine, as it is not as comprehensive as the newer one.
>
> If the newer one will suit *your* needs, then settling on a single
> authoritative implementation would likely be better for users.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/milkypostman/melpa/issues/2377#issuecomment-70416616>.
>



-- 
---------------------------------------------------------------------
川幡 太一 (KAWABATA, Taichi) E-mail: kawabata.taichi@gmail.com

**Comment by purcell** [comment]
> Or, if it is O.K, I can incorporate the document options of "org-pandoc", including the followings: #+EPUB_STYLESHEET

That sounds like a good plan to me.

**Comment by purcell** [comment]
> Or, if it is O.K, I can incorporate the document options of "org-pandoc", including the followings: #+EPUB_STYLESHEET

@kawabata @robtillotson Did anything happen with this?

**Comment by tarsius** [comment]
ping

**Comment by kawabata** [comment]
Hello dear,

I've just updated my 'ox-pandoc' to support new formats, namely "dokuwiki"
and "haddock".

I've also supported "#+EPUB_STYLESHEET" to contain maximum compatibiity
with org-pandoc module.

Also, to be compatible with org-mode 9.0, currently under the development,
I've temporarily removed "PANDOC" export block specification.

regards,

On Mon, Nov 30, 2015 at 10:05 PM, Jonas Bernoulli <notifications@github.com>
wrote:

> ping
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/milkypostman/melpa/issues/2377#issuecomment-160622368>
> .
>



-- 
---------------------------------------------------------------------
川幡 太一 (KAWABATA, Taichi) E-mail: kawabata.taichi@gmail.com

**Comment by tarsius** [comment]
@robtillotson: now that @kawabata has made these changes, is there any reason to keep your implementation?

**Comment by tarsius** [comment]
@purcell We have waited long enough for something to happen. Can I remove `org-pandoc` now?

**Comment by purcell** [comment]
@tarsius Yes please
