### ISSUE TITLE
Packages with outdated recipes 

### ISSUE THREAD

**Issue by Malabarba** [melpa/melpa#2573]
There are a number of recipes on Melpa pointing to Github repositories which have moved. This usually happens when the author changed Github username or the repository name has changed.

This is mostly invisible to Melpa, as Github redirects you to the new location when you try to clone the old one. I only noticed because Paradox uses the Github API, and it seems the redirection does not happen through the API. I'm not saying this is a bug, I just thought I'd share this list here in case anyone cares.

If nobody cares about this, please feel free to ignore this issue.

    Tass/kwin-minor-mode
    apgwoz/ant-el
    apgwoz/mvn-el
    apgwoz/thumb-through
    apgwoz/unipoint
    bastibe/emacs-journal
    bdd/aurora-config.el
    d11wtq/fiplr
    d11wtq/grizzl
    egisatoshi/egison3
    ikame/centered-window-mode
    ikame/minimal-theme
    jasonm23/emacs-clues-theme
    jasonm23/emacs-mainline
    jasonm23/emacs-purple-haze-theme
    jasonm23/emacs-soothe-theme
    joaoxsouls/flymake-rust
    joshuarh/4clojure.el
    judevc/scheme-here
    kbkbkbkb1/emacs-dokuwiki-mode
    krick/tea-time
    lewang/helm-cmd-t
    magnars/clj-refactor.el
    punchagan/metaweblog.el
    rejeep/ansi
    rejeep/drag-stuff
    rejeep/enclose
    rejeep/html-script-src
    rejeep/ruby-end
    rejeep/ruby-tools
    rejeep/servant.el
    rejeep/wrap-region
    ricardmo/requirejs-mode
    rolando2424/angry-police-captain-el
    skeeto/emacs-http-server
    smihica/emmet
    smmcg/showcss-mode
    tarsius/magit-push-remote
    tthieman/soundcloud.el
    vitoshka/ac-math
    vitoshka/imenu-anywhere
    vitoshka/polymode

**Comment by purcell** [comment]
Great, thanks -- those are all the old URLs, presumably. Will update the recipes in due course.

**Comment by Bruce-Connor** [comment]
>  those are all the old URLs, presumably. 

Yes

**Comment by tarsius** [comment]
See https://github.com/melpa/melpa/pull/3575 which comes with fixes :-)
