### ISSUE TITLE
Per-package discussion threads

### ISSUE THREAD

**Issue by vermiculus** [melpa/melpa#2821]
According to [this line](https://github.com/milkypostman/melpa/blob/abe91ad56b0d8664f0645ed896b6d705a2b716da/html/js/melpa.js#L5), Disqus support is desired.

I'm creating this issue to track the progress of this feature.

---

This would actually be pretty neat! My only concern is that as time goes by, packages are superseded, they go unmaintained, and the comments become irrelevant in a matter of months. Are there any ideas on how to avoid or at least mitigate this?

One possibility is to have each package version have its own URL. A package entry may have a unique URL sans version, but pointing to it may redirect to the most recent version. That way, Disqus sees a new URL for each thread. Unfortunately, _this isn't a feasible option_. Most updates introduce only nominal or negligible changes: the current discussion would still be valid.

Any other ideas? (This feature needs something like App Store / Play Store reviews.)

**Comment by purcell** [comment]
> This would actually be pretty neat! My only concern is that as time goes by, packages are superseded, they go unmaintained, and the comments become irrelevant in a matter of months. Are there any ideas on how to avoid or at least mitigate this?

No action needed here, I think - that's just how internet comments work. A bigger concern would be that a lot of comments would end up being bug reports.

> One possibility is to have each package version have its own URL. A package entry may have a unique URL sans version, but pointing to it may redirect to the most recent version. That way, Disqus sees a new URL for each thread. Unfortunately, this isn't a feasible option. Most updates introduce only nominal or negligible changes: the current discussion would still be valid.

This would be particularly likely to lead to comments being used for bug reports, when really I'd prefer it if comments were about tips & tricks, or thanking the package maintainer.

Another thing to bear in mind is that packages can get renamed over time, so disqus will need to be explicitly given an ID for each page rather than allowed to infer it from the URL.

> Any other ideas? (This feature needs something like App Store / Play Store reviews.)

Yes, I would like to have simple star ratings at some point.

**Comment by vermiculus** [comment]
>> Any other ideas? (This feature needs something like App Store / Play Store reviews.)
> Yes, I would like to have simple star ratings at some point.

I was talking more about 'the comments below apply to this version only; click here to see comments for all versions'.

> This would be particularly likely to lead to comments being used for bug reports

Oh, I never thought about that… That's a problem that's going to be harder to solve.

**Comment by purcell** [comment]
Not going to do this, I think, so closing.
