### ISSUE TITLE
bzr merge used but not pull?

### ISSUE THREAD

**Issue by milkypostman** [melpa/melpa#3108]
`python-mode` keeps breaking because for some reason the files in the working directory (the repo checkout) don't merge cleanly or something; i don't know enough about bzr to know why. anyways, in the code we use `merge` instead of `pull`. the former doesn't work but the latter does.

40f0e5ee was the commit where this was actually added. @bbatsov looks like you added bzr support. any ideas?

**Comment by purcell** [comment]
@bbatsov ping! :-)

**Comment by bbatsov** [comment]
I honestly don't remember anything about the code I wrote. :-) It was a long time ago and never revisited it afterwards...

**Comment by purcell** [comment]
:-) I guess the question is -- are you familiar enough with `bzr` that you have any opinion on `pull` vs `merge` etc. in this case?

**Comment by tarsius** [comment]
`bzr` is no longer supported.
