### ISSUE TITLE
Unclear how to handle generated files

### ISSUE THREAD

**Issue by udalrich** [melpa/melpa#3203]
I have a package that I would like to contribute to MELPA, which has a build which generates new .el files.  I have tried several ways to get this to work, but have had no success.  There are many details at http://stackoverflow.com/questions/32930303/creating-a-package-for-melpa-where-some-files-are-generated.

Is there a good process for this use case?

**Comment by purcell** [comment]
If you just say `:files (:defaults "generated/*.el")`, then both `*.el` and `generated/*.el` will be copied to the root of the resulting package, and therefore all be on the `load-path` together. Does that answer the question.

Let me know if that helps. :-)

**Comment by milkypostman** [comment]
@udalrich based on your post I can confirm that we don't let packages run arbitrary "build" procedures. So if you want some code that is "generated" from the repo that's not possible. it would be worthwile to know more about your use-case to understand why you need this generation. you can some some of this problem i THINK by using git hooks.

**Comment by purcell** [comment]
Didn't hear back, so closing this.
