### ISSUE TITLE
Travis build sometimes builds too many recipes

### ISSUE THREAD

**Issue by purcell** [melpa/melpa#3214]
We're building all the recipes included in `$TRAVIS_COMMIT_RANGE`, but this range sometimes seems too large, perhaps due to people submitting PRs from forks in which their "master" is a long way behind ours. We should figure out how to trim this down to a smaller range, perhaps using the other `$TRAVIS*` vars, because it can lead to spurious build failures, as recently in the case of `helm-flx` (IIRC).

http://docs.travis-ci.com/user/environment-variables/

**Comment by vyp** [comment]
Ref #3202 (helm-flx).

**Comment by purcell** [comment]
Thanks @vyp

**Comment by purcell** [comment]
(I should add that I'm not actually sure whether this can be done using a commit range in the case of pull requests - only by comparing with our current `master` can we reliably determine which recipes have been modified.)

**Comment by purcell** [comment]
Going to assume this is fixed by my changes, and will reopen later if not.
