### ISSUE TITLE
Migrating MELPA to organization and separating packages.

### ISSUE THREAD

**Issue by milkypostman** [melpa/melpa#3570]
Two things we want to do,
1. move the MELPA repo to the MELPA organization.
2. separate recipes from the `package-build` package.

What will we do with the recipes? Will they live in the root of the repo? I think this is what we need so that  we can checkout the `package-build.el` package (which includes the scripts) then the recipe repo will be checked out to `./recipes`.

The only other downside is that we need to get the Travis system setup for the recipes repo. That will need to checkout package-build I guess.

For the first step I think I will just move the repo over.

**Comment by milkypostman** [comment]
1edd038

**Comment by milkypostman** [comment]
welcome to the new org, we will have to rename these repos at some point I think, but I don't have time to do the split right now, it'll take a bit more time.

**Comment by purcell** [comment]
I don't think there's any need to split things up further, or move things around inside the repo. Let's just extract `package-build.el` to the root of a separate repo using Jonas' script, and switch `recipes/package-build` to point at that instead. We'd then need to ensure that the build scripts install the latest version of `package-build` when starting up.

**Comment by purcell** [comment]
There'll be some sort of update necessary for travis too, right?

**Comment by purcell** [comment]
Actually, Travis seems to still be working.

**Comment by tarsius** [comment]
> Let's just extract package-build.el to the root of a separate repo using Jonas' script, and switch recipes/package-build to point at that instead.

Is there a reason why you cannot just do so now? ;-)

> We'd then need to ensure that the build scripts install the latest version of package-build when starting up.

I guess something could go wrong here, but if it did then that would be noticed very quickly and would probably be easy to fix, right?

This should be fairly easy to do for you wouldn't it? I could give it a try to, but that would take longer and come with a greater risk of getting it wrong, since I am not familiar with the build scripts.

**Comment by tarsius** [comment]
We've done that.
