### ISSUE TITLE
Errors When Installing Sly

### ISSUE THREAD

**Issue by noctuid** [melpa/melpa#3573]
I was testing a package that depends on sly and noticed that I get errors when trying to install sly in the sandbox:
```
sly-fancy.el:3:21:Error: Cannot open load file: No such file or directory, sly-mrepl
...
sly-fontifying-fu.el:3:1:Error: Cannot open load file: No such file or directory, sly-autodoc
...
sly-indentation.el:2:1:Error: Cannot open load file: No such file or directory, sly-cl-indent
```
I don't know what is causing them. For example, `sly-autodoc.el` and `sly-cl-ident.el` had already compiled successfully before the second and third error. `sly-mrepl.el` compiles successfully after these errors, but `(require 'sly-mrepl)` still fails with the same message.

**Comment by purcell** [comment]
No idea, sorry. Have you asked @capitaomorte?

**Comment by capitaomorte** [comment]
@noctuid can you share the branch of the melpa repo where you're trying to add `sly-repl-ansi-color`? I'd like to debug this error myself.

Anyway, it might help to have a look at the recipes and repos for "sly-hello-world" which is a template for writing SLY contribs. It is already added to MELPA and pulls in SLY cleanly, afaik.

You can find `sly-hello-world` at https://github.com/capitaomorte/sly-hello-world. 

You can also see `sly-macrostep` for a similar contrib which is actually useful. It's also MELPA-ized.

**Comment by noctuid** [comment]
> Anyway, it might help to have a look at the recipes and repos for "sly-hello-world" which is a template for writing SLY contribs. 

Sly gives these errors even when I install it only by itself, so there is no relation to the `sly-repl-ansi-color` package. This also happens to me if I try to install sly with quelpa in regular emacs (not the sandbox). Is this only happening for me?

If you want to look at the package though, it's [here](https://github.com/noctuid/melpa/tree/sly-repl-ansi-color) (currently 24 commits behind the master branch).

**Comment by capitaomorte** [comment]
I've seen it. See the new issue https://github.com/capitaomorte/sly/issues/79 and perhaps close this one. 

Nevertheless, these errors and warnings shouldn't be problematic to what you're trying to achieve: SLY is installed perfectly fine even after all that noise.

**Comment by purcell** [comment]
I'll go ahead and close this because I don't think it's specific to MELPA.
