### ISSUE TITLE
clj-refactor missing dependencies

### ISSUE THREAD

**Issue by izahn** [melpa/melpa#3581]
The `clj-refactor` package depends on `s` , `dash` , `yasnippet`, `paredit`, `multiple-cursors` , `cider`, `edn`, `inflections` and `hydra`[1], but these are not listed as dependencies on MELPA. I don't understand how MELPA works well enough to submit a pull request, but I'm hoping someone who knows more than me can take a look at it. 

[1] https://github.com/clojure-emacs/clj-refactor.el/blob/ba7cc8cd199346497786c37c35e1d1c525fb8ab3/clj-refactor.el#L11
[2] http://melpa.org/#/clj-refactor

**Comment by izahn** [comment]
Maybe I reported in the wrong place -- there is already an open issue at https://github.com/clojure-emacs/clj-refactor.el/issues/291. Let me know if I should close this.

**Comment by Malabarba** [comment]
I think this is the right place. At least, I had a quick look at clj-refactor dependency list and I couldn't find anything wrong with it.

**Comment by purcell** [comment]
Seems like this has been addressed upstream. MELPA is parsing out the correct dependencies, and there's no MELPA-related reason why `package.el` wouldn't install them.

**Comment by benedekfazekas** [comment]
Yup was a problem in clj-refactor. Sry for the inconvenience

**Comment by Malabarba** [comment]
I see. `-cvs` works fine for me, but I guess it must be more recent than 24.5.

**Comment by purcell** [comment]
@Malabarba I might be misunderstanding, but I'm pretty sure `-cvs` has been supported in the emacs version parsing code for much longer.

**Comment by Malabarba** [comment]
Then I'm still unsure what broke deps. :-(
