### ISSUE TITLE
Where did pov-mode go?

### ISSUE THREAD

**Issue by pstray** [melpa/melpa#3583]
I'm pretty sure i installed pov-mode through melpa last summer... now I can't find it. What happened to it?

**Comment by dunn** [comment]
Removed in https://github.com/melpa/melpa/commit/ec97372ea6af02627811cd331188ba7fcd3fd60d; for which see https://github.com/melpa/melpa/issues/2947.

**Comment by pstray** [comment]
Seems to be clonable... just did:

>git clone https://gitorious.org/pov-mode/pov-mode.git
Cloning into 'pov-mode'...
remote: Counting objects: 99, done.
remote: Compressing objects: 100% (52/52), done.
remote: Total 99 (delta 46), reused 99 (delta 46)
Unpacking objects: 100% (99/99), done.
Checking connectivity... done.

**Comment by pstray** [comment]
or, the same guys repo at github: https://github.com/melmothx/pov-mode

**Comment by purcell** [comment]
Cool. Want to submit a fresh recipe?

**Comment by pstray** [comment]
Can try i guess :)

On Thu, Feb 11, 2016 at 8:58 AM, Steve Purcell <notifications@github.com>
wrote:

> Cool. Want to submit a fresh recipe?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/melpa/melpa/issues/3583#issuecomment-182755337>.
>



-- 
  Peder Stray

**Comment by purcell** [comment]
@pstray Thanks for your help. :-)
