### ISSUE TITLE
Support Wisent/Semantic grammar WY files

### ISSUE THREAD

**Issue by gracjan** [melpa/melpa#3591]
In https://github.com/gracjan/haskell-mode/tree/pr-semantic-support  there is a file `haskell.wy` that, when compiled, produces `haskell-wy.el`.

Now as I understand `haskell-wy.el` should not be included in git repo because it is build result artifact. Meanwhile package downloaded from MELPA should have this file included.

How to make MELPA include this output file when it is not in the repo? Is there a way to create a build step at installation time?

Wisent is elisp equivalent of bison parser generator.

**Comment by purcell** [comment]
There's no way to do this currently, and we don't really plan to support any server-side build steps or generation of files beyond the current limited support for texinfo. So the solution for now would be to commit `haskell-wy.el` to the `haskell-mode` repo.

**Comment by gracjan** [comment]
Okay, understood. I'll try out the following:
1. Implement a mechanism to parse `haskell.wy` on the fly when module is loaded.
2. If that fail then commit `haskell-wy.el` to git repo.

**Comment by purcell** [comment]
Yeah, you'd probably also want to byte-compile the resulting file for performance reasons, so probably the second option would be better, because every .el file in the package will automatically be byte-compiled at installation time.
