### ISSUE TITLE
EMMS emma-print-metadata shim program not included in recipe

### ISSUE THREAD

**Issue by wlad** [melpa/melpa#3605]
emma-print-metadata (small C program part of emms) is currently needed for proper integration with TagLib (see e.g. http://hack.org/mc/writings/mac-survival.html) it should be part of the recipe.

**Comment by purcell** [comment]
We can't compile programs on our server for inclusion in packages, so while we could include the `emms-print-metadata.c` file, that wouldn't help you much without the `Makefile`. But I see there's also an `emms-print-metadata.pl` -- hey @jorgenschaefer, does that do the same job? And if so, might it make sense to have `emms-info-taglib.el` default to using a bundled `emms-print-metadata.pl` if no better choice can be found in `exec-path`?

**Comment by jorgenschaefer** [comment]
Hi! I'm afraid I haven't had anything to do with emms for … I think well over a decade now, so I can't help you there. :-(

**Comment by purcell** [comment]
Thanks anyway Jorgen. So @wlad, maybe you can find out for us whether bundling the perl script would be enough for this use case?

**Comment by wlad** [comment]
Ok. Will see what I can do

**Comment by zakame** [comment]
On a related note, [pdf-tools][melpa] just includes the files to make `epdfinfo` on the user for building later (it prompts upon install of the package,) so I don't think it should be a problem for emms to do the same.

[melpa]: https://github.com/melpa/melpa/blob/master/recipes/pdf-tools

**Comment by zakame** [comment]
I realize pdf-tools has `(pdf-tools-install)` which builds its C component.  Perhaps a similar approach can be done for emms here?

**Comment by tarsius** [comment]
@wlad Any progress on this?

**Comment by tarsius** [comment]
Closing. This is upstream's issue at this point.
