### ISSUE TITLE
Adding and removing more debuggers to realgud

### ISSUE THREAD

**Issue by rocky** [melpa/melpa#3635]
In the melpa package [realgud](https://github.com/rocky/emacs-dbgr),  I have removed some older debuggers and put them [in another repo](https://github.com/rocky/realgud-old-debuggers) while adding contributed support for the `ipdb` debugger. 

This however is currently done in a couple of branches so as not to disturb MELPA just now. 

Since I use Makefiles (and yes, eventually I'll ditch them), this causes havoc for Melpa, since you don't want to include that. So I think we still need to coordinate my merging that branch &mdash; here it would be the `ipdb` branch &mdash; with something that has to go on in mepa, right?

**Comment by purcell** [comment]
Sure. It's not an exact science. I'm not clear on exactly what you've changed, or what the failure case would be. Maybe just submit a PR with the recipe changes, and warn us not to immediately merge it, then we'll try to coordinate your merge with you? Or just merge your branch and send an updated recipe -- I doubt it's going to cause much chaos, and we're pretty prompt at merging trivial recipe changes.

**Comment by rocky** [comment]
Thanks for the suggests and help (which begets more - sigh.)

I have merged in the branches in realgud now. 

I can't seem to fork melpa. Perhaps because I deleted it previously? However I have created a new repository cloned from the current melpa: https://github.com/rocky/melpa

In that you'll find branches for the removed code [`realgud-update`](http://github.com/rocky/realgud-update) as well previously-created git repositories for new debuggers maintained outside of this already too large code base. 

Specifically: 

* `master` - should match what is in melpa now
* [`realgud-byebug`](http://github.com/rocky/realgud-byebug)
* [`realgud-debugger2`](http://github.com/rocky/realgud-debugger2)
* [`realgud-old-debuggers`](http://github.com/rocky/realgud-old-debuggers)
* [`realgud-pry`](http://github.com/rocky/realgud-old-debuggers)

**Comment by purcell** [comment]
Okay, ideally you'd combine all those recipe commits into a single PR or branch. The various recipes aren't quite valid yet, though: they all declare the name `realgud` internally, where the name should instead match the containing filename.

**Comment by rocky** [comment]
All of the commits have been combined into the master branch in https://github.com/rocky/melpa . 
There was a typo in the filename for `realgud-old-debuggers`. If there is anything else or more mistakes let me know.

**Comment by purcell** [comment]
Could you please file a PR against this repo? I'd have to go spelunking in your repo to track everything down the relevant commits otherwise and I'm unlikely to get to that in a hurry, sorry. Plus, a PR will trigger our travis build and the associated sanity checks.

**Comment by rocky** [comment]
@purcell Sorry, I tried to explain why can't file a pull request:

> I can't seem to fork melpa. Perhaps because I deleted it previously? 

From the github interface, I don't see how to do this. There may be a command-line way or REST API way, but on the other hand it might fall into the same problems. I've made you a collaborator on https://github.com/rocky/melpa .  Of course if I were a collaborator on melpa/melpa I'd see how to do this easily.

**Comment by purcell** [comment]
Github doesn't recognise your repo as a fork for some reason, which is why it isn't helping either of us file pull requests - it's not a matter of collaborator rights. :-/

**Comment by vyp** [comment]
@rocky I guess you have already tried this, but you should be able to fork by clicking the "Fork" button on the upper right of the page. Even if you already have a repository called "melpa", it should still work and fork to a repository called "melpa-1" (or something like that), or "melpa-2" if melpa-1 already exists, and so on.

**Comment by rocky** [comment]
@vyp that works! Pull request https://github.com/melpa/melpa/pull/3647 has now been created.

**Comment by rocky** [comment]
Sigh. The build fails, but the [build fails](https://travis-ci.org/melpa/melpa/builds/112841499):

```
  Scenario: read recipes
    Given read recipes
      Recipe 'realgud-byebug' contains mismatched package name 'realgud'
2 scenarios (1 failed, 1 passed)
```
It is not clear to me what what is wrong:

```
(realgud :fetcher github :repo "rocky/realgud-byebug"
	 :files ("realgud-byebug.el"
		 ("byebug" "byebug/*.el")))
```

**Comment by vyp** [comment]
@rocky The `recipes/realgud-byebug` filename in pull request #3647 does not match the package name `realgud`. The package name here is the first item in the recipe (i.e. just before the `:fetcher` part), which in this case is `realgud`. So to be clear, the filename of the recipe is `realgud-byebug`, whereas the package name in the recipe is `realgud`, but they have to be the same.

So basically, the `realgud-byebug` recipe should have the package name `realgud-byebug` instead of just `realgud`. Also, the `realgud-debugger2` recipe should have the package name `realgud-debugger2` instead of just `realgud`, and so on for `realgud-old-debuggers` and `realgud-pry`.

**Comment by purcell** [comment]
^ Yep, and thanks for your help @vyp
