### ISSUE TITLE
"Contributing" section of README could be a CONTRIBUTING.md file

### ISSUE THREAD

**Issue by tomjakubowski** [melpa/melpa#3639]
Adding a CONTRIBUTING.md file has a couple nice perks: the file is linked to on the issue and pull request creation forms.  The README can still link to the CONTRIBUTING.md, or the Contributing section could simply inline the contents of that file, of course.

See https://github.com/blog/1184-contributing-guidelines

**Comment by purcell** [comment]
Yep, that makes sense. Would you consider creating a PR for that, such that the README would have a `Contributing` heading which would refer people to the `CONTRIBUTING.md` doc?
