### ISSUE TITLE
installation error: fail to download 'melpa' archive. 

### ISSUE THREAD

**Issue by galactica147** [melpa/melpa#3650]
I have something like this in my .emacs:

```
(setq package-archives '(("gnu" . "http://elpa.gnu.org/packages/")
                     ("marmalade" . "http://marmalade-repo.org/packages/")
                     ("melpa" . "http://melpa.org/packages/")))
(package-initialize) ;; You might already have this line

```
When I did `M-x package-refresh-contexts`, i got the following error:

> Failed to download `melpa' archive. 

I'm using Emacs 24.5.1 in the -nw mode.
How to fix this?

**Comment by purcell** [comment]
Sounds like a network error, or missing proxy configuration if you are somewhere a proxy is required in order to reach the internet. See if other programs on your computer can access the URL http://melpa.org/packages/archive-contents.

**Comment by galactica147** [comment]
my web browser has no problems visiting this URL, and I'm doing this within a company network.

**Comment by purcell** [comment]
Maybe retry in Emacs? I don't think there's anything specific I can suggest otherwise, since the above works for me, and the underlying URL also works for you.

**Comment by ikirill** [comment]
Can you check whether emacs _itself_ can successfully visit the URL, with, e.g.,

    (browse-url-emacs "https://melpa.org/packages/archive-contents" t)

With emacs compiled from git head, it actually gives me an error right now, `(wrong-type-argument number-or-marker-p nil)` inside `url-http-options`, and `package-refresh-contexts` gives me the same error.

**Comment by galactica147** [comment]
yeah, visiting that url from emacs seems fine now. i'm not sure if my previous attempt via VPN caused the access trouble. But now it's working.

**Comment by purcell** [comment]
Okay, thanks for following up.
