### ISSUE TITLE
cannot connect melpa.org?

### ISSUE THREAD

**Issue by zhizunbao84** [melpa/melpa#3678]
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))
and it tells:
connection to `melpa.org'...failed

Failed to download `melpa' archive

what's wrong?

**Comment by purcell** [comment]
Probably you have a network connectivity problem, perhaps proxy-related. You might also have no support for `https` URLs in your Emacs: it's a compile-time option on some platforms. Try changing `https` to `http`.

**Comment by DarrinC** [comment]
I have a similar issue.  My IT people told me they can whitelist its user-agent, where in the code is the user-agent set and what is it?  I can open a new issue for this if you'd like.  Thanks.

**Comment by DarrinC** [comment]
Update:  I found this, it mentions the user-agent: https://github.com/melpa/melpa/issues/3493
"Collect stats on popularity of different Emacsen #3493"

**Comment by DarrinC** [comment]
Found solution in emacs code:
$ git diff lisp/url/url-http.el
diff --git a/lisp/url/url-http.el b/lisp/url/url-http.el
index 680097a..33fe9e1 100644
--- a/lisp/url/url-http.el
+++ b/lisp/url/url-http.el
@@ -215,7 +215,7 @@ request.")
       ""
     (format "User-Agent: %sURL/%s\r\n"
            (if url-package-name
-               (concat url-package-name "/" url-package-version " ")
+               (concat "IT-aproved-string:" url-package-name "/" url-package-version " ")
              "")
            url-version)))

**Comment by zhizunbao84** [comment]
@purcell i am confused.because that:
1. i can visit https://melpa.org in my browser, so i don't have a network connectivity problem?
2. i find a mirror of melpa, which is https://github.com/aborn/popkit-elpa. and i set it like this:
      (add-to-list 'package-archives
            '("popkit" . "http://elpa.popkit.org/packages/"))
    but i still cannot connect it, it tells:
               Contacting host: elpa.popkit.org:80
               Failed to download `popkit' archive.

**Comment by zhizunbao84** [comment]
@DarrinC it works ok for you now?

**Comment by DarrinC** [comment]
@zhizunbao84 
Yes: the best place to set the user agent seems to be in emacs, this is the solution I found that works in my network (behind restrictive web proxy).

**Comment by zhizunbao84** [comment]
@purcell @DarrinC now it seems work ok for me, after i chang https to http.

**Comment by purcell** [comment]
Great

**Comment by rpgoldman** [comment]
Um, isn't changing https to http a terrible idea, because it opens you up to man in the middle attacks?

**Comment by milkypostman** [comment]
If someone is in the middle of your connection they can do whatever they want so it’s not about that. It’s more about sniffing of network traffic and also injection. Although I am not too worried about that because if you can inject fake packets probably you’re in the middle. 

Although I’m not a security expert.

**Comment by rpgoldman** [comment]
They actually don't need to get in the middle of your connection. They just need to poison your DNS lookup, which is much easier than it sounds.  So you don't have to inject fake packets, all you have to do is to impersonate `melpa.org`, which means all you need to do is to get someone in a chain of DNS cachers to get a bad entry.  Seriously, this isn't a "movie threat"; it's a real threat, and everybody should shun http in favor of https, most of the time.

**Comment by milkypostman** [comment]
Ok fair enough. I am not advocating for non https but I also don’t know how to solve the problem.

**Comment by hraban** [comment]
> If someone is in the middle of your connection they can do whatever they want so it’s not about that. It’s more about sniffing of network traffic and also injection. Although I am not too worried about that because if you can inject fake packets probably you’re in the middle.

That is the case for self-signed certificates only.

Full HTTPS with a valid certificated signed by a Certificate Authority (like melpa.org has) protects even against man-in-the-middle attacks.

It definitely is advisable only to connect to MELPA over HTTPS.
