### ISSUE TITLE
sourcegraph missing

### ISSUE THREAD

**Issue by milkypostman** [melpa/melpa#3693]
@samertm any idea why https://github.com/sourcegraph/emacs-sourcegraph-mode is now missing?

**Comment by samertm** [comment]
Not sure, I'm not at the company anymore. Ping @sqs

**Comment by beyang** [comment]
Hi @milkypostman. We made some changes to our backend that would break the plugin, so we decided to make it private for now as we finish those changes that will let us make the plugin better in the future (with things like global usage examples). It was an oversight to leave a reference in melpa, though. I can submit a PR to remove it for now.

**Comment by milkypostman** [comment]
thanks for doing that!
