### ISSUE TITLE
Notifications of new depending packages

### ISSUE THREAD

**Issue by cpitclaudel** [melpa/melpa#3710]
Hey there,

This is a low-priority feature request; it would be awesome for package authors to get notifications if a new package is created that depends on them. For example if a new Flycheck extension is created, I'd love to hear about it.

It's not obvious how complex this would be to set up, but I thought I'd write that suggestion down :)

Cheers,
Clément.

**Comment by purcell** [comment]
Yep, no idea how we'd accomplish that. :-)

**Comment by tarsius** [comment]
This is highly unlikely to ever get implemented. Closing.
