### ISSUE TITLE
"No description available" for cmake-mode

### ISSUE THREAD

**Issue by mcandre** [melpa/melpa#3711]
The cmake-mode package does have a description listed when I view its specific page. However, when cmake-mode is listed in the search results page, MELPA fails to find its description.

**Comment by purcell** [comment]
That's the commentary text, not the package description -- the two pieces of information are parsed out of the source code by different functions provided by Emacs.

`cmake-mode.el` is missing the standard metadata headers, which are required to pase the package description, and our failsafe code to work around this didn't fully handle this file. Our workaround is fixed now, and should resolve itself when the package next builds.
