### ISSUE TITLE
Timeline of downloads?

### ISSUE THREAD

**Issue by cpitclaudel** [melpa/melpa#3715]
Hey there,

It would be really convenient to get a timeline of downloads, instead of a single count; of course it's feasible to get such a thing today by sampling the website every day, but that seems a bit inconvenient. Maybe MELPA could provide this directly instead? That is, a package's page would have a curve of daily downloads, instead of a single count.

Thanks!

**Comment by purcell** [comment]
Yep, this is already described in #2416. :-)

**Comment by cpitclaudel** [comment]
Woops, thanks!
