### ISSUE TITLE
https://melpa.org/packages redirect downgrades to non-tls

### ISSUE THREAD

**Issue by jbusk** [melpa/melpa#3717]
Not really sure where to file operations related bugs, so whatever.

There's a 301 redirect from /packages that downgrades the https connection to http. Verifiably repeatable for me from several different IP addresses and operating systems (windows 8.1, windows server 2012R2; debian 8, debian 9, ubuntu 14.04, freebsd10). E.g. this curl output shows the problem:

```
$ curl -I https://melpa.org/packages
HTTP/1.1 301 Moved Permanently
Server: nginx/1.4.6 (Ubuntu)
Date: Tue, 29 Mar 2016 10:19:41 GMT
Content-Type: text/html
Content-Length: 178
Connection: keep-alive
Location: http://melpa.org/packages/
```

Others in \#emacs haven't been able to repeat it (getting 200 OK instead of 301 Moved Permanently).

Also, please consider implementing HSTS. ;)

**Comment by purcell** [comment]
Yep, can confirm, and it would make sense to fix this. I _think_ @milkypostman would need to do it. I agree re. HSTS: while we want to continue to support HTTP, any client that successfully makes HTTPS requests should indeed be instructed to strongly prefer that method.

**Comment by Bost** [comment]
FYI when opening e.g. https://melpa.org/packages/zenburn-theme-20160327.520.el by latest google-chrome 49.0.2623.110 (64-bit) I get in the console:

```
Mixed Content: The page at 'https://melpa.org/packages/zenburn-theme-20160327.520.el' was loaded over HTTPS, but requested an insecure font 'http://themes.googleusercontent.com/static/fonts/rosarivo/v1/OGdIq-p0tOtBN2VMVvO9W_esZW2xOQ-xsNqO47m55DA.woff'. This request has been blocked; the content must be served over HTTPS.
```

Firefox shows nothing.

What is triggering the woff-font download??? Where does it come from???
I downloaded the el-file via wget and found no woff reference at all! :-(

**Comment by Bost** [comment]
Oh, BTW I'm getting both 200 OK and 301 Moved Permanently:

```bash
$ curl -I https://melpa.org/packages
HTTP/1.1 200 Connection established

HTTP/1.1 301 Moved Permanently
Server: nginx/1.4.6 (Ubuntu)
Date: Wed, 30 Mar 2016 12:15:21 GMT
Content-Type: text/html
Content-Length: 178
Connection: keep-alive
Location: http://melpa.org/packages/
```

**Comment by milkypostman** [comment]
I'll have a look tonight. See what's going on here.

**Comment by milkypostman** [comment]
OK, Fixed the redirect issue.

@Bost i can't repro the font thing but maybe my other fix worked.

**Comment by milkypostman** [comment]
05896bf is the fix.

**Comment by purcell** [comment]
I'm going to guess that's a Chrome extension you've got installed. We
don't use and web fonts, and you certainly shouldn't end up with any
requests for such content if you hit a URL like that which serves raw
elisp.

**Comment by Bost** [comment]
I'm still getting:
```bash
$ curl -I https://melpa.org/packages                                                                                                                                                2016-03-31 15:59:57 
HTTP/1.1 200 Connection established

HTTP/1.1 301 Moved Permanently
Server: nginx/1.4.6 (Ubuntu)
Date: Thu, 31 Mar 2016 14:27:14 GMT
Content-Type: text/html
Content-Length: 178
Connection: keep-alive
Location: https://melpa.org/packages/
```
Except that, at the moment:
```elisp
(setq package-archives '(
                         ;; ...
                         ("melpa" . "http://melpa.org/packages/")))
```
leads to "6 packages marked for upgrading." whereas https://... leads to "No operations specified." (i.e. nothing to upgrade)

**Comment by Bost** [comment]
@purcell @milkypostman concerning the woff font problem - it was triggered by the "Read Mode" https://goo.gl/3zlzJH Chrome extention. Thanx for the hint!
