### ISSUE TITLE
Reupload fasm-mode

### ISSUE THREAD

**Issue by mcandre** [melpa/melpa#3729]
Ouch, fasm-mode seems to have disappeared from MELPA.

**Comment by purcell** [comment]
The author preferred to withdraw it, suggesting nasm-mode instead. See #3263.

**Comment by mcandre** [comment]
would nasm-mode handle fasm files correctly?

**Comment by purcell** [comment]
No idea, sorry, but that's what the author suggests in the issue I linked to above.

**Comment by jcs090218** [comment]
This is another one https://github.com/the-little-language-designer/fasm-mode. Maybe more maintained? 🤔
