### ISSUE TITLE
https://www.melpa.org/ presents a semi-valid certificate

### ISSUE THREAD

**Issue by manandbytes** [melpa/melpa#3765]
When visiting either https://www.melpa.org/ or https://www.stable.melpa.org/, Firefox warns user that 

    The owner of www.melpa.org has configured their website improperly. To protect your information from being stolen, Firefox has not connected to this website.

    www.melpa.org uses an invalid security certificate. The certificate is only valid for the following names: stable.melpa.org, melpa.org

There are three options here, www.melpa.org and www.stable.melpa.org should:
- stop responding on www.* addresses
- HTTP 301 to melpa.org and stable.melpa.org
- change HTTPS certificate to cover www.melpa.org and www.stable.melpa.org

**Comment by purcell** [comment]
Thanks for getting in touch.

We don't really intend to support that server name, and you've hit a wildcard DNS entry here, all of which point at the same server. We don't have an expensive wildcard SSL, so this error will always be possible, e.g. on https://foo.melpa.org/.

> HTTP 301 to melpa.org and stable.melpa.org

That doesn't solve the problem if the initial 301 is requested over HTTPS and is served with an invalid cert. We're probably already doing the redirect.

So I'd imagine this will be a "won't fix", but I'll leave @milkypostman to confirm.

In all likeli

**Comment by manandbytes** [comment]
> We don't really intend to support that server name.

What's the purpose of having wildcard DNS records then?

> so this error will always be possible

Yes, but only until
a) a wildcard DNS record(s) are here
b) the server melpa.org responds to www.melpa.org requests.

Just stop responding to requests to www. names, no?

**Comment by purcell** [comment]
> What's the purpose of having wildcard DNS records then?

Ease of maintenance, but yes, not particularly helpful in this case.

>     so this error will always be possible
> 
> Yes, but only until
> a) a wildcard DNS record(s) are here
> b) the server melpa.org responds to www.melpa.org requests.
> 
> Just stop responding to requests to www. names, no?

No. If there's any DNS name resolving to that server, then if someone connects to it over HTTPS, the presented certificate must match. So option b alone won't work, and if we remove the DNS entry then that's a complete fix. But not sure if it'll be a high priority for @milkypostman to update this, because of the general ease of maintenance cited above.

**Comment by manandbytes** [comment]
>> Just stop responding to requests to www. names, no?

> No. If there's any DNS name resolving to that server, then if someone connects to it over HTTPS, the presented certificate must match.

Seems I have hard times expressing my idea :smile:

Do not reply to requests sent to www.melpa.org via HTTPS. In other words, server that listens for HTTPS connections on melpa.org should not reply if the client requests resource from www.elpa.org.

Anyway, I've updated EFForg/https-everywhere#4613 to redirect https://www.melpa.org to https://melpa.org to make it pass tests.

**Comment by manandbytes** [comment]
> Do not reply to requests sent to www.melpa.org via HTTPS. In other words, server that listens for HTTPS connections on melpa.org should not reply if the client requests resource from www.elpa.org.

Please disregard, I need some :sleeping: All this certificate stuff happens before request reaches HTTP server.

**Comment by milkypostman** [comment]
i'll get this hooked up sometime just not tonight.

**Comment by Fahrradflucht** [comment]
This should really be resolved given the fact that the first hit on Duckduckgo resolves to https://www.melpa.org which then presents the invalid cert.

I see that melpa uses lets encrypt anyway. Why not just get a second cert for the www?

**Comment by purcell** [comment]
@Fahrradflucht Yep, done.
