### ISSUE TITLE
Something preventing bitbucket update

### ISSUE THREAD

**Issue by justbur** [melpa/melpa#3788]
Not sure if this is a version number issue. The next paragraph suggests it might not be. The last non-merge commit on the evil repo right now has date 20160411.918 but this is before the current version of evil on melpa (20160416.119). Something is preventing melpa from building a new package, which I've been waiting on for a few days now. 

I'm not sure if this is specific to hg, but it seems that if I run [this log command](https://github.com/melpa/melpa/blob/master/package-build.el#L668) without the file list I get the date of the last commit (which is a merge), but if I run the full command as it is here I get the grandparent commit. I'm not familiar enough with hg to explain the inconsistency.

UPDATE: It appears that the log is getting sorted according to the date in that hg command. I can find the right commit by expanding the limit and keeping the list of files.

**Comment by milkypostman** [comment]
Ok I'll take a look this morning.

**Comment by justbur** [comment]
Thanks. In case something changes, here's what I'm seeing

## From command line
Notice that these appear to be sorted by date. `-l1` only shows the first.
```
$ hg log --style compact -l10 "evil-commands.el" "evil-common.el" "evil-core.el" "evil-digraphs.el" "evil-ex.el" "evil-integration. el" "evil-jumps.el" "evil-macros.el" "evil-maps.el" "evil-pkg.el" "evil-repeat.el" "evil-search.el" "evil-states.el" "evil-types.el " "evil-vars.el" "evil.el" "doc/evil.texi" "doc/fdl-1.3.texi" "doc/macros.texi" "doc/version.texi"
1825   b0d728a5080e   2016-04-16 10:19 +0200   frank-fischer
  Find characters function to not set a jump mark (fix #655)

1824   24f333b2624f   2016-04-16 10:14 +0200   frank-fischer
  Implement `:delmarks` command (re #658)

1823:1821   174020d7cdb0   2016-04-15 08:43 +0200   frank-fischer
  Come up in emacs state in some pdf view modes (fix #657)

1822   587839c45bd8   2016-04-11 09:18 -0400   justin
  evil-core.el: Add ignore-parent option to get-auxiliary-keymap

1821   41aa7c5943d9   2016-04-06 12:52 +0300   w3techplayground
  Better docs for evil-scroll-line-*

1820   8d3015d69106   2016-04-06 11:55 +0300   w3techplayground
  Make evil-scroll-line-* remember last count.

1819   ad76c246c17d   2016-04-06 11:44 +0300   w3techplayground
  Rename evil-ud-scroll-* ->  evil-scroll-*

1818:1814,1817   08f766cf6573   2016-04-05 07:19 +0200   frank-fischer
  Merge stable

1816[1.2.12]   238b01c6dfbc   2016-04-05 07:17 +0200   frank-fischer
  update version to 1.2.12

1815:1778   5e1af096fd71   2016-04-05 07:14 +0200   frank-fischer
  Respect `evil-search-wrap` when calling `evil-ex-find-next` (fix #654)
```

## From bitbucket
![evil-repo](https://cloud.githubusercontent.com/assets/2208382/14645702/b6babe54-0624-11e6-9192-0202234fe2ce.png)

**Comment by milkypostman** [comment]
The problem is that I cannot get the log to show that merge commit, and thus we had a version backtrack.

i.e.,  the commit 587839c is showing up as the most recent on my log.

```
1822:1818   587839c45bd8   2016-04-11 09:18 -0400   justin
  evil-core.el: Add ignore-parent option to get-auxiliary-keymap

1821   b0d728a5080e   2016-04-16 10:19 +0200   frank-fischer
  Find characters function to not set a jump mark (fix #655)
```

Is there a better way to get this log?

**Comment by justbur** [comment]
Sorry I'm not very familiar with hg. Here is what I get when I omit the file names from the command
```
$ hg log --style compact -l10
1826[tip]:1825,1822   075f9f5044d9   2016-04-16 14:00 +0200   frank-fischer
  Merged in justbur/evil (pull request #59)

1825   b0d728a5080e   2016-04-16 10:19 +0200   frank-fischer
  Find characters function to not set a jump mark (fix #655)

1824   24f333b2624f   2016-04-16 10:14 +0200   frank-fischer
  Implement `:delmarks` command (re #658)

1823:1821   174020d7cdb0   2016-04-15 08:43 +0200   frank-fischer
  Come up in emacs state in some pdf view modes (fix #657)

1822   587839c45bd8   2016-04-11 09:18 -0400   justin
  evil-core.el: Add ignore-parent option to get-auxiliary-keymap
```
so the merge commit shows up there.

**Comment by milkypostman** [comment]
but why does yours show justin's commit after the others but mine shows it first?

**Comment by justbur** [comment]
I don't know. They're not actually ordered though, because they occur on different branches. The only thing that should be true is that they are all children of the merge.

**Comment by milkypostman** [comment]
oh justin, I have rebuilt the package. if you uninstall and reinstall you
will get it. otherwise we currently need a new commit to increment the
version number. I will continue to look at this later tonight but have run
out of time right now.

**Comment by justbur** [comment]
> otherwise we currently need a new commit to increment the
version number.

Right. This is not pressing, so I'm not worried about it. I was just reporting the apparent bug.
