### ISSUE TITLE
melpa-stable is showing an incorrect version for `f`

### ISSUE THREAD

**Issue by mdorman** [melpa/melpa#3817]
http://stable.melpa.org/#/f has the version as `1.18.1`, but the latest version is, in fact, tagged at https://github.com/rejeep/f.el/releases as `0.18.2`.

**Comment by dunn** [comment]
Running `STABLE=t make recipes/f` locally produces a package for 0.18.2, so the stable repository just probably hasn't been regenerated this week.

**Comment by purcell** [comment]
Hmmm... The new tag is there in the “f” working directory on the build server, so I’m not sure what’s going on there. Don’t have more time to dig just now, sorry, but hopefully soon.

**Comment by mdorman** [comment]
Perhaps it was a slip that was the corrected, but the build server synced at just the wrong time?  Maybe the working directory needs to be removed & regenerated?

**Comment by milkypostman** [comment]
fixed. had to wipe the working directory. somehow there was a 1.18 tag in there.

**Comment by milkypostman** [comment]
PS: if you don't see it right away you will soon. sorry about that. but beware that anyone with 1.18 installed already from stable won't get the updates. you may want to mention something on the twitters. I will post something on our twitter.

**Comment by milkypostman** [comment]
done.https://twitter.com/melpa_emacs/status/726509672019030016
