### ISSUE TITLE
Failed to download melpa archive

### ISSUE THREAD

**Issue by mola-T** [melpa/melpa#3833]
http://melpa.org/packages/archive-contents is truncated.

Information by @twlz0ne 

<pre>$ curl -sI http://melpa.org/packages/archive-contents
HTTP/1.1 200 OK
Server: nginx/1.4.6 (Ubuntu)
Date: Wed, 04 May 2016 05:03:44 GMT
Content-Type: text/plain<span class="pl-k">;</span> charset=utf-8
<h3>Content-Length: 0</h3>
Connection: keep-alive
Last-Modified: Wed, 04 May 2016 05:03:34 GMT
ETag: <span class="pl-s"><span class="pl-pds">"</span>572982a6-0<span class="pl-pds">"</span></span>
Accept-Ranges: bytes</pre>

Temporary work around by @jacksonrayhamilton 

<ol>
<li>Set your melpa package archives to the url <code>http://127.0.0.1:8000/packages/</code>. (Cask users should update the url in their <code>Cask</code> files, and in <code>~/.cask/cask-cli.el</code> and <code>~/.cask/cask-bootstrap.el</code>.)</li>
<li>Clone and <code>cd</code> into <code>melpa</code>.</li>
<li>Run <code>make recipes/{recipe1,recipe2,...}</code>.</li>
<li>Run <code>make packages/archive-contents</code>
</li>
<li>Run <code>python -m SimpleHTTPServer</code>
</li>
<li>Attempt to install packages. If there are missing dependencies, do steps 2 through 6 again.</li>
</ol>

**Comment by syohex** [comment]
I suppose you miss `/` at end of URL of `package-archives`. Valid URL is `http://melpa.milkbox.net/packages/archive-contents`.

And you should use `melpa.org` instead of `melpa.milkbox.net`.

See also
- http://melpa.org/#/getting-started

**Comment by andrebeat** [comment]
I'm also having trouble with `melpa` right now (and I'm using the correct url). It seems like the contents of `archive-contents` is being truncated, you can test this with  `curl -L http://melpa.milkbox.net/packages/archive-contents`.

**Comment by Freyr666** [comment]
I have this issue too: package-refresh-contents

Contacting host: melpa.org:80 [2 times]
Failed to download `melpa' archive.

This is my config:

(require 'package)
(package-initialize)
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))
(package-initialize)

**Comment by mola-T** [comment]
It is not me who hard code the URL.
I used this:
`(add-to-list 'package-archives '("melpa" . "http://melpa.milkbox.net/packages/"))`
which has been working for long time.

**Comment by peterwang** [comment]
The same here, the response seems to be truncated at byte 450560 (#x6e000), if this means anything?

**Comment by bomgar** [comment]
stable.melpa.org seems to work tough

**Comment by ackalker** [comment]
Individual files are getting truncated too it seems, see for example: https://melpa.org/packages/highlight-symbol-20160102.1209.el

**Comment by gragusa** [comment]
Same problem here

```
Opening TLS connection with ‘openssl s_client -connect melpa.org:443 -no_ssl2 -ign_eof’...done
Opening TLS connection to ‘melpa.org’...done
error in process filter: End of file during parsing [2 times]
```

**Comment by jacksonrayhamilton** [comment]
I was getting this, but now my packages are downloading again. Was this (willfully) fixed?

**Comment by gragusa** [comment]
yes, it seems `melpa` is back.

**Comment by jacksonrayhamilton** [comment]
I am curious what caused this in the first place. Partial downloads sounds like some sort of buffering error, which are sometimes also security errors.

**Comment by cafeclimber** [comment]
Is this happening again? I had troubles this morning and am having them again now...

**Comment by jacksonrayhamilton** [comment]
Not happening for me. But if this does continue to plague us, here is the workaround I came up with:

1. Set your melpa package archives to the url `http://127.0.0.1:8000/packages/`.
2. Clone and `cd` into `melpa`.
3. Run `make recipes/{recipe1,recipe2,...}`.
4. Run `make packages/archive-contents`
5. Run `python -m SimpleHTTPServer`
6. Attempt to install packages. If there are missing dependencies, do steps 2 through 6 again.

**Comment by milkypostman** [comment]
I'm sorry I didn't see this happen but appears that a lot of people had issues. https://status.digitalocean.com suggests there was no network disturbances during this time but it doesn't mean there wasn't an issue between our providers network and a large subnetwork.

Please feel free to ping this bug if it occurs again.

**Comment by edpaget** [comment]
It looks like this is happening again.

**Comment by milkypostman** [comment]
I just pulled archive-contents. Is there something specific?

**Comment by mstemm** [comment]
When I fetch archive-contents, the output appears to be truncated:

```
$ curl -s  http://melpa.org/packages/archive-contents | wc -c
  471040

$ curl -s  http://melpa.org/packages/archive-contents | tail -c 100
tations" "search" "info" "url" "w3m" "gnus"))]) (boogie-friends . [(20160423 903) ((cl-lib (0 5)) (d
```

**Comment by jxcl** [comment]
Connecting to https://melpa.org/packages/archive-contents, this is the last entry in the list. It appears to be truncated. 

```(boogie-friends . [(20160423 903) ((cl-lib (0 5)) (d```

**Comment by Balooga** [comment]
I too am experiencing this.

**Comment by edpaget** [comment]
I'm seeing the same truncation errors as @jxcl and @mstemm. I ran into error trying to install spacemacs on a new machine. The error I see in the messages buffer is:

```
Contacting host: melpa.org:443
Failed to download `melpa' archive.
```

**Comment by aronatkins** [comment]
Also seeing this problem. 

```
$ curl -s -I http://melpa.org/packages/archive-contents
HTTP/1.1 200 OK
Server: nginx/1.4.6 (Ubuntu)
Date: Wed, 04 May 2016 01:46:54 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 397312
Connection: keep-alive
Vary: Accept-Encoding
Last-Modified: Wed, 04 May 2016 01:46:06 GMT
ETag: "5729545e-61000"
Accept-Ranges: bytes
```

The `Content-Length`/truncated content is not stable. Every few requests, I see a different length and content, so things are changing.

**Comment by hut8** [comment]
Yes, this is still happening.

**Comment by ijoosong** [comment]
This is still happening btw.  I've been trying a lot of different things to try and fix it but I'm not getting any success.  Anything happening soon?

**Comment by twlz0ne** [comment]
```sh
$  curl -s -I http://melpa.org/packages/archive-contents
HTTP/1.1 200 OK
Server: nginx/1.4.6 (Ubuntu)
Date: Wed, 04 May 2016 05:03:44 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 0
Connection: keep-alive
Last-Modified: Wed, 04 May 2016 05:03:34 GMT
ETag: "572982a6-0"
Accept-Ranges: bytes
```

**Comment by cassella** [comment]
I'm also getting an empty file for melpa packages/archive-contents.  stable.melpa looks better:

```
$ curl -s http://melpa.org/packages/archive-contents | wc -c
0
$ curl -s http://stable.melpa.org/packages/archive-contents | wc -c
218332
```

**Comment by agsdot** [comment]
Took me awhile to kind of get @jacksonrayhamilton's work around to work.

After I got it working, I made sure to check out the following. 

https://github.com/redguardtoo/elpa-mirror

Never really saw a use case for it before, but with melpa being down. This is definitely something to keep in mind.

**Comment by s-kostyaev** [comment]
```
$ curl -s -I http://melpa.org/packages/archive-contents
HTTP/1.1 200 OK
Server: nginx/1.4.6 (Ubuntu)
Date: Wed, 04 May 2016 06:26:01 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 0
Connection: keep-alive
Last-Modified: Wed, 04 May 2016 05:38:10 GMT
ETag: "57298ac2-0"
Accept-Ranges: bytes
```

**Comment by milkypostman** [comment]
I think i know the issue.​ we are constantly rebuilding this file so that
as recipes are created, the archive-contents is updated. likely what is
happening is that the file is being written while you are trying to
download it.

the script runs every 5 minutes. so that could be tuned better but I like
to have it up to date. I think what I will do is modify things so that it's
a single file copy instead of truncating and rewriting the file.

sorry about that.

**Comment by milkypostman** [comment]
whoops. looks like we're getting resource constrained. i will work on cleaning up the server.

**Comment by milkypostman** [comment]
rebooting the server and it should be resolved

**Comment by NJBS** [comment]
```
$ curl -s -I http://melpa.org/packages/archive-contents
HTTP/1.1 200 OK
Server: nginx/1.4.6 (Ubuntu)
Date: Wed, 04 May 2016 07:04:35 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 511433
Connection: keep-alive
Vary: Accept-Encoding
Last-Modified: Wed, 04 May 2016 07:03:03 GMT
ETag: "57299ea7-7cdc9"
Accept-Ranges: bytes
```
:+1:

**Comment by ackalker** [comment]
Maybe a silly question, but why not just write the new file as `archive-contents.new`, then rotate this file into place as `archive-contents` as soon as you're done writing it? This way (even very slow) clients can continue reading from `archive-contents` while the new version is being written.

**Comment by milkypostman** [comment]
Does everything seem to have resolved?

**Comment by mstemm** [comment]
I was able to install modules again using M-x package-install, so yes!

**Comment by edpaget** [comment]
Yup looks like it works for me now. Thanks!

**Comment by milkypostman** [comment]
i suspect this was all due to the filesystem filling up.

@ackalker that was how it was originally, the packages were mirrored, and late we changed it so that the we just write packages to the serving directory. in theory this shouldn't be much of an issue but I believe because the filesystem was full performance dropped and/or files were not getting written properly.

will open a separate issue about this.

**Comment by ackalker** [comment]
@milkypostman Ah, thanks for the explanation, and thanks for MELPA :)

**Comment by NJBS** [comment]
It looks like contents of archive-contents are cut off once again.

**Comment by fommil** [comment]
looks like this is happening to `stable.melpa.org` again :-(

**Comment by strom** [comment]
@milkypostman I'm seeing this issue again, on exactly the same date a year later. Is this a cert issue or cron job or similar causing this?

**Comment by milkypostman** [comment]
Disk usage is not too high. I was able to download what looked to be a
complete package-archives file.

Will investigate more.

**Comment by strom** [comment]
```
Debugger entered--Lisp error: (file-error "https://melpa.org/packages/async-20170429.2207.tar" "Not found")
  signal(file-error ("https://melpa.org/packages/async-20170429.2207.tar" "Not found"))
  package-install-from-archive([cl-struct-package-desc async (20170429 2207) "Asynchronous processing in Emacs" nil tar "melpa" nil ((:keywords "async") (:url . "https://github.com/jwiegley/emacs-async")) nil])
  mapc(package-install-from-archive ([cl-struct-package-desc async (20170429 2207) "Asynchronous processing in Emacs" nil tar "melpa" nil ((:keywords "async") (:url . "https://github.com/jwiegley/emacs-async")) nil] [cl-struct-package-desc magit-popup (20170420 544) "Define prefix-infix-suffix command combos" ((emacs (24 4)) (async (20170219 942)) (dash (20170207 2056))) tar "melpa" nil ((:url . "https://github.com/magit/magit") (:keywords "bindings")) nil] [cl-struct-package-desc with-editor (20170417 1458) "Use the Emacsclient as $EDITOR" ((emacs (24 4)) (async (1 9)) (dash (2 13 0))) tar "melpa" nil ((:url . "https://github.com/magit/with-editor") (:keywords "tools")) nil] [cl-struct-package-desc git-commit (20170314 1414) "Edit Git commit messages" ((emacs (24 4)) (dash (20170207 2056)) (with-editor (20170111 609))) single "melpa" nil ((:url . "https://github.com/magit/magit") (:keywords "git" "tools" "vc")) nil] [cl-struct-package-desc magit (20170425 638) "A Git porcelain inside Emacs" ((emacs (24 4)) (async (20170219 942)) (dash (20170207 2056)) (with-editor (20170111 609)) (git-commit (20170214 347)) (magit-popup (20170214 347))) tar "melpa" nil ((:url . "https://github.com/magit/magit") (:keywords "git" "tools" "vc")) nil]))
  package-download-transaction(([cl-struct-package-desc async (20170429 2207) "Asynchronous processing in Emacs" nil tar "melpa" nil ((:keywords "async") (:url . "https://github.com/jwiegley/emacs-async")) nil] [cl-struct-package-desc magit-popup (20170420 544) "Define prefix-infix-suffix command combos" ((emacs (24 4)) (async (20170219 942)) (dash (20170207 2056))) tar "melpa" nil ((:url . "https://github.com/magit/magit") (:keywords "bindings")) nil] [cl-struct-package-desc with-editor (20170417 1458) "Use the Emacsclient as $EDITOR" ((emacs (24 4)) (async (1 9)) (dash (2 13 0))) tar "melpa" nil ((:url . "https://github.com/magit/with-editor") (:keywords "tools")) nil] [cl-struct-package-desc git-commit (20170314 1414) "Edit Git commit messages" ((emacs (24 4)) (dash (20170207 2056)) (with-editor (20170111 609))) single "melpa" nil ((:url . "https://github.com/magit/magit") (:keywords "git" "tools" "vc")) nil] [cl-struct-package-desc magit (20170425 638) "A Git porcelain inside Emacs" ((emacs (24 4)) (async (20170219 942)) (dash (20170207 2056)) (with-editor (20170111 609)) (git-commit (20170214 347)) (magit-popup (20170214 347))) tar "melpa" nil ((:url . "https://github.com/magit/magit") (:keywords "git" "tools" "vc")) nil]))
  package-install(magit)
  use-package-ensure-elpa(magit t nil :ensure)
  eval-buffer(#<buffer  *load*> nil "/Users/strom/.emacs.d/init.el" nil t)  ; Reading at buffer position 3243
  load-with-code-conversion("/Users/strom/.emacs.d/init.el" "/Users/strom/.emacs.d/init.el" t t)
  load("/Users/strom/.emacs.d/init" t t)
  #[0 "\205\266	\306=\203\307\310Q\202?	\311=\204\307\312Q\202?\313\307\314\315#\203*\316\202?\313\307\314\317#\203>\320\321\322!D\nB\323\202?\316\324\325\324\211#\210\324=\203e\326\327\330\307\331Q!\"\325\324\211#\210\324=\203d\210\203\247\332!\333\232\203\247\334!\211\335P\336!\203\201\211\202\214\336!\203\213\202\214\314\262\203\245\337\"\203\243\340\341#\210\342\343!\210\266\f?\205\264\314\325\344\324\211#)\262\207" [init-file-user system-type delayed-warnings-list user-init-file inhibit-default-init inhibit-startup-screen ms-dos "~" "/_emacs" windows-nt "/.emacs" directory-files nil "^\\.emacs\\(\\.elc?\\)?$" "~/.emacs" "^_emacs\\(\\.elc?\\)?$" initialization format-message "`_emacs' init file is deprecated, please use `.emacs'" "~/_emacs" t load expand-file-name "init" file-name-as-directory "/.emacs.d" file-name-extension "elc" file-name-sans-extension ".el" file-exists-p file-newer-than-file-p message "Warning: %s is newer than %s" sit-for 1 "default"] 7]()
  command-line()
  normal-top-level()
```

**Comment by strom** [comment]
This looks like an issue specifically when I try to install `magit`.

**Comment by milkypostman** [comment]
the current melpa version of async is 20170502.2343. it looks like you need
to run 'package-refresh-contents'.

**Comment by strom** [comment]
That worked...sorry about the false alarm. I'm still learning the package system and emacs in general.

**Comment by svapreddy** [comment]
Seeing this issue again with fresh install of emacs. Any leads please?

**Comment by purcell** [comment]
> Seeing this issue again with fresh install of emacs. Any leads please?

@svapreddy It's working fine for me, and the issue you're seeing could be due to any number of factors, so it's impossible for any of us to comment without more information. Which Emacs version do you have? Are you in an unusual network environment, e.g. behind a proxy? Are you using the `http` or `https` URL for MELPA? If `http`, then can your Emacs successfully make network requests to other `https` sites? Does it work if you try it a second time?

**Comment by svapreddy** [comment]
@purcell Thanks for the response. I am using latest emacs version. I am able to make other https calls not behind the proxy. The error message was about invalid certificate. I have got the same issue with VPN connection too. I just switched to http MELPA url and it worked fine.

**Comment by DarrienG** [comment]
Is melpa down again?
