### ISSUE TITLE
Tidy package is broken in melpa.org

### ISSUE THREAD

**Issue by jsirex** [melpa/melpa#3848]
I've failed to find where to submit such kind of issue, so going here.

https://melpa.org/packages/tidy-20111222.956.el is broken (file contains ~1600 lines instead of ~1900).
It corrupted :(

**Comment by purcell** [comment]
Pretty likely this was due to the disk getting full, so the full rebuild we're running as part of fixing #3833 should fix this too. Sorry for the issues: please bear with us.

**Comment by jsirex** [comment]
Thank you for quick response! 
I missed the issue #3833 .
Closing this and will watch that.
