### ISSUE TITLE
keyfreq dependency cl/cl-lib Emacs 23/24

### ISSUE THREAD

**Issue by zimoun** [melpa/melpa#3855]
The package `keyfreq` depends on `reduce` which is provided by `cl` or `cl-lib`.

If I have understood well, `cl-lib` is now in Emacs 24, therefore, there is no dependency issue.

However, under Emacs 23, it is still possible to use MELPA, and the recipe of `keyfreq` does not mention the dependency to `cl`. Even if it is a minor edge case, how to fix ?

**Comment by dunn** [comment]
keyfreq should declare `cl-lib` as a dependency so that `package.el` can install it for users on older versions of Emacs.

**Comment by zimoun** [comment]
In this case, the package will be downloaded from ELPA for the user under Emacs 24, no ?
I mean, it is not clear to me how the built-in packages included in Emacs 24 are managed by `package.el` if they appear in the dependencies of the recipe.

**Comment by dunn** [comment]
> In this case, the package will be downloaded from ELPA for the user under Emacs 24, no ?

No, since with Emacs 24.3+ it will see that `cl-lib` is already available.

**Comment by zimoun** [comment]
ok, thanks !

**Comment by purcell** [comment]
@zimoun The long story: In some 24.x versions of Emacs, built-in packages aren't handled very well, but the worst case is that `cl-lib` 0.5 will be downloaded for those users, and it will actually be at least as new as the `cl-lib` "1.0" bundled with those Emacs versions.

**Comment by zimoun** [comment]
@purcell ok, thank you. It is nice and always useful to understand the long story. Even if `cl-lib` is small, and so, extra-download is not a real issue, it is better to do with a clear mind.

I will send a pull request to fix that.

Thanks both of you for the help.

**Comment by zimoun** [comment]
hum? I do not understand how the dependency / requirement system works.
Is it documented elsewhere ?

I mean, if `package-A` depends on `package-B`, how to specify it in the recipe ?
Or `package.el` does not provide such feature ?

**Comment by dunn** [comment]
Dependencies can be specified in the beginning of the file, like this: https://github.com/flycheck/flycheck/blob/master/flycheck.el#L12

**Comment by zimoun** [comment]
Thank you. I am checking if it works...

**Comment by purcell** [comment]
I looked at the keyfreq.el code, and the current situation isn't too bad, if the maintainers want to ensure it works without needing package.el. But in general I'd recommend adding `;; Package-Requires: ((cl-lib "0.5"))` and just removing any references to `'cl`, since that library is now deprecated.

**Comment by zimoun** [comment]
I added yesterday evening in my branch [`fix`](https://github.com/zimoun/keyfreq/tree/fix). I have started to test if it does the expected behavior before submitting a pull request.

Yes, it is the plan to remove any reference to `cl`, but I am not a guru in this, therefore I would like to avoid annoying for some user.

Well, thank you very much for your help.

**Comment by tarsius** [comment]
Fix has been merged upstream.
