### ISSUE TITLE
Stable is showing an outdated version for 'magit' + associated packages

### ISSUE THREAD

**Issue by mdorman** [melpa/melpa#3868]
@tarsius released [2.6.2](https://github.com/magit/magit/releases/tag/2.6.2) 15 days ago, but stable is still seeing 2.6.1 for [git-commit](http://stable.melpa.org/#/git-commit), [magit](http://stable.melpa.org/#/magit) and [magit-popup](http://stable.melpa.org/#/magit-popup).

**Comment by milkypostman** [comment]
hrm, not sure what happened but the repo appears to have gotten out of date. I am rebooting stable and will rebuild all packages just to make sure we have the newest package versions of all packages.

**Comment by mdorman** [comment]
Thanks!
