### ISSUE TITLE
Failed to download `melpa' archive

### ISSUE THREAD

**Issue by hpr** [melpa/melpa#3914]
I get the error `Failed to download `melpa' archive.` when I try to M-x package-refresh-contents, yet doing a `(browse-url-emacs "https://melpa.org/packages/archive-contents" t)` from within emacs works just fine and gives me the correct file. Here's my .emacs:

```
(require 'package)
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/") t)
(when (< emacs-major-version 24)
  ;; For important compatibility libraries like cl-lib
  (add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages")))
(package-initialize)
```

I'm using emacs version 24.4. What can be done to debug / fix this problem?

**Comment by xuchunyang** [comment]
Not answering your question, but

> (add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages")

you forget the tailing slash of GNU ELPA URL, as far as I know, it matters.

**Comment by Habstinat** [comment]
Thank you, I added the trailing slash but I am still getting the same error when trying to download the mepla archive. Any help would be greatly appreciated.

**Comment by milkypostman** [comment]
do you have `debug-on-error` set?

some more logging details might be shown in the `*Messages*` buffer.

**Comment by rdotdk** [comment]
Hi @milkypostman , here's the error after setting ```debug-on-error```. Emacs version 24.5. But for some reason it works with emacs 25.

Debugger entered--Lisp error: (error "Could not create connection to melpa.org:443")
  signal(error ("Could not create connection to melpa.org:443"))
  error("Could not create connection to %s:%d" "melpa.org" 443)
  url-http([cl-struct-url "https" nil nil "melpa.org" nil "/packages/archive-contents" nil nil t nil t] #[128 "\302\303\304p#\210\300\305\240\2$
  url-https([cl-struct-url "https" nil nil "melpa.org" nil "/packages/archive-contents" nil nil t nil t] #[128 "\302\303\304p#\210\300\305\240\$
  url-retrieve-internal("https://melpa.org/packages/archive-contents" #[128 "\302\303\304p#\210\300\305\240\210\301p\240\207" [(nil) (nil) url-$
  url-retrieve("https://melpa.org/packages/archive-contents" #[128 "\302\303\304p#\210\300\305\240\210\301p\240\207" [(nil) (nil) url-debug ret$
  url-retrieve-synchronously("https://melpa.org/packages/archive-contents")
  url-insert-file-contents("https://melpa.org/packages/archive-contents")
  package--download-one-archive(("melpa" . "https://melpa.org/packages/") "archive-contents")
  #[0 "\301\300\302\"\207" [("melpa" . "https://melpa.org/packages/") package--download-one-archive "archive-contents"] 3 "\n\n(fn)"]()
  funcall(#[0 "\301\300\302\"\207" [("melpa" . "https://melpa.org/packages/") package--download-one-archive "archive-contents"] 3 "\n\n(fn)"])
  package-refresh-contents()
  (if (package-installed-p (quote use-package)) nil (package-refresh-contents) (package-install (quote use-package)))
  eval-buffer()  ; Reading at buffer position 789
  call-interactively(eval-buffer record nil)
  command-execute(eval-buffer record)
  execute-extended-command(nil "eval-buffer")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)

**Comment by purcell** [comment]
Are you maybe on Windows? My guess is that 24.4 was relying on an external program such as `gnutls` or `openssl` to make an `https` connection, whereas (I think) 25 has SSL support compiled-in on Windows. The error indicates that your Emacs 24.4 was either incapable of `https`, or the helper program declined to make the connection. You can test it with other URLs, e.g. by evaluating `(url-copy-file "https://www.google.com/" "google.txt")`.

**Comment by rdotdk** [comment]
I'm using Ubuntu 14.04 @purcell. And with ``` (url-copy-file "https://www.google.com/" "google.txt") ``` from  ``` emacs-24.5 -nw -Q ``` i get the same error

Debugger entered--Lisp error: (error "Could not create connection to www.google.com:443")
  signal(error ("Could not create connection to www.google.com:443"))
  error("Could not create connection to %s:%d" "www.google.com" 443)
  url-http([cl-struct-url "https" nil nil "www.google.com" nil "/" nil nil t nil t] #[128 "\302\303\304p#\210\300\305\240\210\301p\240\207" [(n$
  url-https([cl-struct-url "https" nil nil "www.google.com" nil "/" nil nil t nil t] #[128 "\302\303\304p#\210\300\305\240\210\301p\240\207" [($
  url-retrieve-internal("https://www.google.com/" #[128 "\302\303\304p#\210\300\305\240\210\301p\240\207" [(nil) (nil) url-debug retrieval "Syn$
  url-retrieve("https://www.google.com/" #[128 "\302\303\304p#\210\300\305\240\210\301p\240\207" [(nil) (nil) url-debug retrieval "Synchronous $
  url-retrieve-synchronously("https://www.google.com/")
  url-copy-file("https://www.google.com/" "google.txt")
  eval((url-copy-file "https://www.google.com/" "google.txt") nil)
  eval-last-sexp-1(nil)
  eval-last-sexp(nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)

**Comment by rdotdk** [comment]
I'm using Emacs 24.5 ``` GNU Emacs 24.5.1 (i686-pc-linux-gnu, GTK+ Version 2.24.23) of 2016-03-27 ```

**Comment by milkypostman** [comment]
does it work without https?

**Comment by lascott** [comment]
In debug-on-error mode, I tried as https and http, both failed.  
grabbing google with url-copy-file works just fine.

---------------------------------------------------------------------------------------------------
emacs --version : 24.3.1
uname -a : Linux Neruda 3.19.0-32-generic #37~14.04.1-Ubuntu
dpkg -l : 
ii  libssl1.0.0:amd64     1.0.1f-1ubuntu2 amd64           Secure Sockets Layer toolkit - shared libraries
ii  libssl1.0.0:i386      1.0.1f-1ubuntu2 i386            Secure Sockets Layer toolkit - shared libraries
ii  openssl               1.0.1f-1ubuntu2 amd64           Secure Sockets Layer toolkit - cryptographic ut
---------------------------------------------------------------------------------------------------

`(when (>= emacs-major-version 24)
  (require 'package)
  (add-to-list
   'package-archives
   '("melpa" . "https://melpa.org/packages/") t)
  (package-initialize))`


Loading /home/louis/.emacs.d/init.el (source)...done
Contacting host: elpa.gnu.org:80
Saving file /home/louis/.emacs.d/elpa/archives/gnu/archive-contents...
Wrote /home/louis/.emacs.d/elpa/archives/gnu/archive-contents
Contacting host: melpa.org:80
package-handle-response: Error during download request: Not Found

next I evaluated   `(url-copy-file "https://www.google.com/" "google.txt")`
which read successfully.

Mark set
load-file: Cannot open load file: /home/louis/
Contacting host: www.google.com:443
Wrote /home/louis/google.txt

**Comment by rdotdk** [comment]
@milkypostman it works with ```http``` for me.

**Comment by milkypostman** [comment]
i think this is a local issue, not a problem with the server.

**Comment by haight6716** [comment]
I'm having the same problem.  When I visit the recommended package url (https://melpa.org/packages/) with a web browser, I get an "empty" error page with a meta-redirect embedded.  Seems like an obvious problem.  Looks like someone rejiggered the website for human consumption without thinking about how machines will cope with it?

**Comment by milkypostman** [comment]
Emacs doesn't read that address. It reads
http://melpa.org/packages/archive-contents which is the package index which
package.el loads.

**Comment by NJBS** [comment]
It looks like contents of archive-contents are cut off once again.

**Comment by xuchunyang** [comment]
and https://melpa.org/#/ website are not working correctly either

**Comment by purcell** [comment]
@njbs / @xuchunyang unrelated. disk is full. see #3985

**Comment by tarsius** [comment]
Since we haven't heard from the affected users in a while, I am going to assume that this no longer is an issue. I also think that this is quite likely the case:

> i think this is a local issue, not a problem with the server.

**Comment by tarsius** [comment]
> I still have this issue

What is "this issue"? What error messages do you get?

**Comment by guy-fawks** [comment]
"Failed to download melpa archive." was the error message I got. Then I stayed up through the night and kinda copy pasted package installation code from different init files I found on Github and its working. The melpa link is different and this link seems to work. I'm very new to emacs.
This is what I use in my init file I've added another source too:

(load "package")
(package-initialize)
(add-to-list 'package-archives
             '("marmalade" . "http://marmalade-repo.org/packages/"))
(add-to-list 'package-archives
             '("melpa" . "http://melpa.milkbox.net/packages/") t)

**Comment by purcell** [comment]
@guy-fawks The milkbox.net URL is obsolete and you should instead follow the instructions in the MELPA README.

**Comment by AdanCortes** [comment]
From https://melpa.org/#/getting-started

"Enable installation of packages from MELPA by adding an entry to package-archives **after** (require 'package) and **before** the call to package-initialize in your init.el or .emacs file"

**Comment by lispstudent** [comment]
I apologies since the issue is closed, but it is one of the few places where there is precise information.

For future reference: I am having exact same issue with Emacs 27.2 on illumos (omnios, smartos) installed via pkgsrc. 

Using Emacs 28.0.50 makes the problem disappears. So, it seems the problem lies with Emacs 27.x somehow.
