### ISSUE TITLE
llvm-mode missing?

### ISSUE THREAD

**Issue by souvik1997** [melpa/melpa#3916]
Has llvm-mode been removed? I cannot download the package from MELPA but I see that the recipe still exists in this repo.

**Comment by purcell** [comment]
I'm pretty sure this is due to a 600s timeout we have for package builds: we flushed the server recently, and the huge llvm repo takes more than 600s to clone...

As a workaround, I'm checking it out and building manually on the server now, so it'll then continue to build properly, but we'll need to address this in a more general way.

**Comment by souvik1997** [comment]
Would it be possible to shallow clone git repositories?

**Comment by purcell** [comment]
> Would it be possible to shallow clone git repositories?

No, I don't think so. We need to have details of not only the most recent commit in a repository, but all the commits which last affected the elisp files selected by the recipe. So in the case of a repo like `llvm`, we'd need the commits which last affected `llvm-mode.el` etc. And when we build packages for MELPA stable, we also need the contents (and commit details) for the latest version tag.

**Comment by tarsius** [comment]
You could get this from the Emacsmirror, which periodically imports just the two libraries, discarding all history. I.e. they are imported the same way other packages are imported whose upstreams don't use version control.

Such packages are not updated very often, so this could lag at times. And it is only possible to import a single file like this, so a new package `tablegen-mode` would have to be added.

**Comment by tarsius** [comment]
`llvm-mode` is available now.

**Comment by jaseemabid** [comment]
@purcell @souvik1997 @tarsius The package seems to have disappeared again. Is this a recurring issue?

**Comment by tarsius** [comment]
It was removed in aa2d7a88731ecd9410ab7dc887a7a5f837d8a93b.

> Cloning the repository takes so long that we time out before the
> package ever gets build.  Users will have to install this manually.

The Emacsmirror also no longer has this package, so Melpa cannot get it from there.

Also relevant is #5361.
