### ISSUE TITLE
helm-core-20160523.2314.tar is missing

### ISSUE THREAD

**Issue by haishengwu-okta** [melpa/melpa#3927]
404 of latest helm-core
https://melpa.org/packages/helm-core-20160523.2314.tar

**Comment by syohex** [comment]
Latest version is helm-20160524.820. Please retry after do `M-x package-refresh-contents`.

**Comment by haishengwu-okta** [comment]
Cool. the site https://melpa.org/ seems a little behind when I query. it was still 0523 but now it's updated.
Thanks!
