### ISSUE TITLE
Skip building a newer version if latest commit message contains "[melpa skip]" ?

### ISSUE THREAD

**Issue by xuchunyang** [melpa/melpa#3947]
Sometimes I don't want Melpa to build a newer version of my package,  for example, all I are changing is the README, as a end user, I also don't like to upgrade a package for such reason.

**Comment by purcell** [comment]
We don't build a new version unless the files included in the package have changed, so I don't think this is ever an issue. The package timestamp is calculated based on the latest change to a file *in the package*, not *in the repo*.

**Comment by xuchunyang** [comment]
> The package timestamp is calculated based on the latest change to a file in the package, not in the repo.

You are right, I had a wrong assumption.
