### ISSUE TITLE
Does MELPA's default :files setting exclude ecukes' features directory?

### ISSUE THREAD

**Issue by Trevoke** [melpa/melpa#3954]
The README doesn't indicate such, and since I've got a branch where I added (finally) tests for my package, I want to make sure I don't need to submit a new PR changing the requirements to build my package before I merge it in.

**Comment by purcell** [comment]
The default pattern (listed in the README) excludes test files with certain naming conventions. Check it out and let me know if you have a suggested change.

**Comment by Trevoke** [comment]
Here are my suggestions for additions tot he "excluded" default filter: three directories and all the files underneath them.

1. `features/**/*`
2. `test/**/*`
3. `test/**/*`


What do you think?

**Comment by purcell** [comment]
There's no need to exclude subdirectories, because they will never be included by default in the first place: the default patterns only match `.el` files at the top level of the directory hierarchy.

**Comment by Trevoke** [comment]
Oh! Awesome. I didn't realize that. Excellent, I can now merge in my test branch without fear of giving end users stuff they don't care about.

Thanks!

**Comment by purcell** [comment]
Great, yes. I've made a note in the README to make this fact more obvious.

**Comment by Trevoke** [comment]
Thanks for all your hard work :)
