### ISSUE TITLE
MELPA is down

### ISSUE THREAD

**Issue by d12frosted** [melpa/melpa#3985]
Don't know where is the best place to notify about it. But it seems that MELPA is currently down. Can't download new packages, site doesn't load list of packages.

Aside from that, are there any MELPA mirrors for situations like this?

**Comment by purcell** [comment]
Thanks. Disk is full. Seeing what I can do about it now.

**Comment by d12frosted** [comment]
Wow. Funny 💃 😸 Thanks for a quick response.

**Comment by purcell** [comment]
Mainly for @milkypostman's reference:

- 310MB of packages
- 7.9GB in working dir
- 2.6GB of web logs, 2.2GB sqlite db of download data

Last items would be the key ones to cut down on unless we upgrade the server. I'll copy off some old logs to my local machine for now.

**Comment by purcell** [comment]
Think it's mostly working again now. Had to delete a few truncated files. There may be others, so I'll check through.

**Comment by d12frosted** [comment]
Thank you very much :)

**Comment by d12frosted** [comment]
Site is still not functioning properly. But I confirm that it's possible to install packages from MELPA. Thanks again.

**Comment by purcell** [comment]
Thanks. Website is fixed now too.

**Comment by d12frosted** [comment]
Indeed. Thanks for quick fix!

**Comment by milkypostman** [comment]
i am thinking about the best way to fix this. sorry for the break. I just
checked the server the other day I am surprised it so quickly filled.

**Comment by purcell** [comment]
Also, I think that we *can* actually use shallow clones for git checkouts, though probably not for MELPA Stable. Some of the biggest working dirs (mozc, nemerle, erlang, fuel) would be very significantly smaller then.

**Comment by purcell** [comment]
No. I was wrong.

**Comment by jaccarmac** [comment]
@purcell: Were you wrong about shallow clones being a good idea? The large size of the erlang package repository has bitten me recently, so if there's a desire to change `package-build` behavior to fix that somewhat I have the motivation to get it done.

**Comment by purcell** [comment]
> Were you wrong about shallow clones being a good idea?

Yes, they're not safe. In a large repository, the last time a particular file was touched might have been many hundreds of commits ago, so there's no `--depth` that will reliably produce the last commit that touched any given file.

**Comment by jaccarmac** [comment]
Fair enough, guess the first build of `erlang-mode` just hurts a bit then :/

**Comment by purcell** [comment]
Yup. It's definitely not ideal...
