### ISSUE TITLE
Provide rsync access to the package repo

### ISSUE THREAD

**Issue by purcell** [melpa/melpa#4020]
This would allow people to efficiently mirror our packages.

See https://github.com/melpa/melpa/pull/4012

**Comment by purcell** [comment]
Partially done - see https://github.com/melpa/melpa/issues/4042#issuecomment-233171920

**Comment by purcell** [comment]
Steps to enable on our server:

Create `/etc/rsyncd.conf`:
```
max connections = 1
log file = /var/log/rsync.log
timeout = 300
[packages]
comment = MELPA packages
path = /home/melpa/melpa/packages
read only = yes
list = yes
uid = melpa
gid = melpa
list = yes
```
Edit `/etc/default/rsync` and enable, then `service rsync start` seems to do the job. :-)

**Comment by cpitclaudel** [comment]
(any reason to not `use chroot = yes`, and to run under `uid = nobody` `gid = nogroup`)?

**Comment by purcell** [comment]
> (any reason to not use chroot = yes and run under uid = nobody gid = nogroup?)

Re. chroot, no - we should do that. But for the uid/gid, we're creating some files that are not world-readable, and this was the easy fix because I don't have time right now to fix the root problem.

**Comment by cpitclaudel** [comment]
Ok, neat :)

**Comment by cpitclaudel** [comment]
Do you actually need to do anything? It's trivial to reset permissions while rsync-ing.

**Comment by purcell** [comment]
Probably not, that’s true.

**Comment by xuchunyang** [comment]
It looks like the modification timestamp of all the files served by rsync is also updated after melpa rebuilds packages

```
$ rsync --list-only /var/elpa-packages/melpa/0blayout-20151021.349.el 
-rw-r--r--          5,315 2016/07/22 11:48:32 0blayout-20151021.349.el
```

then when I sync with melpa via rsync every day, rsync re-downloads (though I guess rsync only downloads the difference but it still needs time & network resource to compute the difference firstly) all the files since rsync thinks two files are different if they have different modification timestamp.

One possible solution is use the `--size-only` to inhibit checking the modification timestamp, but this is Inaccurate, because it is possible that two different files have the save size.

**Comment by purcell** [comment]
Yes, that's by design: every time we build packages we overwrite them because if we change our build process, we want the packages to be updated. It's not a perfect system, but that's how it is.

As you say, `rsync` should still only transfer the modified content. Using `--size-only` would be the wrong solution in this case.

**Comment by xuchunyang** [comment]
Keeping the modification timestamp of the identical files can save lots of resource and time in rsync. to achieve this, melpa can use a separate directory for rsync, for example,

```sh
  for file in /path/to/melpa/package/*; do
      dest=/path/to/melpa/rsync/"$(basename $file)"
      if ! [ -f "$dest" ] || ! cmp "$file" "$dest"; then
          cp -v "$file" "$dest"
          chmod 644 "$dest"
      fi
  done
```

> As you say, rsync should still only transfer the modified content.

During rsync, the content of most files is unchanged. Figuring out which part is modified itself is not a trivial task and also can be avoided for unchanged files. If we sustain the modification timestamp for the identical files, rsync will simply skip these file.

**Comment by cpitclaudel** [comment]
@xuchunyang Do you have evidence that this would be significantly faster? rsync is pretty efficient at comparing differences.

**Comment by xuchunyang** [comment]
@cpitclaudel I don't have evidence actually, and after doing some testing, it looks you are right.  That's my guess of the cause of the following issue.

The command we are using to sync melpa is:

    rsync -avz --delete --progress rsync://melpa.org/packages/ /var/elpa-packages/melpa

(only rsync can change the content of `/var/elpa-packages/melpa/`), during every rsync per a few hours I often notice something like

```
kanji-mode-20150202.25.tar
      2,010,407   5%  109.68kB/s    0:04:51
```

and rsync does hang here for a while (though maybe less than `4:51`). It won't occur if I run the rsync command again immediately. Except the timestamp of `kanji-mode-20150202.25.tar`, I can't figure out what is changed in this file.

**Comment by xuchunyang** [comment]
Could you please provide rsync access to melpa-stable? We have switched to rsync for mirroring melpa since a few days ago (July 17), it is generally working well.

**Comment by purcell** [comment]
> Could you please provide rsync access to melpa-stable? We have switched to rsync for mirroring melpa since a few days ago (July 17), it is generally working well.

@xuchunyang done!

**Comment by xuchunyang** [comment]
Thanks. The rsync address is `rsync://stable.melpa.org/packages/` and I can confirm it is working.  We will switch to rsync for mirroring melpa-stable today or tomorrow.

**Comment by purcell** [comment]
Now long completed, so closing.
