### ISSUE TITLE
Remove the recipe/package for delight?

### ISSUE THREAD

**Issue by phil-s** [melpa/melpa#4059]
delight.el used to be maintained on the EmacsWiki, and someone added a MELPA recipe for it a long time ago; but it's now in GNU ELPA, and I've deleted the code from the Wiki as that's no longer the maintained source.

Removing it from MELPA entirely seems like the sensible thing to do?

**Comment by purcell** [comment]
That was done in 713bc10 a couple of days ago, thanks!
