### ISSUE TITLE
evil-surround's :keywords contains its mailing list information

### ISSUE THREAD

**Issue by mineo** [melpa/melpa#4087]
At the moment, the entry for `evil-surround` in `archive-contents` looks like this (newlines inserted by me):

```
(evil-surround . [
(20160501 1704) 
(
(evil 
(1 2 12))) "emulate surround.vim from Vim" single 
(
(:keywords "emulation" "vi" "evil mailing list: <implementations-list at lists.ourproject.org> subscribe: http://tinyurl.com/implementations-list newsgroup: nntp://news.gmane.org/gmane.emacs.vim-emulation archives: http://dir.gmane.org/gmane.emacs.vim-emulation"))]) 
```

The `Keywords` declaration in `evil-surround.el` can be found [here](https://github.com/timcharper/evil-surround/blob/master/evil-surround.el#L14).

`lm-keywords-list` on `evil-surround.el` however returns the correct entries on Emacs 24.5.1. I had a quick look at the history of `lisp-mnt.el` and it looks like https://github.com/emacs-mirror/emacs/commit/ee3c0aeca4e1e31e2b171a4753782a37076e7457 / https://debbugs.gnu.org/cgi/bugreport.cgi?bug=13207 should have fixed situations like this.

**Comment by milkypostman** [comment]
so basically we're just running too old a version of emacs?

**Comment by mineo** [comment]
I've downloaded https://github.com/emacs-mirror/emacs/blob/f4d79bd021831eb64e1bfc7f5c5b1ddb2138b37a/lisp/emacs-lisp/lisp-mnt.el (the version just before 13207 was fixed), `eval-buffer`ed it and now `lm-keywords-list` returns the list with the mailing list information included, so I guess that yes, an old version of Emacs really is the problem.

**Comment by tarsius** [comment]
@milkypostman Has Emacs been updated since?

**Comment by tarsius** [comment]
Closing in favor of #4113.
