### ISSUE TITLE
Ledger mode new repo

### ISSUE THREAD

**Issue by mkaito** [melpa/melpa#4107]
Ledger mode now has its own official repo on github:

https://github.com/ledger/ledger-mode

The recipe for ledger-mode should probably pull from there now.

**Comment by mkaito** [comment]
Nevermind, I'm late: https://github.com/melpa/melpa/pull/4099

**Comment by purcell** [comment]
Thanks anyway. #4099 is merged now, so ledger-mode should be building properly again.
