### ISSUE TITLE
Use a new Emacs on the build server

### ISSUE THREAD

**Issue by purcell** [melpa/melpa#4113]
See #4087. Probably need to use a new Ubuntu snapshot, or maybe an Emacs-specific PPA.

**Comment by tarsius** [comment]
What version do you plan to use?

I am asking because I started cleaning up `package-build.el` and would like to use the latest (well upcoming) release, 25.1. I don't think it's necessary for `package-build` to support older releases as I would assume that everyone who is interested in something like that would also use the latest Emacs release (or the development version).

**Comment by vyp** [comment]
> I don't think it's necessary for package-build to support older releases as I would assume that everyone who is interested in something like that would also use the latest Emacs release (or the development version).

By older are you saying 24.5 (current stable release according to https://www.gnu.org/software/emacs/)? Because quelpa uses package-build and non-developers (users) use it.

**Comment by purcell** [comment]
At this point I'd probably plan to support maybe 24.4 and up.

**Comment by milkypostman** [comment]
i think we should probably to update to 16.04? instead of upgrading in
place I will probably bring up a new instance then switch over when I get a
chance?

**Comment by purcell** [comment]
Yep, sounds good.

**Comment by lunaryorn** [comment]
@tarsius I should probably weight in on behalf of Cask to say that we use `package-build` in Cask, and are definitely not ready to drop support for Emacs 24.  Should you bump package-build.el to Emacs 25 only we'd have to fork.

I should also like to note out that I had hoped to see research about the actual users of a library before making assumption about what Emacs versions it's being used with.  I came across this issue accidentally; had I not seen it we'd likely have run into troubles with Cask following your cleaning up of package-build.

**Comment by tarsius** [comment]
Okay everyone, I'll stick to backward compatible cleanup for now ;-)

**Comment by lunaryorn** [comment]
@tarsius Thanks :blush:

**Comment by purcell** [comment]
Now that we have a separate repo, we can probably put in place some regression tests and a travis build across supported Emacs versions.

**Comment by tarsius** [comment]
@milkypostman Could you please update to 25.3 now? Don't know about the server but at least on Travis Melpa still uses 24.5.

Maybe Melpa could just use the binaries created by @npostavs. We use that successfully [for Magit](https://github.com/magit/magit/blob/master/.travis.yml) and I don't thing he has any plans to stop providing these binaries.

**Comment by npostavs** [comment]
> Maybe Melpa could just use the binaries created by @npostavs. We use that successfully for Magit and I don't thing he has any plans to stop providing these binaries.

There is some risk that spectre/meltdown related fixes will break Emacs building on Travis (so far it's only broken on the non-sudo env, cf travis-ci/travis-ci#9061, builds from the sudo env continue to run on both).

Apart from that issue, the maintenance for providing these binaries has been pretty much zero, so I expect to keep them up indefinitely.

**Comment by milkypostman** [comment]
i'll see what i can do.

**Comment by tarsius** [comment]
It's 25.2 now, see https://github.com/melpa/melpa/issues/5662#issuecomment-410363030. That should do it.

**Comment by Silex** [comment]
I'm a bit late to the party, but since you moved to a docker architecture you might consider https://hub.docker.com/r/silex/emacs :wink:

**Comment by purcell** [comment]
Yeah, I'd quite like to start using @Silex's docker images in all my Emacs-related Travis builds...
