### ISSUE TITLE
melpa-stable hindent stuck at erroneous tag

### ISSUE THREAD

**Issue by mdorman** [melpa/melpa#4124]
Chris Done accidentally set a couple of tags with some transposed numbers last year---5.4.3 instead of 4.5.3.  He corrected and removed them (chrisdone/hindent#202), but melpa-stable still thinks that's higher than anything actually released.  Could someone zap the cache or kick the server or whatever would be necessary for melpa-stable to pick up the correct highest-version (which is, in fact 5.0.0 as of yesterday)?

@purcell I think I harassed you into doing something like this before for something else. :)

**Comment by purcell** [comment]
Done. :-)
