### ISSUE TITLE
Melpa is sending a truncated version use-package

### ISSUE THREAD

**Issue by emmettu** [melpa/melpa#4142]
Am I going crazy?

https://melpa.org/packages/use-package-20160722.1123.el

https://github.com/jwiegley/use-package/blob/master/use-package.el#L1132

If you compare them it's clear the melpa one is not the full file. It is missing everything after line 1132.

**Comment by milkypostman** [comment]
the server was doing maintenance (upsizing) and probably for a bit we ran out of space. this is fixed now though.

**Comment by emmettu** [comment]
Thanks for the quick response! :+1:
