### ISSUE TITLE
High server load

### ISSUE THREAD

**Issue by purcell** [melpa/melpa#4151]
MELPA service [dropped out completely for a while](https://www.reddit.com/r/emacs/comments/4xvo0c/is_melpaorg_down/), and I suspect high load and excessive request queuing on Caddy.

I've dropped the gzip compression level to 3 from the default of 9 (max) to help Caddy clear requests faster. However, the load avg on the machine is still 5, since there are parallel Emacs processes building packages as fast as possible. For each package, not only is the upstream pulled, but the package is unconditionally re-built. Maybe we should try harder to skip that second step?

**Comment by purcell** [comment]
I've made some changes to `package-build` (in https://github.com/melpa/package-build/commit/82a19298d1d8669b0e548a1c80dd0ebf3e8a43ed) in order to short-cut some re-builds.

Essentially, we will now pull a recipe's code from upstream, and then only build a fresh package if the calculated version stamp has changed since the last package was built (or if either of the recipe file or `package-build.el` is newer than the last package built). This should help the server to not be so CPU-bound.

The recreation of `archive-contents` and its JSON equivalent is probably still quite expensive, and would be the next thing to optimise.

In general it's a bit silly that we're reimplementing some of `make` inside `package-build`, then calling through to it from the `Makefile`. ;-)

**Comment by milkypostman** [comment]
I don't understand though, because we have twice the ram than we did now
cause I double capacity.

**Comment by purcell** [comment]
I'm also mystified. The server load was running at around 5-7, which seems excessive for a single processor instance, though, and it's all CPU rather than IO afaict. Cutting back on our CPU-intensive work seems like a good idea whatever the case.

Caddy always seems to end up with 30 processes (or threads), having grown gradually from a smaller number, and I suspect our traffic workload is maybe tying them up after a while. Perhaps quirks of the typical Emacs TLS clients, or timeouts in Caddy (which can't be tuned).

If problems persist, we can fall back to either Caddy reverse-proxying to an nginx, or just plain nginx plus `letsencrypt.sh`.

**Comment by purcell** [comment]
Load during the gap between builds is about 0.05...

**Comment by milkypostman** [comment]
did memory constraints restrict load. now that we have 1GB the constraint
is CPU?

**Comment by purcell** [comment]
Could be, yes.

**Comment by milkypostman** [comment]
The cause is file descriptor limit. I have increased to 4096 as suggested by the server authors.

Error log is filled with,

```
17/Aug/2016:07:11:47 -0700 [ERROR 503 /packages/archive-contents] open /home/melpa/melpa/html/packages/archive-contents: too many open files
```

apparently the warning at startup was a *requirement* and not a suggestion as I had read it. will see if this keeps happening now.

**Comment by Silex** [comment]
Hum, I had do fiddle with high load on some servers and this page helped me a lot:

https://www.tummy.com/articles/isolating-heavy-load/

Basically, work out if the culprit is CPU or IO, then work from there. Ask if you need guidance (in my case, `iostat -x 5` helped a lot).

**Comment by purcell** [comment]
> The cause is file descriptor limit.

Ah, that would totally make sense!

**Comment by purcell** [comment]
Also, thanks @silex.

**Comment by purcell** [comment]
@milkypostman So we hit the file descriptor limit again. Not sure what changes you made the first time, but here's what I did on the main MELPA server only:

In `/etc/security/limits.conf`, add:
```
melpa soft nofile 4096
melpa hard nofile 10240
```

To the end of all files matching `/etc/pam.d/common-session*`, added:
```
session required pam_limits.so
```

Verify with:
```
# su - melpa -c "ulimit -Sn"
4096
```

(This previously displayed 1024.)

These revised limits automatically don't seem to affect the `runit` process hierarchy immediately, so I had to restart the whole lot, and add `-o 4096` to the `chpst` invocation in `/etc/service/melpa/run`.

Can you incorporate the above into any provisioning script you use to build the server?
