### ISSUE TITLE
Melpa Appears to be Down

### ISSUE THREAD

**Issue by AshtonKem** [melpa/melpa#4156]
I cannot seem to load melpa.org, and [Is It Down](https://isitup.org/melpa.org) appears to agree with me.

**Comment by vishakhkumar** [comment]
Same here. Melpa is unavailable for me.

**Comment by liebe444ever** [comment]
Same, Melpa is down, and Melpa stable is available.

**Comment by der-Daniel** [comment]
same in Germany

**Comment by xuchunyang** [comment]
For what it's worth, there are two public ELPA mirrors. Both of them have served for several months.

- https://elpa.zilongshanren.com/
- https://mirrors.tuna.tsinghua.edu.cn/elpa/

For MELPA, the archive locations are:

- https://elpa.zilongshanren.com/melpa/
- https://mirrors.tuna.tsinghua.edu.cn/elpa/melpa/

It looks MELPA's web server is down, but its rsync service is still running, so the packages on these mirror should be up-to-date.

**Comment by 0xmohit** [comment]
I was wondering that it's only for me.  It seems that emacs should be able to handle the case when it's not able to communicate to the melpa host.  I don't have the exact error handy, but it's a case of not being able to get the archive and then trying to perform operations on it.  Which results in error messages that don't make much sense.

**Comment by lf94** [comment]
For people coming from search engines, how do you change to the archive URLs?

**Comment by pedros007** [comment]
> For people coming from search engines, how do you change to the archive URLs?

```
  (setq package-archives '(("gnu" . "http://elpa.gnu.org/packages/")
                           ("marmalade" . "http://marmalade-repo.org/packages/")
                           ("melpa" . "https://elpa.zilongshanren.com/")))
```

**Comment by lf94** [comment]
For those using spacemacs, go into your .spacemacs and find this:

```
(defun dotspacemacs/user-init ()
  "Initialization function for user code.
It is called immediately after `dotspacemacs/init'.  You are free to put almost
any user code here.  The exception is org related code, which should be placed
in `dotspacemacs/user-config'."
    ;; Add the code below here
)
```

and add this:

```
(setq configuration-layer--elpa-archives '(("melpa" . "https://elpa.zilongshanren.com/melpa/")))
```

**Comment by YayConnolly** [comment]
@lf94 on a fresh install of spacemacs develop branch with just that setting I get `error: Package 'package-build-' is unavailable` :(

**Comment by lf94** [comment]
> @lf94 on a fresh install of spacemacs develop branch with just that setting I get error: Package 'package-build-' is unavailable :(

Ah. Well that is for stable at least.

For develop...maybe that one option for alternative package repository works now (it's right above the user-init I think).

Oh, this one:

```
   ;; The default package repository used if no explicit repository has been
   ;; specified with an installed package.
   ;; Not used for now. (default nil)
   dotspacemacs-default-package-repository nil
```

**Comment by purcell** [comment]
Investigating now - sorry for the issues, folks. We've had a couple of problems over the last 2 days, which I have to assume are due to our switch over to the Caddy web server. The little server gets worked quite hard.

Separately I'm working on arranging a more official mirror, since I recognise that MELPA is increasingly relied upon by many people.

**Comment by purcell** [comment]
(MELPA Stable is hosted on a separate server, which is why the two package archives can be up/down independently.)

**Comment by seandjones92** [comment]
I'm seeing that MELPA is back up again. I was able to connect and download/install a package.

**Comment by sufyanadam** [comment]
Thank you for bringing it back online @purcell!

**Comment by hakuch** [comment]
It was briefly available for me, but it's down again.

**Comment by milkypostman** [comment]
sorry about this, we are having issues with our webserver but not clear what the issue is.

**Comment by zhengpd** [comment]
Melpa stable works but melpa.org is down again.

**Comment by der-Daniel** [comment]
yeah melpa is down again

**Comment by IvanMalison** [comment]
Are there any status updates on this issue?

**Comment by milkypostman** [comment]
Site appears up to us. The reason was a switch to caddy web server and user
limit of open files.

**Comment by jasonm23** [comment]
Anyone know of/have a "setting up a MELPA Mirror" guide?

Might be a useful addition to the README?

**Comment by vyp** [comment]
@jasonm23 https://github.com/melpa/melpa/issues/4157

**Comment by purcell** [comment]
@jasonm23 Short answer is that we have an official mirror now anyway, so setting one up yourself should be entirely redundant.

**Comment by hyiltiz** [comment]
melpa.org seems to be down from New York.

**Comment by IvanMalison** [comment]
@hyiltiz Probably best to open a new issue. This is from a year and a half ago.

**Comment by hyiltiz** [comment]
I did notice that I was going to dig up a grave. But since it is the same issue, and the original issue wasn't closed, I see little reason to spread information into two places.

**Comment by IvanMalison** [comment]
The original issue was closed.

**Comment by hyiltiz** [comment]
Oh, I am terribly sorry; I didn't notice it was closed then. I found that I was actually duplicating this:
https://github.com/melpa/melpa/issues/5339

Please close this issue. Thanks!
