### ISSUE TITLE
Document instructions and guidelines for setting up mirrors

### ISSUE THREAD

**Issue by 0xmohit** [melpa/melpa#4157]
https://melpa.org/ is currently unavailable so I can't say if it documents information on setting up mirrors, but https://github.com/melpa/melpa doesn't seem to.

If the information were readily available, *maybe* there would be folks willing to setup mirror sites which would (1) ease the load on the current server, (2) be helpful in cases such as https://github.com/melpa/melpa/issues/4156

**Comment by xuchunyang** [comment]
One easy way is using rsync. MELPA provides rsync access (see #4020) not long ago, the rsync locations are

    MELPA         rsync://melpa.org/packages/
    MELPA Stable  rsync://stable.melpa.org/packages/

**Comment by 0xmohit** [comment]
The point here was to make this information more *accessible*.  Search bug reports and pull requests isn't perhaps the best way to obtain information about setting up a mirror.

**Comment by zvbuhl** [comment]
What's the security situation of the mirrors? I'd hate to use a mirror only to find out that someone had, say, DDoSed melpa.org and then posted links to his own, insecure, mirrors …

(yes, the emacs package security situation is pretty dire to begin with — no reason to let it be worse though)

**Comment by purcell** [comment]
I'm going to request a mirror via mirrorservice.org or similar, so that we have at least one official mirror. I ultimately can't vouch for the security of any mirror, though. We probably need to work towards having fully-signed packages.

**Comment by favadi** [comment]
MELPA is very slow for me for last few days. I setup 2 mirrors for MELPA and MELPA stable using github pages:

- https://9bug.github.io/melpa-stable/
- https://9bug.github.io/melpa/

Currently the rsync interval is daily. Github pages downloading speed is much, much better than melpa.org.

**Comment by purcell** [comment]
Thanks, but I'd really discourage people from creating ad-hoc mirrors. We absolutely cannot vouch for their contents. I'm sorry that there are issues right now, but they will be addressed as soon as possible, and I'm also working to provision an official mirror.

**Comment by purcell** [comment]
More specifically, the most helpful response to MELPA being slow for you is to file an issue telling us about your Emacs version & config. I've also noticed slower responses recently, and I would love more information in order to take more informed action.

**Comment by purcell** [comment]
=> https://github.com/melpa/melpa/issues/4191

**Comment by purcell** [comment]
We now have official mirrors courtesy of mirrorservice.org:

http://www.mirrorservice.org/sites/melpa.org/packages/
https://www.mirrorservice.org/sites/melpa.org/packages/

http://www.mirrorservice.org/sites/stable.melpa.org/packages/
https://www.mirrorservice.org/sites/stable.melpa.org/packages/

Only the packages are mirrored, not the web site frontend itself, so you can use these URLs in your `package-archives` list, and they won't be useful in your browser.

`package.el` itself doesn't do a good job of handling multiple identical packages on mirrors, so I wouldn't recommend adding the mirror to your `package-archives` for day-to-day use: just if there are some server issues. The mirrors will be updated at least daily.

I'll document these mirrors in the README.
