### ISSUE TITLE
old-names not working: emacs-eclim 

### ISSUE THREAD

**Issue by CestDiego** [melpa/melpa#4159]
I get an error that `emacs-eclim` cannot be found when trying to install it. In melpa this has been `renamed` to just `eclim` and one can see there is this handler for old-names in the new recipe:

```
(eclim
 :fetcher github
 :repo "emacs-eclim/emacs-eclim"
 :files ("eclim*.el" "snippets")
 :old-names (emacs-eclim))
```

However it does install with `eclim` Just thought It would be useful to point this out.

**Comment by purcell** [comment]
Yeah, there's no `package.el`-level support for aliased/renamed packages, so our `:old-names` is really only to support redirecting the old web page at https://melpa.org/#/emacs-eclim .

**Comment by CestDiego** [comment]
Oh I didn't know this. Thanks for clarification

**Comment by purcell** [comment]
It means we can't perfectly migrate users when packages get renamed, and it also means that the latest package on MELPA Stable will be immediately renamed too, which some people might find a bit shocking!
