### ISSUE TITLE
SSL / gzip causing problem with package downloads in Emacs 24.5

### ISSUE THREAD

**Issue by glyph** [melpa/melpa#4187]
I am having a *really* hard time boiling this down to a reproducible use-case, but I have a script that re-installs a fresh copy of all my selected packages from (m)elpa, and it has been failing for the last couple of days with some gnarly errors.  Some representative examples:

```
Compiling /Users/glyph/.emacs.d/elpa/rainbow-delimiters-20160430.2358/rainbow-delimiters.el...

In toplevel form:
rainbow-delimiters.el:1:1:Warning: reference to free variable `v|>¾a'
rainbow-delimiters.el:1:19:Warning: reference to free variable `êI¤ß%Á'
rainbow-delimiters.el:1:62:Warning: reference to free variable `©'
rainbow-delimiters.el:1:68:Warning: reference to free variable
    `02¬±þlïpÍCt'
rainbow-delimiters.el:1:104:Warning: reference to free variable
    `Y&éºp »©P3'
rainbow-delimiters.el:1:135:Warning: reference to free variable `ÀM'
rainbow-delimiters.el:1:142:Warning: reference to free variable `¨{'
rainbow-delimiters.el:1:149:Warning: reference to free variable `£L£Ã®Ü'
rainbow-delimiters.el:1:176:Warning: reference to free variable `BDñ'
rainbow-delimiters.el:1:188:Warning: reference to free variable `Ù>'
rainbow-delimiters.el:1:199:Warning: reference to free variable `ª·¬èwÆ'
rainbow-delimiters.el:1:222:Warning: reference to free variable `yÊ'
rainbow-delimiters.el:1:229:Warning: reference to free variable `öcV@'
rainbow-delimiters.el:1:242:Warning: reference to free variable
    `zxÐ'
```

and

```
Compiling /Users/glyph/.emacs.d/elpa/ctable-20140304.1659/ctable.el...

In toplevel form:
ctable.el:1:1:Warning: reference to free variable `ÍKá'
ctable.el:1:18:Warning: reference to free variable `ÿÿ¯ú'
ctable.el:1:47:Warning: reference to free variable `HTTP/1\.1'
ctable.el:1:60:Warning: reference to free variable `OK'
ctable.el:2:1:Warning: reference to free variable `Accept-Ranges:'
ctable.el:2:16:Warning: reference to free variable `bytes'
ctable.el:3:1:Warning: reference to free variable `Content-Encoding:'
ctable.el:3:19:Warning: reference to free variable `gzip'
ctable.el:4:1:Warning: reference to free variable `Content-Type:'
ctable.el:4:15:Warning: reference to free variable `text/plain'
ctable.el:5:1:Warning: reference to free variable `Etag:'
ctable.el:5:7:Warning: reference to free variable `W/'
ctable.el:6:1:Warning: reference to free variable `Last-Modified:'
ctable.el:6:16:Warning: reference to free variable `Tue'
ctable.el:6:24:Warning: reference to free variable `Aug'
ctable.el:6:33:Warning: reference to free variable `22:22:44'
ctable.el:6:42:Warning: reference to free variable `GMT'
ctable.el:7:1:Warning: reference to free variable `Server:'
ctable.el:7:9:Warning: reference to free variable `Caddy'
ctable.el:8:1:Warning: reference to free variable `Strict-Transport-Security:'
ctable.el:8:28:Warning: reference to free variable `max-age=31536000'
ctable.el:9:1:Warning: reference to free variable `Vary:'
ctable.el:9:7:Warning: reference to free variable `Accept-Encoding'
ctable.el:10:1:Warning: reference to free variable `Date:'
ctable.el:10:7:Warning: reference to free variable `Mon'
ctable.el:10:24:Warning: reference to free variable `07:01:22'
ctable.el:11:1:Warning: reference to free variable `Transfer-Encoding:'
ctable.el:11:20:Warning: reference to free variable `chunked'
ctable.el:14:3:Warning: reference to free variable `'
ctable.el:14:17:Warning: reference to free variable `n'
ctable.el:14:24:Warning: reference to free variable `ÿ¤Y{oÛ8'
ctable.el:14:42:Warning: reference to free variable `ÿ\?bâP'
ctable.el:14:63:Warning: reference to free variable
    `¨¿ØîÝâ4îöÐG¤·è´DYÜH¢¢âú>ýÍPoN'
ctable.el:14:184:Warning: reference to free variable `´±Mþ8ÏßÌX'
ctable.el:14:213:Warning: reference to free variable `>|M¶Ù|ÃÚ'
ctable.el:15:1:Warning: reference to free variable `ÿüÞFé¿·'
ctable.el:15:38:Warning: reference to free variable `áÐÑo¸'
ctable.el:15:61:Warning: reference to free variable `ªõe=À'
ctable.el:15:90:Warning: reference to free variable `l'
ctable.el:15:97:Warning: reference to free variable `²'
ctable.el:15:103:Warning: reference to free variable `íy·U'
ctable.el:15:113:Error: Invalid read syntax: ") or . in a vector"
```

My suspicion is that `Content-Encoding: gzip` is something that Emacs is not *quite* ready to deal with.  Looking at files with `url-retrieve`, it looks like the buffer holding them is just gzip garbage until the last byte is received.

**Comment by glyph** [comment]
To make things even weirder, an interactive, GUI emacs seems to have this problem less than one invoked on the command line.

**Comment by glyph** [comment]
I've tested on both OS X and Linux, GNU emacs 24.5.1 in both places.

**Comment by glyph** [comment]
Attempting to upgrade to emacs 25 doesn't seem to help.  However, if I am careful to install it with gnutls support, (via `brew install emacs --devel --with-cocoa --with-librsvg --with-gnutls`), then my upgrade script reliably completes and installs all packages.  So this has something to do with the way that Emacs interfaces with a gnutls subprocess.  (Emacs 24's linked-in gnutls support is insecure because it never valdiates certificates, so I have it explicitly disabled even for builds where it works.)

**Comment by ryfow** [comment]
I owe you one, @glyph. Thanks a bunch.

**Comment by glyph** [comment]
@ryfow - No problem!  Was this actually helpful enough to diagnose the issue?  Because I could not figure out what the heck was going on, and I felt bad about submitting such a vague report ;)

**Comment by ryfow** [comment]
I have no idea about that, but using that brew command to reinstall emacs was what I needed to get my busted install working again.

**Comment by purcell** [comment]
Hmm, weird. We've been gzipping elisp and tar files for a long time now, and recently switched to using Caddy for our static file serving. Not sure what to conclude from this issue you've experienced.

**Comment by glyph** [comment]
@purcell - I basically have a shell script that basically does `emacs -batch -eval '(progn (package-refresh-contents) (okay-now-update-some-packages))'.  Decoupling this from other bits of my customization would be hard, but if you just `(package-install)` a bunch of stuff in a row you should eventually see this.  `tls-program` is set to `(list (format "gnutls-cli --x509cafile %s -p %%p %%h" trustfile))` since that's probably relevant...

**Comment by glyph** [comment]
@ryfow - are you seeing the same issue that I am, in terms of corrupt `.el` files showing up?

**Comment by ryfow** [comment]
I was getting errors about invalid tarballs and errors that made it look
like emacs was trying to parse http headers as elisp.

At first I was trying to get spacemacs to update packages, and hen I tried
a fresh spacemacs install with no luck. Reinstalling emacs with your brew
command made things work.

**Comment by milkypostman** [comment]
I don't understand fully ssl and all that jazz but tls is some weird part
of it correct? So I wonder if now caddy only support certain protocols
(I.e. Now ONLY tls) and so the old built in ssl library doesn't work
properly. ?

**Comment by glyph** [comment]
@milkypostman https://thoughtstreams.io/glyph/there-is-no-ssl/ :)

**Comment by glyph** [comment]
@ryfow - OK, that's the same issue that I am having.

**Comment by glyph** [comment]
Based on when this started happening for me, and the PRs in the issue tracker, it looks like the introduction of Caddy seems to coincide with the errors here.

**Comment by glyph** [comment]
I don't think that this is a bug in Caddy, but rather a bug in Emacs that Caddy's correct-but-different behavior is now exposing.

**Comment by glyph** [comment]
@purcell @milkypostman - I don't have access to the behavior of the old site (obviously) but I think this has to do with the fact that when I do [`http get`](https://github.com/jkbrzt/httpie) on i.e. https://melpa.org/packages/deferred-20160109.2046.el, I see `Content-Encoding: gzip`.  I'm not downloading a `.el.gz` *as* a `.el.gz`, the webserver is compressing it on the fly.  I don't think Emacs can handle this correctly, at least, not at the same time as HTTPS (TLS)

**Comment by purcell** [comment]
@glyph That's what it did before, too. It'll only encode as gzip if the client declared support for it in the request's `Accept-Encoding` header.

**Comment by glyph** [comment]
@purcell hrm. Do you know of any way I can turn that off locally for `package.el` to test?

**Comment by glyph** [comment]
With this change:

```diff
diff --git a/Emacs/firstparty/scripts/pkg-load.el b/Emacs/firstparty/scripts/pkg-load.el
index 159c898..126d63d 100644
--- a/Emacs/firstparty/scripts/pkg-load.el
+++ b/Emacs/firstparty/scripts/pkg-load.el
@@ -1,5 +1,6 @@
 (add-to-list 'load-path "../")
 (require 'url-http)
+(setf url-mime-encoding-string "")
 (require 'pkg-installed)
 (message " *** RESTORING saved installed packages")
 (glyph-setup-restore-saved-installed)
```

my personal update script works reliably again.

So yeah; something to do with gzip encoding.  At least I have a workaround now for my Ubuntu machines where I can't easily update to the Emacs release candidate yet! :)

**Comment by paulyoung** [comment]
@glyph where did you make that change? I'm using Spacemacs and trying to work around this issue.

**Comment by glyph** [comment]
@paulyoung sorry, that's a diff on an elisp script that isn't public, and depends on a bunch of junk in my home directory.  The relevant thing is that you can put

```elisp
(require 'url-http)
(setf url-mime-encoding-string "")
```

at the top of your `~/.emacs` and it will work around this issue.

**Comment by paulyoung** [comment]
Thanks @glyph!

I ended up putting this at the top of `~/.emacs.d/init.el` and then ran `emacs --insecure` and everything appears to be working!

**Comment by glyph** [comment]
@paulyoung Oh my goodness.  Do not pass `--insecure` to Emacs, ever.  You are putting yourself at significant risk by doing so.  [More details are here.](https://glyph.twistedmatrix.com/2015/11/editor-malware.html)

**Comment by purcell** [comment]
As noted in #4191, we've now reverted MELPA to nginx, with further SSL tweaks to get an A+ rating on the SSLLabs test. Would you mind testing again without your workarounds and confirm that things are working fine for you?

**Comment by glyph** [comment]
@purcell - I reverted my workaround, found a machine I hadn't upgraded to 25 yet, and it looks like it's working again.  No idea why, given that the responses look substantially the same in an HTTP client.  Let me know if you need any other testing!

**Comment by purcell** [comment]
Great, thanks. While I wish it were practical to do so, I'm wary of trying to track down exactly why things weren't working.
