### ISSUE TITLE
MELPA currently slow for some people

### ISSUE THREAD

**Issue by purcell** [melpa/melpa#4191]
Mentioned [here](https://github.com/melpa/melpa/issues/4157#issuecomment-243326501). Also issues with gzip encoding + SSL for [some people](https://github.com/melpa/melpa/issues/4187). Feels like we should consider walking back our Caddy setup to the previous Nginx one, even though there will be some work to set up `letsencrypt` manually.

If you're having this issue, please post your Emacs platform and version here.

**Comment by 0xmohit** [comment]
There isn't much manual work in setting up letsencrypt with nginx.  The steps documented [here](https://www.nginx.com/blog/free-certificates-lets-encrypt-and-nginx/) work pretty well.  There aren't issues in setting up automatic cert renewal either.

**Comment by favadi** [comment]
For the last few days, I have many errors with melpa. Most of the times I got "Required package `something' is unavailable". Sometimes it is "invalid character" like #4187. But I can't figure out a way to reproduce it reliable.

> If you're having this issue, please post your Emacs platform and version here.

- OS: OS X 10.11.6
- Emacs version: 24.5.1

I have no error when rsync and serving MELPA in a local web server or Github pages as mentioned earlier.

**Comment by purcell** [comment]
Super, thanks for the details. I run nginx with letsencrypt on other servers, so I'm familiar with the process, but the work still needs to be done. What do you think, @milkypostman?

**Comment by milkypostman** [comment]
I think it would be nice if we could do the same thing we do now. Rather
than proxy just run nginx as the user?

That's the only thing I'd like to preserve. A little bummed caddy doesn't
seem to be working out. Are we sure that's the problem? It doesn't seem
THAT much slower to me. Although the first load can seem to hang a bit.

**Comment by purcell** [comment]
I'm a bit bummed too, but I feel like one way or another, Caddy must be the problem -- we didn't see these issues previously. Either the locked-down SSL config it uses isn't compatible with one or more of the Emacs TLS methods, or there are some edge cases for content negotiation.

If we revert to nginx with letsencrypt.sh, we should be able to get the old proven behaviour with the benefit of cert auto-renewing. It would certainly be possible to run nginx as the melpa user, as long as it can read the private key generated by letsencrypt.sh.

My own config snippet for this is:
```
       ssl_certificate /etc/letsencrypt/certs/yourdomain.org/fullchain.pem;
       ssl_certificate_key /etc/letsencrypt/certs/yourdomain.org/privkey.pem;
       ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
       ssl_ciphers 'kEECDH+ECDSA+AES128 kEECDH+ECDSA+AES256 kEECDH+AES128 kEECDH+AES256 kEDH+AES128 kEDH+AES256 DES-CBC3-SHA +SHA !aNULL !eNULL !LOW !MD5 !EXP !DSS !PSK !SRP !kECDH !CAMELLIA !RC4 !SEED';

       ssl_prefer_server_ciphers on;

       location /.well-known/acme-challenge/ {
         alias /etc/letsencrypt/.acme-challenges/;
       }
```

then I have a weekly cron job to renew:
```
% cat /etc/cron.weekly/letsencrypt
#!/bin/sh -e

cd /etc/letsencrypt
./letsencrypt.sh --cron
/etc/init.d/nginx reload
```

**Comment by paulyoung** [comment]
I think this explains my experience in https://github.com/syl20bnr/spacemacs/issues/6988

**Comment by paulyoung** [comment]
> If you're having this issue, please post your Emacs platform and version here.

- **OS:** OS X El Capitan 10.11.6 (15G1004)
- **Emacs:** 24.5.1
- **Spacemacs:** 0.105.22
- **Spacemacs branch:** master (rev. 9f9faa4)

**Comment by milkypostman** [comment]
Working on this issue now. Rolling back to nginx but need to update certs.

**Comment by milkypostman** [comment]
main melpa site is back to nginx. configs still need storing but will do this later tonight. 

will update stable later too.
