### ISSUE TITLE
Can't install magic

### ISSUE THREAD

**Issue by mok0** [melpa/melpa#4195]
When trying to install `magit` from stable I get this error:

```
https://stable.melpa.org/packages/magit-2.8.0.tar: Not found 
```

**Comment by syohex** [comment]
I cannot reproduce this issue. I can access `https://stable.melpa.org/packages/magit-2.8.0.tar` and get tar file. Can you access above url with other than Emacs(like `curl`, web browser etc) ? If you can access it, I suppose you had temporary network issue.

Please retry after `package-refresh-contents`.

**Comment by mok0** [comment]
I had done `package-refresh-content` but on your suggestion I tried again and now it worked? I did have a network connection, I can't explain what happened. Thanks for your time!
