### ISSUE TITLE
Will that be a good idea to use melpa and melpa-stable archive at the same time?

### ISSUE THREAD

**Issue by zhfuzzy** [melpa/melpa#4202]
With the great melpa, I'am able to take advantage of tons of emacs packages with ease.

There really are some package I do not use very often(less often than the package upgrade). It will be rational to use the stable version of those packages or else It will be realy scary watching them upgrade and upgrade from day to day without using them(melpa package are high quality by themself, usually it's the awkard customization I made cause the crash); At the same time, It's ok to stay at the bleeding edge for those package I use a lot.

Currently mixing melpa and melpa-stable are not possible out of the box, for the reason that `version-list-<` used in the package upgrade logic will mark that melpa package(versioned by date) is newer than melpa-stable(versioned by three digit), but It will be easy to modify the package upgrade logic and avoid upgrade stable package to unstable package(add three line to `package-menu--find-upgrades` will do, see [gist](https://gist.github.com/zhfuzzy/6166e44e038c16d55aa6d48436b5b271) ).

My question is: considering the dependency problem, will there be trouble if I just using stable package?

**Comment by purcell** [comment]
This is possible - check out the variable `package-pinned-packages`.

Note, though, that none of the MELPA maintainers use MELPA Stable, so I can't comment on whether or not it's safe to mix packages from the two archives. In my experience snapshot packages are no more likely to be broken or incompatible with each other than "stable" packages.

**Comment by zhfuzzy** [comment]
thanks for the reply, seems I should learn more about `melpa` and `package.el`'s internal.
