### ISSUE TITLE
Question regarding deleted tags

### ISSUE THREAD

**Issue by rnkn** [melpa/melpa#4205]
Say I push tag `v1.1` to GitHub and a MELPA-stable builds a package for this tag, but then I realise I need to fix something. So I delete tag `v1.1`, do the fix and push the same `v1.1` tag to a later commit.

Will MELPA-stable rebuild at this later commit for `v1.1` or do I need to tag something higher like `v1.2`?

**Comment by purcell** [comment]
MELPA should rebuild, but the right thing to do is of course to push a new version so that people who may have installed the "first" v1.1 package will know there is a new version.

**Comment by rnkn** [comment]
Yeah I could but
🏍🔥🔥🔥

**Comment by vyp** [comment]
You should just release a 'patch' version like `v1.1.1` instead.  I know semantic versioning is controversial, I don't want to start anything here but see http://semver.org/ for more of what I mean by 'patch' version. Then your next 'minor' version will be `v1.2` regardless of how many patch versions `v1.1` had. :)

**Comment by rnkn** [comment]
Hmm pushing the new tag this didn't work. https://github.com/rnkn/olivetti latest tag is `v1.5.5` but MELPA-stable is still at `v1.5.4` (which is built from a now squashed commit).

Sorry could you trigger a rebuild of the package please?
