### ISSUE TITLE
goose-theme source has disappeared

### ISSUE THREAD

**Issue by mdorman** [melpa/melpa#4207]
The recipe is `(goose-theme :repo "thwg/goose-theme" :fetcher github)`, but [that user id](https://github.com/thwg/) appears to not exist any longer.

**Comment by purcell** [comment]
I've fixed this by deleting the recipe, in the absence of more information about where the theme might have moved to... :-)

**Comment by mdorman** [comment]
Yeah, I did do a little googling, couldn't seem to find an alternative source.

**Comment by purcell** [comment]
We might have a clone of the original repo on our server, if you're interested in hosting a fork.

**Comment by tokenrove** [comment]
This user and repo [appear to be back](https://github.com/thwg/goose-theme), BTW.  Just noticed this because my configuration depended on goose-theme and failed on a new machine.
