### ISSUE TITLE
helm-bibtex unavailable

### ISSUE THREAD

**Issue by mok0** [melpa/melpa#4212]
I am trying to install org-ref, but I get the error message:

```
Package 'helm-bibtex-2.0.0' is unavailable
```

I also can't see helm-bibtex in the package list.

**Comment by vyp** [comment]
org-ref depends on version 2.0.0 of it (even though [helm-bibtex](https://github.com/tmalsburg/helm-bibtex) has no tags):
https://github.com/jkitchin/org-ref/blob/1ddb704f15e03ef9da8379068df60b935fa59dd8/org-ref.el#L9

I think when a package repository has no (version number) tags in it, it isn't available for melpa stable. Maybe it is possible to let package.el know to get the non-stable version if a stable version doesn't exist? (I'm not sure.) Otherwise perhaps you could ask the author of helm-bibtex to tag a version.

**Comment by purcell** [comment]
Correct. `helm-bibtex` needs a tag -- can you add one please, @tmalsburg? :-)

Your only other solution, @mok0, would be to enable both MELPA and MELPA Stable, but pin most packages to MELPA Stable using the `package-pinned-packages` variable. That's a crappy workaround, though, so hopefully @tmalsburg can help you out here.

**Comment by mok0** [comment]
Thanks @purcell, tt works when I activate both melba and melba-stable repos and installed the version available from there. I did get a number of lisp compilation errors though, but I am testing the installation now.

**Comment by purcell** [comment]
For what it's worth, I think most people use only MELPA, including us MELPA maintainers. We're not really big fans of MELPA Stable, even though we run it. :-)

**Comment by mok0** [comment]
Oh, thanks, I'll use MELPA instead then.

**Comment by tmalsburg** [comment]
Sorry I'm not familiar with this.  Are we talking about git tags?  Do we need that for MELPA stable?  Helm-bibtex doesn't really have a stable and an unstable version and the most recent version is usually the only recommended version.  I think a lot of smaller projects work that way.  Does that mean that I would have to update the tag every time I make a commit?

**Comment by vyp** [comment]
> Are we talking about git tags?

Yes. Then melpa automatically takes care of it (as long as it looks like a version number). (No need to 'update' on every commit.)

And it is your choice of course. @mok0 Seems to have resolved it anyway by just using melpa as @purcell recommended.

Also @purcell, maybe the `(helm-bibtex "2.0.0")` requirement in org-ref should be changed to `(helm-bibtex "0")`? Not sure if that would make any difference though, I think melpa would still need to be activated, not just melpa-stable, right?

**Comment by purcell** [comment]
> Also @purcell, maybe the (helm-bibtex "2.0.0") requirement in org-ref should be changed to (helm-bibtex "0")? Not sure if that would make any difference though, I think melpa would still need to be activated, not just melpa-stable, right?

Correct. If a package is not available in MELPA Stable, even a dependency on version "0" of it will not make it appear! :-)

**Comment by tmalsburg** [comment]
I added a tag in the git repo.  Is there anything else I need to do or will MELPA automatically generate the stable version?

**Comment by vyp** [comment]
@tmalsburg Nothing else to do. :+1:

**Comment by purcell** [comment]
Thanks! - https://stable.melpa.org/#/helm-bibtex
