### ISSUE TITLE
olivetti stable stuck on old tag

### ISSUE THREAD

**Issue by rnkn** [melpa/melpa#4221]
Package olivetti is stuck on `v1.5.4` on MELPA-stable when the latest tag is `v1.5.5`. A couple of days of builds have happened since.

I think this happened due to a rebase that squashed the tagged commit.

Are you able to trigger a rebuild please?

**Comment by purcell** [comment]
No, that's because the latest tag is actually `v.1.5.5`, which our version tag regexp doesn't match. You should change it to `v1.5.5`.

**Comment by rnkn** [comment]
Boy is my face red. Thanks.

**Comment by purcell** [comment]
No problem. I still had a terminal open on the server so I rebuilt it and that's working now... :-)

**Comment by rnkn** [comment]
Wonderful, thanks so much!
