### ISSUE TITLE
Download stats dead since 2016-09-06

### ISSUE THREAD

**Issue by cpitclaudel** [melpa/melpa#4232]
Looks like download stats have not been updated since 2016-09-06 (download counts have not changed for any packages in the last 4 days). 

Can I help?

**Comment by purcell** [comment]
Duplicate of #4231.

**Comment by cpitclaudel** [comment]
Looks like we posted these at roughly the same time :) Sorry for the noise!

**Comment by purcell** [comment]
All good. :-)
