### ISSUE TITLE
If the package on github download fork and clone from github?

### ISSUE THREAD

**Issue by voltecrus** [melpa/melpa#4239]
It looks like packages from MELPA are just folders with version numbers attached to them.

Suppose I tweaked a few things inside the `user-emacs-directory/elpa/package` and got an enhancement to work.

Now, in order to make it publicly available I have to

1) Find the corresponding github repo
2) Fork/clone
3) Move my changes to the forked repo
4) Create a pull request

That seems redundant/inconvenient when the changes are right there inside elpa. Should it be that if the package is on github clone/fork it automatically and install that locally? Is there a reason it wouldn't work?

I'm aware of github-clone.el and advising functions. I know that I could hack it locally, I'm interested if there are any thoughts on the above approach. If it's not the right place to ask that type of question let me know.

**Comment by voltecrus** [comment]
This looks like an enhancement to package.el/other facilities that emacs uses to install packages.

**Comment by syohex** [comment]
Please see [el-get](https://github.com/dimitri/el-get/) or [cask](https://github.com/cask/cask/).

**Comment by voltecrus** [comment]
@syohex whoa thanks
