### ISSUE TITLE
Preparing to migrate `puml-mode` and `plantuml-mode`

### ISSUE THREAD

**Issue by skuro** [melpa/melpa#4310]
Hey there,

as part of an active effort to merge efforts in supporting PlantUML mode in Emacs, [it was agreed](https://github.com/zwz/plantuml-mode/issues/8) to have one single `plantuml-mode` major mode, which will use the current `puml-mode` repository.

The merge will be finalized at the end of the week, when I will proceed with the following actions:

- merge the renamed mode into `master`
- rename my GitHub repository (`skuro/puml-mode` -> `skuro/plantuml-mode`)
- open a PR to melpa to delete [`puml-mode`](https://github.com/melpa/melpa/blob/master/recipes/puml-mode) and update [`plantuml-mode`](https://github.com/melpa/melpa/blob/master/recipes/plantuml-mode) to point it to my repository

I'd like to know from MELPA if I'm missing anything here, if there's any extra detail that you guys will need to approve the move and, ultimately, if I'm good to go with the merge.

Thanks

**Comment by syohex** [comment]
I suppose you should check [spacemacs](https://github.com/syl20bnr/spacemacs/) too. Because many users use spacemacs and it uses `puml-mode` now. (This is not related to MELPA, sorry).

**Comment by skuro** [comment]
@syohex good point, I'll take that offline though as it's not 100% MELPA related. Thanks!

**Comment by skuro** [comment]
Ok, given the silence I gather that I didn't raise any eyebrow from MELPA. Closing for now.
