### ISSUE TITLE
melpa isn't picking up the description of ergoemacs-mode

### ISSUE THREAD

**Issue by mattfidler** [melpa/melpa#4316]
I'm not sure why, the description field for ergoemacs-mode is missing for melpa:

![image](https://cloud.githubusercontent.com/assets/514778/19334812/630d480a-90c4-11e6-8c7d-2d0aaff3edc7.png)

Even though it follows the package requirements: 

![image](https://cloud.githubusercontent.com/assets/514778/19334839/93140bb0-90c4-11e6-9d07-3feae2c22c8b.png)

It used to work (and still works in melpa stable).  I think this is a bug...

See https://github.com/ergoemacs/ergoemacs-mode/issues/429

**Comment by syohex** [comment]
https://github.com/ergoemacs/ergoemacs-mode/pull/433

Please write package information correctly.

**Comment by mattfidler** [comment]
Thank you.
