### ISSUE TITLE
Add reviews for each package?

### ISSUE THREAD

**Issue by xuhdev** [melpa/melpa#4349]
I suggest we set up a forum such as [discourse](https://www.discourse.org/) and create a thread for each package, for users' comments and reviews. A link to the corresponding thread on each of the package pages on melpa.org is made available for easier access.

Discourse also supports [embedding](https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963), so on each package page embedding a short preview of the thread is also possible.

**Comment by purcell** [comment]
It's something I've thought about previously, but running a community discussion site is rather different from running a package archive, and it comes with additional work, particularly moderation.

**Comment by milkypostman** [comment]
This was discussed before but I prefer we don't do this. People who have
comments should address them with the packages authors.

There may be some packages worthy of a whole discussion section very few
are. And comment sections are always the worst part of the internet.

**Comment by tarsius** [comment]
We could link to the corresponding page on the Emacswiki instead. I have some code that can guess the appropriate page in most cases and also a list of manual mappings which I created when I first started working on the Emacsmirror.

**Comment by purcell** [comment]
Given that we're not keen on integrating this here, I'm going to close this. I'm also -1 on linking to Emacswiki for packages: I'd rather provide better support for exposing website/URL metadata embedded by authors in their packages.
