### ISSUE TITLE
aurora-theme repository no longer exists

### ISSUE THREAD

**Issue by mdorman** [melpa/melpa#4356]
https://github.com/xzerocode/aurora-theme now gives a 404

**Comment by syohex** [comment]
Can we use https://github.com/purcell/aurora-theme instead of it ?

**Comment by purcell** [comment]
Deleted. I'm not going to maintain a fork, but if anyone wants to take over maintainership, we can resurrect the recipes and point them at the new locations.

**Comment by mahaarbo** [comment]
Has anyone taken over ownership of the theme? I've [forked](https://github.com/mahaarbo/aurora-theme) the repo, and can try to maintain it. The theme has been my favorite for quite some time, and it would be convenient if it was back up on melpa.

**Comment by f1729** [comment]
Owner here, sorry for that, coming soon I will re-publish the theme with the new dark version.
