### ISSUE TITLE
hipster-theme repository no longer exists

### ISSUE THREAD

**Issue by mdorman** [melpa/melpa#4357]
https://github.com/xzerocode/hipster-theme, like aurora-theme's repository, is gone.

**Comment by syohex** [comment]
Can we use https://github.com/purcell/hipster-theme instead of it ?

**Comment by purcell** [comment]
Deleted. I'm not going to maintain a fork, but if anyone wants to take over maintainership, we can resurrect the recipes and point them at the new locations.

**Comment by redbeardcreator** [comment]
I don't know anything about hosting and/or maintaining a package for Emacs, but hipster is my favorite Emacs theme and it I miss having it in melpa, so I will dip my to in these waters and offer to take it over. I will likely need help or pointers to where I can find help/directions/documentation.

As a start, I've cloned https://github.com/purcell/hipster-theme to https://github.com/redbeardcreator/hipster-theme. Where do I go from here?

**Comment by purcell** [comment]
First choice would be to drop the author an email. If you can't get a reply, I'm happy to accept a pull request to change the recipe to point at your fork.
