### ISSUE TITLE
Wrong url while trying to get melpa packages

### ISSUE THREAD

**Issue by Narven** [melpa/melpa#4358]
Currently when I try to `list-packages` I get this error:

```
error in process filter: Error retrieving http://melpa.milkbox.net/packagesarchive-contents (error http 404) [2 times]
```

clearly there is a problem with the url, it should be `http://melpa.milkbox.net/packages/archive-contents`, how can I change this?

This is my only configuration related to melpa

```
(add-to-list 'package-archives
             '("melpa-stable" . "https://stable.melpa.org/packages/") t)
```

**Comment by syohex** [comment]
Do you have old byte-compiled file ? I cannot reproduce your issue with above configuration. But I can get 404 response with following configuration(remove last slash).

```lisp
(add-to-list 'package-archives
             '("melpa-stable" . "https://stable.melpa.org/packages") t)
```

However I got following message. Domain is `https://stable.melpa.org/` not `http://melpa.milkbox.net/`

```
error in process filter: Error retrieving: https://stable.melpa.org/packagesarchive-contents (error http 404) 
```

**Comment by purcell** [comment]
Or maybe an old customization preferences file?

**Comment by milkypostman** [comment]
Which Emacs version?

**Comment by Narven** [comment]
25.1.1

Its fixed now.

`(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))`
