### ISSUE TITLE
Add flycheck-package to PR checklist

### ISSUE THREAD

**Issue by alphapapa** [melpa/melpa#4361]
Despite adding checks for things like function names starting with the package prefix, I still see @syohex having to tell people to fix these things himself.  The pull request checklist points people to `CONTRIBUTING.md`, which mentions `flycheck-package`, but people are still not doing it.

Therefore I suggest adding something like this to the PR checklist template:

> I have run `flycheck-package` on the files in my package and fixed all warnings and errors.

Hopefully that would get people to actually do it and save you guys a lot of time and typing.  :)

**Comment by purcell** [comment]
Yeah, really good idea. Ultimately, we plan to integrate `package-lint` into MELPA, but this would be a good step in the meantime. One issue is that `flycheck-package` only activates itself when there's a `Package-Requires:` or `Package-Version:` header, so sometimes users won't see its feedback. Any ideas about how to handle that?

**Comment by alphapapa** [comment]
Here are some ideas I thought of:

1.  Change the conditions `flycheck-package` looks for to increase the probability it will activate without the user making changes for its sake, i.e. look for more common headers like `Author:`.
2.  Instruct the user to add at least one of the specific headers already required by `flycheck-package` in a separate checklist item.  That would turn the 2-item checklist into a 4-item one, but that seems okay to me.
3.  Add a command to `flycheck-package` to enable it or run it manually.  Then add a checklist item instructing the user to use that, and let the user discover that it happens automatically after they add the necessary headers (which packages may eventually have anyway).

I think I would lean toward a combination of 1 and 2: have `flycheck-package` activate on `Author:` or `Url:` headers, add a checklist item for those headers (which are desirable anyway), and add a checklist item for fixing errors and warnings marked by `flycheck-package`.  This would avoid requiring headers that may not be strictly necessary (e.g. `Package-{Requires,Version}`), and would naturally cause `flycheck-package` to be activated.

**Comment by Fanael** [comment]
> `flycheck-package`

Do you mean `package-lint`? `flycheck-package` doesn't really do anything useful anymore.

> have `flycheck-package` activate on `Author:` or `Url:` headers

+1 from me. I'd add `Version:` to this list, as looking for `Package-Version:` but not `Version:` seems pretty silly.

**Comment by Fanael** [comment]
With purcell/package-lint@e7c411ecc it's possible to force `package-lint` to check files even if they have no `Package-{Version,Requires}`, by passing non-nil as the second argument to `package-lint-buffer`.

**Comment by purcell** [comment]
> > have flycheck-package activate on Author: or Url: headers
> 
> +1 from me. I'd add Version: to this list, as looking for Package-Version: but not Version: seems pretty silly.

I'd be +1 for `Version`, maybe, but it's common to find the usual keywords in the headers of secondary files for packages, and `package-lint` then shouldn't complain about those files if it finds errors such as forgetting to include `Package-Requires` header for `cl-lib` where applicable.

**Comment by alphapapa** [comment]
> package-lint then shouldn't complain about those files if it finds errors such as forgetting to include Package-Requires header for cl-lib where applicable.

I guess the only solution there is to determine whether a file is a secondary one, but that seems like a messy prospect.  But IIUC, `package-lint` is currently unlikely to be activated in a secondary file, right?  That seems like another problem that it would be good to fix, otherwise only the most attentive authors will even run it on their secondary files, and that leaves MELPA maintainers to check those files manually.

I suppose one potential heuristic to determine whether a file is a secondary one would be to consider the `.el` file with the shortest name in the directory to be the primary one.  I guess that wouldn't work well in very large packages that have subdirectories, but...one step at a time?  :)  

Well, I'm just throwing out ideas.  I see how much work you put into curating MELPA and I wish more of it were automated to ease your burden.  Thanks.

**Comment by purcell** [comment]
> With purcell/package-lint@e7c411e it's possible to force package-lint to check files even if they have no Package-{Version,Requires}, by passing non-nil as the second argument to package-lint-buffer.

Yeah, probably `package-lint` itself should always lint the file as requested. We should probably have it expose a `does-this-look-like-a-package` function which `flycheck-package` can use to decide whether or not to lint the current buffer fully.

**Comment by purcell** [comment]
I changed `package-lint` such that `Version:` headers also trigger linting, but I'm actually starting to think that the right thing to do is just unconditionally enable it so that `flycheck-package` always treats the current file as a potential package. Users can suppress this when working on their `init` files if they like.
