### ISSUE TITLE
Let's remove color-theme

### ISSUE THREAD

**Issue by tarsius** [melpa/melpa#4371]
Emacs gained support for "deftheme" color themes in v24.1 released in 2012. Can we remove the old `color-theme` now? (And `color-theme-buffer-local` too.)

**Comment by purcell** [comment]
It has lots of downloads, and they can't all be due to confusion. I suspect that lots of people must be using it for some of the very many themes bundled into it. I'm wary of removing it.

**Comment by tarsius** [comment]
Are those recent downloads?

**Comment by purcell** [comment]
Good question. Not sure, tbh. I'd like to update our download tracker so we can generate bar charts for that sort of thing.

**Comment by tarsius** [comment]
Okay, I retract that one.
