### ISSUE TITLE
Let's remove marmalade

### ISSUE THREAD

**Issue by tarsius** [melpa/melpa#4372]
I consider the Marmalade Elpa archive to be unmaintained (and am rather annoyed by how Nic has handled that, i.e. just keeps [ignoring requests for years](https://github.com/nicferrier/elmarmalade/issues)). So `marmalade` is also obsolete and should be removed. If someone has a different opinion on whether Marmalade is still maintained, then they can just get `marmalade` from ... well Marmalade.

**Comment by purcell** [comment]
I agree that it's crappy, and I'd be happy for us to remove this package, but more generally I wonder whether we should ever bother removing packages unless they're actually unusable. There are thousands of packages here, after all, and presumably they were all added because somebody wanted them.

**Comment by tarsius** [comment]
> generally I wonder whether we should ever bother removing packages...

I think we should, but I have no problem with you rejecting some of my proposals. This should be decided on a case by case basis, I think.

> ...unless they're actually unusable

This interface to Marmalade is actually for the old node.js-base Marmalade. It won't work with the current Marmalade. So this couldn't be more obsolete and removing it is the only sensible thing to do.

**Comment by purcell** [comment]
> So this couldn't be more obsolete and removing it is the only sensible thing to do.

Oh, in that case, yes - go for it.

**Comment by purcell** [comment]
Thanks. :-)
