### ISSUE TITLE
mmm-jinja2, salt-mode: repository no longer exists

### ISSUE THREAD

**Issue by mdorman** [melpa/melpa#4424]
The recipe(s) point to https://github.com/beardedprojamz/mmm-jinja2 and https://github.com/beardedprojamz/salt-mode, respectively, but https://github.com/beardedprojamz as a whole is gone.

**Comment by syohex** [comment]
Should we switch them to emacs mirror or remove recipes ?

- https://github.com/emacsmirror/salt-mode
- https://github.com/emacsmirror/mmm-jinja2

**Comment by purcell** [comment]
@mdorman Would you perhaps be willing to email the author and ask him if he has moved the code to another account or hosting service? His email address is visible at https://github.com/emacsmirror/salt-mode/blob/master/salt-mode.el

If he has not, and you're a happy user of these packages, you might like to volunteer to maintain them.

**Comment by mdorman** [comment]
Hmm, that plus a little googling suggests that he renamed his github account to @deybhayden (if you go back far enough in his commit history, you can see the merges for salt-mode and mmm-jinja2), though the repositories in question aren't present in that new account.  @deybhayden did you move them elsewhere, and/or would you object to them being kept in melpa via emacsmirror?

(And I'm not actually a user of these packages, I just handle generating the expressions for emacs packages for nix, so I get errors on stuff that's no longer available).

**Comment by tarsius** [comment]
> or would you object to them being kept in melpa via emacsmirror

If we go down that road, then I would move the repositories to the Emacs Orphanage, and re-mirror from there. Melpa should then also get the packages from the orphanage directly, instead of using the mirror on the Emacsmirror

**Comment by purcell** [comment]
I've removed those recipes. I'd like an actual user to step up and help decide what to do about the code having disappeared; ideally someone who would take over maintainership.

**Comment by syohex** [comment]
Should we re-add those recipes(use emacsmirror  instead of original repository) ? This change breaks spacemacs(https://github.com/syl20bnr/spacemacs/issues/8225).

**Comment by purcell** [comment]
I've left a comment on that spacemacs issue. I'd like a user to step up to maintain those packages, rather than us scramble to patch things.

**Comment by glynnforrest** [comment]
@purcell @syohex I'd like to maintain these packages, and I use salt-mode myself.

I've never maintained an emacs package before, but willing to learn. I would guess the next steps are:

- create new upstream repos under my account
- indicate they now have a new maintainer
- resubmit to melpa

Am I missing anything?

**Comment by tarsius** [comment]
> create new upstream repos under my account

You can do so simply by forking the repositories from the emacsmirror. I will then delete those repositories and recreate them to be forks of your repository instead of the other way around.

**Comment by glynnforrest** [comment]
@tarsius repositories are here:

https://github.com/glynnforrest/mmm-jinja2
https://github.com/glynnforrest/salt-mode

**Comment by tarsius** [comment]
Hm, I just deleted the mirror repositories but now your repositories are reported as having been forked from some random fork. It might be better if you deleted your repositories and re-create them from scratch to make those bogus fork relation ships go away.

**Comment by tarsius** [comment]
I have merged your pr's because the mentioned issue does not really matter to Melpa. But please still fix the fork relationships by recreating the repositories. (And mention here when you have done so, so that I can do the same for the Emacsmirror.)

**Comment by glynnforrest** [comment]
Thanks for merging @tarsius, I've recreated repositories for them both now.
