### ISSUE TITLE
quicksetindent

### ISSUE THREAD

**Issue by SteveJobzniak** [melpa/melpa#4456]
One of Emacs' greatest strengths, the per-mode indentation settings, is also a great weakness. It's complicated to set up unified indentation across all of your filetypes. Newcomers have to scour the net for old, partial lists of what variables to use for configuring each mode, and where and how to put those configurations. And they end up with partial configurations where only a few of their modes are affected.

I compiled an up-to-date list of all variables, and the great thing about these is that they're all pretty standardized by now. New modes usually stick to using one of these. So this list should stay universal for a long time.

I then put it all into a package which lets you easily set the indentation variables either globally or locally per-buffer, with a single command.

So somebody who wants a global default of 4 spaces, no tabs, would just add the following three lines to their dotspacemacs user-config:

```emacs-lisp
  (require 'quicksetindent)
  (quicksetindent/set-indentation t 4)
```

Source: https://github.com/SteveJobzniak/emacs-quicksetindent/blob/master/quicksetindent.el

Would it be worth turning into a MELPA package? Something like this?

`(quicksetindent :fetcher github :repo "SteveJobzniak/emacs-quicksetindent")`

**Comment by syohex** [comment]
> Would it be worth turning into a MELPA package?

 No, I don't think so.

- Indentation configuration should be set in mode hook function. Some modes sets own indentation setting before calling hook function, for example python-mode sets tab-width to `8`(hard-coded).
- Many symbols which are not used for most people are interned
- I suppose few people want to set same indentation for all modes.

**Comment by SteveJobzniak** [comment]
@syohex I use this as a global default for all modes, and then EditorConfig for per-project overrides.

>Indentation configuration should be set in mode hook function. Some modes sets own indentation setting before calling hook function, for example python-mode sets tab-width to 8(hard-coded).

Yes, but those modes are rare. Mainly python (which auto-detects it from file contents since whitespace matters in that language), and PHP (which sets itself to PEAR style and uses 4-space indentation by default).

The problem for beginners is that when they try to set indentation in Emacs, they're met with absolutely terrible resources online. Most have a list of 5 or so of these global variables. No hooks. And no details about how to hook each language.

So this is meant as a quick way to get started.

> Many symbols which are not used for most people are interned

Yes, that's intentional to ensure that I don't have to make a list of all packages that use these symbols, because the list grows all the time (tons of packages use c-basic-offset for example).

And I cannot check if a variable is bound before deciding to overwrite it, because due to lazy packet loading, people's modes may simply not be loaded yet.

Therefore, I set them all. So what? Are you going to look at your Emacs environment variables all the time? That's a 0th world problem. Don't worry about it. They're just unused variables.

> I suppose few people want to set same indentation for all modes.

I think _most_ people want to set a global default of for example 4-space indentation, and then override it per-mode for specific modes.

**Comment by purcell** [comment]
I can understand your intentions, but I don't believe there's a single correct indentation level to rule them all. Most modes should use the standard indent width by default (and if not, the best solution would be submitting PRs for those modes), while other language modes have opinionated defaults which reflect the prevailing community standards for those languages.

There are a few little issues with the code itself, but fundamentally I think it would be counterproductive to promote this approach. As documentation, the list of variables might be helpful, but as code, I'm not so sure.

**Comment by SteveJobzniak** [comment]
@purcell You are completely right, it's more in the corner of "it's good as documentation to know what variables to use" and less of a "it's a good idea to share this as a package". I will close this ticket.
