### ISSUE TITLE
melpa.org: Include package name in <head><title>

### ISSUE THREAD

**Issue by mcandre** [melpa/melpa#4473]
Could the HTML package index include the name in the page title, for easier bookmarking and sharing?

**Comment by purcell** [comment]
It does, but only in browsers: I see the page title change when I click from the package index to the page for a specific package. But it's a single page app, so the raw HTML is the same simple shell for all pages. This isn't likely to change any time soon, but there are related issues open, so I'll close this one.

**Comment by mcandre** [comment]
JavaScript can modify the title in a single HTML page app: `document.title = packageName;`

**Comment by purcell** [comment]
Yes, and we already do. Here's such a page title directly in the rendered DOM:

![screen shot 2016-12-30 at 10 16 55](https://cloud.githubusercontent.com/assets/5636/21555023/3d8fec7a-ce79-11e6-8664-2f7e328df227.PNG)
