### ISSUE TITLE
ox-clip package install doesn't install html-clip-w32.py

### ISSUE THREAD

**Issue by notuntoward** [melpa/melpa#4490]
I installed the melpa ox-clip package but when I select a region of an org mode file and run

    M-x ox-clip-formatted-copy

I get the error message

    python: can't open file 'c:/Users/scott/OneDrive/scotto/.emacs.d/elpa/ox-clip-20161106.823/html-clip-w32.py': 
    [Errno 2] No such file or directory
    Quit

The documentation says that html-clip-w32.py will be installed on Windows but it's not in my case.  I'm using windows 10 and emacs 25.1.1

**Comment by purcell** [comment]
Please file this issue with the author of `ox-clip`, not here. /cc @jkitchin
