### ISSUE TITLE
ctags recipe references missing repo

### ISSUE THREAD

**Issue by mdorman** [melpa/melpa#4496]
The current recipe is `(ctags :fetcher bitbucket :repo "semente/ctags.el")`, but https://bitbucket.org/semente/ctags.el gives a 404.  No clear new location.  Haven't contacted the author.

**Comment by syohex** [comment]
It should switch to [emacsmirror version](https://github.com/emacsmirror/ctags) or remove because It says `ctags.el is no longer supported!`.
