### ISSUE TITLE
"No description available." for 0xc on melpa?

### ISSUE THREAD

**Issue by xuchunyang** [melpa/melpa#4519]
I notice https://melpa.org/#/0xc and `M-x list-packages` show "No description available." for 0xc. However `0xc.el` does contain a short description (https://github.com/AdamNiederer/0xc/blob/master/0xc.el#L1):

    ;;; 0xc.el --- Base conversion made easy

**Comment by syohex** [comment]
Such packages have problems about package header.

I have sent PRs
- https://github.com/gbgar/company-bibtex/pull/5
- https://github.com/howardabrams/demo-it/pull/10
- https://github.com/AdamNiederer/0xc/pull/5
- https://github.com/ksjogo/typoscript-mode/pull/1
- https://github.com/anshulverma/projectile-speedbar/pull/10
- https://github.com/vic/color-theme-buffer-local/pull/9
- https://github.com/rubikitch/sudo-ext/pull/1
- https://github.com/rubikitch/emacs-git-dwim/pull/1
- https://github.com/rubikitch/time-ext/pull/1

PR was already sent but they are not merged yet.
- https://github.com/pronobis/helm-words/pull/2
- https://github.com/mbriggs/railgun.el/pull/1
- https://github.com/mori-dev/cn-outline/pull/1
- https://github.com/imakado/perl-completion/pull/4

**Comment by xuchunyang** [comment]
Oh, I didn't know that. 

And from Emacs 25.1, `M-x package-install-from-buffer` on the previous version of `0xc.el` then `M-x describe-package 0xc` provides a correct short description. In other words,

    ;; Package-Requires: ((emacs "24.4") (s))

is treated as

    ;; Package-Requires: ((emacs "24.4") (s "0"))

So I thought there might be something wrong with melpa or the version of emacs used by melpa to create package archive.

**Comment by syohex** [comment]
https://melpa.org/#/0xc

0xc issue is fixed by my PR. I think above PRs are merged then this issue is fixed too.

**Comment by xuchunyang** [comment]
Yes, it's fixed.  Thank you.

**Comment by purcell** [comment]
> ;; Package-Requires: ((emacs "24.4") (s))

`package-lint` detects this as an error. Very new versions of `package.el` allow the above, but that is backwards-incompatible, so it is best to avoid it.

**Comment by xuchunyang** [comment]
I see.  Thanks for telling.
