### ISSUE TITLE
The command `package-install` not mentioned in README

### ISSUE THREAD

**Issue by bjodah** [melpa/melpa#4553]
First time users of melpa (such as me) will run `package-list-packages` as instructed.
But then one must guess that there might be a command such as `package-install` - I would
open a PR for adding this change in README but since I'm new I don't actually know for sure
that this is the recommended workflow?

**Comment by syohex** [comment]
BTW `package-install` does not update package archives. Users may fail `package-install` without updating package archives. `package-list-packages` updates package archives before listing packages. So users should update package archives at first.

**Comment by xuchunyang** [comment]
As far as I know, `package-install` won't fail for gnu and org elpa because they keeps old releases of packages, but melpa-(stable) doesn't (I have suggested melpa-stable should keep old releases in a previous issue).

**Comment by purcell** [comment]
Hi @bjodah -- a PR to update the README would be very welcome in his case. I'll close this issue pending that fix. Thanks!
