### ISSUE TITLE
Would "virtual" packages be acceptable, to ease automatic update of built-in packages?

### ISSUE THREAD

**Issue by thblt** [melpa/melpa#4554]
This [Reddit conversation](https://www.reddit.com/r/emacs/comments/5sx7j0/how_do_i_get_usepackage_to_ignore_the_bundled/) shows how hard it may be to automatically grab the latest version of built-in packages, like org.  In most cases, (use-package) or other managers won't install the package if it's already available.  Users have to resort to strange workarounds to get this done (or, like myself, have it working and have no idea how) 

Melpa could provide a solution for this problem if it carried a virtual package, like `org-virtual`, without any contents but with a dependency on the latest version of org.   I can create and maintain such a package and contribute it to Melpa.

Would you accept to provide such a package in your repository?

**Comment by xuchunyang** [comment]
To install org from ELPA automatically, one can install org-plus-contrib from org elpa or install any package which uses org 8.2+ as a dependency, such as orglink (because the Emacs built-in org is 8.2 while orglink needs 8.3). And one can also try the following

```
(use-package org
  :init
  ;; Install Org from ELPA if not already
  (unless (package-installed-p 'org (version-to-list "8.3"))
    (package-refresh-contents)
    (package-install (cadr (assq 'org package-archive-contents)))))
```

**Comment by thblt** [comment]
Thanks for your answer.  I believe the `org-virtual` option remains valid, for the following reasons:

> one can install org-plus-contrib from org elpa

Org Elpa provides unsigned packages over unencrypted http.  I believe this repository should then be avoided if possible, in favor of Gnu or Melpa, until it provides signatures or https.  Creating a `org-virtual` package in Melpa package would achieve the same goal without introducing security issues.   Of course, people who actually *need* `org-plus-contrib` would still have to use Org Elpa (or another insecure package source), but people who don't should get a chance to avoid having to use it.  

> or install any package which uses org 8.2+ as a dependency

People who use these packages would obviously get latest org.  But adding a package just to get its dependencies doesn't sound like a good solution:  beyond being far from clean, it may introduce new bugs, for example.

> And one can also try the following

I understand there already are workarounds.  The solution I'm proposing is just a simpler workaround, which provides a general and simple fix for the "updating org-mode" problem:   "replace `(use-package org)` by  `(use-package org-virtual)`.

**Comment by purcell** [comment]
I feel like this proposed fix is very personal, due to your feelings about installing packages over http (which shouldn't be an issue if those packages have `gpg` signatures), and this virtual package would need maintenance, while providing little benefit to most users. So I'm against adding it here.

> People who use these packages would obviously get latest org. But adding a package just to get its dependencies doesn't sound like a good solution: beyond being far from clean, it may introduce new bugs, for example.

I didn't understand this point, sorry.

**Comment by thblt** [comment]
> your feelings about installing packages over http (which shouldn't be an issue if those packages have gpg signatures)

I have no objections over installing GPG-signed packages over http, or any other insecure transit.  The problem here is that AFAIK, Org ELPA provides *neither* https nor GPG signatures.

> and this virtual package would need maintenance, while providing little benefit to most users.

If this package gets added to Melpa, I'll of course maintain it. 

> I didn't understand this point, sorry.

xuchunyang suggested that people could automate installation of latest version of org-mode by installing any package which depends on a more recent version than the built-in one.  This would certainly work, but a) introduces new code which may be or become buggy, change emacs behavior in unexpected ways, etc; and b) introduces unnecessary complexity to Emacs configuration (";; Here I'm installing this package, but what I really mean is to pull its org dependency").

**Comment by purcell** [comment]
I'm going to decline this, sorry. I really don't want us to get into using empty virtual packages to work around shortcoming in other people's packages.

**Comment by thblt** [comment]
I perfectly understand. Thanks a lot for your time in reviewing this!
