### ISSUE TITLE
There should be a way to add a preview image

### ISSUE THREAD

**Issue by rbanffy** [melpa/melpa#4556]
Having a way to select an image to be displayed as a preview would be cool. Maybe a selecting `preview.png` or `preview.gif` with a fallback to the first image (or no image, if not found).

**Comment by purcell** [comment]
What preview? We don't have any support for previews, do we?

**Comment by rbanffy** [comment]
Sorry, @purcell. I misunderstood the interface for a moment and got confused by the badge section. Still, it'd give a nice feature request for the future (it could be useful for themes), if we find a solution for the security issues pointing to external resources can have. I edited the initial comment and title to better reflect that.

**Comment by purcell** [comment]
Closing this, because there's no hope of making this happen in the foreseeable future.
