### ISSUE TITLE
Installing package "cider" fails - Inconsistent dependencies?

### ISSUE THREAD

**Issue by fgeorges** [melpa/melpa#4565]
I have not found any other way to report issue on MELPA, hope this is the right way to do it.

`M-x package-install RET cider RET` fails, with the following message in the minibuffer: `http://melpa.milkbox.net/packages/clojure-mode-20161221.523.el: Not found`

The buffer `*Messages*` contains the following:

    Contacting host: melpa.milkbox.net:80
    url-insert-file-contents: http://melpa.milkbox.net/packages/clojure-mode-20161221.523.el: Not found

Any idea what's wrong?  It seems like some dependency descriptors are broken.

**Comment by syohex** [comment]
It looks your package archives is too old. Please update it by `M-x package-refresh-contents` and try again.

**Comment by fgeorges** [comment]
Thank you, @syohex!  That solved the issue.  I was not aware of this command, I thought it was done automatically when calling `M-x list-packages`.  Thanks for the tip!
