### ISSUE TITLE
package not found

### ISSUE THREAD

**Issue by ananthakumaran** [melpa/melpa#4570]
We have got couple of complaints from users not being able to install tide package. Please refer https://github.com/ananthakumaran/tide/issues/103 for the exact urls. From browsing other issues in this repo, it looks like the users need to run `package-refresh-contents` to fix the issue. To get the latest version it makes sense to run package-refresh-contents. But, why is it necessary before each install? Does melpa do some sort of resource cleanup such that packages won't be available after a specified time?

**Comment by purcell** [comment]
Yes, we don't keep old packages, sorry.
