### ISSUE TITLE
Package Error At Testing Phase

### ISSUE THREAD

**Issue by apierz** [melpa/melpa#4583]
I'm am trying to test my recipe but keep running into this error:

`autoload-generate-file-autoloads: nord-theme.el:0:0: error: end-of-file: nil`

I have cloned melpa and added my recipe which seems to download fine when I `C-c C-c`. I haven't been able to find any guidance on what to do with this error. Any help would be appreciated.

Directory of package I am trying to add: https://github.com/apierz/nord-emacs

**Comment by syohex** [comment]
https://github.com/apierz/nord-emacs/blob/94dd9eb0d47c7291791808b4389848831d87e1e6/nord-theme.el#L380-L382

Because You specify buffer local variable but you don't set its value.

And
- There are too many warnings
- Missing `:` at `Version header

```
nord-theme.el:28:1:Warning: global/dynamic var ‘nord0’ lacks a prefix
nord-theme.el:29:1:Warning: global/dynamic var ‘nord1’ lacks a prefix
nord-theme.el:30:1:Warning: global/dynamic var ‘nord2’ lacks a prefix
nord-theme.el:31:1:Warning: global/dynamic var ‘nord3’ lacks a prefix
nord-theme.el:32:1:Warning: global/dynamic var ‘nord4’ lacks a prefix
nord-theme.el:33:1:Warning: global/dynamic var ‘nord5’ lacks a prefix
nord-theme.el:34:1:Warning: global/dynamic var ‘nord6’ lacks a prefix
nord-theme.el:35:1:Warning: global/dynamic var ‘nord7’ lacks a prefix
nord-theme.el:36:1:Warning: global/dynamic var ‘nord8’ lacks a prefix
nord-theme.el:37:1:Warning: global/dynamic var ‘nord9’ lacks a prefix
nord-theme.el:38:1:Warning: global/dynamic var ‘nord10’ lacks a prefix
nord-theme.el:39:1:Warning: global/dynamic var ‘nord11’ lacks a prefix
nord-theme.el:40:1:Warning: global/dynamic var ‘nord12’ lacks a prefix
nord-theme.el:41:1:Warning: global/dynamic var ‘nord13’ lacks a prefix
nord-theme.el:42:1:Warning: global/dynamic var ‘nord14’ lacks a prefix
nord-theme.el:43:1:Warning: global/dynamic var ‘nord15’ lacks a prefix
```

**Comment by apierz** [comment]
Thanks! I knew there must be some problem with my package code.
