### ISSUE TITLE
MELPA Stable: server disk is 100% full

### ISSUE THREAD

**Issue by purcell** [melpa/melpa#4608]
It has 11GB in "working", just like the main MELPA server, and nothing else is obviously huge, so I'm unsure how it has filled 20GB, or how to fix this. Can we bump up the disk size maybe?

I don't currently have `root` on this machine so can't resolve it, but here's where I'd start in order to free up a little initial space:

- 479MB in `/var/cache`: `apt-get clean` would help slightly
- 812MB in `/var/log`

**Comment by milkypostman** [comment]
On it.

**Comment by milkypostman** [comment]
should be fixed.

gave it a reboot for good measure.

**Comment by Silex** [comment]
Give disk space is a reccurent issue, maybe a bit of monitoring would help. Something that alerts you when < 15% disk space.

**Comment by purcell** [comment]
Yup, mainly a matter of having time to set it up. I personally like `monit` for this sort of thing.

**Comment by milkypostman** [comment]
Hosting service now supports monitoring out of the box. I have setup an alert at 90% disk utilization.
