### ISSUE TITLE
Packages whose upstream repositories have disappeared

### ISSUE THREAD

**Issue by tarsius** [melpa/melpa#4622]
- github
  - by @jorgenschaefer
    - [x] bitly
    - [x] gitty
    - [x] gplusify
  - by @yascentur (account no longer exists)
    - [ ] cursor-in-brackets [shelved, still on Melpa]
    - [ ] dummy-h-mode [shelved, still on Melpa]
    - [ ] judge-indent [shelved, still on Melpa]
  - by @thwg:
    - [x] goose-theme [still on Melpa and Emacsmirror]
  - by @lvillani
    - [ ] metafmt [shelved, still on Melpa]
  - by @cajetanus  (account no longer exists)
    - [ ] gregorio-mode [shelved, still on Melpa]
  - by @rjmac 
    - [ ] flycheck-scala-sbt [shelved, still on Melpa]
- elsehwere
  - [ ] org-password-manager [shelved, still on Melpa]
  - [ ] **notmuch** [still on Melpa and Emacsmirror]
  - [ ] mwe-log-commands [shelved, still on Melpa]
  - [x] redshank [see #5010]
  
Questions to the (former?) maintainers of these packages:

- Have the repositories moved elsewhere?
- Should these packages be removed from Melpa?
- I intend to [move them from the Emacsmirror to the Emacsattic](https://emacsmirror.net/). Does that sound reasonable?

**Comment by glynnforrest** [comment]
Hi @tarsius, I took over the maintenance of mmm-jinja2 and salt-mode, see https://github.com/melpa/melpa/issues/4424

The repos live here:

* https://github.com/glynnforrest/mmm-jinja2
* https://github.com/glynnforrest/salt-mode

Nothing has changed since I took over maintenance, as far as I'm aware. I'd like to keep these packages in melpa please.

Let me know if I need to do anything.

**Comment by jorgenschaefer** [comment]
The packages listed for me are/were tiny toy projects, I have no idea why they were on MELPA in the first place. Can be safely removed.

**Comment by tarsius** [comment]
@glynnforrest Thanks for the reply. Turns out there was a glitch on the Emacsmirror side. The database was updated to point to your repositories, but `.git/config` was not. I am now checking the other mentioned packages again to see if the same applies there...

**Comment by tarsius** [comment]
> I have no idea why they were on MELPA in the first place.

Someone liked them and submitted a recipe. And, toy or not, they were good enough to pass review ;-)

**Comment by tarsius** [comment]
> Can be safely removed.

I am doing that. (Also see #4384.)

**Comment by glynnforrest** [comment]
Thank you @tarsius for fixing that!

**Comment by thwg** [comment]
Hey @tarsius, I'd stopped maintaining that theme, and forgotten it was in MELPA.  I've reuploaded it with a note that it is unmaintained and that it may be picked up by anyone interested.

**Comment by tarsius** [comment]
@thwg thanks!

**Comment by Wilfred** [comment]
@tarsius has redshank disappeared? I successfully cloned http://www.foldr.org/~michaelw/projects/redshank.git today.

As mentioned in #5010, it might be a good candidate for the attic. This will enable us to fix the header.

**Comment by lvillani** [comment]
Hi @tarsius, I stopped maintaining metafmt, feel free to kill it.

**Comment by tarsius** [comment]
@Wilfred before we do that, we should try to summon upstream again. Meanwhile feel free to submit a pull request in https://github.com/emacsattic/redshank. Having the changes in `git pull`able state available might also help upstream find the necessary motivation.

**Comment by tarsius** [comment]
@lvillani Thanks for the information!

**Comment by purcell** [comment]
I didn't hear back from the Redshank author, so I deleted the package as per #5010. The package shouldn't be re-added here until there's a fixed version somewhere that someone is prepared to maintain later if necessary.

**Comment by Wilfred** [comment]
@tarsius I've created https://github.com/emacsattic/redshank/pull/1, would you be willing to accept the PR at this point?

**Comment by tarsius** [comment]
I have merged it.

Note that it might be problem that this just says "the GPL" instead of "GPLv3 [or later]". But if the author does not reply, then we can do little about that.

**Comment by tarsius** [comment]
Also Melpa doesn't currently mirror any packages from the attic and if @purcell decides to re-add this despite the license problem, then I would prefer it if you could "maintain" this in your own repository, which Melpa and the Emacsmirror could then import.

**Comment by Wilfred** [comment]
Is there a license problem? As long as redshank is not distributed with anything else, I can't see any issue here.

**Comment by tarsius** [comment]
> Is there a license problem? As long as redshank is not distributed with anything else, I can't see any issue here.

I am afraid that Richard thinks that all Elisp that couldn't be ported to Common Lisp with only minor changes does derive from Emacs i.e. everything that is strongly tied to Emacs APIs). We had to removed a few dozen packages because of this. @purcell explained the situation rather nicely somewhere, but I cannot find that anymore.

**Comment by tarsius** [comment]
I have removed the remaining packages in 6e94462928aa237a3f2b7027e0e409d061a87064.
