### ISSUE TITLE
apples-mode outdated

### ISSUE THREAD

**Issue by ghost** [melpa/melpa#4667]
Current apples-mode relies on OSX calling the Applescript editor "Applescript Editor". This has changed about 3 years ago with the release of OSX 10.10, where the editor's name was reverted to "Script Editor".

apples-mode repository has not changed in 6 years:
https://github.com/tequilasunset/apples-mode

Yesterday, I've created a pull-request including that change of name and a few modifications to cl- functions that required the "cl" prefix, etc. Considering the way the author has left his code without modification after the first commits, I fear this pull request will be ignored.

What are the possible ways to fix that issue?

**Comment by xiongtx** [comment]
Since the author clearly has not been active on GitHub for quite some time, why not fork the repo and maintain it yourself?

**Comment by suzume** [comment]
I did fork the repo and created the modifications on my side, then sent a pull request. I don't feel confident in my elisp skills to do much more than that but if it's only about maintenance, I'm fine with that.

What would be the procedure to have my mods included into melpa ?

**Comment by xiongtx** [comment]
See the [contributing](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md) doc.

**Comment by suzume** [comment]
The person who created the recipe for apples-mode from the original repository is @yasuyk :
https://github.com/melpa/melpa/blob/master/recipes/apples-mode
I'll see what we can do together.

**Comment by purcell** [comment]
Cool. Please file a PR if there are any recipe changes you want to request.
