### ISSUE TITLE
hledger-mode fails to compile because it depends on emlib

### ISSUE THREAD

**Issue by YoungFrog** [melpa/melpa#4680]
I just installed hledger-mode from melpa, and compilation failed at some point:

> Compiling file /home/youngfrog/.emacs.d/elpa/hledger-mode-20170402.1110/hledger-suggest.el at Tue Apr  4 19:13:59 2017
> hledger-suggest.el:34:1:Error: Cannot open load file: Aucun fichier ou dossier de ce type, emlib

hledger-suggest.el indeed requires emlib, but hledger-mode-pkg.el only has:

> (define-package "hledger-mode" "20170402.1110" "A mode for writing journal entries for hledger."
>   '((emacs "24.4")
>     (popup "0.5.3")
>     (async "1.9")
>     (htmlize "1.47"))
>   :url "https://github.com/narendraj9/hledger-mode.git" :keywords
>   '("data"))
> ;; Local Variables:
> ;; no-byte-compile: t
> ;; End:

Since hledger-mode-pkg.el is not present upstream, I guess it was created by melpa scripts. I'm not sure if they are supposed to work in this kind of situation though.

for future reference:
- package is http://melpa.milkbox.net/packages/hledger-mode-20170402.1110.tar
- upstream is at https://github.com/narendraj9/hledger-mode.git
- recipe is: `(hledger-mode :fetcher github :repo "narendraj9/hledger-mode" :files ("*.el"))`

**Comment by milkypostman** [comment]
the depends needs to be added to hledger-mode.el. melpa builds it's -pkg
file from that.

**Comment by purcell** [comment]
Fixed upstream.
