### ISSUE TITLE
Using consistent name and type for "the package" argument in package-build.el functions

### ISSUE THREAD

**Issue by tarsius** [melpa/melpa#4687]
@purcell Have you intentionally disabled issues on `melpa/package-build`? I would have opened this issue there if I could have.

Many functions take an argument that is expected to be an atom that identifies a package. Sometimes that is named `package-name`, sometimes `name`. Sometimes it is expected to be a symbol, sometimes a string, and sometimes it can be either.

I suggest we always call it `name` and expect it to be a string.

**Comment by milkypostman** [comment]
i'm happy for a progressive change to something more consistent. i think in
general we use 'name' when we mean the string and 'package-name' when we
mean the atom. there are times when both are valuable and I tend to avoid
conversion from atom <-> string <-> atom where possible.

**Comment by purcell** [comment]
> @purcell Have you intentionally disabled issues on melpa/package-build? I would have opened this issue there if I could have.

Nope, I don't think it was me. But I've enabled Issues there now, in any case.

**Comment by purcell** [comment]
I'd be happy for this to be made more consistent. You should be wary of breaking Cask, not just MELPA.
