### ISSUE TITLE
melpa stable appears to not parsing version numbers correctly

### ISSUE THREAD

**Issue by phillord** [melpa/melpa#4693]
I have just released by package "m-buffer" to version 0.15 but this appears
not to updating on melpa-stable. Cloning melpa and running

    make STABLE=t recipes/m-buffer

gives:

    No valid stable versions found for m-buffer
    Makefile:91: recipe for target 'recipes/m-buffer' failed
    make: [recipes/m-buffer] Error 255 (ignored)
     ✓ Wrote 12K -rw-r----- 1 phillord phillord   94 Apr  9 21:59 ./packages/m-buffer-0.15.entry
    60K -rw-r----- 1 phillord phillord  50K Apr  9 21:59 ./packages/m-buffer-0.15.tar
    12K -rw-r----- 1 phillord phillord  806 Apr  9 21:59 ./packages/m-buffer-badge.svg
    12K -rw-r----- 1 phillord phillord 1.5K Apr  9 21:59 ./packages/m-buffer-readme.txt 
     Sleeping for 0 ...

But I do have a stable version.

The cause of the problem appears to be in `package-build--find-version-newest`
which does this:

     (let ((tags (split-string
                  (buffer-substring-no-properties
                   (or bound (point-min)) (point))
                 "\n")))

But this code is called from `package-build--checkout-git` like so:

    (let ((tag-version
              (and (package-build--run-process dir "git" "tag")
                   (or (package-build--find-version-newest
                         (or (plist-get config :version-regexp)
                              package-build-version-regexp)
                          (goto-char (point-max)))
                          (error "No valid stable versions found for %s" name)))))

So, AFAICT, `(= bound (point-max))` and therefore tags will always be empty.

The documentation for `find-version-newest` says "The match found must not
before after that position.", so I think that something has gone wrong here.

I haven't checked extensively, but ivy.el seems behind the times (0.8.0 on stable, 0.9 in source)

**Comment by dunn** [comment]
It's been a while since I wrote that, but how `buffer-substrings-no-properties` works is by taking the two values passed and returning the buffer string in between them:
```
(buffer-substring-no-properties START END)

Return the characters of part of the buffer, without the text properties.
The two arguments START and END are character positions;
they can be in either order.
```
So what `split-string` should return there is whatever's between point and the end of the buffer.

Apparently it's not doing that for your package, though (ivy might just be due to a delay in rebuilding the packages on the MELPA Stable server).

If I have the chance I'll take a closer look soon.

**Comment by milkypostman** [comment]
we merged in a new version of package-build with a lot of changes. 41c623f3d4393272db5c9b19be5a2e22f46638e9

the changes surrounding this look innocuous, but I am debugging now.

**Comment by milkypostman** [comment]
I see the problem. Am working on a fix.

**Comment by milkypostman** [comment]
rebooted the server. you should see correct versions soon unless my change inadvertently broke everything.

thanks for reporting.

**Comment by tarsius** [comment]
Sorry about that! It appears I only tested building for unstable. I'll make sure I test building for stable too in the future. (Also I should have realized this change was no good when I made it, let-bindings involving buffer positions tend to be necessary.)
