### ISSUE TITLE
consider providing a git repo, or even a .tar.gz of the whole melpa

### ISSUE THREAD

**Issue by ninrod** [melpa/melpa#4706]
Hi, and thanks for mantaining the biggest emacs-lisp archive know to mankind. 

Several users of Melpa also use emacs from work and sadly, more often than not, we suffer from draconian firewall blocks that make us unable to use melpa properly. 

@d12frosted provided an awesome alternative solution in his [elpa-mirror](https://github.com/d12frosted/elpa-mirror), where all the packages from gnu, org, melpa and melpa-stable are fetched and commited inside a git repo. 

Access to github is pratically a necessity, so I have access to it and then I can git clone the repo and use all of melpa's goodness.

So I was wondering: couldn't you provide this as a feature of melpa.org? like: `git clone unstable.git.melpa.org`. This would be nice because then we wouldn't have to rely on an individual script to fetch the dependencies. 

Alternatively, you could mantain this repo updated in the melpa organization on github, as @d12frosted is doing now.

here's a full tutorial that teaches setting up the melpa git repo like I described: https://github.com/ninrod/emacs-antiproxy

What do you think?

**Comment by purcell** [comment]
Sorry, this is very much a niche use case, and not something we're going to actively support. We already provide `rsync` access, and have documented mirrors elsewhere.
