### ISSUE TITLE
Declare dependency on 'org while accepting 'org-plus-contrib?

### ISSUE THREAD

**Issue by alphapapa** [melpa/melpa#4721]
I recently upgraded to Org 9.0.5, using `org-plus-contrib` to get the `contrib` directory, which was formerly provided by my distro's org-mode package, which appeared to Emacs as `org`.

I now have the problem that, when I build and install a recipe of one of my own packages that depends on `org`, it downloads and installs the `org` package, even though I already have `org-plus-contrib` installed.  This leaves me with two copies of org-mode installed.

Is there any way to declare a dependency that can be satisfied by either one?  I can't seem to find anyone else talking about this problem, but maybe I missed it.

**Comment by purcell** [comment]
There's no way to do this because the org packaging is pretty lame, sorry. Really they should have an `org-contrib` package which depends on `org`.

**Comment by purcell** [comment]
(Or, better still, separate packages for each org-contrib library, with appropriate dependencies.)
