### ISSUE TITLE
Something wrong with melpa.org

### ISSUE THREAD

**Issue by kaushalmodi** [melpa/melpa#4738]
Hi,

I just went to melpa.org and all it shows is this:

![image](https://cloud.githubusercontent.com/assets/3578197/25782295/b398f690-3315-11e7-8676-fddbfc90c6d6.png)

**Comment by O5M3** [comment]
The same problem here. However i still can search and see info about packages in emacs.

**Comment by milkypostman** [comment]
There was recently a change submitted to add commit hashes. I am traveling
now so cannot fix.

Since this shouldn't affect the package download and just the website. I
will look at it tonight.

**Comment by szkl** [comment]
@milkypostman I've submitted a fix already #4739.

**Comment by kaushalmodi** [comment]
Thanks. I see that Melpa.org is showing the package list again.
