### ISSUE TITLE
Merging two packages?

### ISSUE THREAD

**Issue by DarwinAwardWinner** [melpa/melpa#4784]
In the next major release of ido-ubiquitous and ido-completing-read+, I'm planning to merge the two packages, with the combined package being called ido-completing-read+. In order to ensure that people with configs that install ido-ubiquitous continue to get their required features, I'm planning to leave the ido-ubiquitous package around as a dummy that just loads ido-cr+, sets up some obsolete aliases for functions and variables, and displays a deprecation warning to the user. Does this seem like a reasonable approach, and is there anything else I can or should do to ensure that people who get ido-ubiquitous through MELPA have a smooth upgrade experience?

**Comment by DarwinAwardWinner** [comment]
Note: for now, the package will still live in the Github repo named ido-ubiquitous, so I don't think the recipes will need updating.

**Comment by purcell** [comment]
Yes, that sounds like a reasonable plan. Marking your aliases as obsolete should do the trick regarding deprecation warnings.

Mentioning it just in case: I guess you'd want to keep the `ido-ubiquitous` repo around fairly indefinitely so that the fully-functional MELPA Stable package can continue to be built.

**Comment by DarwinAwardWinner** [comment]
So I wasn't aware of this until recently, but apparently Github added redirects for repo renames, as described here: https://github.com/blog/1508-repository-redirects-are-here

So I should be able to just rename the repo without having any transient breakage of MELPA until the recipe's repo URL is updated. (Obviously I'll test on a dummy repo first.)

**Comment by milkypostman** [comment]
You can just do the rename then commit the PR. Or ping the PR when you're
ready.
