### ISSUE TITLE
What is the best way to update cross dependency in multi-package repos?

### ISSUE THREAD

**Issue by ptrv** [melpa/melpa#4790]
I am the co-author of [emacs-ycmd](https://github.com/abingham/emacs-ycmd). It has a multi-package repository, it consists of `ycmd`, `company-ycmd` and `flycheck-ycmd` packages which are all on MELPA.

`company-ycmd` and `flycheck-ycmd` both have `ycmd` as dependency. The current version of `ycmd` is `1.2-cvs` and `company-ycmd` and `flycheck-ycmd`  require `(ycmd "1.1")`.

We had the situation that we added a macro in `ycmd` which was also used in `company-ycmd`. The user run a package update and the problem was that `company-ycmd` was installed before `ycmd` so  `company-ycmd` was compiled with the macro from `ycmd` not defined yet. The error was:

```
Invalid function: ycmd-deferred:timeout
```

I guess this behavior is somehow "normal" because `company-ycmd` only reqreuied `ycmd 1.1`.

So, my question is what is the best strategy for such a case?
Bump the version of `ycmd` as soon as I add something new which is needed in `company-ycmd` and require the new version? Is then guaranteed that `ycmd` is updated before?

**Comment by purcell** [comment]
For MELPA Stable packages, just tag the shared repo with a version number at the same time, making sure that `company-ycmd` and `flycheck-ycmd` depend on that version of `ycmd`. After that release, switch the dependencies to the next version number, e.g. `1.2` or `1.2-cvs` (though the latter is pretty pointless).

For MELPA snapshot packages, there's not really anything you can do.

**Comment by ptrv** [comment]
Ok, thanks for your answer.
