### ISSUE TITLE
Melpa makes Emacs 25.2 crash on M-x list-packages

### ISSUE THREAD

**Issue by palbarede** [melpa/melpa#4791]
M-x list-packages 
makes Emacs 25.2 crash.

Beginning of crash report :

Process:               Emacs-x86_64-10_9 [11568]
Path:                  /Applications/Emacs-25.2.app/Contents/MacOS/Emacs-x86_64-10_9
Identifier:            org.gnu.Emacs
Version:               Version 25.2 (9.0)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Emacs-x86_64-10_9 [11568]
User ID:               501

Date/Time:             2017-06-10 22:03:03.320 +0200
OS Version:            Mac OS X 10.11.6 (15G1510)
Report Version:        11
Anonymous UUID:        0DB348FC-F518-FB15-210F-406725E9B6F7

Sleep/Wake UUID:       7D9A8A6D-01AB-4AC6-B38C-06A6E11C8653

Time Awake Since Boot: 130000 seconds
Time Since Wake:       19000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGABRT)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread

mac-de-Papa% cat ~/.emacs
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages (quote (pyenv-mode-auto elpy company-jedi auctex))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )

(require 'package) ;; You might already have this line
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/"))
(when (< emacs-major-version 24)
  ;; For important compatibility libraries like cl-lib
  (add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages/")))
(package-initialize) ;; You might already have this line

No problem with Emacs 25.1.

No problem with only Elpa.

**Comment by purcell** [comment]
This isn't a MELPA issue that we can fix, sorry: my best guess is that SSL support is broken in your Emacs. Try changing `https` to `http` in the MELPA URL to confirm that.

**Comment by palbarede** [comment]
I confirm that http: works.  Thanks.
