### ISSUE TITLE
Assume :fetcher based on :url, if unspecified

### ISSUE THREAD

**Issue by joewreschnig** [melpa/melpa#4794]
I'm tremendously lazy. I'd like to avoid specifying a `:fetcher` for URLs with domains that either begin with `git.` (e.g. `git.example.com`) or end with `.git` (e.g. `https://source.example.com/pacakge.git`). The same could probably be done for `svn.example.com`, `hg.example.com`, and `bzr.example.com`, which are also often served over HTTP(S).

I don't believe this would affect any existing recipes, since right now `:fetcher` is mandatory.

**Comment by purcell** [comment]
Thanks. I agree - that _is_ tremendously lazy! :-)

Not going to do this, sorry. The maintenance of the extra code would not remotely be worth its complexity.

**Comment by joewreschnig** [comment]
That's fair. Thanks for considering it!
