### ISSUE TITLE
Drop support for rarely used sources

### ISSUE THREAD

**Issue by Fuco1** [melpa/melpa#4798]
This is somewhat related to #4712.  If we want to have a way to fetch manifests and cache the dependency graphs we should ideally just use git that supports this best (with tags) or mercurial (but nobody uses mercurial).

I have counted 9 recipes using svn fetcher, 2 with darcs, 0 with fossil, ~0 with csv~, 4 with cvs, 1 with hg.

There is also 160 wiki packages which should become unavailable just because it's terrible. (see also #2342)

This is the first step towards making something that would be able to build packages on-the-fly (that is when user requests an old version not on the server, we would fetch it and build and serve).  The less sources we support the simpler the process becomes.

**Comment by mdorman** [comment]
@Fuco1 Hmmm, did you actually look for `csv`?  Because that's not gonna find anything, but `cvs` will---admittedly, only 4, but `w3m` at least is a pretty prominent package.

Anyway, while I understand your utilitarian argument, I, personally, would be leery of instituting a monoculture---and I say that as the guy who once a week regenerates the melpa package list for `nix`, and thus has to deal with things like `cvs` servers that can't seem to get their act together.

**Comment by Fuco1** [comment]
Silly me, I wrote `csv` yes :). 

The thing is, we already have a monoculture.  If someone is afraid of using git there is the emacs mirror project that can substitute for just the release snapshots.

It seems w3m is on github now: https://github.com/ecbrown/emacs-w3m (last update 10 days ago)

There is a lot of, well, crap, accumulated over the years.  I would very much like to donate my time to make things faster, simpler, cleaner and more convenient.  If only for myself as an author of 40+ emacs packages.

**Comment by dunn** [comment]
How many use `bzr`?

**Comment by Fuco1** [comment]
2 on my 3 months old copy, which is safe to assume is up to date with regard to bzr packages.

**Comment by aplaice** [comment]
The `bitbucket` fetcher also uses mercurial. A year ago (when I compiled some stats) there were 37 sources fetching from there.

I personally think that locking oneself into a git-monoculture is not a great idea.

Also, in what way is a repository using, say `bzr` worse (in the context of MELPA stable) than one using `git` but not tags? Considering that there will always be `git` repositories without tags (people are lazy), and hence "non-stable" MELPA will presumably always be around, why can't the less frequently used sources just be excluded from MELPA stable?

**Comment by dunn** [comment]
> why can't the less frequently used sources just be excluded from MELPA stable?

That makes the Stable user experience a lot worse; see https://github.com/melpa/melpa/issues/3306 etc.

But I believe @Fuco1 is proposing we drop support entirely, not just for Stable.  I don't have a strong opinion either way, but that code hasn't needed to change much so maintainability probably isn't an issue.

**Comment by Fuco1** [comment]
@aplaice "non-stable" melpa can be handled by tracking branches the same way npm, bundler, stack, composer and others do it.  A branch in git is the same thing as tag as commit hash => a pointer.

> Considering that there will always be git repositories without tags (people are lazy)

This is a people problem which I believe can be fixed after a couple blog posts and an explanation of why it is a good idea to tag releases.  If I am wrong on this one, well maybe we need to decide to promote quality over laziness and just stop compromizing.  It has worked great for other communities/environments.

@dunn Agreed on the maintainability so far, but if we ever make the leap towards some other scheme of things plugging in these other sources will just be an obstacle.

All complex systems tend to break, this is a given in programming.  Reducing complexity promotes experimentation and growth.  When rolling out "partial support" is met without much enthusiams, then we should simply drop the support altogether.

> Perfection is Achieved Not When There Is Nothing More to Add, But When There Is Nothing Left to Take Away

**Comment by purcell** [comment]
Closing since discussion in #4802 covers this.
