### ISSUE TITLE
Package rename

### ISSUE THREAD

**Issue by joostkremers** [melpa/melpa#4812]
Hi,

I have a package on Melpa that I wish to rename. (`writeroom-mode`, to be specific.) I have read through several other package rename threads that I could find, but I'm still unsure how to proceed. Is there a procedure for dealing with such renames, or is it more a case-by-case thing?

The code for the package is on Github, and I'd like to rename the repo as well as the package, if that's possible. Under these circumstances, is there a way to automatically upgrade existing users of the packages to the new name, or will users need to install the new package manually?

**Comment by purcell** [comment]
There's no process that will completely avoid disruption to any users, so if you're set on renaming, you should just rename the code and submit a recipe change that adds the `:old-names (writeroom-mode)` clause -- this way, the MELPA web page for the package will redirect, but it won't fix anything for package users directly.

But I also have to ask: why rename it? (I use `writeroom-mode` myself, btw.)
