### ISSUE TITLE
The guide on melpa.org does not work for windows solution inside

### ISSUE THREAD

**Issue by johnmorrisbeck** [melpa/melpa#4820]
I had a user in #emacs have trouble installing melpa packages on windows. This was the exe version of emacs available at the gnu mirror. The version was 25.1.1

I had the exact same issue. When I went for m-x package install auto-comp<tab> I got "no package found"

I dug around and I found out that windows does not like the https in the melpa link. For windows you have to install melpa with http only. So I changed it to http and I did m-x package-refresh RET

Please change the guide on melpa.org to reflect that if you are installing it on windows that you must use http and not https. Also please change all subsequent guides to reflect this as well, pretty please and thank you.

I know windows is dumb but it technically is a supported platform.

Thanks for all of your hard work guys. Cheers!

**Comment by bradyt** [comment]
This is bad.

**Comment by bradyt** [comment]
> For windows you have to install melpa with http only.

This is incorrect. The closing commit is not appropriate.
