### ISSUE TITLE
golden-raito can not update since 2015, can we regard it as unmaintain ?

### ISSUE THREAD

**Issue by tumashu** [melpa/melpa#4864]
https://github.com/roman/golden-ratio.el

golden-raito can not update since 2015 and the maintainer have not reply pull request again...

**Comment by tarsius** [comment]
What are you suggesting we do? Import some fork instead? Which?

**Comment by tumashu** [comment]
the problem is that all forks seem to be unmaintained,

**Comment by Silex** [comment]
What would happen if we reguarded it as unmaintained?

**Comment by tarsius** [comment]
It could be used to argue for the removal from Melpa. However I see no reason to do that in this case.

Also see #4384.

**Comment by Silex** [comment]
I see no reason for removal either.

**Comment by tumashu** [comment]
![ze 8z2 8wja5mm ckjf_ 87](https://user-images.githubusercontent.com/67725/28445679-901f90ac-6df8-11e7-92fd-813ac98b88e7.png)

I don't think  removing it is a good idea, for many people use it.  maybe we should fork it to emacsmirror and use it.  so if we have some minor pull quest,  we can let emacsmirror's maintainer just merge it.  until some people want to maintain this package.

**Comment by purcell** [comment]
> we can let emacsmirror's maintainer just merge it. until some people want to maintain this package.

There is no maintainer on `emacsmirror`: that's kind of the point. But there is https://github.com/emacsorphanage.

**Comment by tumashu** [comment]
https://github.com/emacsorphanage is a good place :-)

**Comment by tarsius** [comment]
I don't think that adding this to the orphanage would do much good at this point. Unless the current maintainer transferred the issue there we would lose the old issues and I don't see anything to be gained. Unless there is someone willing to take over as maintainer I think we just have to let it linger and hope for the maintainer to resume work.
