### ISSUE TITLE
Indium package on melpa stable seems to be stuck at 0.28.

### ISSUE THREAD

**Issue by NicolasPetton** [melpa/melpa#4866]
I'm not sure if I'm doing something wrong in [indium](/nicolaspetton/indium), but the stable package seems to be stuck at v.028, while the latest release is 0.7.2.

https://stable.melpa.org/#/indium

**Comment by milkypostman** [comment]
this is because 28>7. I'm not sure how we can reconcile this thing. each
section is considered a number , they are not sorted in lexigraphically

**Comment by NicolasPetton** [comment]
Donald Curtis <notifications@github.com> writes:

> this is because 28>7. I'm not sure how we can reconcile this thing. each
> section is considered a number , they are not sorted in
> lexigraphically

Indeed, it makes sense. I was planning to bump the major version number
anyway soon.
