### ISSUE TITLE
password-store melpa package is not getting updated

### ISSUE THREAD

**Issue by svend** [melpa/melpa#4892]
Melpa is not picking up a new version of password-store that I committed on July 26. The password-store repository switched to HTTPS with a redirect, so I updated that in Melpa, and that change was merged 13 hours ago (#4885). However, the password-store version in Melpa is still 20151027.1449.

http://melpa.milkbox.net/#/password-store

I cloned Melpa and ran `make recipes/password-store`. The resulting package had my updates.

Any ideas why the package version isn't getting updated?

**Comment by purcell** [comment]
Our server considers your certificate invalid:

```
Cloning https://git.zx2c4.com/password-store to /home/melpa/melpa/working/password-store/
Command '(env LC_ALL=C /usr/bin/timeout -k 60 600 git clone https://git.zx2c4.com/password-store /home/melpa/melpa/working/password-store/)' exited with non-zero status 128: Cloning into '/home/melpa/melpa/working/password-store'...
fatal: unable to access 'https://git.zx2c4.com/password-store/': gnutls_handshake() failed: Handshake failed
```

I can `git clone` your repo locally using `git` from `homebrew`, but Apple's `openssl` doesn't like your server:
```
% openssl s_client -showcerts -connect git.zx2c4.com:443                                                   
CONNECTED(00000003)
47968:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:/BuildRoot/Library/Caches/com.apple.xbs/Sources/OpenSSL098/OpenSSL098-64.50.6/src/ssl/s23_clnt.c:593:
```

My guess is that you don't have a full certificate chain in your cert, and that perhaps you're relying on clients having a local cert for your certifying authority.

**Comment by svend** [comment]
Thanks for investigating. I'll take a look at the certificate chain.

**Comment by svend** [comment]
The password-store repository is using a Let's Encrypt certificate. Let's Encrypt certificates are signed by "IdenTrust’s DST Root X3" CA, which is trusted by most browsers and operating systems:

https://letsencrypt.org/docs/certificate-compatibility/

Here is the certificate chain presented by the password-store repository.

```
x509 -noout -subject -hash -issuer -issuer_hash  
subject= /CN=krantz.zx2c4.com
861eba23
issuer= /C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
4f06f81d
subject= /C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
4f06f81d
issuer= /O=Digital Signature Trust Co./CN=DST Root CA X3
2e5ac55d
```

Could you check if the Melpa sever trusted CAs include IdenTrust’s DST Root X3?

**Comment by purcell** [comment]
I can't really spend time checking now, sorry. MELPA runs an older Ubuntu release currently, but the fact that the openssl command above was failing on my MacOS workstation indicates more of a fundamental problem, because the connection isn't even getting established. Normally the command would succeed, and then print out a partial certificate chain if the root authority was not trusted locally, but it's not even getting that far. I can use the same command to successfully probe one of my own LetsEncrypt-enabled servers, for example.

Sorry I can't be more help.

**Comment by svend** [comment]
I think I found the issue. password-store's git server only uses ECDSA ciphers, which are not supported by gnutls on Ubuntu trusty.

```
$ nmap --script ssl-enum-ciphers -p 443 git.zx2c4.com

Starting Nmap 7.50 ( https://nmap.org ) at 2017-07-31 13:49 PDT
Nmap scan report for git.zx2c4.com (192.95.5.69)
Host is up (0.093s latency).
Other addresses for git.zx2c4.com (not scanned): 2607:5300:61:14f::c05f:545
rDNS record for 192.95.5.69: krantz.zx2c4.com

PORT    STATE SERVICE
443/tcp open  https
| ssl-enum-ciphers: 
|   TLSv1.0: 
|     ciphers: 
|       TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA (secp384r1) - A
|       TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA (secp384r1) - A
|     compressors: 
|       NULL
|     cipher preference: server
|   TLSv1.1: 
|     ciphers: 
|       TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA (secp384r1) - A
|       TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA (secp384r1) - A
|     compressors: 
|       NULL
|     cipher preference: server
|   TLSv1.2: 
|     ciphers: 
|       TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 (secp384r1) - A
|       TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 (secp384r1) - A
|       TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 (secp384r1) - A
|       TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384 (secp384r1) - A
|       TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256 (secp384r1) - A
|       TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA (secp384r1) - A
|       TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA (secp384r1) - A
|     compressors: 
|       NULL
|     cipher preference: server
|_  least strength: A

Nmap done: 1 IP address (1 host up) scanned in 24.11 seconds
```

On Ubuntu trusty with gnutls-bin installed:

```
$ gnutls-cli -l | grep ECDHE_ECDSA
$
```

I don't run the password-store infrastructure, I only maintain the Emacs package in contrib/, but I can bring up the issue on the password-store mailing list.

**Comment by purcell** [comment]
Cool. Not a lot we can do from our side, but there's a reasonable chance we'll be moving servers now, and we'll use that as an opportunity to bump up to a new Ubuntu release.

**Comment by bricewge** [comment]
The administrators of `git.zx2c4.com` doesn't seems to want to add less secure ciphers (https://lists.zx2c4.com/pipermail/password-store/2017-September/003030.html), which is understable. The repo as a read-only mirror on [github](https://github.com/zx2c4/password-store), so until the melpa server is upgraded we could the mirror instead.
I just made a pull-request with the workaround.
