### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by yassinphilip** [melpa/melpa#4911]
Did I miss a step in the procedure? Some PRs are more than a month old, [mine](https://github.com/melpa/melpa/pull/4900) has been sitting there for 4 days now, I didn't even receive an automated mail, that's why I'm worrying about not having done things properly ; I'd really like to move along, did something bad happened? How would I know?

**Comment by purcell** [comment]
Hi! We're very busy with full-time jobs these days. I mostly work through fresh PRs at the weekends, as time allows, and I work from oldest to newest. I agree we could make that "service level" clearer, perhaps in the pull request template. Thanks for your patience!
