### ISSUE TITLE
FYI: emacs-package-dev-handbook

### ISSUE THREAD

**Issue by alphapapa** [melpa/melpa#4917]
Allow me to mention this new little project: https://alphapapa.github.io/emacs-package-dev-handbook/  There's not a lot there yet, but I hope it will eventually become a useful reference.  I started it because I found myself having to look up things repeatedly, and because there doesn't seem to be a best-practices guide for a lot of issues.

I will be adding to it from time to time when something occurs to me, but I would greatly appreciate any contributions.

Forgive posting it as an issue, but it seems very relevant here, and this is the target audience.  :)

**Comment by milkypostman** [comment]
Let's have this track addition of the guide to melpa.

I think those would be awesome but it would be good to have the others,
namely Purcell, who do reviews have a proof read over it. Then we should
add it to the PR template and readme

**Comment by alphapapa** [comment]
Thanks.  I think I'll make a top-level "Best Practices" section, and I'll add more to it as things occur to me.

**Comment by alphapapa** [comment]
FYI, I've added a package skeleton example to https://alphapapa.github.io/emacs-package-dev-handbook/#orgf86ffc0 (Packaging/Best Practices/Skeleton).

**Comment by milkypostman** [comment]
awesome, thanks!
