### ISSUE TITLE
hl-sentence and sentence-highlight essentially the same

### ISSUE THREAD

**Issue by alphapapa** [melpa/melpa#4933]
Hi @sbelak; and @milkypostman and other MELPA maintainers,

I noticed that `hl-sentence` and `sentence-highlight` are essentially the same.  In fact, both admit they are based on code from http://www.emacswiki.org/emacs/SentenceHighlight.  Several of the functions are sexp-for-sexp identical.  `hl-sentence` is more idiomatic as a package, as it uses `define-minor-mode`, while `sentence-highlight` manually adds itself to the `minor-modealist`.

It seems unnecessarily confusing to have both of these packages in MELPA.  I suppose it would inconvenience existing users of one or the other package to have it removed, but for potential new users, it is confusing to have both, as, without examining the source, it's unclear which is preferable.

Not a very important or urgent issue, but I thought I'd bring it to your collective attention.

Thanks for your work.

**Comment by tarsius** [comment]
To save you some clicking: [`hl-sentence`](https://github.com/milkypostman/hl-sentence) and [`sentence-highlight`](https://github.com/sbelak/sentence-highlight).

**Comment by tarsius** [comment]
I think we should settle on `hl-sentence`. I have submitted some cleanup and fixes to make that more appealing.

**Comment by tarsius** [comment]
We can add `:old-names (sentence-highlight)` to the `hl-sentence` recipe to help users of the latter.

**Comment by sbelak** [comment]
I'm totally fine with retiring sentence-highlight, the more idiomatic solution, the better.
