### ISSUE TITLE
Need ability to "freeze" packages that are abandoned

### ISSUE THREAD

**Issue by alphapapa** [melpa/melpa#4935]
It might be a good idea to have a way to "freeze" packages that seem abandoned by their maintainers.  That way if their GitHub account were compromised or deleted, the package wouldn't be affected.  e.g. https://github.com/melpa/melpa/issues/4864

Although, it seems like moving the package to the emacsorphanage repo would solve this issue... @tarsius ?  :)

**Comment by purcell** [comment]
Interesting idea, but already have processes to deal with this, and I don't personally see any value in writing and maintaining code to deal with this. Some "abandoned" packages just continue to work, so "abandoned" is a really fuzzy concept. And if someone want to move the work forward, they can apply to the previous maintainer to take over. If the old maintainer is unresponsive for a long time, and the new maintainer seems committed, we'll often switch our recipes to point to the new fork. If all else fails, new maintainers can create a fork with a different name.
