### ISSUE TITLE
[Policy question] Are installer shims appropriate on MELPA?

### ISSUE THREAD

**Issue by raxod502** [melpa/melpa#4939]
I have a package manager [`straight.el`](https://github.com/raxod502/straight.el), which is intended to be used as a replacement for `package.el` (and other package managers). The only way to "install" `straight.el` is to place a [specially crafted bootstrap snippet](https://github.com/raxod502/straight.el#getting-started) into your init-file. You can't install it using `package.el`.

However, the first thing most users do when wanting to install a package (or even package manager) is to `M-x package-install` and hope that it shows up in the list. For example, I've received this inquiry on my issue tracker: https://github.com/raxod502/straight.el/issues/134.

Thus, one option would be to create a shim package on MELPA, under the name `straight`, which is not actually `straight.el` but is instead an interactive guide on how to set up `straight.el` properly.

However, I recognize that this kind of thing is quite unorthodox. Is it desirable to have such "packages" on MELPA? The alternative, of course, would be to simply not have `straight.el` on MELPA, which I would also be fine with.

**Comment by vyp** [comment]
I think this is a really specific case where the package itself cannot or should not be on MELPA, hence the 'need' for a shim package. However another slight advantage of having something called straight on MELPA would be to effectively reserve the name, so that no one else in the future makes a package called straight, which would conflict with straight.el. (Or otherwise they're forced to rename it if they want to add it to MELPA.)

**Comment by purcell** [comment]
I don't think it makes sense for us to host a pure shim package here, but note that `el-get` is in MELPA, and is also a `package.el` replacement. It'd be possible, for example, to install `el-get` via `package.el`, and then load it from its installed location and use it in preference to `package.el`. So we'd conceivably host a properly-packaged `straight.el` in package format, but we wouldn't host a "how to" guide or non-functional shim package.

**Comment by raxod502** [comment]
OK, thanks for the response.

I'd like to point out that `el-get` is designed to be compatible with `package.el` (since it allows you to install packages via `package.el`), so it makes sense that you can install `el-get` via `package.el`.

However, compatibility with `package.el` is an explicit non-goal of `straight.el` and it's actually completely impossible to replicate the features of the `straight.el` bootstrap using `package.el`. I maintain that installing `straight.el` via `package.el` is a fundamentally broken use case; if you did that, you would lose a number of extremely important features of `straight.el`.

But not wanting shim packages on MELPA is a totally reasonable position, and the remaining discussion is really only relevant to `straight.el` and not MELPA, so I'll close this issue.
