### ISSUE TITLE
Is it possible to introduce 'install/compile this first' dependencies?

### ISSUE THREAD

**Issue by vermiculus** [melpa/melpa#4944]
I think there were some timing issues that caused vermiculus/magithub#127 and vermiculus/ghub-plus#3. Here's my guess at what happened (from vermiculus/magithub#127): 

> The issue is not that `ghubp-get-repos-owner-repo` is not defined (if you look at your backtrace, it's there), the issue is that ghub+ was updated before apiwrap.el was. The previous version of apiwrap.el looked for `:get`, `:put`, … keywords in the `apiwrap-new-backend` function, but the updated version just uses a single `:request` keyword for the generic request function (i.e., `ghub-request`). When apiwrap.el built out the ghub+ functions, it wasn't able to retrieve the `:get` function, so `(alist-get 'get functions)` returned nil, so we tried to call a nil function.

Is there anything package developers can do to mitigate this?

**Comment by vermiculus** [comment]
Relatedly, it would be nice if `package.el` had the ability to say 'updating this package should kick off a recompile of packages dependent on it'.

**Comment by purcell** [comment]
> Is there anything package developers can do to mitigate this?

Not really, sorry. This lies with `package.el`.
