### ISSUE TITLE
Package now depends on another package

### ISSUE THREAD

**Issue by yassinphilip** [melpa/melpa#4981]
Hi!

This is not an issue _per se_, but I though you guys would like a heads up: I contacted the team that does [Faust-mode](https://melpa.org/#/faust-mode) (both in MELPA and stable) in order to make [Faustine](https://melpa.org/#/faustine) depend on it (but not the opposite) and thus eliminate any redundancy between the two packages. It's done, currently in test phase in a special branch on [both](https://github.com/rukano/emacs-faust-mode/blob/refactoring/faust-mode.el) [repos](https://bitbucket.org/yassinphilip/faustine/src/f3e37bb287c7d2bca5f61551d6f478cfcbbf0cf3/faustine.el?at=ext-mode&fileviewer=file-view-default).

Now in Faustine, I'm not sure exactly what version of Faust-mode I should require, for now it's the "stable" version number:

```
;; Package-requires: ((emacs "24.3") (faust-mode "0.1"))
```
But this one is not yet up-to-date. So the order of doing things would be :

- Push those refactoring changes to the master branch of both repos
- And then what, add a special "stable" tag to Faust-mode (and maybe Faustine as well)?
- Do something to the MELPA repo recipe(s)?

Thanks again for your work.

**Comment by purcell** [comment]
There's nothing to change in the MELPA recipes. Just make sure that the package dependencies in the current tagged version of faustine points at the latest tagged version of faust-mode.

Thanks for the heads-up.

**Comment by yassinphilip** [comment]
> Just make sure that the package dependencies in the current tagged version of faustine points at the latest tagged version of faust-mode

Yes but, what you call "the latest tagged version" is MELPA stable, right? This is what we have now:

- [The unstable version](https://melpa.org/#/faust-mode)
- [The stable version](https://stable.melpa.org/#/faust-mode)

Now the only indication of "version" that we have on those pages are in the badges, and correct me if I'm wrong, but this "version" argument of the "package-depends" header tag is not documented anywhere. So, that's:

- 0.1 for the stable version
- 20160930.222 for the unstable

Now from what I understand (again, scarce docs) the unstable version number is incremented at each commit, but apparently those 3 digits (here "222") are not the hash of said commit. So I'm a little confused as to exactly what version of faust-mode I should put in Faustine. I mean, there is actually no mention of "version" on the MELPA pages.

While we're at it, how do you declare a package "stable"? Is it a git tag?
And a last one: Can you make an unstable package depend on a stable one? I mean, for the user that only has unstable configured? I'm guessing no ; So that would make two sets of header for the two archives... Do I get this right?

If those questions are answered anywhere on the Interflubes, then please excuse my stupidity :)

**Comment by purcell** [comment]
Stable versions are determined by git tags. It's best if a stable version doesn't depend on a snapshot version, because then it won't be possible for someone to install it from MELPA Stable alone. My suggestion was that you should depend on `(faust-mode "0.2")` in `faustine`, but that you shouldn't tag a new version of faustine until `faust-mode` has been tagged with 0.2. Does that make sense?

**Comment by yassinphilip** [comment]
> Stable versions are determined by git tags. 

Aaah, thanks. So any snaphot repo, once it's been tagged something like _n.n_ appears automatically in stable, right?

> It's best if a stable version doesn't depend on a snapshot version, because then it won't be possible for someone to install it from MELPA Stable alone.

Note that it's actually the opposite : A snapshot (Faustine) depending on a stable (Faust-mode).

Thanks a lot for your help ; so that would mean this workflow:

- Increment the version number of faust-mode by creating the appropriate git tag
- Require this new version in Faustine
- Push all those changes to both master of both repos

And then later, optionally, 

- Create a version tag for Faustine so both are in stable.

Sorry again, I didn't realize the git tagging thing, I never use tags (and I've been told repeatedly that it's wrong, so it must be true).

**Comment by yassinphilip** [comment]
What was (and still kind of is) confusing me is that running `git tag` in my fork of faust-mode did not return anything... 

I was already wondering how this package made it to snapshot in the first place, as it didn't had the mandatory headers, that kind of things...? But now I'd like to know how it appeared in stable..?

Anyway, I issued the command

`git tag -a 0.2 -m "Refactored from Faustine" `
And pushed to master.

And in Faustine, I updated the header to say:

`;; Package-requires: ((emacs "24.3") (faust-mode "0.2"))`

Then tagged it too:
`git tag -a 0.2 -m "Refactored to work with faust-mode" `

And pushed to master.

So now, to test that everything is OK, I have to wait for the next stable roll, right?

**Comment by magnetophon** [comment]
@yassinphilip A while ago I got this very helpful mail regarding tagging ``faust-mode``:

```
Tagging is as simple as

     $ git tag v0.1 41379dd

I personally use version numbers like `v1.2.3`, but `1.2.3` or `1.2`
work just as well.  And don't fear, you only have to tag the latest
stable version...

Unfortunately, Git doesn't push tags automatically.  So after you are
done (or in case you've already tagged some of your commits and the
tags don't show up), you have to manually push the tags to the Git
repository:

     $ git push --tags origin

Now, everytime you reach a stable state, add a new tag to that commit.
The actual transition to the stable repository should happen
automatically.

In addition to the above, it's probably a good idea to place the
version number at a prominent place in your main script.  This and
tagging your stable commits will make it easier for your users to find
and compare different releases.  So you see, there's a lot to win and
nothing to lose... :)
```

I hope it helps.
