### ISSUE TITLE
Is it possible to bypass rebuilding a new package version only if specific files have changed?

### ISSUE THREAD

**Issue by kaushalmodi** [melpa/melpa#5005]
Hello,

How is it decided if a particular package needs to be rebuilt? Is a Melpa rebuild triggered after *any* commit to the repo? (It seems that's the case if the time-stamp in the build version is in US Eastern time zone.)

For my package in question, [`ox-hugo`][1], I'd like Melpa to rebuild it only if the two ox-*.el files change.
The latest build version was *20170911.1341*. What time zone is that? 

If it is 1:41pm EST, I made no changes to the ox-*.el files before then. If that's the case, I would like to prevent those rebuilds, because otherwise people would get unnecessary update notifications in the package manager.. even when I update just the documentation (README, Wiki, etc.).

[1]: https://github.com/kaushalmodi/ox-hugo

**Comment by milkypostman** [comment]
It is only the commits relevant to the package. If there is some file in
the package that was in the commit then it would update the
timestamp/version.

**Comment by kaushalmodi** [comment]
How can I figure out the files from the repo are considered as part of the package, based on the recipe? My recipe is simply this: https://github.com/melpa/melpa/pull/4993/files

**Comment by kaushalmodi** [comment]
The new ox-hugo build had no commits in the ox-*.el files compared to the previous build. So I was surprised to see a new build appear.

**Comment by milkypostman** [comment]
There may be other files in the commit.

Also merge commits can be confused for commits on the files sometimes just
based on how git works. I'll dig if I can find a chunk of time.

**Comment by aplaice** [comment]
@kaushalmodi The time-zone (if I've worked it out correctly by looking at the latest version of ox-hugo on MELPA — `ox-hugo-20170911.1436` as of writing) is GMT -0700. The time (and date) of the package correspond to the time (and date) of the latest "relevant" commit, in the time-zone where the package was built. Hence,  `20170911.1341` corresponds to 16:41 EST (-0400) and commit `899939c`, which did touch the elisp files.

The list of default files is [here](https://github.com/melpa/melpa/blob/12cdbdf404fa859a48d1bb69f058321d7595d2a2/package-build/package-build.el#L138).

You could even carry out some tests locally, by cloning MELPA, changing your recipe to point to a local git repo (you can do that! (`:fetcher git :url "/local/path/"`)) and checking when `make recipes/your-recipe` updates the package.

**Comment by kaushalmodi** [comment]
@aplaice Thanks for those details. They should be documented somewhere on the Melpa guide for developers (or is it already and I missed it? :) )

> The time-zone (if I've worked it out correctly by looking at the latest version of ox-hugo on MELPA — ox-hugo-20170911.1436 as of writing) is GMT -0700

That explains why I thought that it unnecessarily built the package. I was just short of doing a diff on the Melpa built tarballs.

> The time (and date) of the package correspond to the time (and date) of the latest "relevant" commit, in the time-zone where the package was built. Hence, 20170911.1341 corresponds to 16:41 EST (-0400)

That's golden.. I'll add that to my notes.

> and commit 899939c

On that note, is there a log somewhere that tells which commit hash was used to built that Melpa-built version?

> The list of default files is here.

Thanks! That confirms that my current recipe does not need to be touched.

> You could even carry out some tests locally, by cloning MELPA, changing your recipe to point to a local git repo (you can do that! (:fetcher git :url "/local/path/")) and checking when make recipes/your-recipe updates the package.

I did that, and confirmed that it fetched only the ox*-el files. It's the time-zone that got me confused. I am back on track now.

Should this issue be left open for documentation update?

**Comment by aplaice** [comment]
> They should be documented somewhere on the Melpa guide for developers (or is it already and I missed it? :) )

You're right, it would probably be helpful if this were explicitly in the `README.md` — I mostly found out by reading the source (plus docstrings) and experimenting. I'm not sure where the best place to specify this would be, though. 

Perhaps the [section on the build scripts](https://github.com/melpa/melpa/blob/master/README.md#build-scripts) (L351-354), which currently says:

```markdown
* `recipes/<NAME>` -- Build individual recipe `<NAME>`. Built packages
are put in the `packages/` folder with version corresponding to the
newest HEAD revision available; given according to the `%Y%m%d`
format.
```

should be clarified — the date corresponds to the latest commit that modified one of the files specified in the recipe (more exactly [`git log --first-parent -n1 --pretty=format:'\%ci' ${source-file-list}`](https://github.com/melpa/melpa/blob/master/package-build/package-build.el#L606), at least for git). Would something like:

```markdown
* `recipes/<NAME>` -- Build individual recipe `<NAME>`. Built packages
are put in the `packages/` folder with version corresponding to the
date of the latest commit that modified at least one of the files specified by
the recipe; given according to the `%Y%m%d` format.
```

have been sufficiently informative (and not overly verbose)? I think that the statement is also mostly correct for non-git fetchers. 

> On that note, is there a log somewhere that tells which commit hash was used to built that Melpa-built version?

Other than implicitly in the date from the version string, not really. There's the "entry" file ([example, will break eventually](https://melpa.org/packages/ox-hugo-20170911.1436.entry)), but it refers to the commit that happened to be HEAD at the time the package was built, so in general it will neither be the last commit that modified the recipe files (which we care about most) nor the last commit overall.

**Comment by kaushalmodi** [comment]
> Perhaps the section on the build scripts (L351-354), which currently says .. should be clarified

+1

> There's the "entry" file (example, will break eventually), 

That's good to know.

> but it refers to the commit that happened to be HEAD at the time the package was built, so in general it will neither be the last commit that modified the recipe files (which we care about most) nor the last commit overall.

Yes, I realized that indirectly.. [this page][1] shows that commit hash too. 

I have tried to summarize my understanding below:

```
                                                        (T0) commit N   <- This commit happened while Melpa is in a build cycle
                                               
         Melpa happens to poll the package repo here -> (T1) commit N-1    !But the package is built using commit N-1!         <--+
                                                                            (melpa.org/#/PKG, entry file reference commit N-1)    |
                                                        (T2) commit N-2                                                           |
                                                                                                                                  |
        This commit changes a recipe file as time T3 -> (T3) commit N-3 ->  Package will be versioned as PKG-T3 ------------------+

                                                        (T4) commit N-4
```

[1]: https://melpa.org/#/ox-hugo

**Comment by aplaice** [comment]
> I have tried to summarize my understanding below:

Nice diagram! As far as I understand, that is correct. An added, slight wrinkle is that if commit `N` (and later commits `N+1`, `N+2`, etc. occurring after this build cycle) do not touch the recipe files, then the package won't be updated and so the commit referred to on melpa.org/#/PKG and in the entry file, will continue to be `N-1` even after later build cycles, at least until the cache is cleared. (The package version will also stay as `T3`.)

Overall, the distinctions between these commits is usually not really important, for the purposes of MELPA, since the recipe files do not change between them, unless you're (understandably) worried about unnecessary updates for users.
