### ISSUE TITLE
Remove packages with malformed headers

### ISSUE THREAD

**Issue by purcell** [melpa/melpa#5010]
There were 10 packages listed as "no description available" due to the metadata in their main `.el` files being malformed or missing. I intend to remove all of these, and have already removed some for which fixes were submitted upstream and subsequently ignored: `cn-outline`, `helm-words` and `perl-completion`. I have also removed `zeitgeist`. (See f8498918, cc53e7cf, 109c352e, 38c334df.)

Of the remaining list, `caml` really [needs some work upstream](https://github.com/ocaml/ocaml/blob/trunk/emacs/caml.el) (and I'm not personally motivated to do that), and I've sent a patch offline to the maintainer of `redshank`. I've also sent reminders, pull requests or issues for [wolfram-mode](https://github.com/kawabata/wolfram-mode/pull/8), [syntactic-close](https://github.com/emacs-berlin/syntactic-close/pull/32), [zonokai-theme](https://github.com/ZehCnaS34/zonokai-emacs/issues/4) and [merlin](https://github.com/ocaml/merlin/pull/719). At a certain point soon I'll just go ahead and remove any remaining packages which have not been fixed up.

Status:
- [x] [caml](https://github.com/ocaml/ocaml/pull/1346)
- [ ] [wolfram-mode](https://github.com/kawabata/wolfram-mode/pull/8)
- [x] [syntactic-close](https://github.com/emacs-berlin/syntactic-close/pull/32)
- [ ] [zonokai-theme](https://github.com/ZehCnaS34/zonokai-emacs/issues/4)
- [x] [merlin](https://github.com/ocaml/merlin/pull/719)
- [ ] Redshank

**Comment by purcell** [comment]
Following this, I'd like to make it a hard fail in the build process if a package is malformed, so that no broken packages are published. This will force us to handle failure better, and report it along with any package-lint issues. Goal is to publish only high-quality well-maintained packages, and name-and-shame those with issues which could be fixed.

**Comment by purcell** [comment]
I didn't hear anything more from the maintainers of the still-non-compliant packages, so I've removed the recipes.

**Comment by Wilfred** [comment]
@purcell have you heard back from the redshank maintainer? emacs-refactor depends on it: https://github.com/Wilfred/emacs-refactor/issues/36

**Comment by purcell** [comment]
Didn't hear back from the Redshank maintainer, so it got removed, sorry. I sent a patch too. Happy to re-add if you're willing to babysit a fixed version in an https-hosted location.

**Comment by stardiviner** [comment]
I saw emr is been unavailable for a long time, what will go for this redshank?

**Comment by Wilfred** [comment]
OK, I've created https://github.com/emacsattic/redshank/pull/1 to fix the redshank headers.

@purcell would you be happy to accept a PR to restore redshank to MELPA from the attic? If not, I'm willing to maintain it, but only the bare minimum required to meet emr's needs.

**Comment by purcell** [comment]
> @purcell would you be happy to accept a PR to restore redshank to MELPA from the attic? If not, I'm willing to maintain it, but only the bare minimum required to meet emr's needs.

Yep, sounds good.

**Comment by kenkangxgwe** [comment]
@purcell , the wolfram-mode has just merged your PR. https://github.com/kawabata/wolfram-mode/pull/8. Could you please add it back to Melpa?

**Comment by purcell** [comment]
@kenkangxgwe Done in 40ded230, thanks.
