### ISSUE TITLE
Moving rubikitch's packages to github

### ISSUE THREAD

**Issue by tarsius** [melpa/melpa#5020]
Hello @rubikitch 

Packages from the Emacswiki will soon be removed from Melpa or at least "frozen" (see #5008), so I would like to ask you again to move your remaining packages elsewhere.

This is a follow up to https://github.com/melpa/melpa/pull/3889#issuecomment-220726713. Sorry for not replying there earlier.

You said that you would move the following packages to github:

- [x] lispxmp
- [x] minor-mode-hack
- [x] recentf-ext
- [x] sticky
- [x] usage-memo
- some others which are not (or no longer) available from melpa

As far as I can tell you have not done that yet. Could you do so now please?

You also said that `sequential-command` is already available from github but that appears to not (or no longer) be the case.

Thanks!

**Comment by tarsius** [comment]
Oh, and there is also `screenshot`, which you said you are "not using".

If you would like to keep this available for others to install through Melpa, then please move it to Github too.

**Comment by joewreschnig** [comment]
rubikitch is also the only committer for the past five years on http://repo.or.cz/r/anything-config.git which we are tracking in #3004, and also needs to be moved.

**Comment by tarsius** [comment]
Friendly ping @rubikitch!

I checked my lists again and these packages showed up:

* Your packages that Melpa still gets from the Emacswiki.

- [ ] lispxmp
- [ ] minor-mode-hack
- [ ] recentf-ext
- [ ] screenshot
- [ ] sequential-command
- [ ] sticky
- [ ] usage-memo

* Your packages that the Emacsmirror still gets from the Emacswiki.

- [ ] anything-kyr
- [ ] anything-kyr-config
- [ ] auto-install
- [ ] d-insert-assert
- [ ] display-buffer-for-wide-screen
- [ ] display-hatebu
- [ ] eijiro
- [ ] el-expectations
- [ ] eldoc-extension
- [ ] emacs-init-check
- [ ] icicles-iswitchb
- [ ] install-elisp
- [ ] lispxmp
- [ ] minor-mode-hack
- [ ] mode-line-frame
- [ ] recentf-ext
- [ ] screenshot
- [ ] space-chord
- [ ] sticky
- [ ] unify-buffer
- [ ] usage-memo

**Comment by tarsius** [comment]
I have send an email to @rubikitch informing/reminding them about this issue.

**Comment by tarsius** [comment]
@rubikitch Due to a little mishap the packages from the wiki have been removed a little earlier than intended. For more information see #5008.

**Comment by ahungry** [comment]
@tarsius potential fix in this PR (rehosting under a github repo I set up to mirror the files).

https://github.com/melpa/melpa/pull/5268

At least with that repo rehost, we can have a history on file changes + people can audit them for security concerns when they get a chance (worst case, users are in the same state they were in pre-5008 merge).

**Comment by aplaice** [comment]
The packages that were on MELPA, with the exception of `screenshot`, seem to be already on GitHub, (though unfortunately without any history):

https://github.com/rubikitch?tab=repositories

**Comment by tarsius** [comment]
Closing this now. With only one package (`screenshot`) remaining by this author it isn't necessary to treat it any different than any of the other packages that had to be removed. And the packages that are in the Emacsmirror but never were in Melpa aren't Melpa's problem.
