### ISSUE TITLE
SICP package missing

### ISSUE THREAD

**Issue by mnsanghvi** [melpa/melpa#5024]
It looks like the SICP package which was added via commits f7e7e74e and ddc3ab62 was removed but I do not see anything in the logs regarding its removal.   Is this accidental removal or was this done for a reason ?

**Comment by purcell** [comment]
It was removed in https://github.com/melpa/melpa/commit/cf92ce1a2bc92c73071d157e7e223982bbd3f818#diff-420491f3c3c0f0a5443d9dcb936fa260 - the comment there explains why. :-)

**Comment by mnsanghvi** [comment]
Thanks for the response.  Wonder why I wasn't able to come across that commit when I was doing a search on it for sicp.

**Comment by purcell** [comment]
I found it on the command line with `git log -- recipes/sicp`, fwiw. :-)

**Comment by webframp** [comment]
I've been slow to handle this one sorry, will continue discussion over in https://github.com/webframp/sicp-info/issues/6
