### ISSUE TITLE
melpa down

### ISSUE THREAD

**Issue by benma** [melpa/melpa#5025]
http://melpa.org/

Just in case you weren't notified yet ;) Feel free to close this.

Thanks.

**Comment by joymax** [comment]
Server IP is 104.131.31.21 and it's working fine. Something wrong with DNS records

**Comment by benma** [comment]
What's the IP of melpa.milkbox.net?

**Comment by purcell** [comment]
Guessing that our name servers (NS1.HOVER.COM, NS2.HOVER.COM) aren't responding.

@benma melpa.milkbox.net isn't a thing any more, just melpa.org.

In any case, if anyone is stuck and unable to install packages, you can use a [mirror](https://github.com/melpa/melpa/blob/master/README.md#mirrors). :-)

**Comment by purcell** [comment]
Looks like the systems of hover.com - our registrar - are dead. :-/

https://twitter.com/search?q=hover.com&src=typd

**Comment by benma** [comment]
> In any case, if anyone is stuck and unable to install packages, you can use a mirror. :-)

TIL :) Great thinking ahead.
