### ISSUE TITLE
A problem with Install or Update package

### ISSUE THREAD

**Issue by u-combinator** [melpa/melpa#5039]
- My `Emacs` version is 25.3.1.
- I already set melpa to `package-archives`.
- I installed package are all from `MELPA`.

For example, if I want to **install** `AAA` package.

when I  in 

1. `list-package`  -> search for `AAA` mode, and install it.

or

2.  `package-install` RET `AAA` 

are all show a message to me

```
Error while verifying signature AAA.sig:

Command output:
gpg: no valid OpenPGP data found.
gpg: the signature could not be verified.
Please remember that the signature file (.sig or .asc)
should be the first file given on the command line.
```

And also some wrong in show `AAA` information.

That's not as text as normal , only show information with **html code**.

 I want to ask:

Is that a `Emacs` bug or a `MELPA` problem?

And how to solve it ?

Thanks!

**Comment by purcell** [comment]
This is not a MELPA issue: we don't provide signatures for our packages (yet?). Check out the docs for the `package-check-signature` variable.
