### ISSUE TITLE
sly package broken in melpa.

### ISSUE THREAD

**Issue by mfiano** [melpa/melpa#5071]
Something MELPA is doing has broken the sly package. Please see https://github.com/joaotavora/sly/issues/131

**Comment by purcell** [comment]
Sorry, this is invalid as a MELPA issue as far as I am concerned: we don't do anything but package up the files in the recipe and make them available for your `package.el` to download and install. I note that `sly.el` is doing some clever stuff to identify its own version: the fault is most likely with that code, when run in the presence of a previously-installed-and-loaded version of Sly. If you can provide steps to reproduce this, @joaotavora and I might be able to help more.

**Comment by joaotavora** [comment]
For the record, i agree. I also don't think this is a melpa issue.
Reproduction steps would be great though.

**Comment by mfiano** [comment]
I apologize for the noise. I can't reproduce it with a simple -Q command line recipe, so I'll have to bisect my config some other time when my job isn't whipping me. Still strikes me as odd that it only occurs with the latest 2 commits of sly, but nothing I can dig deeper into at the moment, and I also do not think it is MELPA's fault. Thanks and sorry again.

**Comment by joaotavora** [comment]
It's understandable that you cant use `emacs -Q` to reproduce as this is possibly related to unknown compilation techniques that package.el might be using. Reproducing it would take some effort, perhaps it's not worth it yet. Keep an eye on it and I'll also try to take some cautionary measures and keep the cleverness that @purcell mentioned to a minimum.

**Comment by purcell** [comment]
> I'll also try to take some cautionary measures

Maybe look at the code that the `pkg-version` package uses to do something similar?

**Comment by joaotavora** [comment]
What package is that? Is it in MELPA?

**Comment by joaotavora** [comment]
I think you mean the pkg-info package. That doesn't seem to do exactly what I want. I need that the most recent load of either `sly.el` or `sly.elc` sets the correct value in the variable `sly-package-version`. This should happen regardless of the file name. Also just compiling `sly.el` into `sly.elc` shouldn't set it in the current session.

**Comment by purcell** [comment]
> I think you mean the pkg-info package

Ah yes, sorry. Wasn't sure if it would be helpful.
