### ISSUE TITLE
Opinion: OS specific packages should be omitted or forced to require a tag that matches the OS

### ISSUE THREAD

**Issue by ahungry** [melpa/melpa#5098]
I just noticed wordsmith-mode pop up in my Elpa updated packages area.

When I went to read about the mode, I found that it is OSX specific.

https://github.com/melpa/melpa/pull/1457

Since we have the `#'package-menu-filter` function to filter the list by matching tags, I think OS specific packages should identify themselves as such in their keywords - this would assist users of the OS in finding specialized packages, and also make it slightly easier to ignore those packages if one is not a user of that OS.

**Comment by purcell** [comment]
I agree that consistent use of keywords would be nice, but I don't think this issue is actionable as far as MELPA is concerned, sorry, so I'm going to close it.
