### ISSUE TITLE
Feature/Help: Calculated version number (or running script, or replaces in recipies)

### ISSUE THREAD

**Issue by wsnyder** [melpa/melpa#5117]
I want to add a recipe for a package where the repository has a version number that is calculated by it's (own) makefile.  e.g.

  (defconst my-mode-version "__VERSION__-__REVISION__-__PACKAGER__"

When MELPA does its build this should become:

  (defconst my-mode-version "2017-10-25-1a6d846-mod-melpa"

Is there a way to do this now?  If not, I can think of several options:

1. A recipie specifies a shell command to run post-download.

2. A recipie specifies an elisp function within the package to run post-download.

3. A recipie can make replacements, e.g.

  (my-mode :fetcher github :repo "myrepo/my-mode"
           :files ("my-mode.el")
           :replace (("__VERSION__" 'pkg-version)
                     ("__REVISION__" 'pkg-revision)
                     ("__PACKAGER__" "melpa")))

If there isn't already a way to do this, would 3) be acceptable?  I have a rough patch prototyped to implement 3).

**Comment by milkypostman** [comment]
this was a discussion a long time ago and we decided not to do this. there were arguments against doing this to begin with. i believe there is a way to get a packages version from package.el but dont quote me on this. 

what is it you're trying to do?

**Comment by milkypostman** [comment]
^^^ i mean, why do you need this variable?

**Comment by wsnyder** [comment]
It's used for bug reporting, and all versions distributed outside github.  Let's hypothetically say that variable wasn't there, how would that help melpa then get a github hash related version number?

**Comment by milkypostman** [comment]
Melpa uses the Git commit timestamp for unstable packages and uses versions
parsed from git tags for stable releases. That's just the way it works. I
will have to find time to dig and see what our previous resolution was.

**Comment by purcell** [comment]
Yep, we're not going to change anything here, but if you want to include a `;; Version:` header or corresponding variable in your file, it will be left untouched by MELPA. You can include in your package a function which retrieves it, using the `lm-` functions.
