### ISSUE TITLE
Help clarify adding MELPA package for package already in Emacs core

### ISSUE THREAD

**Issue by wsnyder** [melpa/melpa#5118]
If I want to add a recipe for my package that is already in the Emacs core distribution, is anything special required or to be careful of either in the recipe or in how users install it?  

(The use case is users have requested it be added to MLPA so they can get the most recent version over what comes with Emacs by default.)

I can guarantee that the repo's version will always be the latest and greatest.

A brief sentence in the docs about this would be helpful.  Sorry in advance if it is there and I missed it.

**Comment by purcell** [comment]
Hi! Yeah, there's no issue with that, I think - just submit a recipe as usual. The MELPA versions will all have snapshot tags. If you have version tags on the repo, then MELPA Stable will include those versions too, so you might have to coordinate those versions of your package with those in the core Emacs distro. There may be some special handling (pinning etc.) of built-in packages in recent versions of `package.el`, but I'm not sure.

Does that help? Overall this is an unusual case, so I don't really plan to document it centrally, sorry.
