### ISSUE TITLE
Alexandria-like package for elisp

### ISSUE THREAD

**Issue by alphapapa** [melpa/melpa#5142]
Hi @purcell, et al,

Now and then I come across a macro or function which seems generally useful but is not in Emacs nor any MELPA package.  Sometimes I see them essentially duplicated in multiple MELPA packages that need them.  I've put some in my own packages, but having to use the prefix every time I call one (e.g. `org-super-agenda--macro-name`) is tedious.  I've tried submitting some to, e.g. `dash`, but they are typically rejected as not being in the package's scope.

CL has Alexandria, but Emacs Lisp doesn't seem to have an equivalent.  So, I would like to propose such a package, perhaps called Elexandria.  I've collected a few macros and functions already.  My intention would be to publish them to a repo, document and give examples for each function and macro, and submit it to MELPA.

My question is about naming.  Alexandria does not use a prefix (of course, being CL, it doesn't need to), and `elexandria-` is a rather long prefix, which somewhat defeats the purpose (or at least my own purpose of avoiding long prefixes for generally useful things).  MELPA requires packages to use their name as a prefix for all macros and functions in it, although there are older packages that have sort of been "grandfathered in" to this policy.

So, given that no names are used which exist in Emacs or commonly installed ELPA/MELPA packages, would you permit such a package to omit the prefix from its macro and function names?  My intention would be to only add ones which are generally, widely useful, with proven use cases, so there would not be a proliferation of non-prefixed names.  And if any were eventually added to Emacs proper, I would gate them on the Emacs version or `featurep`/`functionp`.  I would also be happy to collaborate on the repo with MELPA maintainers so that it wouldn't be a one-maintainer project.

If this is not allowable, would you allow them to be aliased to a shorter prefix, e.g. `elexandria-with-gensyms` to `el-with-gensyms`?  (I considered naming the package `el.el`, which is sort of self-referentially clever, but that may be too short, and an homage to Alexandria seems appropriate, anyway.)

Thanks for your thoughts.

**Comment by purcell** [comment]
Sorry, we'd still require a prefix, and the prefix should match the package name, so `el-` is out. Maybe call the package something shorter like `elexa`. This sounds like a personal "utils" package, though, so I'd be a bit wary that it wouldn't be widely useful in its initial form -- if a package doesn't aim to provide a consistent set of functionality that potential users can relate to, it's generally not likely to see much use.

**Comment by alphapapa** [comment]
> This sounds like a personal "utils" package, though, so I'd be a bit wary that it wouldn't be widely useful in its initial form -- if a package doesn't aim to provide a consistent set of functionality that potential users can relate to, it's generally not likely to see much use.

That's not my intention.  I have lots of macros in personal projects that are specific to the project or my own programming style, and I would not include those.  My intention is to provide an Emacs Lisp equivalent of the CL Alexandria package.  Here's an example of the small collection I have so far: https://github.com/alphapapa/elexandria/blob/master/elexandria.el  In fact, there was just a post on /r/Emacs asking about how to do something that my `defclass*` macro solves in a simple way: https://www.reddit.com/r/emacs/comments/7fnfju/how_to_customize_constructors_for_eieio_objects/

`elexa` isn't very long, but it sounds a lot like Alexa, which, considering Amazon, gives me the creeps.  ;)

Well then, what if I did officially name the package `el`?

**Comment by purcell** [comment]
Looking at Alexandria, I feel like big portions of it are already covered well by existing core and extension libraries like `pcase` and `seq`, so I still feel like one or more small specific libraries would be a _much_ better choice. Most of your existing code is useful macros, so releasing those as a package along the lines of [mmt](https://github.com/mrkkrp/mmt/blob/master/mmt.el) makes much more sense for discoverability and user convenience than bundling them with other random functions.

**Comment by alphapapa** [comment]
To be honest, I'm not sure exactly what Steve meant in his last comment.

> Looking at Alexandria, I feel like big portions of it are already covered well by existing core and extension libraries like pcase and seq, so I still feel like one or more small specific libraries would be a much better choice. 

Just to be clear, I didn't mean to suggest making an Elisp version for everything in Alexandria, but only things that are useful in Emacs.

> Most of your existing code is useful macros, so releasing those as a package along the lines of mmt makes much more sense for discoverability and user convenience than bundling them with other random functions.

I hadn't seen mmt before.  There is some overlap between my proposed package and it, but some of the macros and functions in mine aren't macro tools.

So this is the part I find confusing: does that mean that I *should* release this as a package after all?  The alternative, to release purpose-specific packages, seems too granular to me.  For example, I have one math function, one string macro, and one process macro, that I think are useful enough to be worth packaging, but obviously having them each in their own package would be silly (we don't want to become the Emacs equivalent of `npm`, haha).

So, with the expected polishing and finishing touches, would you accept this package named `el` with `el-`-prefixed names?

Thanks.

**Comment by tarsius** [comment]
> So, with the expected polishing and finishing touches, would you accept this package named `el` with `el-`-prefixed names?

@purcell I think we need a decision here :wink:

**Comment by purcell** [comment]
> So, with the expected polishing and finishing touches, would you accept this package named el with el--prefixed names?
> 
> @purcell I think we need a decision here 😉

LOL, SORRY. :-)

The answer is that yes, I'd accept a two-character package name, but I'd strongly suggest it not be "el", because there are lots of `el*` identifiers out there in the wild. I would merge an `el`, but I'd feel more icky about it than, say, `al`. :-)

**Comment by alphapapa** [comment]
LOL, well I guess that would mean calling the package `alexandria.el`, which isn't as cute, and might convey some expectation of parity with the real Alexandria.  I'll give it some more thought.  Thanks, Steve and Jonas.

**Comment by tarsius** [comment]
Ping?

**Comment by tarsius** [comment]
Closing this now...
