### ISSUE TITLE
Feature Request: Show HEAD hash for packages from repos on website

### ISSUE THREAD

**Issue by justbur** [melpa/melpa#5159]
It would be nice to be able to quickly figure out what the latest commit is for the current version of a package on melpa.org. Would it be possible to record this information when the package is built and report it on the website? I'm only suggesting that the latest commit hash be shown somewhere. I'm not asking for a change to the versioning scheme or anything like that.

**Comment by milkypostman** [comment]
doable. but not sure when someone will get around to it. thanks for the
feature request!

**Comment by justbur** [comment]
I understand. Thanks!

________________________________

**Comment by purcell** [comment]
Just click on the package and the individual package page has that info:

![screen shot 2017-12-02 at 13 39 19](https://user-images.githubusercontent.com/5636/33509418-4f8c9454-d766-11e7-8137-4f36b944f373.PNG)

**Comment by purcell** [comment]
I just pushed a change which - once it gets pulled onto the build server - will make the "github" etc. links point directly at the corresponding source tree in the package's repo. For example, in the example pictured above, the `github` link would point at https://github.com/LouisKottmann/zygospore.el/tree/1af5ee663f5a7aa08d96a77cacff834dcdf55ea8.

**Comment by justbur** [comment]
Whoops sorry. I’ve looked at those pages many times and never noticed it.

**Comment by purcell** [comment]
No worries. The new links will be a bit more convenient anyway.
