### ISSUE TITLE
Recipes with :files (:defaults ...) don't build properly

### ISSUE THREAD

**Issue by dieggsy** [melpa/melpa#5164]
Namely, if I try `make recipe/recipe-name` on any recipe with something like `:files (:defaults "additional-file")` (such as neotree for example), all I see in the `packages` directory is `.entry`, `.tar`, `.svg`, and `-readme.txt` files, but no `.el` files or additionally specified files.

**Comment by purcell** [comment]
That *is* building properly. Multi-file packages are built into tarballs.

**Comment by dieggsy** [comment]
Heh, woops - thanks for the clarification.
