### ISSUE TITLE
The recipe for use-package needs update

### ISSUE THREAD

**Issue by meiyopeng** [melpa/melpa#5171]
Recent git commits of use-package split use-package.el into several emacs-lisp
files. So the melpa recipe for use-package is not working anymore.

The latest use-package on melpa.org is broken. I experienced an error when I
install use-package from melpa.
```
File is missing: Cannot open load file, No such file or directory, up-core
```

The unavailability of use-package will affect a lot of emacs users. Please fix
this issue as soon as possible.

**Comment by terlar** [comment]
This is WIP: https://github.com/melpa/melpa/pull/5167

**Comment by meiyopeng** [comment]
Sorry. I didn't found that pull request.
