### ISSUE TITLE
Question regarding re-naming of company-eshell-autosuggest

### ISSUE THREAD

**Issue by dieggsy** [melpa/melpa#5182]
This was discussed here: https://github.com/melpa/melpa/pull/5094, but the recommended method of usage has since changed to a minor mode that activates company-mode but overrides local company frontends, backends, delay, and active map (see [updated README](https://github.com/dieggsy/company-eshell-autosuggest)). Company is still a central part of the package, but the package is no longer "just" a company backend. I was wondering if it would be ok now to rename to `eshell-autosuggest`, or whether `company-` is still recommended.

My variable and function names are also getting quite long, heh... so if the `company-` prefix is still required, recomendations on shortening the package prefix are welcome.

**Comment by purcell** [comment]
Sure, if you want to rename it to `eshell-autosuggest` now, just rename the file and its symbols etc., then submit a PR to rename the recipe and its contents. The modified recipe can include `:old-names (company-eshell-autosuggest)`.

**Comment by dieggsy** [comment]
@purcell any opinion on `esh-` vs `eshell-`? I know there's some packages than use `esh-` as well as some builtins that use it only for filenames.

**Comment by dieggsy** [comment]
Going ahead with `esh` based on existence of other packages with this prefix, let me know otherwise. Will open a PR soon

**Comment by purcell** [comment]
Sounds fine, but if it were me and I wanted people to find & use the package, I'd favour the longer, more searchable name.
