### ISSUE TITLE
Building local melpa on RHEL 6 timeout

### ISSUE THREAD

**Issue by eflanigan00** [melpa/melpa#5197]
The timeout isn't compatible with RHEL 6.
I remove the timout but everything just hangs.
Any advice for an alternate timeout call?

**Comment by purcell** [comment]
Please can you provide more info? What do you mean by "isn't compatible". What is the "everything" that just hangs? How could someone reproduce this? Our code already checks for a `timeout` that supports `-k`... without more information, there's nothing anyone can do to address the issue you're seeing.

**Comment by eflanigan00** [comment]
Recipe rules, the line where:

    $(TIMEOUT) $(EVAL)    

I had to change to 

    $(EVAL)

I don't think the timeout command is compatible with timeout 8.4 which is what I'm using on RHEL.

After this change the individual recipes hang after they are built.

**Comment by eflanigan00** [comment]
@tarsius can you reopen this please?

**Comment by tarsius** [comment]
I have reopened but I don't know what you want us to do.

> I don't think the timeout command is compatible with timeout 8.4 which is what I'm using on RHEL.

What would be? (I don't understand what this does in the first place, so I cannot help with this.)

**Comment by eflanigan00** [comment]
I am trying to build a local melpa. I would like to make the packages without the timeout.

It seems like the timeout kills the package build process after an individual package builds. I need to know how to run without the timeout (if that is possible).

**Comment by milkypostman** [comment]
you need to provide (attach) a log that we can see what you are trying to
do. what jonas is saying is that your explanation is very short and
unclear. we have no context and thus no idea what could be wrong.

**Comment by eflanigan00** [comment]
Sorry for the delayed reply.
`timeout` on RHEL 6 doesn't support the `-k` option
Does anyone have a creative workaround for modifying the makefile to work without using -k in timeout?

**Comment by purcell** [comment]
> timeout on RHEL 6 doesn't support the -k option

But we specifically check for that case. :-/

https://github.com/melpa/melpa/blob/19c7c36af8e30b9a9ccc4afda2a7b7e39e8d32ff/package-build/package-build.el#L91

**Comment by eflanigan00** [comment]
I have cloned the entire melpa repo and have changed the recipes to point to local git repos.
I do this because I am behind a firewall.

I am talking about the timeout here while building the recipe target:

https://github.com/melpa/melpa/blob/master/Makefile

**Comment by purcell** [comment]
Okay, thanks - that helps.

You can override the timeout command by running `make TIMEOUT= TARGET` instead of `make TARGET`. (You can probably also set `TIMEOUT` as an environment variable if that's easier.)
