### ISSUE TITLE
[help] Add a recipe for a large repo with a single Emacs Lisp file

### ISSUE THREAD

**Issue by MaskRay** [melpa/melpa#5199]
We want to submit a recipe of a single Emacs Lisp file in a large (disk usage) repository.

<https://github.com/jacobdufault/cquery/blob/master/emacs/cquery.el>

Is there some way to create a recipe that will not waste the Melpa server's disk space?

```
% du -sh .git         
52M     .git 
```

Most changes are unrelated to Emacs Lisp but they contribute most of the space usage.

**Comment by MaskRay** [comment]
![finding references in a C++ project](https://ptpb.pw/ZdRr.jpg )

**Comment by purcell** [comment]
We don't have a way to efficiently handle this situation, but I wouldn't worry too much about 52MB, because we have some much bigger repos. The best solution, generally, is to break the elisp out into its own repository.
