### ISSUE TITLE
Unable to refresh package list

### ISSUE THREAD

**Issue by zeusdeux** [melpa/melpa#5259]
## Summary
`M-x package-list-packages` leads to
```
Importing package-keyring.gpg...done
error in process filter: End of file during parsing [2 times]
```
I have attempted to refresh my package list on two different, distinct internet connections.

## Steps to reproduce
1. `emacs -q`
2. Eval the following block (in `*scratch*` or wherever)
    ```elisp
    (setq package-archives '(("gnu" . "https://elpa.gnu.org/packages/")
			         ("melpa" . "https://melpa.org/packages/")))
    ```
3. `M-x package-list-packages`

**Comment by terlar** [comment]
I also experience this issue.

**Comment by zeusdeux** [comment]
`curl -i -L https://melpa.org/packages/archive-contents` returns `Content-Length: 0`. This is why we get the `End of file during parsing`.

@terlar Any idea what might be up? I don't see anything on the melpa twitter either.

**Comment by milkypostman** [comment]
Possibly the server is full. I don't know right now as I'm not near a machine.

**Comment by zeusdeux** [comment]
@milkypostman Ah the disk space issue again. Not sure how the repo is run or where it's hosted, but if it's on AWS then maybe we should look into some auto resizing?

**Comment by milkypostman** [comment]
I am working in something for the server but have not had much time lately. I didnt get a disk space warning so am a bit surprised.

**Comment by milkypostman** [comment]
I have rebooted the server and it seemed to be back. I will resolve the disk issues tonight.

**Comment by zeusdeux** [comment]
Thanks @milkypostman!

**Comment by milkypostman** [comment]
it was fuller than the hosting would suggest. the main problem is that we auto upgrade kernels but they don't get cleaned up.

**Comment by milkypostman** [comment]
this is resolved for now... there is another issue tracking the longer fix.
