### ISSUE TITLE
Many packages are unavailable today on Melpa, though are present on Melpa Stable

### ISSUE THREAD

**Issue by vlebedev** [melpa/melpa#5260]
Popular starter kits like graphene or purcell's .emacs.d can't be bootstrapped on the clean emacs installs, because of dependent package errors.

**Comment by milkypostman** [comment]
Should be done now and/or you can temporarily use a mirror.

**Comment by kommen** [comment]
Many spacemacs users running into problems with missing packages: https://github.com/syl20bnr/spacemacs/issues/10244

**Comment by kommen** [comment]
The packages still missing are emacs wiki packages. See https://github.com/melpa/melpa/pull/5008#issuecomment-360103510 for a discussion.

**Comment by purcell** [comment]
> Popular starter kits like graphene or purcell's .emacs.d can't be bootstrapped on the clean emacs installs, because of dependent package errors.

Mine is now fixed, and I'd encourage other authors to either discontinue use of emacswiki packages, or vendor them manually into their own config trees.

**Comment by purcell** [comment]
Closing this now. See #5008 for questions about Emacswiki packages.
