### ISSUE TITLE
centered-window-mode removed from melpa.org

### ISSUE THREAD

**Issue by anler** [melpa/melpa#5280]
Hello!

Sorry if this is not the place for asking this 🙏 
For some reason the package [centered-window-mode](https://github.com/anler/centered-window-mode/) does not appear in [melpa.org](https://melpa.org/#/?q=centered-window-mode) but it does in the [this repository](https://github.com/melpa/melpa/blob/master/recipes/centered-window-mode). Do you know how can I fix this?

Thanks!

**Comment by tarsius** [comment]
Yes. Rename the package here also.

**Comment by anler** [comment]
Hi @tarsius  what do you mean? How should I rename it? Thanks!

**Comment by tarsius** [comment]
This: 58bfd795d4d620f0c83384fb03008e129c71dc09.
