### ISSUE TITLE
lsp-php package is causing confusion

### ISSUE THREAD

**Issue by NateEag** [melpa/melpa#5314]
As you can see in [this thread](https://www.reddit.com/r/emacs/comments/7xz6bd/im_having_the_worst_time_trying_to_get_php/), the [lsp-php](https://github.com/melpa/melpa/blob/master/recipes/lsp-php) recipe is causing some confusion.

The confusion stems from the fact that there are two available lsp-php packages, one from the [emacs-lsp organization](https://github.com/emacs-lsp/lsp-php) and one from [tszg](https://github.com/tszg/lsp-php), both started last month.

Both packages offer the same feature (`lsp-php`), and the one from emacs-lsp is not yet installable from package.el.

I know that generally packages are supposed to be named for their feature, but could it make sense to add a recipe for the emacs-lsp version with the name `lsp-php-emacs-lsp`?

That way, the two libraries would show up next to each other in the `package-list-packages` view, so people would be less likely to confuse them, since they'd see both exist.

If there's a better way forward, I'm all ears - just trying to figure out what to do about [this issue I filed](https://github.com/emacs-lsp/lsp-php/issues/1) with the emacs-lsp project.

**Comment by tarsius** [comment]
The best outcome would be if the author(s) of the two implementations joined forces.

**Comment by NateEag** [comment]
Yeah, I suppose that would make more sense.

I don't own either project, but I'll see if I can get a discussion started about the idea.

**Comment by tarsius** [comment]
I have merged #5463.
