### ISSUE TITLE
Release branch for MELPA stable

### ISSUE THREAD

**Issue by dajva** [melpa/melpa#5317]
Is it possible to have stable releases on other branches than the branch specified in the melpa recipe in github based packages?

What I want to do is to have a stable bugfix release but this will mean that master and and stable would have to diverge since master have some new code that is not on stable.

**Comment by milkypostman** [comment]
Stable builds are based on tags which are repo global. They are not based on branches. So you can have whatever branches and regular MELPA build will come from whatever the default GitHub repo is and stable will come from there latest tag.

**Comment by dajva** [comment]
Thanks
