### ISSUE TITLE
Donation to MELPA project

### ISSUE THREAD

**Issue by syohex** [melpa/melpa#532]
How do I donate to MELPA project ?

Please register [flatter](https://flattr.com/]) or similar donation service or PayPal donations.

**Comment by dakrone** [comment]
Did the donation link get lost somewhere? I can't seem to find it on the page.

**Comment by milkypostman** [comment]
yeah I removed it for the time being. we need to look into setting
something up.

**Comment by purcell** [comment]
We should probably set up Patreon or similar.

**Comment by gonsie** [comment]
Any change? GitHub has built in payments as well.

**Comment by jthaman** [comment]
Hey all, I'd also like to donate to cover server fees. So count 'em: two people inquire about donating within one week.

**Comment by milkypostman** [comment]
Hello all, I have created an Open Collective to receive contributions for MELPA. https://opencollective.com/melpa

And I've added the sponsorship page as well.

I hope this works for everyone.

**Comment by milkypostman** [comment]
Let me say more.

1. It was easy to setup. Also, as I was going to setup Github sponsorships it seemed like I'd either need to setup a bunch of financial stuff or use a financial proxy and one of those was Open Collective.
2. There is transparency about spending of funds.


I will just document here that we plan to use the money to pay server fees. After collecting enough for a month I would like to consider contributing to our maintainers, right now that would be @riscy and @tarsius who are managing PRs and maintaining the package-build code.

**Comment by tarsius** [comment]
Not to forget you and @purcell :grimacing:

IMO @riscy should get the biggest share since currently he is doing nearly all the review work and that takes a lot of time and isn't all that exciting (but very valuable).

It will probably take a while but I expect that eventually this will be a few hundred $ per month.

**Comment by tarsius** [comment]
Just tweeted about it. You might want to do the same. :wink:

**Comment by tarsius** [comment]
How do we all get listed in "our team"? I only found "create an organization" but not "[apply to] join organization".

**Comment by milkypostman** [comment]
Do you mean on open collective?

i think I need to add you. Let me know your username.

**Comment by tarsius** [comment]
"jonas": https://opencollective.com/jonas

**Comment by riscy** [comment]
Thanks all -- I set myself up and my username is `riscy`.
