### ISSUE TITLE
req-package has a new dependency on el-get

### ISSUE THREAD

**Issue by DarwinAwardWinner** [melpa/melpa#5341]
As of https://github.com/edvorg/req-package/commit/aa509eeeab549c19071588675ce12e65c0bf0a34, req-package now requires el-get to be installed.

**Comment by aplaice** [comment]
The dependencies reported by MELPA are fetched from the repository itself (in particular the [Package-requires header](https://github.com/edvorg/req-package/blob/699d5aa9204c07905db4574406f771c69aa5752c/req-package.el#L8), so this should be solved upstream.

**Comment by purcell** [comment]
Yep, this is an upstream issue. Thanks for following up on that, @aplaice.

**Comment by aplaice** [comment]
For future reference, in case somebody has a similar issue, it seems that no packages should specify an explicit dependency (for the purposes of `MELPA`/`package.el`) on `el-get`, as `el-get` tries to uninstall its MELPA version (from `~/.emacs.d/elpa/`) and instead manage itself by itself (at `~/.emacs.d/el-get/`) and having a (M)ELPA package depending on it, prevents that. See also: https://github.com/dimitri/el-get/issues/2618

(Weirdness to be expected from a package manger being installed by another package manager.)
