### ISSUE TITLE
Status message on https://melpa.org sounds strange

### ISSUE THREAD

**Issue by gizmomogwai** [melpa/melpa#5364]
````
Next build: 12 hours ago, last ended 12 hours ago and took 3 hours
````
I think it should say
````
Next build in 12 hours, last ended 12 hours ago and took 3 hours
````

**Comment by milkypostman** [comment]
the former is correct. the part that says "last ended 12 hours ago and took
3 hours" is a more detailed description of the first part which is just
saying it wast 12 hours ago. there is probably a better way to do this and
i can see the confusion. but it's not really saying "next build IN".

i'll leave this bug open to discuss what we may want as a status message.

On Sat, Mar 10, 2018 at 6:10 AM, Christian Köstlin <notifications@github.com

**Comment by gizmomogwai** [comment]
Now its writing
````
Current build started: an hour ago, last took 3 hours
````
Just for reference.
