### ISSUE TITLE
Latest package build breaks builds

### ISSUE THREAD

**Issue by milkypostman** [melpa/melpa#5396]
Currently emacs 24 is on the build server and eieio-object-class doesn't exist in that version so all new builds are failing. For now I am looking at upgrading the emacs version to see if that helps but that will take a few hours. 

You should decide if it's worth reverting that commit for now. But we can wait until upgrade fails and I have to restore 😀

**Comment by milkypostman** [comment]
@tarsius

**Comment by milkypostman** [comment]
Upgraded to 24.5

**Comment by tarsius** [comment]
Why not 25.3?
