### ISSUE TITLE
Unable to install git package

### ISSUE THREAD

**Issue by forthrin** [melpa/melpa#5397]
```
Install package ‘git-20140128.241’? (y or n) y
Package menu: Operation started [Installing 1]
forward-sexp: Scan error: "Unbalanced parentheses", 1957, 7613
```

https://github.com/pashky/restclient.el/issues/130

> Melpa serves truncated file.

**Comment by milkypostman** [comment]
please try again. this may have been a temporary issue while we were
upgrading the server. if it persists then it may be a network issue on your
end.

i have tried to reproduce but had no problems.

**Comment by forthrin** [comment]
WFM
