### ISSUE TITLE
rsync://melpa.org/packages/ no longer working since 2018-03-29

### ISSUE THREAD

**Issue by xuchunyang** [melpa/melpa#5402]
We use the rsync service to sync Melpa everyday. I notice it is no longer working since 2018-03-29.

```
~ $ rsync --list-only rsync://melpa.org/packages/
rsync: failed to connect to melpa.org: Connection refused (61)
rsync error: error in socket IO (code 10) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-52/rsync/clientserver.c(106) [receiver=2.6.9]
```

**Comment by milkypostman** [comment]
it'll take me a bit to debug this, something to do with the upgrade i
suspect but @purcell set this up originally so i'm not sure what to check.

**Comment by purcell** [comment]
Yep, I'll take a look. The setup details were noted here: https://github.com/melpa/melpa/issues/4020#issuecomment-233172008

**Comment by milkypostman** [comment]
It’s all good. I can take a look thanks for the link.

**Comment by xuchunyang** [comment]
Melpa Stable is also no longer working since 2018-04-01

```
# rsync --list-only rsync://stable.melpa.org/packages/
rsync: failed to connect to stable.melpa.org (104.131.31.21): Connection refused (111)
rsync error: error in socket IO (code 10) at clientserver.c(128) [Receiver=3.1.0]
root@AY1309092152572985dfZ:~# less /var/log/rsync-melpa-stable.log
```

It was working when the issue was created.

**Comment by milkypostman** [comment]
Yeah I haven't gotten to enabling it again.  Will try to get to it this weekend.

**Comment by milkypostman** [comment]
i fixed this. sorry for the delay.

**Comment by xuchunyang** [comment]
They are working now. Thank you very much.
