### ISSUE TITLE
:commit not respected in recipe build

### ISSUE THREAD

**Issue by ebanner** [melpa/melpa#5404]
Perhaps I'm misunderstanding the usage of `:commit` in recipes, but I thought melpa would clone the code corresponding to the sha argument. However when I do

```
(ein :repo "millejoh/emacs-ipython-notebook" :fetcher github
     :files ("lisp/*" (:exclude "lisp/zeroein.el"))
     :commit "a8fc712ca837591c39927a41d6ddf884257d904b")
```

I get the code corresponding to the latest commit. For example I get

https://github.com/millejoh/emacs-ipython-notebook/blob/115c16eb9f38447790a75c71e67036c5f4be15e0/lisp/ein-shared-output.el#L198

when I expect to get

https://github.com/millejoh/emacs-ipython-notebook/blob/a8fc712ca837591c39927a41d6ddf884257d904b/lisp/ein-shared-output.el#L197 

The contents of `*package-build-recipe*` are identical when providing the sha and omitting it.

```
;; Please check the following package descriptor.
;; If the correct package description or dependencies are missing,
;; then the source .el file is likely malformed, and should be fixed.
(ein .
     [(20180329 1115)
      ((websocket
        (1 7))
       (auto-complete
        (1 4 0))
       (request
        (0 3))
       (deferred
         (0 5))
       (request-deferred
        (0 2 0))
       (cl-generic
        (0 3))
       (dash
        (2 13 0))
       (s
        (1 11 0))
       (skewer-mode
        (1 6 2)))
      "Emacs IPython Notebook" tar nil])
```

I should not that I did have to do a `(setq package-build-recipes-dir default-directory)` inside the recipe buffer as the default value of `package-build-recipes-dir` was somewhere in `.emacs.d`. I also had to run `M-x package-build-minor-mode`.

When I built packages from melpa in the past I didn't have to do either of these steps (emacs auto-detected that I was in a recipe buffer and enabled package build minor mode automatically). So could the reason for this change have caused it? And maybe I'm missing another step?

**Comment by ebanner** [comment]
Stepping through the function `package-build-current-recipe` [the call to `package-build-archive`](https://github.com/melpa/package-build/blob/50c41597d15fb5f39ec65d8009e10ea8fb11d67a/package-recipe-mode.el#L89) does evaluate to

```
Result: ("ein" "20180310.507")
```

which looks right but then in the very next line I get

```
(... (ein . [(20180329 1115) ((websocket (1 7)) (auto-complete (1 4 0)) (request (0 3)) (deferred (0 5)) (request-deferred (0 2 0)) (cl-generic (0 3)) (dash (2 13 0)) (s (1 11 0)) (skewer-mode (1 6 2))) "Emacs IPython Notebook" tar nil]))
```

which seems to override the previously correct version of `ein`.

**Comment by purcell** [comment]
The version number should be the time of the latest commit that touched any of the files included in the recipe, so it could potentially be much older than the time of the `:commit` itself.

**Comment by ebanner** [comment]
Hm not sure why I would be getting a version number of `20180329 1115` for that repo then considering the last commit was on 03/11/2018...?

**Comment by purcell** [comment]
I actually can't reproduce this locally using the recipe you've posted above: I get `ein-20180311.207`, which version looks correct to me based on the modification times of the files. :-/
