### ISSUE TITLE
Time to remove ido-ubiquitous?

### ISSUE THREAD

**Issue by DarwinAwardWinner** [melpa/melpa#5425]
It's been a while (about 10 months) since the switch to ido-cr+, when ido-ubiquitous became nothing more than a placeholder that loads ido-cr+, and there are no more packages in MELPA that depend directly on ido-ubiquitous. And ever since the switch, anyone who loads ido-ubiquitous has been getting a warning about it being obsolete. Furthermore, having it available to install from MELPA seems to be causing some issues, e.g. https://github.com/DarwinAwardWinner/ido-completing-read-plus/issues/150. So I propose that we finally remove it from MELPA for good.

Thoughts?

**Comment by purcell** [comment]
Fine with me, though note that it will also disappear from MELPA Stable. `ido-cr+` is in MELPA Stable, though, so it shouldn't be a big deal for all users to move across.

**Comment by purcell** [comment]
Done.
