### ISSUE TITLE
Logo Design Offer as Open Source Contribution

### ISSUE THREAD

**Issue by anharismail** [melpa/melpa#5452]
Hello Sir. I'm a UI/UX and Graphics Designer. I want provide a logo for you. Would you mind if I propose a new logo design for your application as my Open Source Contribution?

Thanks before.

**Comment by milkypostman** [comment]
We’d totally be happy to entertain the idea of a logo. Feel free to contribute some ideas and I’ll take a look!

**Comment by anharismail** [comment]
Hello, Sir @milkypostman . These are my logo proposal for your application.
I'm very welcome if you have any comments, opinions, or revisions. Please just tell me.
I'll provide all file types and sizes you needed.
Hope you like it.

### Version 1
![melpa ver 1](https://user-images.githubusercontent.com/37614260/39687225-92642a10-51f7-11e8-99ce-cbfc61fa52da.png)

### Version 2
![melpa ver 2](https://user-images.githubusercontent.com/37614260/39687231-991fe538-51f7-11e8-9aca-e016c4d19d4b.png)

**Comment by tarsius** [comment]
Ping @milkypostman @purcell 

Personally I feel these logos are rather generic but look quite nice, so maybe we want to use them - at least for the time being?

**Comment by anharismail** [comment]
Hi @milkypostman , thanks for your response. I've waited so long about it, but it's not a problem.

Yes, the white and black logo are on the same package with the purple. You can choose one of them in any different background. Because proportional and professional logo must have the black and white version.

Anyway, is this revision you mean? I've created two versions of it.

### Version 1
![melpa ver 2 1](https://user-images.githubusercontent.com/37614260/42441323-0fc77964-8392-11e8-81d8-ba7667161d3a.png)

### Version 2
![melpa ver 2 2](https://user-images.githubusercontent.com/37614260/42441342-18e9358c-8392-11e8-8ed7-e732fb064650.png)

If there's no revision anymore, please just tell me what type and size you needed for your project.

**Comment by milkypostman** [comment]
I like both! I’m not sure which to choose. 

@purcell you have any opinions? 

I tend to like lowercase characters but given that melpa is an acronym and we normally describe it in all capitals I think version 2 fits the current aesthetic more.

**Comment by anharismail** [comment]
I feel the same with your opinion. On one side, I love the lowercase style and the other side melpa is an acronym.

**Comment by alphapapa** [comment]
Jonas is right that these are rather generic-looking, but I feel like the "Version 1" set, with the two shapes rather than the three, looks more distinctive.

@anharismail What if you used the Emacs "E" from the Emacs logo, rotated 90 degrees so it looks like an M, as the "M" in "MELPA"?  At least that would communicate that the logo is related to Emacs.  As it is, there's not much about the logo that communicates any relation to Emacs.

**Comment by alphapapa** [comment]
Here's an example of what I was thinking of.  It uses the Emacs logo theme, the E turned sideways, and a box to represent the repository contents.
![melpa1 svg](https://user-images.githubusercontent.com/601365/42458129-e55301ea-835e-11e8-8f30-0b0daf059f24.png)

**Comment by anharismail** [comment]
Hi @alphapapa, if you want it, the Emacs logo can be added easily. But, it will make it disproportionate. But, if the other like your Idea, I'll do it for you.

**Comment by milkypostman** [comment]
Just a side note, I want to be careful about using the emacs logo unless we can be sure it has proper licensing to do so. It should be fine but it’s just something I’ve thought of.

**Comment by milkypostman** [comment]
@alphapapa I understand the generic ness argument to a degree but I don’t like the way the shapes look in version one. It ends up creating sharp points almost star-shaped and it doesn’t do it for me.

**Comment by alphapapa** [comment]
The Emacs logo is licensed under GPLv3, like everything in the Emacs source tree, isn't it?

**Comment by alphapapa** [comment]
According to `etc/images/icons/README`:

> COPYRIGHT AND LICENSE INFORMATION FOR IMAGE FILES
> 
> Files: hicolor/16x16/apps/emacs.png hicolor/24x24/apps/emacs.png
>        hicolor/32x32/apps/emacs.png hicolor/48x48/apps/emacs.png
>        hicolor/128x128/apps/emacs.png hicolor/scalable/apps/emacs.svg
>        hicolor/scalable/mimetypes/emacs-document.svg
> 
> Author: Nicolas Petton <nicolas@petton.fr>
> Copyright (C) 2015-2018 Free Software Foundation, Inc.
> License: GNU General Public License version 3 or later (see COPYING)

And `hicolor/scalable/apps/emacs.svg` is the Emacs logo image.

**Comment by milkypostman** [comment]
Ok cool. Not a lawyer but that seems to suggestion the only restriction is that our art also be licensed as GPLv3 which is fine by me as long as @anharismail agrees. 

But now that licensing is resolved I’ll just say I like the idea but I don’t particularly like the emacs logo :-P

**Comment by anharismail** [comment]
No problem as long as it has free license, so I can put it on. But, the final decision is on @milkypostman side. I just waiting what idea he chosen.

**Comment by milkypostman** [comment]
Thanks. I’d like to wait for Purcell to give his 2c before I make a final call.

**Comment by purcell** [comment]
> I tend to like lowercase characters but given that melpa is an acronym and we normally describe it in all capitals I think version 2 fits the current aesthetic more.

Agree.

**Comment by milkypostman** [comment]
In that case let’s go with version 2 of the second iteration!  I think it’d be good to put an svg copy of all files somewhere in the repo and then update the web images. I can help with that.

**Comment by anharismail** [comment]
All right @milkypostman, I'll provide it soon
