### ISSUE TITLE
Plug into shields.io to get all the shield styles

### ISSUE THREAD

**Issue by gizmomogwai** [melpa/melpa#5459]
http://shields.io/

I do know nothing what needs to be done there, but I think it would be great to also get the shields from there. Especially because of the styles they provide.

**Comment by milkypostman** [comment]
That’s how we do get them afaik. We pull from there and store in our repo.

**Comment by gizmomogwai** [comment]
would there be a way to also get some more parameters passed through, e.g.
https://img.shields.io/badge/style-flat--square-green.svg?longCache=true&style=flat-square
?

**Comment by milkypostman** [comment]
It would be best if you submitted a pull request with the change and we can discuss it there. Or add it as a separate option or something.

**Comment by tarsius** [comment]
This is implemented here: https://github.com/melpa/package-build/blob/master/package-build-badges.el.

But note the commentary (by @purcell if I remember correctly):

> ;; In future we should provide a hook.  Note also that it would be
> ;; straightforward to generate the SVG ourselves, which would save
> ;; the network overhead.

I would prefer that too.

**Comment by gizmomogwai** [comment]
Do you mean enable shields to pull information from melpa? or pushing updated melpa information to shields?

**Comment by tarsius** [comment]
The idea is that instead of using an external service we should generate these images ourselves.

**Comment by tarsius** [comment]
@gizmomogwai Do you have any intention of implementing that? Otherwise I am going to close this - what we have is good enough and there doesn't appear to be much interest in something fancier.

**Comment by gizmomogwai** [comment]
You are right, please close.
