### ISSUE TITLE
Can't change the MELPA archive

### ISSUE THREAD

**Issue by cakebytheoceanLuo** [melpa/melpa#5479]
Hi
I just added the line of code in my .emacs.d
But when i M-x package-list
The packages are only the old ones, nothing new.
![screenshot from 2018-05-12 21-23-42](https://user-images.githubusercontent.com/28505034/39960867-c265897a-562a-11e8-8b2b-c28dcccf97fa.png)

**Comment by purcell** [comment]
You should restart Emacs to take effect, or evaluate the changed code in your emacs init files.

**Comment by cakebytheoceanLuo** [comment]
Restart and reboot don't help.

And that is what i have in the .emacs.
`
;; 19.4.2018 install ess for r
(add-to-list 'load-path "/usr/share/emacs/site-lisp/ess")
(require 'ess-site)

;;可选配置

;;设置ESS的Working目录
(setq ess-ask-for-ess-directory nil)
(setq ess-set-working-directory "~/R/")
;;设置默认语言
;;(setq ess-ask-for-dialect nil)
(setq ess-dialect "R")

(add-to-list 'auto-mode-alist '("\\.R$" . R-mode))
(add-to-list 'auto-mode-alist '("\\.r$" . R-mode))

(setq ess-local-process-name "R")
(setq ansi-color-for-comint-mode 'filter)
(setq comint-prompt-read-only t)
(setq comint-scroll-to-bottom-on-input t)
(setq comint-scroll-to-bottom-on-output t)
(setq comint-move-point-for-output t)

(global-set-key [(meta i)] 'ess-eval-line)
(global-set-key [(meta o)] 'ess-eval-region)
(global-set-key [(meta p)] 'ess-eval-buffer)

;;11. 5 for merlin
(push "<SHARE_DIR>/emacs/site-lisp" load-path) ; directory containing merlin.el
(setq merlin-command "<BIN_DIR>/ocamlmerlin")  ; needed only if ocamlmerlin not already in your PATH
(autoload 'merlin-mode "merlin" "Merlin mode" t)
(add-hook 'tuareg-mode-hook 'merlin-mode)
(add-hook 'caml-mode-hook 'merlin-mode)

;;11.5 MELPA
(require 'package)
(let* ((no-ssl (and (memq system-type '(windows-nt ms-dos))
                    (not (gnutls-available-p))))
       (proto (if no-ssl "http" "https")))
  ;; Comment/uncomment these two lines to enable/disable MELPA and MELPA Stable as desired
  (add-to-list 'package-archives (cons "melpa" (concat proto "://melpa.org/packages/")) t)
  ;;(add-to-list 'package-archives (cons "melpa-stable" (concat proto "://stable.melpa.org/packages/")) t)
  (when (< emacs-major-version 24)
    ;; For important compatibility libraries like cl-lib
    (add-to-list 'package-archives '("gnu" . (concat proto "://elpa.gnu.org/packages/")))))
(package-initialize)


`

**Comment by purcell** [comment]
Okay. To check, then:

- After starting up, evaluate `package-archives` in your `*scratch*` buffer. Check it includes the MELPA entry.
- In the `M-x list-packages` buffer, press `r`: the minibuffer should show that requests are being made to `elpa.gnu.org` and `melpa.org`.

**Comment by purcell** [comment]
That package entry looks really old, and hasn't been obtained from either ELPA or MELPA, so I suspect you have old state files hanging around that are problemative. Can you maybe delete your local `~/.emacs.d/elpa/archives/*/archive-contents` files (or just `~/.emacs.d/elpa`) and restart Emacs?
