### ISSUE TITLE
Update on packages removed due to licensing issues

### ISSUE THREAD

**Issue by tarsius** [melpa/melpa#5498]
FYI. It has been a while since we dealt with licensing issues. Here's the final report.

Of the packages that were removed, only the following have not been added back yet.

| Package (23)       | License         | Mirror  | Link                                              |
| ------------------ | --------------- | ------- | ------------------------------------------------- |
| crab               | pending         | shelved | https://github.com/puffnfresh/crab-emacs          |
| ess-R-object-popup | pending         | shelved | https://github.com/myuhe/ess-R-object-popup.el    |
| flycheck-scala-sbt | public-domain   | shelved | https://github.com/rjmac/flycheck-scala-sbt       |
| imgix              | pending         | shelved | https://github.com/imgix/imgix-emacs              |
| inf-php            | pending         | shelved | https://github.com/taksatou/inf-php               |
| inform7-mode       | pending         | shelved | https://github.com/fred-o/inform7-mode            |
| jaunte             | pending         | shelved | https://github.com/kawaguchi/jaunte.el            |
| memento            | pending         | shelved | https://github.com/ehartc/memento                 |
| n3-mode            | pending         | shelved | https://github.com/doriantaylor/n3-mode-for-emacs |
| nyan-prompt        | COPYLOVE        | github  | https://github.com/PuercoPop/nyan-prompt          |
| org-jekyll         | pending         | shelved | https://github.com/juanre/org-jekyll              |
| crontab-mode       | GPL-2           | shelved | https://github.com/emacsorphanage/crontab-mode    |
| pyim-greatdict     | pending         | shelved | https://github.com/tumashu/pyim-greatdict         |
| railgun            | pending         | shelved | https://github.com/mbriggs/railgun.el             |
| rails-new          | pending         | shelved | https://github.com/cheunghy/rails-new             |
| refheap            | pending         | shelved | https://github.com/Raynes/refheap.el              |
| ruby-dev           | pending         | shelved | https://github.com/Mon-Ouie/ruby-dev.el           |
| ruby-guard         | pending         | shelved | https://github.com/cheunghy/ruby-guard            |
| sourcetalk         | pending         | shelved | https://github.com/malroc/sourcetalk_emacs        |
| tj-mode            | pending         | shelved | https://github.com/katspaugh/tj-mode              |
| uzumaki            | pending         | shelved | https://github.com/geyslan/uzumaki                |
| vimgolf            | CC BY-NC-SA 3.0 | shelved | https://github.com/timvisher/vimgolf.el           |
| slime-ritz         | EPL             | shelved |                                                   |

* `pending` means "the license isn't specified and the author has been contacted (but did not reply)".
* `shelved` means "the package was moved from the Emacsmirror to the Emacsattic".

One package, `redshank`, remains in Melpa that is licenced under "the" GPL, without specifying a version.

Thanks to @matsl and others for helping with this.

In case we need it ever again, here's some code useful to determine such things:

<details>

```lisp

#+BEGIN_SRC emacs-lisp :results silent
  (require 'epkg)

  (defun emir--format-license-table (table)
    (--when-let (assoc "failure" table)
      (setcar it  "((failure))"))
    (--when-let (assoc "pending" table)
      (setcar it  "((pending))"))
    (--when-let (assoc "none" table)
      (setcar it  "((none))"))
    (--when-let (assoc "custom" table)
      (setcar it  "((custom))"))
    (let ((total (apply '+ (mapcar 'cadr table)))
          (gnu   (apply '+ (mapcar (pcase-lambda (`(,license ,count))
                                     (if (and license
                                              (string-match-p "GPL" license))
                                         count
                                       0))
                                   table))))
        (cl-flet ((percent (n) (round (* (/ n total 1.0) 100))))
          `(("License" "Count" "Percent")
            hline ,@(mapcar (pcase-lambda (`(,license ,count))
                              (list license count (percent count)))
                            table)
            hline ("total GNU" ,gnu ,(percent gnu))
            hline ("total" ,total 100)))))

  (defun emir--insert-melpa-packages-using-licenses (&rest licenses)
    (epkg-with-org-header ("Package" "License" "Class" "Link")
      (epkg-sql [:select :distinct
                 [packages:name packages:license packages:class packages:repopage]
                 :from [packages melpa-recipes]
                 :where (= packages:name melpa-recipes:epkg-package)
                 :and license :in $v1
                 :group-by packages:repopage
                 :order-by [(asc packages:name)]]
                (apply #'vector licenses))))

  (defun emir--insert-mirror-packages-using-licenses (&rest licenses)
    (epkg-with-org-header ("Package" "License" "Class" "M" "Link")
      (mapcar (pcase-lambda (`(,name ,license ,class ,repopage))
                (list name license class
                      (if (melpa-get name) t "")
                      (and (not (eq class 'wiki)) repopage)))
              (epkg-sql [:select [name license class repopage] :from packages
                         :where license :in $v1
                         :and (not (= class 'shelved))
                         :order-by [(asc name)]]
                        (apply #'vector licenses)
                        [shelved]))))
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (emir--format-license-table
   (epkg-sql [:select :distinct [packages:license (funcall count *)] :as count
              :from [packages melpa-recipes]
              :where (= packages:name melpa-recipes:epkg-package)
              :group-by packages:license
              :order-by [(desc count) (asc license)]]))
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (emir--insert-melpa-packages-using-licenses
    "GPL" "GPL-2" "failure" "pending")
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (let ((removed
         '(;; [[orgit-rev:~/git/emacs/melpa/::7aa634e8]]
           "smali-mode"
           ;; [[orgit-rev:~/git/emacs/melpa/::cf92ce1a]]
           "achievements"
           "avk-emacs-themes"
           "bpr"
           "coq-commenter"
           "crab"
           "darkane-theme"
           "easy-after-load"
           "edit-at-point"
           "el-pocket"
           "eno"
           "ess-R-object-popup"
           "euslisp-mode"
           "firebelly-theme"
           "flappymacs"
           "flycheck-scala-sbt"
           "gap-mode"
           "ghost-blog"
           "hlint-refactor"
           "ids-edit"
           "imgix"
           "inf-php"
           "inform7-mode"
           "ivariants"
           "ivs-edit"
           "jaunte"
           "mandoku-tls"
           "memento"
           "monochrome-theme"
           "n3-mode"
           "niflheim-theme"
           "nnir-est"
           "nyan-prompt"
           "org-jekyll"
           "ox-pandoc"
           "psc-ide"
           "sicp"
           "yatex"
           "zerodark-theme"
           ;; [[orgit-rev:~/git/emacs/melpa/::c3366117]]
           "crontab-mode"
           "harvest"
           "helm-ctest"
           "inline-crypt"
           "plantuml-mode"
           "pushover"
           "py-gnitset"
           "pyim-greatdict"
           "railgun"
           "rails-new"
           "refheap"
           "ruby-dev"
           "ruby-guard"
           "sly-repl-ansi-color"
           "smartwin"
           "sourcetalk"
           "stgit"
           "subshell-proc"
           "sudden-death"
           "syslog-mode"
           "tj-mode"
           "tronesque-theme"
           "turkish"
           "uzumaki"
           "vimgolf"
           "wordsmith-mode"
           "xah-css-mode"
           "xah-elisp-mode"
           "xah-find"
           "xah-fly-keys"
           "xah-get-thing"
           "xah-lookup"
           "xah-math-input"
           "xah-reformat-code"
           "xah-replace-pairs"
           "xahk-mode"
           "zig-mode"
           ;; [[orgit-log:~/git/emacs/melpa/::master]]
           "slime-ritz"
           ;; [[orgit-rev:~/git/emacs/melpa/::b20f5126]]
           "lively"
           ;; [[orgit-rev:~/git/emacs/melpa/::e5476274]]
           "slime-annot"
           )))
    (epkg-with-org-header ("Package" "License" "Mirror" "Link")
      (--keep (-when-let (pkg (epkg it))
                (let ((rcp (melpa-get it)))
                  (and (not rcp)
                       (list it
                             (oref pkg license)
                             (substring (symbol-name (class-of pkg)) 5 -8)
                             (oref pkg repopage)))))
              removed)))
#+END_SRC
```

</details>

**Comment by milkypostman** [comment]
Thanks Jonas for keeping an eye on this.
