### ISSUE TITLE
sql-indent package conflict name with different package from elpa with the same name.

### ISSUE THREAD

**Issue by proofit404** [melpa/melpa#5519]
ELPA contains this one: https://github.com/alex-hhh/emacs-sql-indent/

MELPA contains this one: https://github.com/bsvingen/sql-indent/

It's confusing to find out which package will be installed.

**Comment by purcell** [comment]
Related: https://github.com/alex-hhh/emacs-sql-indent/issues/62

**Comment by tarsius** [comment]
I have removed our recipe, see https://github.com/alex-hhh/emacs-sql-indent/issues/62.

**Comment by proofit404** [comment]
Is there any cache/mirror mechanism? I still got `sql-indent-20170112.1507` installed each time I update.

**Comment by milkypostman** [comment]
What do you mean? It’s likely that the package remained on our server after the package was removed if that’s what you mean. But it’s gone now.

**Comment by proofit404** [comment]
I run my update script 2 hours ago and `sql-indent-1.2.signed` from `elpa` was rewritten by `sql-indent-20170112.1507`. That's why I'm guessing there are some mirrors/servers out of sync.

I'm not pretending I diagnosed the problem correctly. I have no idea about Melpa infrastructure. Just guessing.

**Comment by milkypostman** [comment]
We switched servers yesterday so likely that’s the cause of the weirdness. The package is official gone from melpa. 

Have a good one.
