### ISSUE TITLE
color-theme reverted to older version?

### ISSUE THREAD

**Issue by snits** [melpa/melpa#5534]
It looks like color-theme has reverted to an older version that doesn't have the themes/ directory. 

Previously there was color-theme-20080305.34, and now it is color-theme-20070910.1007.

**Comment by Silex** [comment]
FWIW I took this as an opportunity to port my `color-theme-install` theme to a modern `deftheme` one... It was not very hard, just need to do a bit of replacements there and there.

**Comment by purcell** [comment]
Thanks - I fixed this regression in be81fe3d. But yes, I agree with @silex that modern themes are definitely the way to go IMO.

**Comment by snits** [comment]
Thanks @Silex and @purcell. Yeah, I moved my emacs configs to using solarized-theme instead of the color-theme based solarized themes today.
