### ISSUE TITLE
No packages at melpa.org

### ISSUE THREAD

**Issue by lyr3** [melpa/melpa#5539]
waaaaaaaaaaaat?!

**Comment by milkypostman** [comment]
it looks like all the packages are there and still accessible from emacs.
i'll look into the website bug. likely a package is being built that is
causing our builder problems.

**Comment by milkypostman** [comment]
this is due to 6f4c29f   i am looking at how to fix it quickly 👍 

thanks for the report!

**Comment by tarsius** [comment]
I am online and looking into it as well.

**Comment by milkypostman** [comment]
it's clearly https://github.com/melpa/melpa/blob/master/package-build/package-build.el#L955

it's inserting the file into itself. but i think what you're trying to do is insert the contents of the recipe file. i'm guessing you want 

```
                           (insert-file-contents (expand-file-name name package-build-recipes-dir))
```

**Comment by milkypostman** [comment]
@tarsius i'm going to commit the fix then you can reconcile things later. I'm still unclear how to merge in the package-build stuff :)  i'll submit a separate PR to package-build

**Comment by milkypostman** [comment]
harmony has been restored to the front page.  🎆  🍻

**Comment by milkypostman** [comment]
thanks! i don't understand why i had such a hard time groking this subtree
thing before....

**Comment by tarsius** [comment]
Thanks for the quick fix. I was looking somewhere else.

**Comment by tarsius** [comment]
> i don't understand why i had such a hard time groking this subtree thing before

I didn't add the `add-package-build-remote` target before yesterday, so maybe you got a confusing error message and there was no documentation (I hope the make target serves that purpose now).

**Comment by milkypostman** [comment]
Probably I never sat down and really tried hard to understand what it’s going. Dunno. Anyways thanks for your work. Goodnight!

**Comment by tarsius** [comment]
Goodnight!
