### ISSUE TITLE
Delete evil-ediff since it's now part of evil-collection

### ISSUE THREAD

**Issue by Ambrevar** [melpa/melpa#5549]
@justbur: If you are OK with it of course :)

**Comment by justbur** [comment]
I'll put a note on the readme and leave the repo up for a little while. I think the first step would be to remove the recipe from melpa

**Comment by purcell** [comment]
Done, thanks.

**Comment by syl20bnr** [comment]
@purcell Is it possible to resurrect this package ? Spacemacs does not use `evil-collection` and relies on it.

**Comment by purcell** [comment]
@syl20bnr Done, to avoid any short-term breakage, but I guess it's possible that @justbur doesn't intend to maintain the package now over the longer term.

**Comment by justbur** [comment]
@purcell that was the idea. The plan is to maintain it as part of evil-collection. There’s a note in the evil-ediff repo to that effect. It’s possible to just load evil-ediff through evil-collection so this shouldn’t be an issue.

**Comment by purcell** [comment]
Cool, so perhaps @syl20bnr could arrange to switch Spacemacs to grab the `evil-ediff` bindings from `evil-collection`, and then we can drop this package without disruption?

**Comment by syl20bnr** [comment]
@purcell thank you for the revert, I'll work on it soon and let you know. Thanks again.
