### ISSUE TITLE
Magithub (and possibly other packages?) not being updated from source

### ISSUE THREAD

**Issue by vermiculus** [melpa/melpa#5580]
vermiculus/magithub#343

@wyuenho noticed that the above pull request was not available on MELPA for some time. After more investigation (using the commit hash now present on [package pages](https://melpa.org/#/magithub)), I discovered that in fact *nothing* in the past three weeks has been pulled. How could this be?

I was unsure on whether to open this issue here or on package-build, but I figured this would get more eyes.

**Comment by vspinu** [comment]
I just noticed this with [sesman](https://melpa.org/#/sesman) which hasn't been pulled for a day or two. The [version](https://stable.melpa.org/#/sesman) from melpa stable has been updated as expected though.

**Comment by milkypostman** [comment]
Thanks for bringing this to our attention. I will have to look into this tonight but it will be later this afternoon until I can have a look. I suspect there is either a bad package or a recent change to package-build broke the server. 

Very sorry for the inconvenience.

**Comment by vermiculus** [comment]
No worries; let us know if there's any way we can help!

**Comment by milkypostman** [comment]
things should be unstuck now. and i have been working on a better way to manage our build which is almost ready. it will avoid these problems in the future, or at least make them more apparent and/or less of an issue to deal with.
