### ISSUE TITLE
A lot of packages are missing?

### ISSUE THREAD

**Issue by cjohansson** [melpa/melpa#5585]
That were available yesterday, i.e.:
* image+
* rust-mode
* smex
* ssh-deploy

What happened? It looks like my old previously accepted pull request has been removed from the repo as well: https://github.com/cjohansson/melpa

**Comment by milkypostman** [comment]
I had to rebuild everything. It’ll be back in a few more hours. In not fully understanding the extent of the bug I was dealing with I deleted packages. They are getting rebuilt.

**Comment by cjohansson** [comment]
Thanks for fixing this issue, I appreciate your work on this project
