### ISSUE TITLE
The sources of spike-theme and sqlite.el have disappeared

### ISSUE THREAD

**Issue by aplaice** [melpa/melpa#5590]
### `spike-theme`

[MELPA's recipe](https://github.com/melpa/melpa/blob/master/recipes/spike-theme).

(Broken) [GitHub link](https://github.com/m31271n/spike-theme).

[Emacsmirror link](https://github.com/emacsmirror/spike-theme).

### `sqlite.el`

[MELPA's recipe](https://github.com/melpa/melpa/blob/master/recipes/sqlite).

(Broken) [GitHub link](https://github.com/cnngimenez/sqlite.el).

[Emacsmirror link](https://github.com/emacsmirror/sqlite)

The relevant [emacswiki elisp source page](https://www.emacswiki.org/emacs/sqlite.el) which points at the above broken GitHub link. The [description page](https://www.emacswiki.org/emacs/SQLite-el) also points there.

Looking at [MELPA's metadata](https://melpa.org/archive.json), neither of the packages seems to be depended upon.

**Comment by tarsius** [comment]
Thanks for notifying us. Could you please also contact the upstreams and figure out what has happened? Maybe the packages have moved elsewhere, maybe they have been deprecated, ...

Unless that results in a more appropriate action, I will move these packages from the Emacsmirror to the Emacsattic.

**Comment by aplaice** [comment]
I've sent e-mails to them asking about the situation. I'll provide updates if/when I get replies.

**Comment by cnngimenez** [comment]
Hi!

Following the recommendations of most people, I migrate my repositories to Gitlab. If you cannot find some repositories, it is possible to find them in other hosts (Bitbucket, Savannah, etc.).

sqlite.el con be finded at https://gitlab.com/cnngimenez/sqlite.el

**Comment by aplaice** [comment]
Hi!

Thanks very much for the reply! Moving to GitLab is indeed probably a wise course of action. :) 

Unfortunately, it seems that your repositories are private — when I try to go to [sqlite.el](https://gitlab.com/cnngimenez/sqlite.el) I get the message:

> You need to sign in or sign up before continuing.

It appears that Travis [can't access your repository](https://travis-ci.org/melpa/melpa/builds/401463245) either. Your list of [publicly available personal projects](https://gitlab.com/users/cnngimenez/projects) also seems to be empty.

Sorry for the trouble!

**Comment by cnngimenez** [comment]
Fixed! It should be public now. 

Sorry, didn't realize it was imported as private.

**Comment by tarsius** [comment]
I've remove `spike-theme` and updated the `sqlite` recipe.
