### ISSUE TITLE
Where is the homepage metadata?

### ISSUE THREAD

**Issue by xuchunyang** [melpa/melpa#5596]
I have not use package.el/melpa for a few months, today I notice it looks that `C-h P` doesn't show the homepage for all packages from Melpa, it seems Melpa now strips the url/homepage metadata (I don't know when it started):

```
~ $ grep :url ~/.emacs.d/elpa-27.0.50/archives/gnu/archive-contents | head
	      ((:url . "https://github.com/abo-abo/ace-window")
	(:url . "https://github.com/leoliu/ack-el"))])
	     (:url . "http://www.nongnu.org/ada-mode/"))])
		(:url . "http://stephe-leake.org/ada/arm.html"))])
		 ((:url . "http://elpa.gnu.org/packages/adaptive-wrap.html")
		 ((:url . "http://elpa.gnu.org/packages/adjust-parens.html"))])
		     ((:url . "https://github.com/Malabarba/aggressive-indent-mode")
		  (:url . "https://github.com/ahungry/color-theme-ahungry"))])
       ((:url . "http://elpa.gnu.org/packages/all.html")
	((:url . "http://elpa.gnu.org/packages/ampc.html")
~ $ grep :url ~/.emacs.d/elpa-27.0.50/archives/melpa/archive-contents
~ $
```

**Comment by milkypostman** [comment]
Yeah there is a bug about this and I haven’t had a chance to fix it yet. There is a problem with the way that melpa is parsing the package info.

**Comment by seagle0128** [comment]
Same issue here. Homepages are missing.

**Comment by milkypostman** [comment]
Yes we are aware of the issue. If you find the issue named “MELPA is broken” you can see the issue. I haven’t found time to remedy this situation and given it isn’t breaking core functionality I haven’t made it a priority. I would happily accept a PR to fix the JSON encoding issue but I won’t be able to get to it until next week. Sorry about the problem.

**Comment by tarsius** [comment]
#5584

**Comment by tarsius** [comment]
That should be fixed now.
