### ISSUE TITLE
ace-jump-mode gone?

### ISSUE THREAD

**Issue by ConstantineXVI** [melpa/melpa#5602]
Just set up my emacs on a new machine and ace-jump-mode seems to have disappeared from MELPA. Recipie's there, http://melpa.org/packages/ace-jump-mode-20140616.115.el is there, but it's not showing up in the archive

**Comment by Silex** [comment]
The recipe still exists (https://github.com/melpa/melpa/blob/master/recipes/ace-jump-mode)

These days there are some issues with the build system, so I guess it'll be fixed somewhat soon.

@milkypostman just notifying you but I guess you are aware already.

**Comment by milkypostman** [comment]
@tarsius can you please help I’m away from machine. I’m not able to debug until Sunday evening. 

@constantinexvi if you can help Debug it’s appreciated.

**Comment by tarsius** [comment]
I was gone all day and now I am pretty tired, but some quick testing didn't reveal any issues:

```sh
% make recipes/ace-jump-mode packages/archive-contents json index
 • Building package ace-jump-mode ...
Package: ace-jump-mode
Fetcher: github
Source:  https://github.com/winterTTr/ace-jump-mode.git

Updating /home/jonas/git/emacs/melpa/working/ace-jump-mode/
Package ace-jump-mode is up to date - skipping.
 ✓ Success:
 44K -rw------- 1 jonas jonas  43K Jul  8 00:53 packages/ace-jump-mode-20140616.315.el
4.0K -rw------- 1 jonas jonas   94 Jul  8 00:53 packages/ace-jump-mode-20140616.315.entry
4.0K -rw------- 1 jonas jonas  966 Jul  8 00:53 packages/ace-jump-mode-badge.svg
4.0K -rw------- 1 jonas jonas 1.9K Jul  8 00:53 packages/ace-jump-mode-readme.txt

 • Updating packages/archive-contents ...
 • Building html/archive.json ...
 • Building html/recipes.json ...
 • Building html index ...
make -C html
make[1]: Entering directory '/home/jonas/git/emacs/melpa/html'
erb updates.rss.erb > updates.rss.tmp && mv updates.rss.tmp updates.rss
make[1]: Leaving directory '/home/jonas/git/emacs/melpa/html'

% ls packages html
html:
archive.json  favicon.ico  jslicense.html  partials      updates.rss
css           index.html   Makefile        recipes.json  updates.rss.erb
donate.png    js           packages        robots.txt

packages:
ace-jump-mode-20140616.315.el     ace-jump-mode-badge.svg   archive-contents
ace-jump-mode-20140616.315.entry  ace-jump-mode-readme.txt  index.html

% cat packages/archive-contents 

(1 (ace-jump-mode . [(20140616 315) nil "a quick cursor location minor mode for emacs" single]))

% cat html/archive.json 
{"ace-jump-mode":{"ver":[20140616,315],"deps":null,"desc":"a quick cursor location minor mode for emacs","type":"single","props":null}}

**Comment by milkypostman** [comment]
So this was broke and I’m not sure why. I didn’t go hog wild and try to repo, I got it fixed by deleting the package file and rerunning the build for this package. 

My only guess is that if the .entry file is not there then something in package build causes the build to not recreate it. I’ll try to reproduce one more time tonight but at least for now the package should be back.

**Comment by milkypostman** [comment]
closing as this is back now.
