### ISSUE TITLE
.entry files don't get re-created if they go missing

### ISSUE THREAD

**Issue by milkypostman** [melpa/melpa#5610]
repro:

```
make recipes/ace-jump-mode
rm packages/ace-jump-mode*.entry
make recipes/ace-jump-mode
```

Expected result: The `.entry` file gets re-created.
Actual outcome: The `.entry` file is not re-created.

**Comment by milkypostman** [comment]
so, it appears that if the `.el` file is there and the version matches we don't re-generate the rest of the files.

the solution is that we should regenerate all the files all the time. the major bottleneck is IO fetching repo state. I think actually updating the files is pretty low cost.

**Comment by tarsius** [comment]
> the solution is that we should regenerate all the files all the time

That's one solution, but you could also check both files (are there any other?).

For `single` packages such a fix would look like:

```diff
diff --git a/package-build.el b/package-build.el
index b763dc5..4906cca 100644
--- a/package-build.el
+++ b/package-build.el
@@ -800,9 +800,12 @@ (defun package-build--build-single-file-package (rcp version file source-dir)
                           (downcase (file-name-nondirectory pkg-source)))
       (error "Single file %s does not match package name %s"
              (file-name-nondirectory pkg-source) name))
-    (if (file-exists-p pkg-target)
-        (package-build--message "Skipping rebuild of %s" pkg-target)
-      (copy-file pkg-source pkg-target)
+    (if (and (file-exists-p pkg-target)
+             (file-exists-p (expand-file-name
+                             (format "%s-%s.entry" name version)
+                             package-build-archive-dir)))
+        (package-build--message "Package %s is up to date - skipping" name)
+      (copy-file pkg-source pkg-target t)
       (let ((enable-local-variables nil)
             (make-backup-files nil))
         (with-current-buffer (find-file pkg-target)
```

Note that the call to `copy-file` is changed too.

For `tar` packages the fix should be basically the same.

For `tar` packages `package-build--up-to-date-p` is used, but for `single` packages it is not. So the first step probably should be to make the latter use that function too - then we only have to fix this in one place.

**Comment by milkypostman** [comment]
so right now there are 4 files that we create. we would need to add all 4 of them.

what's the harm in re-creating the files?

**Comment by purcell** [comment]
I'd be wary of accidentally recreating "make" in an ad-hoc way here, because so many more edge cases are possible. The original code very simplistically recreated these files every time to avoid that.

**Comment by tarsius** [comment]
If I understand that correctly you are willing to go back to rebuilding every single package on every update cycle, i.e. multiple times a day?

----

By the way, where is that cycle implemented? I probably figured that out at some point, but I forgot and there are so many scripts in repository making it quite hard to find the "entry point" without reading a lot of scripts that might or might not still be relevant.

Also are some of these scripts actually obsolete and/or dead code (similar to the tests we recently removed)? It might be a good idea to provide a file that summarizes what the various scripts are used for and to purge some cruft in the process.

Why are there scripts at the top-level when there is a `scripts/` directory? Is that reserved for certain kinds of scripts only?

**Comment by milkypostman** [comment]
Which scripts are in the top level? If you look at my most recent PR where I setup the Docker builds the entry point should be better. But probably the docket directory needs a read me as well. I tried to consolidate things better.

**Comment by milkypostman** [comment]
Here’s the thing. I don’t think rebuilding the packages is costing that much. Certainly it’s more costly than checking the file and, but the trade off appears to be reliability.

**Comment by tarsius** [comment]
> Which scripts are in the top level?

`migrate`, `run-travis-ci.sh` and `travis-changed-files`.

**Comment by tarsius** [comment]
> I don’t think rebuilding the packages is costing that much.

Agreed, but it may result in slightly different files or at least different modification times and that could impact caches.

Anyway, I am just raising some concerns in case you overlooked some potential issue. If you want to do it like this, then I am totally fine with that.

**Comment by tarsius** [comment]
It's unlikely that we will need it but just in case I am posting these here before deleting the obsolete branch.

```diff
diff --git a/package-build.el b/package-build.el
index 21b9c43..9342b3a 100644
--- a/package-build.el
+++ b/package-build.el
@@ -799,9 +799,12 @@ (defun package-build--build-single-file-package (rcp version file source-dir)
                           (downcase (file-name-nondirectory pkg-source)))
       (error "Single file %s does not match package name %s"
              (file-name-nondirectory pkg-source) name))
-    (if (file-exists-p pkg-target)
-        (package-build--message "Skipping rebuild of %s" pkg-target)
-      (copy-file pkg-source pkg-target)
+    (if (and (file-exists-p pkg-target)
+             (file-exists-p (expand-file-name
+                             (format "%s-%s.entry" name version)
+                             package-build-archive-dir)))
+        (package-build--message "Package %s is up to date - skipping" name)
+      (copy-file pkg-source pkg-target t)
       (let ((enable-local-variables nil)
             (make-backup-files nil))
         (with-current-buffer (find-file pkg-target)
```
