### ISSUE TITLE
rsync address will soon change

### ISSUE THREAD

**Issue by milkypostman** [melpa/melpa#5613]
I am migrating all the build stuff down to one server. #5612 is the change that makes it all happen.

however, since rsync is kinda dumb (can't do multiplexing based on hostname) and i don't want to mess with other things, i have changed rsync so that there is now,

```
rsync://melpa.org/packages
rsync://melpa.org/packages-stable
```

the rest of the server still uses hostnames to distinguish between the main and stable repos, i.e., when we make the switch `melpa.org` and `stable.melpa.org` will point to the same server and will both work fine.

@purcell @tarsius do you know who i should notify about this change?

**Comment by purcell** [comment]
Hmm. A couple of users are mentioned in old issues here - there's at least one big Chinese mirror of both - and our official mirror for MELPA Stable would probably be broken by this change if we don't coordinate it with the mirror admins.

**Comment by SuJiKiNen** [comment]
@xuchunyang 
friendly ping

**Comment by xuchunyang** [comment]
@SuJiKiNen Thank you.

So the melpa-stable's will change, I will update Emacs China ELPA when the change is online.

```diff
- rsync://stable.melpa.org/packages
+ rsync://melpa.org/packages-stable
```

**Comment by milkypostman** [comment]
This has changed now. Please update.
