### ISSUE TITLE
nix-mode is messed up in stable

### ISSUE THREAD

**Issue by cg505** [melpa/melpa#5618]
On MELPA Stable, [nix-mode](https://stable.melpa.org/#/nix-mode) claims to be version 1.11.13, but the badge says 1.2.2 (which is the actual latest version on GitHub). The GitHub link does not work, and the version you get from downloading the actual package is definitely not 1.2.2. So this phantom 1.11.13 seems to be sticking around for who knows what reason and preventing builds of the actual correct version (or something).

**Comment by aplaice** [comment]
It's an artefact of the source of the package changing from part of the [nix repository](https://github.com/NixOS/nix/) to its own [repo](https://github.com/NixOS/nix-mode). Unfortunately, the latest git tag in the nix repo before the change was [1.11.13](https://github.com/NixOS/nix/releases/tag/1.11.13), which is greater than 1.2.2...

If you look, then the commit 0ec723375bc6008a8a88024962b052c3fbbaf4b8 does exist in the nix repo, but not the nix-mode one:

https://github.com/NixOS/nix/tree/0ec723375bc6008a8a88024962b052c3fbbaf4b8/misc/emacs

This would probably have to be fixed manually, by deleting the old package file.

(History of the relevant recipe file, for reference:

https://github.com/melpa/melpa/commits/master/recipes/nix-mode )

**Comment by milkypostman** [comment]
Tomorrow morning I will switch the MELPA dns to the new server. This should resolve the issue. However people who have installed 1.11... will never get upgrades. Mix-mode should probably take a version greater than 1.11

**Comment by milkypostman** [comment]
Correct now.
