### ISSUE TITLE
Process to take over an abandoned package

### ISSUE THREAD

**Issue by kidd** [melpa/melpa#5622]
Hello, 
There's org-gcal package ( https://github.com/myuhe/org-gcal.el/) which hasn't had any updates for 1.5 years. I tried to contact the author to no avail (no mail anywhere, and no other activity in gh).

After proposing to adopt the package, people seems to be ok with it: https://github.com/myuhe/org-gcal.el/issues/115 .

What would be the process to make this happen melpawise?
Thanks!

**Comment by tarsius** [comment]
> no mail anywhere

You can use `git log` to get your hands on an email address.

**Comment by kidd** [comment]
OMG, that's genius (and obvious at the same time I guess, but I totally failed to think about this). 

I'll mail him and wait a bit.

Thanks! @tarsius !

**Comment by mwfogleman** [comment]
Any update on this? I think the maintainer is AWOL.
