### ISSUE TITLE
Melpa is down?

### ISSUE THREAD

**Issue by grandynguyen** [melpa/melpa#5637]
`package-list-packages` -> `U` never finishes refresh

**Comment by cesquivias** [comment]
I'm having the same issue, but [the mirror sites](https://github.com/melpa/melpa#mirrors) is working

**Comment by mikezackles** [comment]
Same:
```
$> curl -sI http://melpa.org/packages/archive-contents
HTTP/1.1 200 OK
Server: nginx
Date: Mon, 23 Jul 2018 18:05:13 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 0
Last-Modified: Mon, 23 Jul 2018 18:05:11 GMT
Connection: keep-alive
ETag: "5b5618d7-0"
Strict-Transport-Security: max-age=15768000
Accept-Ranges: bytes
```

**Comment by seagle0128** [comment]
Same here. Please fix it asap...
Thanks.

**Comment by Silex** [comment]
@purcell, @milkypostman :wink:

**Comment by mikezackles** [comment]
Anybody know the current practice for using a melpa mirror in spacemacs? Doesn't look like `configuration-layer--elpa-archives` exists anymore.

**Comment by milkypostman** [comment]
sorry for the delay.  i have fixed the main server.

please also try `test.melpa.org` and `stable-test.melpa.org`

I have spent the last month re-writing much of the server scripts and such to allow us to move to a new server structure to avoid these problems. basically the server is filling up. i have remedied the problem for now and will switch the URLs tonight if i find time.

**Comment by milkypostman** [comment]
resizing the main server for a temporary fix before migration. i don't have time to sit here and do the new server migration as it's very late and i will need to get the https certs updated once i finally switch the dns entries. this will give us more time.

**Comment by milkypostman** [comment]
I have migrated servers.
