### ISSUE TITLE
package-install offers hundreds of updates from melpa

### ISSUE THREAD

**Issue by j0ni** [melpa/melpa#5644]
Is this just package-install losing its cache context due to the new server switch? I'm hoping so, but I'm not seeing anyone else reporting this.

UPDATE: seems it isn't just me:
```
<Hasimir> j0ni, yep it says I need to update 389 packages
```
I'll update and hopefully that will make it regain its sanity. Maybe you should post a note on Twitter or the front page or something.

**Comment by milkypostman** [comment]
I think this is due to melpa/package-build#22 which basically means because of a package-build change things got behind. Sorry about that. We don’t have a great way to check that everything is up to date.

**Comment by j0ni** [comment]
Thanks @milkypostman - I let the update run until it was done, and nothing was damaged :)

Feel free to close this, unless you want to leave it up to funnel in other folks who come looking.

**Comment by CSRaghunandan** [comment]
@milkypostman is there no way to go around this other than having to update all the MELPA packages? I don't have fast access to internet right now and it might take a while to complete installing all packages.

**Comment by milkypostman** [comment]
I think you can install new packages without updating old. Just don’t upgrade?

**Comment by CSRaghunandan** [comment]
I can hold off on not upgrading, but for how long? Eventually, if there any upstream changes made to a package, then I'd have to delete that package and install it again for me to get the latest version. That's tedious.

**Comment by milkypostman** [comment]
You don’t have to delete every package. You just upgrade them. I don’t understand how this current situation is different than if packages had updated over time?

**Comment by casouri** [comment]
I guess @milkypostman means you can upgrade these packages when their upstream updates, one by one.

**Comment by milkypostman** [comment]
Well I was suggesting that these packages have updated that we somehow didn’t get in the past. So rather than getting one update every week you’re getting all at once. But you don’t have the newest version either way. At some point you should upgrade these packages.
