### ISSUE TITLE
FYI: Some download counters lost or reset

### ISSUE THREAD

**Issue by alphapapa** [melpa/melpa#5646]
Hi Donald, Steve, et al,

Forgive me if you already know this, but just in case it's relevant, considering the recent infrastructure changes: I just noticed that some downloads data has been lost, or perhaps reset to earlier values.  e.g. I noticed that the download counter for `magit-todos`, which was around 400-500 last time I checked (probably a week or two ago), is now at 188.

Thanks.

**Comment by milkypostman** [comment]
Yeah it’s something I forgot to update. It’s possible I can fix it but I expect when people upgrade the next time it’ll fix itself. 

Counts are based on unique up address. I’ll see if I can fix it but it’ll be a week or so. Sorry for the inconvenience.

**Comment by alphapapa** [comment]
No problem, it's not important.  Thanks.

**Comment by alphapapa** [comment]
Closing as this is either fixed or too old to matter.  Thanks.
