### ISSUE TITLE
Badges are gone?

### ISSUE THREAD

**Issue by Silex** [melpa/melpa#5656]
Hello,

Just for information, the badges seems to be gone (HTTP 404).

Example at https://melpa.org/#/docker

**Comment by Silex** [comment]
@milkypostman, @tarsius: is there anythign I can do?

I see that https://github.com/melpa/melpa/blob/master/package-build/package-build.el#L118 is nil by default, is that maybe it?

Are the build logs online so we can try to debug it for you?

**Comment by milkypostman** [comment]
You know what. It’s probably that I don’t have curl installed in the docker package.

**Comment by Silex** [comment]
@milkypostman: thanks!

> Are the build logs online so we can try to debug it for you?

Can you answer that?

**Comment by milkypostman** [comment]
there are no build logs online. sorry.

**Comment by Silex** [comment]
> there are no build logs online. sorry.

No worries. If it's not too much work, consider exposing them somehow (e.g build with travis?) that way people can inspect what's going on and could make PRs more easily.
