### ISSUE TITLE
ac-ispell package missing

### ISSUE THREAD

**Issue by Miciah** [melpa/melpa#5657]
Several Spacemacs users have reported that the ac-ispell package is missing.  http://melpa.org/#/ac-ispell shows, "Package not found: ac-ispell".

It looks like https://github.com/melpa/melpa/blob/master/recipes/ac-ispell has not changed since 2013, and https://github.com/syohex/emacs-ac-ispell has not had a commit since 2015.

How can we get the ac-ispell package restored?

More generally, are there public build logs or a process to follow when a package goes missing like this?

**Comment by Nate-Wilkins** [comment]
This is curious because I've run into the same spacemacs cannot find `ac-spell` but the code you references points to a live repository https://github.com/syohex/emacs-ac-ispell 

Not sure what to do here but I'd like to know if someone finds anything out.

**Comment by milkypostman** [comment]
Can you verify that the package builds locally? I’m out and about right now so it’ll be a bit before I can check on this. Would help to know that it’s our build systems problem vs a problem with the package in general or recent changes with package-build.

**Comment by rprimus** [comment]
Tue Aug  7 10:07:38 BST 2018

`ac-ispell` is once again `available` (via melpa.org and package.el).   
What was the problem/solution?

Package built successfully (locally) on Aug 2nd and also today - with no visible differences:

```
: ; ls -la melpa-archive/ac-is*
-rw------- 1 rprimus staff 4975 Aug  2 11:47 melpa-archive/ac-ispell-20151101.226.el
-rw------- 1 rprimus staff  336 Aug  2 11:47 melpa-archive/ac-ispell-20151101.226.entry
-rw------- 1 rprimus staff  967 Aug  2 11:47 melpa-archive/ac-ispell-badge.svg
-rw------- 1 rprimus staff  509 Aug  2 11:47 melpa-archive/ac-ispell-readme.txt
```
```
: ; ls -la packages/ac-is*
-rw------- 1 rprimus staff 4975 Aug  7 09:36 packages/ac-ispell-20151101.226.el
-rw------- 1 rprimus staff  336 Aug  7 09:36 packages/ac-ispell-20151101.226.entry
-rw------- 1 rprimus staff  967 Aug  7 09:36 packages/ac-ispell-badge.svg
-rw------- 1 rprimus staff  509 Aug  7 09:36 packages/ac-ispell-readme.txt
```
