### ISSUE TITLE
[FYI] Relocated repos and CLRF encoded recipes

### ISSUE THREAD

**Issue by rprimus** [melpa/melpa#5664]
Wed Aug  1 17:40:38 BST 2018

### Relocated repos:
Following on from this [issue](https://github.com/joaotavora/sly/issues/184), the following recipes have `old` repos listed:

<details>
<summary>Relocated repos</summary>
<hr>

### Relocated Repos:

recipe | listed repo | new repo
------ | ------------  | ---------------
ac-html | cheunghy/ac-html | zhangkaiyulw/ac-html
angular-mode | omouse/angularjs-mode | rudolfolah/angularjs-mode
autopair | capitaomorte/autopair | joaotavora/autopair
bubbleberry-theme | jasonm23/emacs-bubbleberry-theme | emacsfodder/emacs-bubbleberry-theme
bundler | tobiassvn/bundler.el | endofunky/bundler.el
challenger-deep-theme | MaxSt/challenger-deep | challenger-deep-theme/emacs
clips-mode | grettke/clips-mode | clips-mode/clips-mode
company-ghci | juiko/company-ghci | orimh/company-ghci
dart-mode | nex3/dart-mode | bradyt/dart-mode
diffscuss-mode | hut8labs/diffscuss | tomheon/diffscuss
drawille | sshbio/drawille | josuah/drawille-el
efire | capitaomorte/efire | joaotavora/efire
egison-mode | egisatoshi/egison3 | egison/egison
elisp-refs | Wilfred/refs.el | Wilfred/elisp-refs
elixir-mode | elixir-lang/emacs-elixir | elixir-editors/emacs-elixir
emr | chrisbarrett/emacs-refactor | Wilfred/emacs-refactor
eshell-prompt-extras | hiddenlotus/eshell-prompt-extras | kaihaosw/eshell-prompt-extras
expand-line | cheunghy/expand-line | zhangkaiyulw/expand-line
find-file-in-repository | hoffstaetter/find-file-in-repository | h/find-file-in-repository
flycheck-demjsonlint | z4139jq/flycheck-demjsonlint | zenkiezhu/flycheck-demjsonlint
flymake-perlcritic | illusori/emacs-flymake-perlcritic | flymake/emacs-flymake-perlcritic
github-theme | philiparvidsson/emacs-github-theme | philiparvidsson/GitHub-Theme-for-Emacs
hacker-typer | therockmandolinist/emacs-hacker-typer | dieggsy/emacs-hacker-typer
hal-mode | strahlex/hal-mode | machinekoder/hal-mode
helm-dired-recent-dirs | akisute3/helm-dired-recent-dirs | yynozk/helm-dired-recent-dirs
how-many-lines-in-project | hiddenlotus/how-many-lines-in-project | kaihaosw/how-many-lines-in-project
inf-mongo | tobiassvn/inf-mongo | endofunky/inf-mongo
inferior-spim | hiddenlotus/inferior-spim | kaihaosw/inferior-spim
jst | cheunghy/jst-mode | zhangkaiyulw/jst-mode
julia-mode | JuliaLang/julia-emacs | JuliaEditorSupport/julia-emacs
kroman | cheunghy/kroman-el | zhangkaiyulw/kroman-el
magit-topgit | magit/magit-topgit | greenrd/magit-topgit
merlin | the-lambda-church/merlin | ocaml/merlin
metaweblog | punchagan/metaweblog | org2blog/metaweblog
mexican-holidays | shopClerk/mexican-holidays | sggutier/mexican-holidays
ninja-mode | martine/ninja | ninja-build/ninja
org-alert | groksteve/org-alert | spegoraro/org-alert
org-doing | omouse/org-doing | rudolfolah/org-doing
org2blog | punchagan/org2blog | org2blog/org2blog
pcmpl-homebrew | hiddenlotus/pcmpl-homebrew | kaihaosw/pcmpl-homebrew
pcmpl-pip | hiddenlotus/pcmpl-pip | kaihaosw/pcmpl-pip
php-mode | ejmr/php-mode | emacs-php/php-mode
pretty-mode | akatov/pretty-mode | pretty-mode/pretty-mode
private | cheunghy/private | zhangkaiyulw/private
realgud | rocky/emacs-dbgr | realgud/realgud
realgud-byebug | rocky/realgud-byebug | realgud/realgud-byebug
realgud-old-debuggers | rocky/realgud-old-debuggers | realgud/realgud-old-debuggers
realgud-pry | rocky/realgud-pry | realgud/realgud-pry
realgud-rdb2 | rocky/realgud-ruby-debugger2 | realgud/realgud-ruby-debugger2
rubocop | bbatsov/rubocop-emacs | rubocop-hq/rubocop-emacs
scheme-here | hiddenlotus/scheme-here | kaihaosw/scheme-here
scratches | cheunghy/scratches | zhangkaiyulw/scratches
sly | capitaomorte/sly | joaotavora/sly
sly-hello-world | capitaomorte/sly-hello-world | joaotavora/sly-hello-world
sly-macrostep | capitaomorte/sly-macrostep | joaotavora/sly-macrostep
sly-named-readtables | capitaomorte/sly-named-readtables | joaotavora/sly-named-readtables
sly-quicklisp | capitaomorte/sly-quicklisp | joaotavora/sly-quicklisp
smart-mark | cheunghy/smart-mark | zhangkaiyulw/smart-mark
sos | omouse/emacs-sos | rudolfolah/emacs-sos
swift-mode | chrisbarrett/swift-mode | swift-emacs/swift-mode
tab-jump-out | cheunghy/tab-jump-out | zhangkaiyulw/tab-jump-out
transfer-sh | Brillow/transfer-sh.el | SRoskamp/transfer-sh.el
turing-machine | therockmandolinist/turing-machine | dieggsy/turing-machine
volume | dbrock/volume-el | dbrock/volume.el
vue-mode | CodeFalling/vue-mode | AdamNiederer/vue-mode
zig-mode | zig-lang/zig-mode | ziglang/zig-mode
zweilight-theme | philiparvidsson/emacs-zweilight-theme | philiparvidsson/Zweilight-Theme-for-Emacs

<hr> 
</details>

#### Notes:
1. The raw data can be found [here](https://gist.github.com/2596326f96aaf05451c116733ba0e11d).
Moved repos contain the word `Location:` in the third column (`FS = ::`).
2. This is only an `issue` as the generated `recipes.json` file will contain incorrect data.

### DOS files:
While collecting the above data, the following recipes were found to be  in `dos`/`CLRF` format:

```
ahk-mode
chinese-number
clipmon
clj-refactor
dokuwiki
dyalog-mode
espresso-theme
evil-mark-replace
helm-pt
ivy-todo
mxf-view
org-capture-pop-frame
ssh-agency
sunburn-theme
temporary-persistent
```

**Comment by rprimus** [comment]
Tue Aug  7 18:47:01 BST 2018

Research has revealed that the github REST (v3) API also correctly handles redirects for relocated repos.

Thanks for all your (collective) work on MELPA!

**Comment by tarsius** [comment]
> Research has revealed that the github REST (v3) API also correctly handles redirects for relocated repos.

But we would still like to use the correct repositories.

> DOS files:

We should contact the authors and ask whether that is done on pupose.

@npostavs Since `ssh-agency` is no longer limited to Windows, maybe you should change the eol?

**Comment by npostavs** [comment]
Is this about each repo, or the MELPA recipe files themselves? As far as I can tell, the `ssh-agency` source is LF only.

**Comment by tarsius** [comment]
I though @rprimus was talking about the package libraries, but I guess I was wrong.

**Comment by rprimus** [comment]
Tue Aug  7 23:13:21 BST 2018

@tarsius - I was only referring to the recipes.

**Comment by rprimus** [comment]
Tue Aug  7 23:52:25 BST 2018

Commit https://github.com/melpa/melpa/commit/3416586d4d782cdd61a56159c5f80a0ca9b3ddf4 updated 28 repos (`a` -> `j`), however 39 repos (`kroman` -> `zweilight-theme`) still remain?

Just wondering:
1. Should I submit a PR for the remaining 39 repos (`kroman` -> `zweilight-theme`)?
2. Would it make sense to write a `pretty printer` for recipe files (to `standardize` the layout)?
(This would make it easier to work with tools -  `grep`, `sed` etc)
