### ISSUE TITLE
Info manuals of packages (such as Magit) are gone

### ISSUE THREAD

**Issue by xuchunyang** [melpa/melpa#5672]
Some packages, such as Magit and Use-Package, used to have info manuals. Now it seems Melpa stops shipping them since a few days ago.

```
~/Downloads $ tar -t -f magit-20180726.1649.tar | grep info
magit-20180726.1649/magit.info-1
magit-20180726.1649/magit.info-2
magit-20180726.1649/magit.info
~/Downloads $ tar -t -f magit-20180729.1644.tar | grep info
~/Downloads $
```

**Comment by tarsius** [comment]
When I create these package locally, then the tarballs contain the info files. I guess `makeinfo` is missing on the server.

**Comment by milkypostman** [comment]
Anyone know which Debian package provides it?
