### ISSUE TITLE
Error in PHP

### ISSUE THREAD

**Issue by gjm** [melpa/melpa#5674]
Hi.

I get this error in php-mode:

```
Company: An error occurred in auto-begin
Company: backend company-ac-php-backend error "Wrong type argument: hash-table-p, nil" with args (candidates fu)
```

**Comment by zonuexe** [comment]
@gjm 
I'm maintainer of `php-mode`, but here is not for that question or discussion.
Probably, it related to [xcwen/ac-php](https://github.com/xcwen/ac-php), I am not that user, so it is difficult to advise you.
