### ISSUE TITLE
Regarding non-https, especially on Windows

### ISSUE THREAD

**Issue by bradyt** [melpa/melpa#5682]
Regarding commit a46d878 which closed issue #4820.

In that issue, @johnmorrisbeck says,

> For windows you have to install melpa with http only.

This is not true. Options for allowing https via emacs on windows include:

- Using Cygwin emacs (many more things will work out of the box this way anyways, such as `M-x grep`)
- Following instructions at https://www.gnu.org/software/emacs/manual/html_node/emacs-gnutls/Help-For-Users.html
- It appears since emacs 25, gnu.org is providing the dependencies: https://ftp.gnu.org/gnu/emacs/windows/emacs-25/

I don't think melpa should be so tasked to encourage non-https. At best, it should be a comment. The snippet at https://melpa.org/#/getting-started is getting a bit complicated, and new users may likely not read it before copy-pasting. Even the conditioning on emacs < 24 may be just a comment, 23 is pretty old now.

If I were on Windows, and did not have https via emacs, I'd be more likely to download a package from github via the browser, where there should be https.

The snippet from https://melpa.org/#/getting-started:

``` emacs lisp
(require 'package)
(let* ((no-ssl (and (memq system-type '(windows-nt ms-dos))
                    (not (gnutls-available-p))))
       (proto (if no-ssl "http" "https")))
  ;; Comment/uncomment these two lines to enable/disable MELPA and MELPA Stable as desired
  (add-to-list 'package-archives (cons "melpa" (concat proto "://melpa.org/packages/")) t)
  ;;(add-to-list 'package-archives (cons "melpa-stable" (concat proto "://stable.melpa.org/packages/")) t)
  (when (< emacs-major-version 24)
    ;; For important compatibility libraries like cl-lib
    (add-to-list 'package-archives '("gnu" . (concat proto "://elpa.gnu.org/packages/")))))
(package-initialize)
```

**Comment by milkypostman** [comment]
Since I don’t use Windows I can’t say the right solution. Please update the text which you have objection to and submit a PR and we can make the fix from that approach.

**Comment by bradyt** [comment]
For non-Cygwin Emacs:

Before emacs 25, users were simply directed to dump binaries in `bin` from sourceforge, per the manual. Looking through the emacs-devel list, I'm realizing that at version 25, the download servers provided the dependencies as a separate download. As of version 26, there is a download option prebundled with the dependencies included.

From https://github.com/emacs-mirror/emacs/blob/master/nt/INSTALL#L753-L760:

>   In order to support GnuTLS at runtime, a GnuTLS-enabled Emacs must
>   be able to find the relevant DLLs during startup; failure to do so
>   is not an error, but GnuTLS won't be available to the running
>   session.
> 
>   You can get pre-built binaries (including any required DLL and the
>   header files) at http://sourceforge.net/projects/ezwinports/files/
>   and on https://ftp.gnu.org/gnu/emacs/windows/.

**Comment by josteink** [comment]
Yeah. If you download the properly packaged Windows-version these days, you get all dependencies and full HTTPS support. Starting with Emacs 27.1 (when that time comes), we should also get a proper *installer* which handles all dependencies.

If you install Emacs in any way near normal for Windows-users, this really *should* be a non-issue these days.

**Comment by johnmorrisbeck** [comment]
So I think the easiest way to deal with this is state in the specifications that it is discouraged to use melpa on the official graphical version on windows because *that* version does not yet have a working solution for https. If the user wants to use https they need to use emacs from cygin, bash for windows, or in a virtual machine.

However if one is to use the offical graphical version of emacs designed for windows https must be given up to use melpa, unless someone comes up for a solution for it.

The reason it is important to have this distinction is for our windows bretheren who are not familiar with linux tools they may give up in the graphical emacs thinking it doesn't work and switch over to a powershell version of vim simply cause they can't figure out how to get melpa to work and melpa is necessary for some of the cooler stuff in emacs.

Furthermore people have asked in the #emacs irc multiple times about https not working on GUI emacs in windows which is another reason why the explanation needs to be left up in some form: so that the chatter in #emacs is left clear.

**Comment by josteink** [comment]
> that it is discouraged to use melpa on the official graphical version on windows because that version does not yet have a working solution for https. If the user wants to use https they need to use emacs from cygin, bash for windows, or in a virtual machine.
>
> However if one is to use the offical graphical version of emacs designed for windows https must be given up to use melpa, unless someone comes up for a solution for it.

As I stated in the previous comment in this very issue, this is not true. 

Nowadays https works fine with zero effort or additional, even on Windows.

**Comment by bradyt** [comment]
> [...] that version does not yet have a working solution for https. [...]
> 
> [...] https must be given up to use melpa [...]

@johnmorrisbeck, Where are you getting the above statements? The source code for emacs has had documentation in the `nt` directory that has pointed at one time or another to the three sources,

- https://ftp.gnu.org/gnu/emacs/windows/
- https://sourceforge.net/projects/ezwinports/files/
- https://alpha.gnu.org/gnu/emacs/pretest/windows/

As I've been trying to clarify in previous comments, for versions of emacs:

- < 25, there have been gnutls DLLs at sourceforge for some time. 
- = 25, they are available at gnu.org or the mirrors. 
- &gt; 25, they are prebundled with emacs. 

Sourceforge has been pointed to in the emacs-gnutls manual for some time.

John do you agree that there is a working solution for https in emacs? If so, please clarify the rest of your comment with that in mind.

I don't really understand the argument about #emacs. I have been discussing this there, I do not get the impression anyone feels melpa should encourage http to lighten the load on IRC.

**Comment by johnmorrisbeck** [comment]
If it is fixed now then it is fixed but if I go back and check it and see it's not I will reopen the issue and github will know eternally that you were incorrect muahahahha. Don't have a windows machine right now so meh.

**Comment by bradyt** [comment]
Oh dear,

``` emacs-lisp
(defcustom package-archives `(("gnu" .
                               ,(format "http%s://elpa.gnu.org/packages/"
                                        (if (gnutls-available-p) "s" ""))))
```

**Comment by purcell** [comment]
Now tackled, I believe.
