### ISSUE TITLE
wishlist: only show (or highlight) updated packages since last visit

### ISSUE THREAD

**Issue by slippycheeze** [melpa/melpa#5696]
It'd be nice to see only things that have changed since my last visit to mela, when browsing the package list.  I don't care deeply about it -- a simple cookie for storage would be sufficient -- but being able to filter that way would be very nice.

I care more about "totally new" than updated packages, in some ways, as the goal is to keep an eye out for interesting new packages that tackle one of the problems I'm not yet happy with my solution to.

**Comment by tarsius** [comment]
That's a feature that sound good in theory but when you think about the details it quickly gets difficult. What do you do if the user refreshes after ten seconds; show nothing?

I don't think this is going to happen unless you implement it and in that case I recommend you implement as an Emacs package. Before a refresh copy the `archive-contents` files somewhere else (using a hook if available or else an advice) and provide commands that compare the contents of the old and new versions of these files and then list the new and/or updated packages.

On the web you can already get a list of recently updated packages by sorting by the "Version" column.
