### ISSUE TITLE
flycheck-protobuf repository disappeared

### ISSUE THREAD

**Issue by tarsius** [melpa/melpa#5728]
`flycheck-protobuf` is no longer available from https://github.com/edvorg/flycheck-protobuf.

@edvorg, have you moved the repository elsewhere?
Or is this obsolete and should be removed from Melpa?

**Comment by edvorg** [comment]
Hi @tarsius my apologies, the repository became obsolete as functionality has been reimplemented in `flycheck` package. `flycheck-protobuf` package should be removed from Melba.

**Comment by tarsius** [comment]
Thanks for the information!
