### ISSUE TITLE
Timezone of MELPA build server can cause version number conflict with sandbox?

### ISSUE THREAD

**Issue by alphapapa** [melpa/melpa#5736]
At the moment, the version of `org-web-tools` in MELPA is `(20180920 311)`.  The version that gets built on my system at the moment, which is from a different commit that I just pushed to the package's repo, is `(20180920 54)`.  Here's the relevant part of `package-archive-contents` from the sandbox Emacs:

```el
(org-web-tools #s(package-desc org-web-tools
				(20180920 311)
				"Display and capture web content with Org-mode"
				((emacs
				  (25 1))
				 (org
				  (9 0))
				 (dash
				  (2 12))
				 (esxml
				  (0 3 4))
				 (s
				  (1 10 0))
				 (request
				  (0 3 0)))
				tar "melpa" nil
				((:commit . "30315bcf6183b49352ce37d66615df3ec67f8319")
				 (:keywords "hypermedia" "outlines" "org" "web")
				 (:authors
				  ("Adam Porter" . "adam@alphapapa.net"))
				 (:maintainer "Adam Porter" . "adam@alphapapa.net")
				 (:url . "http://github.com/alphapapa/org-web-tools"))
				nil)
		#s(package-desc org-web-tools
				(20180920 54)
				"Display and capture web content with Org-mode"
				((emacs
				  (25 1))
				 (org
				  (9 0))
				 (dash
				  (2 12))
				 (esxml
				  (0 3 4))
				 (s
				  (1 10 0))
				 (request
				  (0 3 0)))
				tar "sandbox" nil
				((:commit . "a2b2cdfa75d50dd00f4106dfdb6b6bec19280b7d")
				 (:keywords "hypermedia" "outlines" "org" "web")
				 (:authors
				  ("Adam Porter" . "adam@alphapapa.net"))
				 (:maintainer "Adam Porter" . "adam@alphapapa.net")
				 (:url . "http://github.com/alphapapa/org-web-tools"))
				nil))
```

The problem is that I need to test the newer commit in the sandbox, but the sandbox Emacs insists on installing the older version from MELPA.

I'm guessing this is caused by the build server being in a different time zone.

I don't know of an easy way to fix or work around this problem, and it doesn't happen very often, but at least this documents it.

Thanks.

**Comment by seblemaguer** [comment]
I think that may be the cause for #5809 too

**Comment by tarsius** [comment]
> I don't know of an easy way to fix or work around this problem, and it doesn't happen very often, but at least this documents it.

It would be better to do something about it though, probably in `package-build--parse-time`.

**Comment by purcell** [comment]
> It would be better to do something about it though, probably in `package-build--parse-time`.

I guess we'd want to make the MELPA build server time zone the default in `package-build` too, and probably set via a variable. Then `package-build--parse-time` would append it to the string parsed by `date-to-time`...

**Comment by alphapapa** [comment]
What if UTC were always used?  That seems like the most correct solution.

**Comment by tarsius** [comment]
We've just switched to UTC.
