### ISSUE TITLE
Melpa.org down

### ISSUE THREAD

**Issue by beojan** [melpa/melpa#5837]

**Comment by alu-** [comment]
+1

**Comment by danielbarbarito** [comment]
😞

**Comment by peterwvj** [comment]
This could be related to the migration to Linode

https://twitter.com/melpa_emacs/status/1066444071139463170

**Comment by Willyfrog** [comment]
adding the following lines should help until it comes back

```elisp
(add-to-list 'package-archives '("melpa-mirror" . "http://www.mirrorservice.org/sites/melpa.org/packages/") t)
```

**Comment by milkypostman** [comment]
It looks like the server completely crashed and it’s unclear why. Trying to
reboot to unblock things.

**Comment by bzalasky** [comment]
If you happen to be using Spacemacs develop branch, you can implement Willyfrog's suggestion by modifying the .lock file in your in the directory where Spacemacs is installed (~/.emacs.d).

```
;; TODO: revert to melpa.org/packages/

(setq configuration-layer-elpa-archives
  `(("melpa"    . "http://www.mirrorservice.org/sites/melpa.org/packages/")
    ("org"      . "orgmode.org/elpa/")
    ("gnu"      . "elpa.gnu.org/packages/")
    ("spacelpa" . ,(concat configuration-layer-stable-elpa-directory
                           "spacelpa-"
                           configuration-layer-stable-elpa-version))))
```

**Comment by milkypostman** [comment]
It’s back up. It’s unclear what the problem was and I will investigate more
soon. From the console it looks like a kernel panic.

**Comment by peterwvj** [comment]
Great, thanks!

**Comment by beojan** [comment]
This seems to have generated a lot of discussion elsewhere suggesting packages use Github releases for distribution.
Perhaps an alternative would be if Melpa used a CDN (Cloudflare, for instance) so it would remain available even if the hosting goes down.

**Comment by purcell** [comment]
> This seems to have generated a lot of discussion elsewhere suggesting packages use Github releases for distribution.

Where's that? Curious to read up on people's experiences.

> Perhaps an alternative would be if Melpa used a CDN (Cloudflare, for instance) so it would remain available even if the hosting goes down.

Maybe. It all takes time to set up, though, and an occasional blip in availability doesn't necessarily justify a lot of extra volunteer work, expense or complexity for a relatively non-critical service like this. MELPA does pretty well overall in terms of uptime IMO.

**Comment by beojan** [comment]
I'm sure I saw it on Hacker News somewhere, but that has no search.
Reddit has [this](https://www.reddit.com/r/emacs/comments/a1pxfj/to_melpa_or_not_package_authors_need_not_run_a/).
