### ISSUE TITLE
Better RSS feeds

### ISSUE THREAD

**Issue by emacksnotes** [melpa/melpa#5846]
(cf. [Welcome to /r/planetemacs, and a request for help](https://redd.it/a2yym4))

## Help create a better RSS feed for https://melpa.org packages

Here is an atom feed for the `recipes` dir of MELPA: https://github.com/melpa/melpa/commits/master/recipes.atom.  Yesterday, as an experiment, I looked at that feed, and *translated* the items for most of  Nov 2018 to what you now see in /r/planetemacs.   

I did this:

1. I looked at the commit diff to `recipes` dir
2. Proceeded to the associated github, gitlab or bitbucket repo in question (based on the `fetcher` and `url` values).
3. Posted a link to that repo to /r/planetemacs.  The link  description was mostly the TITLE of the README file, and if the README had no title, then I collectedsome excerpt from the first (few) paragraph(s) of the README, particularly any URL it mentions.

If the MELPA project provides an RSS feed that does 1-to-3 above, (or if there is service that does what I did above) then these feeds will be more suitable as feed to  /r/planetemacs or planet.emacsen.org.

Let me reiterate. The RSS feed should link to the individual's github repo, and it's description should be meaningful to an ordinary joe.  See also https://redd.it/663fld.

Here is a screenshot of the Github RSS feeds (as seen within Firefox).  Note that the Feeds have no desciption about the package, and the feed links to git commit diffs and not to repo URLs. 

Adding a link to repo URL will require tooling.  But including a description in the feed is a matter of providing a better commit message. For example, if you adopts the following convention --Add <pkg-name>: <pkg-description> etc--to changes in recipes dir, then that in and of itself will be a good improvement.  (There are many changes to recipes dir that *does not* change the available packages (i.e., remove or add files) but they modify what files are bundled with that package.  I am assume that such *minor* commits can be pruned at Feed Readers's end) 

![screenshot from 2018-12-04 10-55-21](https://user-images.githubusercontent.com/42199775/49443632-fa66fd80-f7f2-11e8-9fe7-4afbd51ca016.png)

**Comment by kjambunathan** [comment]
> Adding a link to repo URL will require tooling.

And this tool can leverage the current tool that generates archive-contents.

archive-contents already has pkg name, url and desc.  See https://old.reddit.com/r/emacs/comments/a2y02z/melpa_feed_for_new_packages/eb2es9s/?context=1

**Comment by purcell** [comment]
Thanks. I'm not really sure what to do with this, because the desired outcome is not very clearly stated. The existing RSS feed is mostly to support auto-posting of build updates via Twitter. If you're looking to generate a new more potential-user-oriented RSS feed which describes noteworthy changes in MELPA, I'm not sure how that would be determined. Maybe you could have a script which diffs the archive contents (or JSON version of them) and then builds a feed based on changes in that over time.

**Comment by emacksnotes** [comment]
## RSS feed link

https://github.com/melpa/melpa/commits/master/recipes.atom

## RSS  Entry as provided by Github:

```
<entry>
  <id>tag:github.com,2008:Grit::Commit/3b8f9437268a51654b2bebdd024c35060b078962</id>
  <link type="text/html" rel="alternate" href="https://github.com/melpa/melpa/commit/3b8f9437268a51654b2bebdd024c35060b078962"/>
  <title>
    Add recipe for emacs-buttons
  </title>
  <updated>2018-12-05T23:03:28Z</updated>
  <media:thumbnail height="30" width="30" url="https://avatars2.githubusercontent.com/u/5349288?s=30&amp;v=4"/>
  <author>
    <name>erjoalgo</name>
    <uri>https://github.com/erjoalgo</uri>
  </author>
  <content type="html">
    &lt;pre style=&#39;white-space:pre-wrap;width:81ex&#39;&gt;Add recipe for emacs-buttons&lt;/pre&gt;
  </content>
</entry>

```

## Proposed Entry

```

<entry>
  <id>tag:github.com,2008:Grit::Commit/3b8f9437268a51654b2bebdd024c35060b078962</id>
  <link type="text/html" rel="alternate" href="https://github.com/erjoalgo/emacs-buttons"/>
  <title>
    Define and visualize hierarchies of keymaps
  </title>
  <updated>2018-12-05T23:03:28Z</updated>
  <media:thumbnail height="30" width="30" url="https://avatars2.githubusercontent.com/u/5349288?s=30&amp;v=4"/>
  <author>
    <name>erjoalgo</name>
    <uri>https://github.com/erjoalgo</uri>
  </author>
  <content type="html">
    &lt;pre style=&#39;white-space:pre-wrap;width:81ex&#39;&gt;Add recipe for emacs-buttons&lt;/pre&gt;
  </content>
</entry>
```


## Diffs in entries between the current and proposed feeds

$ diff -u a.xml b.xml
--- a.xml	2018-12-07 09:15:08.607591797 +0530
+++ b.xml	2018-12-07 09:21:49.079288992 +0530
@@ -1,8 +1,8 @@
 <entry>
   <id>tag:github.com,2008:Grit::Commit/3b8f9437268a51654b2bebdd024c35060b078962</id>
-  <link type="text/html" rel="alternate" href="https://github.com/melpa/melpa/commit/3b8f9437268a51654b2bebdd024c35060b078962"/>
+  <link type="text/html" rel="alternate" href="https://github.com/erjoalgo/emacs-buttons"/>
   <title>
-    Add recipe for emacs-buttons
+    Define and visualize hierarchies of keymaps
   </title>
   <updated>2018-12-05T23:03:28Z</updated>
   <media:thumbnail height="30" width="30" url="https://avatars2.githubusercontent.com/u/5349288?s=30&amp;v=4"/>

## Description of the proposed difference

1. Link URL should point to the pkg's repo
2. Link Description  should point to pkg description

## How to achieve the above RSS feed: *This will require additional tooling*

The tool that dumps MELPA's `archive-contents` could be modified to dump the above entry.  This is because `archive-contents` already contains all the information for generating the above feed.

##  What if MELPA maintainers aren't interested in additional tooling

Adopt better conventions for the commit message i.e., commit message *may* mention package name and description.

**Comment by tarsius** [comment]
> then these feeds will be more suitable as feed to /r/planetemacs or planet.emacsen.org.

Please do not try to get such a feed included in planet.emacsen.org. I quite enjoy that the content there is created by humans. Automatically injecting "stuff that has happened" would be an annoyance, akin to what  entities that are trying to monetize do, i.e. spam.

As a separate feed this *could* be useful, though given the lack of interest expressed at https://www.reddit.com/r/emacs/comments/a2b0lk/welcome_to_rplanetemacs_a_link_only_subreddit_for/ maybe not.

> The tool that dumps MELPA's `archive-contents` could be modified to dump the above entry.  This is because `archive-contents` already contains all the information for generating the above feed.

You could also generate that yourself base on the output of `git log` and/or `archive-contents`. Given the lack of interest, I think that is the way to go. Once you have something like this, then *maybe* users will get interested.

> What if MELPA maintainers aren't interested in additional tooling. Adopt better conventions for the commit message i.e., commit message *may* mention package name and description.

As a major contributor I am not interested. There are much more important things that should be done first.

> Adopt better conventions for the commit message i.e., commit message *may* mention package name and description.

The process is already challenging for recipe authors. There are a lot of conventions to follow, tools to run, etc. I am against making it even harder for them by imposing some commit message conventions, only to make it easier to produce some secondary output, which appears to not be in great demand.

On the other hand generating such a feed could be a fun project. There's nothing to stop you from doing it, but you will likely have to work with imperfect input data.
