### ISSUE TITLE
Seems melpa stops building doom-modeline

### ISSUE THREAD

**Issue by seagle0128** [melpa/melpa#5881]
Hi, melpa.org stops building [doom-modeline](https://github.com/seagle0128/doom-modeline) from 20181220.1741. The latest commits are https://github.com/seagle0128/doom-modeline/commits/master on Dec 23, 2018 and the latest release is 1.2.1.

I noticed the build takes 1 hour or so  now but took 11 hours before. What's the matter with building? Is it able to be triggered manually?

**Comment by milkypostman** [comment]
I’ll have a look in the next few days

**Comment by seagle0128** [comment]
Same issue for melpa stable repo. It stay at 1.1.0, but the latest tag is 1.2.2.

**Comment by seagle0128** [comment]
@milkypostman Gently ping... Any update? Stopped building for one week.

**Comment by milkypostman** [comment]
@seagle0128 it looks like the repo changed things around and our build system couldn't handle it. basically the tags seem to have been re-written and the pull request was being rejected. i'm concerned that maybe the repo got a force push which is like, really bad for a mainline repo.

anyways, it's fixed now.

**Comment by seagle0128** [comment]
@milkypostman Thank you very much!

**Comment by seagle0128** [comment]
Hi @milkypostman , it seems the build is broken again, after a force push by mistake. Please help to fix it. Sorry for that! 

I'm wondering if the system uses the clean codes or just makes incremental build (pull the codes based on existing codes)? IMO, it's better clean all codes and get the latest codes (or tags, but only `--depth=1`) to make the builds in CI systems.

**Comment by purcell** [comment]
> I'm wondering if the system uses the clean codes or just makes incremental build (pull the codes based on existing codes)? IMO, it's better clean all codes and get the latest codes (or tags, but only `--depth=1`) to make the builds in CI systems.

We pull each time. Fetching 4000 entire repositories (some of which are 1GB) is too much. `--depth=1` can't work for MELPA because we use last-commit times for the packaged files to calculate package versions, and looking at the single most recent commit in the repo is often not sufficient for this.

**Comment by purcell** [comment]
P.S. The code is in package-build.el if you're curious.

**Comment by seagle0128** [comment]
Thank you very much! I understand now. I don't know if fetching a several recent commits works, since I don't know the details.

**Comment by seagle0128** [comment]
Please help to fix the build anyway. Thanks a lot!

**Comment by milkypostman** [comment]
I will when I get a chance. Sorry for the delay.

**Comment by milkypostman** [comment]
i reset the working snapshot so it should work itself out when we hit
doom-modeline build next.

**Comment by seagle0128** [comment]
Than you, @milkypostman !

**Comment by seagle0128** [comment]
@milkypostman , seems the build system stops working now?
It says: `Next build: unknown, last ended 16 hours ago and took unknown`.

**Comment by milkypostman** [comment]
It happens but I think it’s still building. I’m not sure the time issue.
Will have a look tonight.

**Comment by seagle0128** [comment]
The builds are available now. Thanks very much!

**Comment by seagle0128** [comment]
@milkypostman Sorry for disturb you again! I just notice `melpa-stable` build doesn't work correctly yet. Could you please help to check? Thanks.

**Comment by milkypostman** [comment]
What specifically doesn’t work on melpa-stable?

**Comment by seagle0128** [comment]
@milkypostman The `melpa-stable` version of `doom-modeline` still stays on `1.6.3`, but the latest tag is `1.7.1`. It seems not working for a few weeks.

**Comment by seagle0128** [comment]
@milkypostman Oh! maybe need more time to observe.  I will check tomorrow. Thanks for the patience!

**Comment by milkypostman** [comment]
When was the tag pushed?

**Comment by seagle0128** [comment]
A few hours ago.Best Regards,Vincent Zhang-------- 原始邮件 --------主题：Re: [melpa/melpa] Seems melpa stops building doom-modeline (#5881)发件人：Donald Curtis 收件人：melpa/melpa 抄送：Vincent Zhang ,Mention When was the tag pushed?



On Mon, Feb 11, 2019 at 14:46 Vincent Zhang <notifications@github.com>

wrote:

**Comment by milkypostman** [comment]
Yeah if you don’t see it tomorrow then send a message back here and I’ll
check it out.

**Comment by seagle0128** [comment]
I checked just now. It's back and works well. Thank you, @milkypostman .
