### ISSUE TITLE
rsync melpa down

### ISSUE THREAD

**Issue by ninrod** [melpa/melpa#5994]
hi guys, it seems that the rsync service is again not working, similar to #5402 

as of 2019.01.30 17:54 (GMT -3):

```sh
$ rsync --list-only rsync://melpa.org/packages/
rsync: failed to connect to melpa.org (178.128.185.1): Connection refused (111)
rsync error: error in socket IO (code 10) at clientserver.c(125) [Receiver=3.1.2]
rsynced-melpa ➜ 
```

**Comment by ninrod** [comment]
@xuchunyang friendly ping

**Comment by milkypostman** [comment]
Yeah I think somehow I messed something up. I’ll fix it tonight sorry.

**Comment by milkypostman** [comment]
all good now.

**Comment by ifelsefi** [comment]
Hi,

Can this be enabled again?

```
rsync --list-only rsync://stable.melpa.org/packages/
rsync: failed to connect to stable.melpa.org (137.184.119.165): Connection timed out (110)
rsync error: error in socket IO (code 10) at clientserver.c(126) [Receiver=3.1.2]
```

**Comment by purcell** [comment]
I believe the rsync paths for MELPA and MELPA Stable are now: rsync://melpa.org/packages/ and rsync://melpa.org/packages-stable/

**Comment by purcell** [comment]
(I double-checked and this is correctly specified in the current documentation, though I believe that a few years ago it used to look like the URL you were trying.)
