### ISSUE TITLE
cannot read getting started site with eww

### ISSUE THREAD

**Issue by thomasmey** [melpa/melpa#6008]
Hi,

I wanted to install melpa on a console-only laptop and did search for melpa getting started with eww.

But the site is empty, likely because content is only shown with JavaScript.

At least the getting started text should also be available on a static website

**Comment by purcell** [comment]
Thanks. Most of the same getting-started content is available in the README here on Github. We're not going to make the website compatible with eww anytime soon.

**Comment by aplaice** [comment]
FWIW, the actual contents of the "getting started" page is also already available online in a completely static, eww-friendly form at https://melpa.org/partials/getting-started.html, though it's probably not linked to by search engines.

Making the "main" getting-started page static, but still using the same visual style as the rest of the site (including when the style changes!) would probably not be worth it (or not much more so than making the entire site available without javascript (#3728)).

**Comment by skallinen** [comment]
adding my vote to this, would also love to be able to browse the site and check packages via eww.

**Comment by tarsius** [comment]
> Thanks. Most of the same getting-started content is available in the README here on Github. We're not going to make the website compatible with eww anytime soon.

We would however accept a pull-request that added a link to that README inside `noscript`...

**Comment by tarsius** [comment]
Thanks to @aplaice there's such a link now.
