### ISSUE TITLE
Package not found: po-mode but there is a recipe for it

### ISSUE THREAD

**Issue by xuchunyang** [melpa/melpa#6023]
- Recipe: https://github.com/melpa/melpa/blob/master/recipes/po-mode
- Melpa: https://melpa.org/#/po-mode (Package not found)

There is a po-mode-20180505.1115 in my Elpa directory, I don't know when and why Melpa stoped shipping this package, or is this expected?

**Comment by purcell** [comment]
My guess is that the enormous repo in which the source code is found can't be cloned within the timeout of 60 seconds that is applied to every package build on the server.

Honestly my inclination here would be to remove the recipe entirely because of the repo size.

**Comment by manuel-uberti** [comment]
Wouldn't it be possible to extract the package from there into its own dedicated repository?

**Comment by manuel-uberti** [comment]
@purcell Friendly ping here. :)

**Comment by purcell** [comment]
Thanks for the suggestion @dakra: done in 38e855cd.

**Comment by manuel-uberti** [comment]
Great, thank you!
