### ISSUE TITLE
zmq package not being updated

### ISSUE THREAD

**Issue by dzop** [melpa/melpa#6039]
The package is stuck at version 20190210.1712 on MELPA even though I made a commit yesterday. After looking at https://github.com/melpa/melpa/issues/5992#issuecomment-458786980, I think it might be because I force pushed to the master branch 😄.

**Comment by milkypostman** [comment]
aw c'mon this is like the first rule of git club!

**Comment by milkypostman** [comment]
should be fixed in the next build cycle. so give it a day.

**Comment by dzop** [comment]
Shhhh...no more talking about it.

**Comment by purcell** [comment]
I feel like the code in `package-build.el` should already handle this case, no? It does `git fetch --all --tags` and then `git reset --hard master`. So I'm confused about why this would fail.

**Comment by purcell** [comment]
(See https://github.com/melpa/melpa/blob/master/package-build/package-build.el#L242)

**Comment by milkypostman** [comment]
you're right, but i didn't look the last time at what the problem was.
something breaks so whatever we're doing isn't correct.

next time we catch something like this i'll have to look more carefully.
