### ISSUE TITLE
ivy-rich package is not being updated

### ISSUE THREAD

**Issue by flatwhatson** [melpa/melpa#6069]
It seems that MELPA is stuck with package 20181210.845 (commit ad90a1).  When I build locally I get the correct version 20190309.1933 (commit 25e36b).

I'm not sure if the author has force-pushed, but it *might* be related to #6039 and #5992.

**Comment by milkypostman** [comment]
Will look into this when I get a chance hopefully tonight. On my radar.

**Comment by milkypostman** [comment]
@Yevgnen did you force push a tag?

```shell
# git fetch --all --tags
Fetching origin
From https://github.com/Yevgnen/ivy-rich
 ! [rejected]        0.1.2      -> 0.1.2  (would clobber existing tag)
error: Could not fetch origin
```

So I'm going to add a `-f` to the `git fetch --all --tags` command so this happens automatically if someone does bad stuff like force pushing. Anyways, this package is fixed and will update soon.

cc: @purcell

**Comment by flatwhatson** [comment]
Great, thanks!

**Comment by Yevgnen** [comment]
@milkypostman Thanks for the quick response, and sorry for such bad stuff...
