### ISSUE TITLE
jupyter package not being updated

### ISSUE THREAD

**Issue by dzop** [melpa/melpa#6081]
I haven't force pushed the master branch after my last incident with the zmq package so don't really know why its stuck. The last tag I created was after the last time the package was updated so I don't think its a tags issue either.

**Comment by Zulu-Inuoe** [comment]
I've noticed the same with the [sly](https://melpa.org/#/sly) and [assess](https://melpa.org/#/assess) packages.
Sly in particular hasn't been updated since January, when its last commit was 5 days ago.

**Comment by Zulu-Inuoe** [comment]
@milkypostman Hey sorry for the ping, but it's been a while and I wanted to make sure this got some eyes on it.
Some of the packages I'm using have bugs fixed in the latest versions, but melpa hasn't updated them in months.

**Comment by dzop** [comment]
This appears to have been fixed.
