### ISSUE TITLE
Some repositories no longer being tracked

### ISSUE THREAD

**Issue by mfiano** [melpa/melpa#6099]
The `sly` package has had recent commits, but MELPA is a few months old. I have also seen some other repositories affected, despite the recipe not looking for anything particular.

**Comment by milkypostman** [comment]
I’ll have a look later today.

**Comment by mfiano** [comment]
Thanks!

**Comment by milkypostman** [comment]
@mfiano i don't understand the problem here. current melpa version is `20190109.2208`. joaotavora/sly@affc61adfe5d23db0b326735a9576660df7cd16f is the latest commit.

are you sure this isn't a matter of syncing your packages locally?

**Comment by dzop** [comment]
The latest commit is actually joaotavora/sly@0a622da46251e620433d76f5ed98e40ef375ee01.

**Comment by milkypostman** [comment]
you're right, i clicked our melpa link. 

so the issue is that something has changed in how we're detecting what to copy. for some reason the recipe says to copy `*` from a directory into a directory that is named the same thing. this is kinda weird and it's different on the build server than on my local machine.

still looking into how to fix this.

**Comment by mfiano** [comment]
@milkypostman Thanks. For the record, I did check and some other repositories are also affected. From memory the `assess` package is another victim too.

**Comment by purcell** [comment]
The "sly" recipe was a mess, btw, so I've just tidied it up in 974d8812.

**Comment by milkypostman** [comment]
Hehe, I was trying to avoid this for debugging purposes but I’ll hope there
are enough others that are stuck which I can simulate.

It’s a hard case because it only repros on the build server. Maybe it’s a
Linux vs Mac thing.

**Comment by purcell** [comment]
> Hehe, I was trying to avoid this for debugging purposes but I’ll hope there are enough others that are stuck which I can simulate.

Haha, I figured it'd be a while till the recipe got updated on the build server. There wasn't anything particularly magical about that recipe afaict.

> It’s a hard case because it only repros on the build server. Maybe it’s a Linux vs Mac thing.

Could be a git version thing too, or perhaps a glob expansion difference between shells? Though if the `assess` package was really affected, that's a very simple one.

**Comment by milkypostman** [comment]
i don't think there is a problem with `assess`. the update on jan 5 was only to the readme.

the recipe change is already on the server and the package is now updated...

**Comment by milkypostman** [comment]
will leave this open for a few days and see if anyone can report broken packages. we need a better way to report on broken packages.

**Comment by mfiano** [comment]
I went through all of the packages that were last updated in January, and it seems there are no other affected packages with changes to recipe-tracked files. Do we know why Sly got stuck? I see it is fixed now. Thanks! I think this would be safe to close now.

**Comment by milkypostman** [comment]
yeah it was something to do with the odd nature of the recipe. probably we
need to ban it but it was written incorrectly to use a * for a directory
when it should've just included the directory name.

**Comment by mfiano** [comment]
I see. Thanks for looking into this!
