### ISSUE TITLE
Cask package is broken (I think…?)

### ISSUE THREAD

**Issue by TinaRussell** [melpa/melpa#6121]
I’m new to Cask, and all the documentation I can find for it expects that I can use a “cask” executable from the command line. But, the MELPA package for Cask doesn’t seem to include anything other than Emacs Lisp files, even though the recipe points to the repository at [https://github.com/cask/cask](https://github.com/cask/cask), which has the executable (and much else besides).

Moreover, if I use `(load-library "cask-cli")` with the Cask package from melpa-stable, I get `Cask file does not exist: "/home/tina/.emacs.d/elpa/cask-0.8.4/Cask"`. (With the unstable package, that command yields `Symbol’s function definition is void: green` … weird.)

So, is there something I’m missing? (I know I could clone the repo and use that instead of the MELPA package, but I’m hoping to avoid manually installing and updating a package that’s supposed to make it easier to maintain packages :dizzy_face:)

**Comment by purcell** [comment]
Probably the `cask` recipe should contain only `cask.el`, but that would just be for writing elisp that uses `cask`. To actually use `cask` as a user, in most cases you'd follow the Cask installation instructions so that you end up with a `cask` executable on your path.

**Comment by TinaRussell** [comment]
Okay. I think there should also be some instructions in the package description, like “this package requires the ‘cask’ executable, install via blablablah.”
Man I wish Cask had a deb package :disappointed:

**Comment by purcell** [comment]
The package description comes from the `cask.el` file, so you could perhaps file a pull request there.

Agree re. the deb package: since `cask` is a Python package, perhaps it is (or could be made to be) installable via `pip` or `easy_install` etc.
