### ISSUE TITLE
melpa stable hydra version 0.14.0 missing lv.el

### ISSUE THREAD

**Issue by ahyatt** [melpa/melpa#6166]
In the version 0.14.0 of the hydra package, the `lv.el` file is missing.  It is required in `hydra.el`, causing an error when the package is loaded.

**Comment by milkypostman** [comment]
60d4791ac1e7e230b52e6ed93cba580fc62f1a9f says it needed to be removed. 

the problem is likely that lv is not a dependency for hydra. so @abo-abo needs to chime in on that :(

**Comment by abo-abo** [comment]
I just published [0.15.0](https://github.com/abo-abo/hydra/releases/tag/0.15.0). I think it will fix the dependency problem.

**Comment by ahyatt** [comment]
Thanks, I tested this out and it is fixed now.
