### ISSUE TITLE
Elnode is unusable because of a teeny-tiny, itsy-bitsy bug.

### ISSUE THREAD

**Issue by jcaw** [melpa/melpa#6184]
[Elnode](https://github.com/nicferrier/elnode/), a popular package for running an HTTP server within Emacs (written by the author of Marmalade), is currently unusable on Emacs 25.1+, because of an update to the way servers are created. Elnode creates servers with two flags that are now mutually exclusive, so it can't start servers.

The fix for this appears to be a single line, [disabling the `:nowait`](https://github.com/nicferrier/elnode/pull/105/files) parameter in the TCP process. I've been running this patch for a while and it hasn't caused me any problems. 

There's a [pull request](https://github.com/nicferrier/elnode/pull/105) in the original repository to fix this bug, but it's been sitting for 6 months with no response. Elnode itself seems to have had no commits in 4 years. I opened an [issue](https://github.com/nicferrier/elnode/issues/106) on Elnode 5 days ago to bump the issue, but no response yet.

Is it worth temporarily updating the MELPA recipe to use a patched version of Elnode until this is fixed? Aside from this issue, the package seems stable and doesn't seem to be suffering from bit-rot.

Paging Elnode's author too: @nicferrier

**Comment by purcell** [comment]
One option would be to ask @nicferrier if he would be comfortable adding you as a collaborator on the repo in order to do a little maintenance.

**Comment by jcaw** [comment]
It doesn't look like he's responding to inquiries about Elnode. I'd be happy to do that if he was open to it.

**Comment by jcaw** [comment]
I've opened two fresh pull requests on Elnode that are a safer than the initial one, and the latter targets the Melpa branch, which MELPA seems to build from. 

https://github.com/nicferrier/elnode/pull/107
https://github.com/nicferrier/elnode/pull/108

@nicferrier

**Comment by purcell** [comment]
@jcaw Great, thanks.

If it turns out that `elnode` is functionally unmaintained and you would be willing to maintain it, then in the absence of a response from the current maintainer within a reasonable amount of time, we'd be happy to point the recipe at your maintained fork.

**Comment by jcaw** [comment]
I'd be happy to do that, adding Nic as a maintainer and leaving it open for him to take the project back if he ends up with more time.

**Comment by purcell** [comment]
Recipe updated. If you could work towards eliminating the "melpa" branch so that we can instead point the recipe at "master", that would be good.

**Comment by jcaw** [comment]
Version bumped. *0.9.9.8* is now the minimum version of Elnode that should be used on Emacs 26+.

**Comment by nicferrier** [comment]
I'm not the maintainer of any melpa version because I don't agree melpa is a useful thing.

But if there's a pure emacs bug I guess I'll fix it, yeah.

**Comment by purcell** [comment]
> I'm not the maintainer of any melpa version because I don't agree melpa is a useful thing.

Sure. This was about overall maintenance of elnode.

**Comment by tychobrailleur** [comment]
This new elnode “stream” is breaking with emacs `HEAD`:

> Wrong number of arguments: (1 . 1), 2

This seems to be caused by the `melpa` branch requiring `'assoc` which is obsolete.  From looking at the elnode code, it looks like the `melpa` branch is out-of-sync with master – the `melpa` branch should probably be re-created based off `master` on the `jcaw/elnode` repo.

BTW, @jcaw where should we report bugs on the new repo?  Issues seem to be off.

**Comment by jcaw** [comment]
@tychobrailleur Yep, `assoc` is obsolete. Works on 26, just gives a warning. I'll try eliminating the assoc dependency on the `melpa` branch for now so the package is still usable.

I'm wary of building off master for now. I don't know what the side effects will be and I don't want to diverge from the original project yet, since Nic Ferrier might take it back. 

>BTW, @jcaw where should we report bugs on the new repo? Issues seem to be off.

Missed this. They must have been disabled on the fork. I've enabled them again.

**Comment by jcaw** [comment]
@tychobrailleur assoc removed, it should work now. Let me know if you're still having problems.
