### ISSUE TITLE
Remove Fill Column Indicator mode

### ISSUE THREAD

**Issue by equwal** [melpa/melpa#6245]
Not actively maintained.

See https://github.com/alpaker/fill-column-indicator/issues/87

I'm not associated with the package, but it has crashed my emacs.

**Comment by akirak** [comment]
I also noticed that the package can be a performance bottleneck in one's config. Still, the amount of slowdown is not fatal for me (that is, there are some more CPU-intensive packages in my config), and I find this package useful.

Do you know a better alternative to this package?

**Comment by equwal** [comment]
An "alternative" is available in spacemacs: it highlights letters past column 80 with a different font.

This package is included in Emacs 27 by default, perhaps that implementation is efficient enough.

**Comment by akirak** [comment]
Thank you. 

> An "alternative" is available in spacemacs: it highlights letters past column 80 with a different font.

You are talking about `column-enforce-mode`, right? 

- https://github.com/syl20bnr/spacemacs/blob/c7a103a772d808101d7635ec10f292ab9202d9ee/layers/%2Bspacemacs/spacemacs-editing-visual/packages.el#L275
- https://github.com/jordonbiondo/column-enforce-mode/

I didn't know of this package, and it looks useful.

**Comment by equwal** [comment]
Indeed, this package. It is bound to `SPC t 8`.

I'd be in favour of adding it to Melpa, and depricating FCI mode.

**Comment by purcell** [comment]
> I'd be in favour of adding it to Melpa, and deprecating FCI mode.

It's already in MELPA.

I don't think we're going to remove `fill-column-indicator` though: it seems to work fine for many people, and is in the 98th percentile of MELPA packages by download count.
