### ISSUE TITLE
Switch from git merge to git rebase for PRs?

### ISSUE THREAD

**Issue by lassik** [melpa/melpa#6253]
Recent `git log --graph` looks like this (the ASCII art lines are merge lineages):

```
* | | | | | | | | | | |   commit 69fb1a2c590eb1a9a7cae09a7080b24185e49c74
|\ \ \ \ \ \ \ \ \ \ \ \  Merge: 059b003c b9efcd28
| | | | | | | | | | | | | Author: Steve Purcell <steve@sanityinc.com>
| | | | | | | | | | | | | Date:   Mon Jun 3 13:11:33 2019 +1200
| | | | | | | | | | | | |
| | | | | | | | | | | | |     Merge pull request #6160 from DLaps/flycheck-clolyze
| | | | | | | | | | | | |
| | | | | | | | | | | | |     Add flycheck-clolyze recipe
| | | | | | | | | | | | |
| * | | | | | | | | | | | commit b9efcd28fa3f9c13dbf51d31487464f655aaeda6
| | | | | | | | | | | | | Author: Daniel Laps <daniel.laps@hhu.de>
| | | | | | | | | | | | | Date:   Tue May 7 11:23:17 2019 +0200
| | | | | | | | | | | | |
| | | | | | | | | | | | |     Add clolyze package
| | | | | | | | | | | | |
* | | | | | | | | | | | |   commit 059b003c74acdfdd917ecb6fecb782a0f54d155b
|\ \ \ \ \ \ \ \ \ \ \ \ \  Merge: 7df44ae0 774fbeab
| | | | | | | | | | | | | | Author: Chris Rayner <riscy@users.noreply.github.com>
| | | | | | | | | | | | | | Date:   Sun Jun 2 14:41:02 2019 -0700
| | | | | | | | | | | | | |
| | | | | | | | | | | | | |     Merge pull request #6168 from redguardtoo/master
| | | | | | | | | | | | | |
| | | | | | | | | | | | | |     Add dianyou
| | | | | | | | | | | | | |
| * | | | | | | | | | | | | commit 774fbeaba04e91e75acd0be8596d296673e7880a
| | |_|_|_|_|_|_|_|_|/ / /  Author: Chen Bin <chenbin.sh@gmail.com>
| |/| | | | | | | | | | |   Date:   Fri May 17 16:14:52 2019 +1000
| | | | | | | | | | | | |
| | | | | | | | | | | | |       Add dianyou
| | | | | | | | | | | | |
* | | | | | | | | | | | |   commit 7df44ae0ba89a2c4089a39b212784a6a359f1521
|\ \ \ \ \ \ \ \ \ \ \ \ \  Merge: 71ca87a0 e2069f2b
| |_|_|_|_|_|_|_|_|_|_|_|/  Author: Chris Rayner <riscy@users.noreply.github.com>
|/| | | | | | | | | | | |   Date:   Sun Jun 2 09:43:46 2019 -0700
| | | | | | | | | | | | |
| | | | | | | | | | | | |       Merge pull request #6177 from DerBeutlin/add-ros-el
| | | | | | | | | | | | |
| | | | | | | | | | | | |       add ros.el
| | | | | | | | | | | | |
```

I'd like to suggest using rebase instead of merge to accept PRs. This would make the history cleaner (we'd have one parallel lineage instead of having up to 15). This can be selected from the _Merge button_ panel in the repo's settings in the GitHub UI. Workflow is the same as for merge-based PRs.

**Comment by conao3** [comment]
It seems @riscy do merge PRs with rebase, @purcell do merge PRs without rebase.
I think both strategies are good. But It is better MELPA maintainers use the same strategy, isn't it?

**Comment by lassik** [comment]
Agreed. The thing is, the primary use of a merge is to resolve conflicts between edits to the same file. The secondary use is to group a batch of related commits together under the merge commit. Since most MELPA PRs just add/change one recipe file, and two PRs rarely touch the same file, there is not much benefit in creating merge commits.

**Comment by tarsius** [comment]
@purcell Last time I made the same request your response was that you accidentally switched to merge. To prevent that from happening again I suggest that you disallow the "merge merge" method on Github and perform real merges using Magit. (Have you checked out Forge yet? That streamlines merging.)

**Comment by purcell** [comment]
> Last time I made the same request your response was that you accidentally switched to merge.

Yes, that could be the case. Generally I'm a fan of rebase vs. merge, but simply merging PRs allows them to be reverted more easily if necessary in the case where there *are* multiple commits.

> I suggest that you disallow the "merge merge" method on Github and perform real merges using Magit.

I've checked out Forge, but it's much more efficient for me to do all of this via the Github web interface tbh. I have a streamlined workflow for processing big batches of PRs in my browser, and I'll confess to not caring very much about the specific method used when I click "Merge".

**Comment by lassik** [comment]
> Generally I'm a fan of rebase vs. merge, but simply merging PRs allows them to be reverted more easily if necessary in the case where there _are_ multiple commits.

The GitHub merge button now offers "squash" as a third alternative in addition rebase and merge. Squash makes one commit out of the whole PR even if the person who send the PR made many commits. This could be the best of both worlds: easy reverts and no merge commits.

Of course, for particularly complex PRs, there's still the option of using  merge or rebase manually for that particular PR.

**Comment by purcell** [comment]
> now offers "squash" as a third alternative in addition rebase and merge

Yep, I did that for a long time: Github's "merge" button remembers the last-used merge method.

**Comment by tarsius** [comment]
So... you try to use "rebase" most of the time and if you forget to switch back to that method after using one of the other methods in a special case then we tell you about it? Works for me. (I prefer "rebase" but don't care about it much.)

> I'll confess to not caring very much about the specific method used when I click "Merge".

Key take away. Considering this I don't think it makes much sense to keep this open.
