### ISSUE TITLE
Cannot find package hide-comnt

### ISSUE THREAD

**Issue by adrianstaniec** [melpa/melpa#6261]
Why is this package is missing from melpa?

**Comment by purcell** [comment]
See a26379472690f2fdf7a0cd57aa8fbfc3b1dea0d3

**Comment by adrianstaniec** [comment]
thank you Steve, 
in case someone has the same question, here is even more context:
[reddit](https://www.reddit.com/r/emacs/comments/7vocqa/update_on_melpa_removing_emacswiki_packages_they/dtuhzmt/)
