### ISSUE TITLE
Beta-testers wanted for Sunrise Commander

### ISSUE THREAD

**Issue by lassik** [melpa/melpa#6267]
Sunrise Commander, the [orthodox file manager](https://en.wikipedia.org/wiki/File_manager#Orthodox_file_managers) for Emacs, now has a new home at [sunrise-commander/sunrise-commander](https://github.com/sunrise-commander/sunrise-commander). I promised to maintain it for the near future. I'm committed to finally getting it into MELPA. The MELPA submission has been pending since 2013 due to problems with Sunrise Commander's extension mechanism. SC's main author is open to changing the mechanism to be MELPA-compatible. I'm willing to do that work, but I need beta testers. If you are interested, please come to https://github.com/sunrise-commander/sunrise-commander/issues/65 and I'll be happy to discuss the details.

(I've kind of stolen the MELPA issue tracker for this ad with the excuse that SC is a prominent missing package that would be of long-standing interest to the community. I'll close this in a week or two so it doesn't clutter the listing.)

**Comment by purcell** [comment]
I'll tweet about this via the MELPA Twitter account, and close this issue, since it's otherwise not actionable by us MELPA maintainers, and I don't think hundreds of Emacs users are randomly reading our issue list. To more effectively reach potential users, I would suggest posting this call for beta testers to the emacs subreddit or a mailing list.

**Comment by lassik** [comment]
Thank you! Well, this repo has a fair number of watchers :) I didn't post on emacs-devel since RMS has had reservations about MELPA. Didn't know there's an active reddit. Could also try IRC.

**Comment by purcell** [comment]
Yep, IRC would be a good bet.
