### ISSUE TITLE
My plugin was a fork but I asked Github to detach it to make it an own project, will that cause any trouble?

### ISSUE THREAD

**Issue by ema2159** [melpa/melpa#6279]
Recently I did that, I'm not quite sure if it will cause any problem. The Github link remains the same so I would imagine that there shouldn't be any problems

**Comment by purcell** [comment]
Should be fine, thanks for checking.

**Comment by ema2159** [comment]
Thanks Mr. Purcell! By the way, thanks for all your work, you're incredible!

**Comment by purcell** [comment]
Thanks! ❤️
