### ISSUE TITLE
wisp-mode missing on melpa.org

### ISSUE THREAD

**Issue by ArneBab** [melpa/melpa#6301]
wisp-mode is available in [recipes/wisp-mode](https://github.com/melpa/melpa/tree/master/recipes/wisp-mode), but it is not available on https://melpa.org/#/wisp-mode

Is extra filtering happening? Or is something missing from the package? For me it builds locally in melpa via `make recipes/wisp-mode`.

The package is on bitbucket: Is this connected to https://github.com/melpa/melpa/issues/3788 ?

**Comment by purcell** [comment]
I don't appear to have SSH access to the build server these days, so I can't check it - pinging @milkypostman.

**Comment by tarsius** [comment]
It's no longer missing.

**Comment by ArneBab** [comment]
Thank you!
