### ISSUE TITLE
how to compare package dates for stable and unstable MELPA

### ISSUE THREAD

**Issue by juhp** [melpa/melpa#6319]
The version numbers on MELPA Stable are quite different from "non-stable" MELPA, sometimes I really want to know when Stable packages were last updated... eg "Is 16.1 newer than my current installed  20180917.923 or should I update to 20190714.652?"

Is there an easy way to see the dates of Stable MELPA releases, or one has to go look at the upstream?  I think this would make a nice enhancement if it could be done.

**Comment by purcell** [comment]
Hmm, interesting idea! We could maybe add a metadata header to every package containing its last-updated time. For MELPA packages this would match the `Package-Version` header, and for MELPA Stable packages it would be different.

**Comment by juhp** [comment]
That would be really useful for Stable yes!

**Comment by tarsius** [comment]
I've finally implemented a new version string format (well three), see melpa/package-build#81.

Closing in favor of that pull-request, but if you want to follow up on something said above, then feel free to do that here.
