### ISSUE TITLE
bad request on all attempts to download packages from emacs 26.1 on redhat 8

### ISSUE THREAD

**Issue by willoch** [melpa/melpa#6333]
GNU Emacs 26.1 (build 1, x86_64-redhat-linux-gnu, GTK+ Version 3.22.30) of 2018-09-10)

(Installed with yum install emacs)
( Linux localhost.localdomain 4.18.0-80.4.2.el8_0.x86_64 #1 SMP Fri Jun 14 13:20:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux)

All attempts to install a package get something like :

package-install-from-archive: https://elpa.gnu.org/packages/svg-1.0.el: Bad Request

I am able to browse  https://elpa.gnu.org with eww. Even the very files it say is a bad request.

**Comment by willoch** [comment]
If things has changed or not, I do not know, but many things work.
But it seems like no packages fro marchive gnu works.
And the package I want, ccls stops because of its dependency on spinner, which is a gnu package.

**Comment by milkypostman** [comment]
Sorry to hear of the problems. We don’t maintain that archive so you will
need to contact the owner. Try emailing emacs-devel.
