### ISSUE TITLE
Loading/compiling order of files in multifiles packages (Helm)

### ISSUE THREAD

**Issue by thierryvolpiatto** [melpa/melpa#6336]
Hi,
Helm is a package with a dependency called Helm-core.
When I make changes in both packages, it seems Helm is compiled first and then Helm-core is compiled/loaded after it.
Generally the changes made in Helm-core are used in Helm (not the contrary) so when I for example add a new macro or function or even a variable to Helm-core, when Helm compile (before Helm-core) users have an error e.g. (void variable helm-foo).
Is there a way to specify the order of compilation? I.e. first Helm-core and second Helm.
Thanks.

**Comment by purcell** [comment]
> Is there a way to specify the order of compilation? I.e. first Helm-core and second Helm.

Not really: this sounds like an issue with `package.el`, if it is compiling `helm` before `helm-core` in some circumstances.

(A somewhat related issue: if you define a macro in package `p` then install package `q` which uses that macro, updating `p` later will not cause `q` to be recompiled. I think that's also a shortcoming of `package.el`.)

**Comment by thierryvolpiatto** [comment]
Steve Purcell <notifications@github.com> writes:

>     Is there a way to specify the order of compilation? I.e. first Helm-core and second Helm.
>
> Not really: this sounds like an issue with package.el, if it is
> compiling helm before helm-core in some circumstances.

Hmm, I see, thanks.

> (A somewhat related issue: if you define a macro in package p then
> install package q which uses that macro, updating p later will not
> cause q to be recompiled. I think that's also a shortcoming of
> package.el.)

Yes I had this issue too in the past, generally users have to uninstall and
reinstall all.

--
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Perhaps something like this (fully not tested) may fix first issue, second issue seems more difficult to fix:

```elisp
(defun package-menu--find-upgrades ()
  (let (installed available upgrades dependencies)
    ;; Build list of installed/available packages in this buffer.
    (dolist (entry tabulated-list-entries)
      ;; ENTRY is (PKG-DESC [NAME VERSION STATUS DOC])
      (let ((pkg-desc (car entry))
            (status (aref (cadr entry) 2)))
        (cond ((member status '("installed" "unsigned"))
               (push pkg-desc installed))
              ((string= status "dependency")
               (push pkg-desc dependencies))
              ((member status '("available" "new"))
               (setq available (package--append-to-alist pkg-desc available))))))
    ;; Assume DEPENDENCIES are needed by INSTALLED packages to compile
    ;; properly so append INSTALLED to DEPENDENCIES so that the
    ;; UPGRADES list be reverted in next loop.
    (setq installed (append installed dependencies))
    ;; Loop through list of installed packages, finding upgrades.
    (dolist (pkg-desc installed)
      (let* ((name (package-desc-name pkg-desc))
             (avail-pkg (cadr (assq name available))))
        (and avail-pkg
             (version-list-< (package-desc-priority-version pkg-desc)
                             (package-desc-priority-version avail-pkg))
             (push (cons name avail-pkg) upgrades))))
    ;; DEPENDENCIES should now be on top of UPGRADES.
    upgrades))
```

**Comment by milkypostman** [comment]
I have seen this type of thing before. File a bug to Emma a about it. There
was a problem before about calculating dependency order that needed to be
fixed. Possibly the same thing has happened.

**Comment by thierryvolpiatto** [comment]
I made some changes in the Helm interface for package.el that fix these issues (maybe there is some bugs though).
Of course there is some corner cases that are not covered yet...
I am closing now as this is not really a Melpa issues.
Thanks.
