### ISSUE TITLE
Remove my packages

### ISSUE THREAD

**Issue by lunaryorn** [melpa/melpa#6391]
Hello,

MELPA still builds the following packages from my Github account:

- pkg-info
- fancy-battery
- osx-trash 
- ansible-doc
- opam

I'd like to make you aware that I intend to remove these packages from my Github account at 
some point—I've long stopped maintaining these repositories.

I'll transfer those repos to anyone interested; otherwise you may want to remove them from MELPA.

Cheers,
Sebastian

**Comment by purcell** [comment]
Oh hey, hope you're doing well!

I'd probably suggest transferring those repos to the [emacsorphanage](https://github.com/emacsorphanage) organisation, if that's acceptable to you. We'd add you to the org, then after the transfer you could leave it. This is probably the least work. I can imagine eventually moving `pkg-info` into the MELPA org since it's quite related, and also widely used afaict.

**Comment by lunaryorn** [comment]
I will move these repositories wherever you like, as long as I can get rid of those :)   

I deleted the opam package before I realized I should've asked, but I don't think it was used a lot and there's probably also a fork somewhere.  As for the others I'll happily transfer ownership to emacsorphanage, the sooner the better.

I guess I'll have to be a member of the org to do that(?) but I'd leave it again right after transferring ownership.

**Comment by purcell** [comment]
> I guess I'll have to be a member of the org to do that(?) but I'd leave it again right after transferring ownership.

Yep, exactly. Only @tarsius is an owner for that org: Jonas, please can you either add Sebastian or make me an owner so I can do it?

**Comment by tarsius** [comment]
I've invited Sebastian, created an opam repository, and made you an owner.

**Comment by purcell** [comment]
Great, thanks.

**Comment by lunaryorn** [comment]
I've transferred all repos and left the org again.  Thanks!

PS: I've also unsubscribed from this thread; if you need anything from me, please mention me explicitly.

**Comment by tarsius** [comment]
The transfer is complete. Melpa and Emacsmirror have been updated.

**Comment by purcell** [comment]
Thanks @tarsius!

**Comment by lunaryorn** [comment]
Thanks, @purcell and @tarsius, for your quick help.  Cheers!

**Comment by tarsius** [comment]
Cheers!

**Comment by purcell** [comment]
Ein Prosit!
