### ISSUE TITLE
Question about submitting a package with multiple files

### ISSUE THREAD

**Issue by sehnsucht13** [melpa/melpa#6399]
Hello everybody! 
First of all, thanks to everybody for their work on MELPA. It is awesome!
Now, onto my question. I have a package which is almost done and I will be submitting it to MELPA relatively soon. The only thing which I am unsure of is what to do when the package itself is broken up into multiple files. In the CONTRIBUTING file, it mentions the following:

> MELPA only looks at the main .el file (or -pkg.el file, if provided, though we discourage that).
> If  you have different optional parts of a large package, each of which has different
>  dependencies, then these should really be published as separate packages.

The files in my package could be condensed into only one file but I have broken them up into separate ones which take care of different functionalities. Can I leave the file structure as is and simply add a `-pkg.el` file or do I really have to condense all of the code into one file to follow best practice? Is there a preferred alternative to having a `-pkg.el`?

For reference, [here is a link to the repo](https://github.com/emacs-taskrunner/emacs-taskrunner).
A short summary of what the package does:
Taskrunner is a library which aims to collect targets/tasks(Makefiles, package.json, leiningen, grunt, gulp...) from taskrunners/build systems in the currently visited project and let the user run them. The library by itself has no way of displaying them  to the user and requires a frontend to be built which uses the data created from it(these will be submitted as separate packages!). There are several files in the repo and some of them are related to particular build systems(web/javascript, java, c/c++...) and while they could be condensed, the code feels like it is organized better if they are kept separately.

If there are any more details which I can provide then please let me know. Thanks in advance!

**Comment by milkypostman** [comment]
Our package-build script should create a -pkg file for you. All you need to
do is write a very basic recipe and everything should work fine. You don’t
have to worry about the files being split up this is pretty standard.

**Comment by sehnsucht13** [comment]
Perfect, thank you very much for the quick response! I appreciate it!
