### ISSUE TITLE
evil broken due to missing undo-tree

### ISSUE THREAD

**Issue by fouric** [melpa/melpa#6455]
In both stable and...non-stable (?), the `evil` package appears to be broken due to a dependency on `undo-tree`, which is missing from both MELPAen.

Suggestion: `evil` appears to gracefully degrade in the absence of `undo-tree`, perhaps remove that dependency entirely?

**Comment by purcell** [comment]
`undo-tree` is in GNU ELPA. As noted in the README, MELPA is designed to work alongside ELPA, and not entirely replace it. Certain important widely-used packages, like `cl-lib` and `seq` are only available in ELPA.

**Comment by purcell** [comment]
(Additional note, just to provide extra background information: MELPA doesn't control the package dependencies, since they are declared by the package authors upstream.)

**Comment by Silex** [comment]
I think this happens because since a while this happens:

```
Failed to verify signature archive-contents.sig:
No public key for 066DAFCB81E42C40 created at 2019-09-25T23:10:03+0200 using RSA
Command output:
gpg: Signature made mer 25 sep 2019 23:10:03 CEST
gpg:                using RSA key C433554766D3DDC64221BFAA066DAFCB81E42C40
gpg: Can't check signature: No public key
```

Which points to https://www.reddit.com/r/emacs/comments/aug9in/failed_to_verify_signature_archivecontentssig/, which points to https://debbugs.gnu.org/cgi/bugreport.cgi?bug=33825 which points to using https instead of http when fetching the GNU archives.

**Comment by purcell** [comment]
Ah, yes, that's possible. As a workaround, setting `package-check-signature` to `nil` can help, or use this:
```el
(when (and (version< emacs-version "26.3") (boundp 'libgnutls-version) (>= libgnutls-version 30604))
  (setq gnutls-algorithm-priority "NORMAL:-VERS-TLS1.3"))

```
