### ISSUE TITLE
Need advice: How best to handle a package’s language being renamed?

### ISSUE THREAD

**Issue by treyharris** [melpa/melpa#6475]
>_Note: this isn’t directly MELPA-related, but I can’t find any other venue where I’m likely to find the experienced Emacs packagers from whom I desperately need advice. I’ll try to make the impact on this repo as small as possible, so I’d very much appreciate it if this issue can be left open for a little while as I outline at the bottom of this issue below. Thanks! @treyharris_

The Perl 6 language is likely changing names soon in order to alleviate the confusion people have that it is a new version of the Perl 5 language (rather than what it is—an entirely new, Perl-inspired language) and to allow Perl 5 to evolve without having Perl 6 stand in its way. The most likely new name is “Raku”. I’m trying to figure out how to deal with this renaming in the perl6-mode package (and/or its successor raku-mode package).

I just did a stupid (but, I hope, smart enough) bisect of MELPA’s Git log to look for any cases of this, and I’ve only found what I’d call “blunt-force” name changes (text search-and-replaces) and AFAICT, only for languages that were already new and didn’t have a large installed base. I can’t find an example of a language package existing for many years and _then_ the language’s name changing. #2514 comes closest, but it isn’t really relevant here. (I’d appreciate any pointers if I missed such an example I could study.)

I can find a few examples of packages changing names as they significantly changed/enhanced functions, but those looked more like forks, and weren’t language modes, so users had very explicit signals that “there are changes here you must opt in to”. There are also cases (more in core than in MELPA, I think) where new, better-architected language modes replaced old ones, mostly _without_ changing names—the odd duck of cperl-mode (of _course_ it’s Perl!) being the exception that proves the rule. But it looks like these modes either strove to be 100% backwards-compatible, or went to a lot of effort to do a proper long-term deprecation cycle—effort, time, and Elisp know-how to implement, we don’t really have.

There will be a transitional period (on the close order of a year, I’d think) where both names are in use, and unfortunately the original Emacs package’s author didn’t use `defcustom` for most configuration, so reducing impact on existing users who have variables, advice, key bindings, hooks, snippets, etc., all depending on `perl6-.*` names is a thorny problem. The obvious thing seems to be to make raku-mode a derived mode of perl6-mode that’s nearly vacuous except for aliasing to new names and file patterns. But then we have two packages to maintain, and it appears to me there’s no way to avoid _eventually_ having an impactful cutover—if we want to make raku-mode be derived directly from prog-mode so the dependency goes away and then we can obsolete, and remove, the perl6-mode package.

(I have some dim ideas for something clever that could be done by modifying the libraries in perl6-mode to make way for the upcoming transition—starting with making _raku-mode_ the prog-mode derivation and deriving perl6-mode on _it,_ turning it from the outset into the “legacy mode”— but I very much suspect that most of our users do not update their modules frequently enough to count on this, and when they see a “raku-mode” is available, they’ll ignore any perl6-mode updates.)

Further complicating things, the perl6-mode package also includes a mode for NQP, the language’s compiler-bootstrapping/runtime-opcode language, which is _not_ going away _or,_ AFAIK, being renamed. So if we throw up our hands on having a smooth migration path and do a search-and-replace into a new package, we have a naming conflict—and one can guarantee that pretty much every early adopter of raku-mode will already be a perl6-mode user, so they’ll definitely hit the nqp-mode name collision.

I’m a part-time Elisp coder of very little sophistication, so I’d much appreciate the expertise any readers can bring to this. I realize this isn’t really a MELPA issue, but I think I’m unlikely to find experienced packagers anywhere else. I don’t want to add noise to your repo, though. So I’m happy to close this issue in no more than 30 days (Fri 8 Nov 2019)—which is less than the current median idle time of open issues here, so should negligibly increase the background noise. In the meantime, I’d suggest that perhaps answers that could be useful to any MELPA packagers searching in the future be added here, and any back-and-forth or specifics to how perl6-mode works be redirected to perl6/perl6-mode#22 where the name change is being tracked. (Note that if that link doesn’t work, it’s possible that you’ll need to look for raku-mode’s issue 22—the GitHub migration hasn’t been nailed down yet either!) Thanks for any help you can provide!

**Comment by tarsius** [comment]
Since nobody else replied so far: my approach would be "just do it".

**Comment by treyharris** [comment]
As promised, closing this issue. Again, I still welcome advice at https://github.com/perl6/perl6-mode/issues/22.
