### ISSUE TITLE
Help removing deprecated lsp-mode packages from archive

### ISSUE THREAD

**Issue by muirrn** [melpa/melpa#6501]
Hello

There are a handful of deprecated packages whose recipes were removed in 9e9de1cf264047a33127abaec88bdac97867e994. However, they still show up in https://melpa.org/packages/archive-contents, so they show up in Emacs when you do `package-list-packages`. These packages should not be used because they break things. Can they be fully purged ?

I think the full list is (please confirm @yyoncho):
lsp-clangd
lsp-css
lsp-dart
lsp-fortran
lsp-go
lsp-html
lsp-javascript
lsp-ocaml
lsp-php
lsp-python
lsp-ruby
lsp-rust
lsp-sh
lsp-typescript
lsp-vue

Edit: additional deprecated packages:
lsp-scala
lsp-hack

**Comment by milkypostman** [comment]
I will do this tonight. Previously I believe our prescribed path was to
keep these around until they ultimately got pruned but in this case we can
remove them.

**Comment by milkypostman** [comment]
ok they been removed. if they are still in recipes they will come back and you may not see the effects for a few hours. I didn't manually trigger a cleanse, but it'll happen when it happens. re-open if this is still an issue in 24hours (it should be ~1-2 hours to be completely removed).

Thanks for reporting!
