### ISSUE TITLE
Twitter account or RSS feed for new projects only

### ISSUE THREAD

**Issue by scottjad** [melpa/melpa#654]
Unlike the current twitter account that includes updates to projects, this would include a single tweet/article when a project is added to MELPA for the first time.

This would be a low-traffic way for people to find out about a new package here and there.

**Comment by vyp** [comment]
@scottjad There's http://elpa.brause.cc/ now thanks to @wasamasa.

**Comment by purcell** [comment]
Not going to do this, sorry.

**Comment by alphapapa** [comment]
Maybe it would be possible to do this from within Emacs.  `package-menu--populate-new-package-list` is the function used to mark new packages in the package list.
