### ISSUE TITLE
Duplicate jq-format packages

### ISSUE THREAD

**Issue by jimmywongroo** [melpa/melpa#6561]
The recipes only has `jq-format` but the Melpa index has returned both `json-reformatter-jq`, which points to the same repo on github. I suspect that at some point the package repo was renamed and the author added a recipe for the new repo location, and removed the old one from the recipes, but somehow some cache for the old package is still remaining.

**Comment by tarsius** [comment]
> the Melpa index

Not sure what you are referring to.

Also, can you still reproduce this issue?

**Comment by jimmywongroo** [comment]
> Also, can you still reproduce this issue?

Yes, I just had to remove `~/.emacs.d/elpa/archives/melpa` and ran `M-x list-packages` again. `json-reformatter-jq` is in the JSON response, but there's no recipe for it.

**Comment by tarsius** [comment]
b547298254a88ead2c9b0d0f32c3ab274d2c21b7 should fix this. It will take a few hours until the updated code is actually called, so the fix doesn't take effect immediately.

Thanks for the report.
