### ISSUE TITLE
Somehow lusty-explorer requirements have gotten corrupted.

### ISSUE THREAD

**Issue by stsquad** [melpa/melpa#6572]
I can't install @sjbach's [lusty-emacs](https://github.com/sjbach/lusty-emacs) from MELPA due to broken requirements - explicitly that of dired-0. However I can install the MELPA stable version which is based on the exact same commit. I'm not sure where the confusion has crept in because there are no explicit versions in the lusty requirements.

**Comment by stsquad** [comment]
My bad - it seems the non-versioned Package-requires was added since the last stable release. They however meet the spec of [the elisp manual](https://www.gnu.org/software/emacs/manual/html_node/elisp/Library-Headers.html#Library-Headers).

**Comment by sjbach** [comment]
That's my doing in https://github.com/sjbach/lusty-emacs/commit/3b9b774883cfab5225497f3dbe6df8da756472a6. I can change it back - dired and cl-lib are always available, so it's a pointless addition anyway.

**Comment by stsquad** [comment]
@sjbach it would certainly be the pragmatic change. I think melpa is doing the right thing of setting the version number to zero:

    (lusty-explorer . [(20191115 1552) ((cl-lib (0)) (dired (0))) "Dynamic filesystem explorer and buffer switcher" single ((:commit . "4197a5e4e32f8bc2a94f7777ec6cc12279a1000c") (:keywords "convenience" "files" "matching" "tools") (:url . "https://github.com/sjbach/lusty-emacs"))])

versus:

    (dired-rsync . [(20191110 1115) ((s (1 12 0)) (dash (2 0 0)) (emacs (24))) "Allow rsync from dired buffers" tar ((:commit . "3eb1ff3ded8e2881606459cf6e64cf28d8062b64") (:authors ("Alex Bennée" . "alex@bennee.com")) (:maintainer "Alex Bennée" . "alex@bennee.com") (:url . "https://github.com/stsquad/dired-rsync"))])

but for some reason is trips up package-install. I suspect the bug is with emacs itself.

**Comment by sjbach** [comment]
Thanks for the report. 👍

**Comment by stsquad** [comment]
FWIW I raised a bug against Emacs: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=38473

**Comment by purcell** [comment]
> My bad - it seems the non-versioned Package-requires was added since the last stable release. They however meet the spec of [the elisp manual](https://www.gnu.org/software/emacs/manual/html_node/elisp/Library-Headers.html#Library-Headers).

`package-lint` warns about such non-versioned `Package-Requires` entries for the simple reason that older Emacsen cannot parse them. I think that syntax was a mistake in the evolution of `package.el`.
