### ISSUE TITLE
Testing recipe with `C-c C-c` does not work

### ISSUE THREAD

**Issue by Silex** [melpa/melpa#6578]
Hello,

The page https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#test-your-recipe mentions that we can press `C-c C-c` to test a recipe instead of doing `make recipes/foo`, but in my setup (Emacs 26.3) the recipe is in fundamental-mode and I can't find which mode to activate. 

Originally asked in #6571

**Comment by purcell** [comment]
The mode loading  and activation works via `.dir-locals.el`. Did you maybe choose not to accept the `.dir-locals.el` settings?

**Comment by Silex** [comment]
@purcell: that is likely the issue, I'll reopen if I can't figure it out. Thanks!
