### ISSUE TITLE
Policy for Org-related packages broken by Org releases?

### ISSUE THREAD

**Issue by alphapapa** [melpa/melpa#6647]
@tarsius 

See https://github.com/melpa/melpa/commit/1b15a29bbd36919b637e3f2aa56bf3cdbff15ee1

I have mixed feelings about this.  Org isn't developed with much concern for third-party packages that use Org code.  When I bring up such concerns on the Org mailing list, they are usually ignored or dismissed.  

In my own packages, it's been frustrating trying to maintain compatibility with such changes.  Although they have their reasons internally, these changes often seem, from the outside, much like churn.

Due to the nature of Emacs and Org, with users building their own configurations upon them, upgrading to a new Org version can be risky and time-consuming, because breaking changes are likely.  Some are documented in the release notes, but ones that affect third-party packages usually are not.  So it's not at all uncommon for Org users to delay upgrading Org for months or even years.  I regularly correspond with Org users who are on early Org 9.x versions, and one who's still on Org 8.2.  I am still using earlier Org 9.x versions in my own config, because upgrading to Org 9.3 is going to require transitional work that won't bring me much benefit.

For a maintainer of an Org-related package, these changes can require time, work, and testing to update for.  And all of these maintainers work in their spare time.  And if they haven't yet upgraded their own Org installation, they may have no personal need to make the changes yet.

So, all this to ask, is it now MELPA's policy to delete packages that are broken by Org releases only about a month old?  Your last comments on those issues were 29 days ago.  That's not really much time for a package maintainer who doesn't closely monitor Org or GitHub to make the changes.  And there are still many Org users on the older versions for which such packages are still compatible.

I mean, I can just imagine an Org 9.y being released that breaks `org-super-agenda` or `org-ql` or `helm-org-rifle`, and if I get busy with real life stuff and don't have time to investigate and fix, would those packages just be deleted from MELPA, even though there would probably be more users on the still-compatible Org versions than on the newer one?  I can imagine all the posts on /r/emacs asking, "Where did these packages go?  I was redoing my Emacs config on a new machine and now they aren't found.  I'm still using Emacs N-1, so I'm on Org N-2, so those package versions still work fine for me, but they're gone.  How to fix??"

Then after fixing the packages, I'd have to request that they be re-added, go through reviews again(?), and then post announcements, hoping that former users will notice.  I can just imagine, even then, having to reply to comments on Reddit, "No, the package is back on MELPA now, it's not dead."

**Comment by tarsius** [comment]
There is no policy in place, but I can assure you that I am not going to remove your packages or similar packages just because the maintainers are temporarily unresponsive.

I've been monitoring the quality of Emacs packages for a decade or so now and in the time I have developed a sense for when a maintainer is just busy and when waiting another year or two wouldn't make a difference.

"Sense" is maybe the wrong term, I look at the repository, the user account, past encounters etc. to determine what to do. In these four cases I am fairly sure that waiting and pinging is not gonna make a difference.

**Comment by tarsius** [comment]
I put a lot of work into giving orphan packages at least some future (see for example all the work on the Emacs orphanage that I have done just today). But its a *lot* of work and I have to *more* pragmatic about it. Just ripping of the bandage in some less important but likely laborious cases, allows me to spend more time on cases with better prospects.

**Comment by alphapapa** [comment]
I certainly trust your judgment and am glad things are in your good hands.  Thanks for the clarification.  :)
