### ISSUE TITLE
Missing maintainer, @syohex

### ISSUE THREAD

**Issue by purcell** [melpa/melpa#6674]
I noticed from a [pull request](https://github.com/syohex/emacs-hcl-mode/pull/13) that I filed that @syohex has been essentially inactive on Github for over a year. Of [45 (!) packages](https://melpa.org/#/?q=syohex) by that user hosted on MELPA, the latest was updated in Dec 2018, and a random sampling of projects shows a large number of open issues and pull requests.

So here I am wondering out loud what to do about this. Options include:

* Explicitly allowing new maintainers to volunteer and host forks of these projects in their own Github accounts
* Pro-actively forking some of these packages into the emacsorphanage org

Ideally @syohex would respond, and possibly consider transferring ownership of the repos, or adding co-maintainers. I guess I'd suggest that if we don't hear back before the end of Feb, we should feel free to do either of the above.

**Comment by seagle0128** [comment]
Totally agree with @purcell . 

The progress is too slow. `melpa` is the motst important package center for all emacs users. Many people have to switch to `staight.el` or other similar things to get the latest package from GitHub, Gitlab or Emacswiki directly. Can you image VSCode can grow so fast without a good extension marketplace?

**Comment by conao3** [comment]
I now notice this issue. I've send message to him via Emacs-JP Slack.

**Comment by purcell** [comment]
Thanks @conao3.

**Comment by gonewest818** [comment]
fwiw, I'm willing to pitch in on maintenance tasks if you're looking for volunteers.

**Comment by tarsius** [comment]
@gonewest818 What packages are you most interested in. Or do you want to help with all of them?

**Comment by conao3** [comment]
I think it is difficult to manage everything alone. I also want to help.

**Comment by gonewest818** [comment]
@tarsius:
I sorted the list and focused on the packages with more than 25,000 downloads. Of the 20 packages above that threshold, I could see helping with any of the `git-*`, `smeargle`, `dired-k`, maybe `anzu` and `company-jedi`.  I'm not a helm person, so the `helm-*` add-ons would be somewhat more foreign to me.

Would you consider adding me to emacsorphange (can be provisionally, or whatever you feel is appropriate) to start chipping away at the backlog of issues and pull requests?  Or do you prefer finding someone to own the fork, as I do `osx-plist` and `elisp-ilnt`?

**Comment by tarsius** [comment]
I think we are in no hurry and can try a few more times to get @syohex's attention.

@syohex The idea is that you would transfer the repositories to the [Emacsorphanage](https://github.com/emacsorphanage). (This is only possible once I have made you a member, so please let me know if you want to do this.) At that point @purcell and I can appoint new maintainers and maybe do some light maintenance ourselves.

**Comment by gonewest818** [comment]
Agree, not a rush for me either.

**Comment by jcs090218** [comment]
> At that point @purcell and I can appoint new maintainers and maybe do some light maintenance ourselves.

Just here to say, I can help maintain some of the packages if you guys need volunteer! 😄

**Comment by purcell** [comment]
I've gone ahead and taken over `hcl-mode` because I needed it and am personally willing to maintain it.

**Comment by tarsius** [comment]
> I've gone ahead and taken over `hcl-mode` because I needed it and am personally willing to maintain it.

Yeah, if we cannot get @syohex to hand over the repositories then we have to do that eventually, and in cases where there is a concrete need I am fine with doing this now already.

Still it would be nice if we could take the existing issues along. Would be nice if Github allowed us to do that. Oh well.

> I've send message to him via Emacs-JP Slack.

@conao3 Any luck?

**Comment by conao3** [comment]
Nothing, unfortunately.

**Comment by tarsius** [comment]
Okay then... I think we are looking for volunteers.

**Comment by gonewest818** [comment]
Unless someone else is really eager to take them, I’ll volunteer for the `git-*` packages and `smeargle`.

**Comment by conao3** [comment]
I don't think someone needs to do maintenance alone.
I would like to maintain all of his packages with someone together.

P.S.
I've sent @syohex a message again via Emacs-JP Slack.

**Comment by alphapapa** [comment]
> I don't think someone needs to do maintenance alone.
> I would like to maintain all of his packages with someone together.

Is it wise for you to take on maintenance of *all* of Yoshida's packages, rather than the ones which you actually use?  Is it fair for you to ask for commit rights on *all* of his packages, rather than letting other interested parties adopt packages they are interested in, who have not asked for you as a co-maintainer?

**Comment by jcs090218** [comment]
I am still waiting for @syohex to reply. Anyway, I am interested maintaining these packages.

* [zoom-window](https://github.com/syohex/emacs-zoom-window)
* [fontawesome](https://github.com/syohex/emacs-fontawesome)
* [sound-wav](https://github.com/syohex/emacs-sound-wav)
* [counsel-gtags](https://github.com/syohex/emacs-counsel-gtags)
* [helm-themes](https://github.com/syohex/emacs-helm-themes)
* [helm-gtags](https://github.com/syohex/emacs-helm-gtags)
* [helm-ag](https://github.com/syohex/emacs-helm-ag)

**Comment by syohex** [comment]
I apologize for very late reply. I no longer use emacs and it is difficult to maintain those packages.Please register forked repositories instead of my repositories.

Regards.

**Comment by alphapapa** [comment]
@syohex I think it's traditional to say something like, "So long, and thanks for all the fish."  :)  Thanks for your contributions to Emacsland over the years.

**Comment by tarsius** [comment]
@syohex Thanks for getting back to us!

> Please register forked repositories instead of my repositories.

Would you be willing to transfer the original repositories to us instead? That way way we would not partially "lose" the existing issues and pull-requests. I.e. counting would not start from `1` again and we would be able to close issues that have been addressed and Github would mark merged pull-requests as such.

You could simply transfer all your repositories to the https://github.com/orgs/emacsorphanage. I have just invited you to that organization because without (temporary) being a member you would not be able to do so. We (@purcell and I) will then handle appointing new maintainers. So after transferring the repositories, there is nothing left for you to do.

**Comment by tarsius** [comment]
@syohex To make it simpler for you to transfer the repositories, I am providing this hopefully complete list of your packages. The links are to the *settings* pages of the repsoitories. On these page you will have to scroll to the bottom and there click on the `Transfer` button.  Then use `emacsorphanage` as the "New owner’s GitHub username or organization name".

- ac-alchemist https://github.com/syohex/emacs-ac-alchemist/settings
- ac-capf https://github.com/syohex/emacs-ac-capf/settings
- ac-emoji https://github.com/syohex/emacs-ac-emoji/settings
- ac-etags https://github.com/syohex/emacs-ac-etags/settings
- ac-ispell https://github.com/syohex/emacs-ac-ispell/settings
- ac-racer https://github.com/syohex/emacs-ac-racer/settings
- anzu https://github.com/syohex/emacs-anzu/settings
- codic https://github.com/syohex/emacs-codic/settings
- counsel-gtags https://github.com/syohex/counsel-gtags/settings ([fork](https://github.com/FelipeLema/emacs-counsel-gtags))
- dired-k https://github.com/syohex/emacs-dired-k/settings
- easy-highlight https://github.com/syohex/emacs-easy-highlight/settings
- emamux https://github.com/syohex/emacs-emamux/settings
- emamux-ruby-test https://github.com/syohex/emamux-ruby-test/settings
- evil-anzu https://github.com/syohex/emacs-evil-anzu/settings
- evil-textobj-line https://github.com/syohex/evil-textobj-line/settings
- fontawesome https://github.com/syohex/emacs-fontawesome/settings
- git-gutter https://github.com/syohex/emacs-git-gutter/settings
- git-gutter-fringe https://github.com/syohex/emacs-git-gutter-fringe/settings
- git-messenger https://github.com/syohex/emacs-git-messenger/settings
- go-add-tags https://github.com/syohex/emacs-go-add-tags/settings
- go-direx https://github.com/syohex/emacs-go-direx/settings
- go-eldoc https://github.com/syohex/emacs-go-eldoc/settings
- go-impl https://github.com/syohex/emacs-go-impl/settings
- gom-mode https://github.com/syohex/emacs-gom-mode/settings
- hcl-mode https://github.com/syohex/cpp-auto-include/settings ([fork](https://github.com/purcell/emacs-hcl-mode]))
- helm-ack https://github.com/syohex/emacs-helm-ack/settings
- helm-ag https://github.com/syohex/emacs-helm-ag/settings
- helm-github-issues https://github.com/syohex/emacs-helm-github-issues/settings
- helm-gtags https://github.com/syohex/emacs-helm-gtags/settings
- helm-haskell-import https://github.com/syohex/emacs-helm-haskell-import/settings
- helm-ispell https://github.com/syohex/emacs-helm-ispell/settings
- helm-open-github https://github.com/syohex/emacs-helm-open-github/settings
- helm-package https://github.com/syohex/emacs-helm-package/settings
- helm-perldoc https://github.com/syohex/emacs-helm-perldoc/settings
- helm-pydoc https://github.com/syohex/emacs-helm-pydoc/settings
- helm-robe https://github.com/syohex/emacs-helm-robe/settings
- helm-themes https://github.com/syohex/emacs-helm-themes/settings
- import-popwin https://github.com/syohex/emacs-import-popwin/settings
- jedi-eldoc https://github.com/syohex/emacs-jedi-eldoc/settings
- konoha-mode https://github.com/syohex/emacs-konoha-mode/settings
- literate-coffee-mode https://github.com/syohex/emacs-literate-coffee-mode/settings
- ltsv https://github.com/syohex/emacs-ltsv/settings
- octicons https://github.com/syohex/emacs-octicons/settings
- perl-utils https://github.com/syohex/emacs-perl-utils/settings
- popup-complete https://github.com/syohex/emacs-popup-complete/settings
- quickrun https://github.com/syohex/emacs-quickrun/settings
- reverse-theme https://github.com/syohex/emacs-reverse-theme/settings
- smeargle https://github.com/syohex/emacs-smeargle/settings
- sound-wav https://github.com/syohex/emacs-sound-wav/settings
- sourcemap https://github.com/syohex/emacs-sourcemap/settings
- splitjoin https://github.com/syohex/emacs-splitjoin/settings
- terraform-mode https://github.com/syohex/emacs-terraform-mode/settings
- test-more https://github.com/syohex/emacs-test-more/settings
- tora-mode https://github.com/syohex/emacs-tora-mode/settings
- zoom-window https://github.com/syohex/emacs-zoom-window/settings
- **We already forked this to the Emacsorphanage. Please transfer your repoitory to my user-account instead.** cpp-auto-include https://github.com/syohex/cpp-auto-include/settings ([fork](https://github.com/emacsorphanage/cpp-auto-include))

**Comment by tarsius** [comment]
How was it who eventually got @syohex to make the above statement? Could you please work your magic again and get him to read my [response and request](https://github.com/melpa/melpa/issues/6674#issuecomment-598373532) above.

@syohex Please take some time to hand off you packages properly. It will take some time but not very much. It should be possible to go through the list that I posted right above in twenty minutes or so. Thank you very much!

**Comment by tarsius** [comment]
@syohex I wrote a little script that you can use to transfer all the repositories. This is what you would have to do:

1. Accept my invitation to the `emacsorphanage` organization.
2. Go to https://github.com/settings/tokens and generate a token with the `repo` scope.
3. Put the bellow script in a file and make it executable.
4. Run the script with the token as argument.

```
$ chmod u+x script.sh
$ ./script.sh 12345qwert
```

```shell
#!/bin/sh

TOKEN=$1
if [ -z "$TOKEN" ]; then
    echo "usage: $0 TOKEN"
    echo "  Generate a token at https://github.com/settings/tokens."
    echo "  The \"repo\" is required."
    exit 1
fi

PACKAGES="
emacs-ac-alchemist
emacs-ac-capf
emacs-ac-emoji
emacs-ac-etags
emacs-ac-ispell
emacs-ac-racer
emacs-anzu
emacs-codic
counsel-gtags
emacs-dired-k
emacs-easy-highlight
emacs-emamux
emamux-ruby-test
emacs-evil-anzu
evil-textobj-line
emacs-fontawesome
emacs-git-gutter
emacs-git-gutter-fringe
emacs-git-messenger
emacs-go-add-tags
emacs-go-direx
emacs-go-eldoc
emacs-go-impl
emacs-gom-mode
cpp-auto-include
emacs-helm-ack
emacs-helm-ag
emacs-helm-github-issues
emacs-helm-gtags
emacs-helm-haskell-import
emacs-helm-ispell
emacs-helm-open-github
emacs-helm-package
emacs-helm-perldoc
emacs-helm-pydoc
emacs-helm-robe
emacs-helm-themes
emacs-import-popwin
emacs-jedi-eldoc
emacs-konoha-mode
emacs-literate-coffee-mode
emacs-ltsv
emacs-octicons
emacs-perl-utils
emacs-popup-complete
emacs-quickrun
emacs-reverse-theme
emacs-smeargle
emacs-sound-wav
emacs-sourcemap
emacs-splitjoin
emacs-terraform-mode
emacs-test-more
emacs-tora-mode
emacs-zoom-window
"

transfer() {
    pkg=$1
    dst=$2; [ -z "$dst" ] && dst=emacsorphanage
    echo ">>> Transfering $pkg to $dst"
    curl -X POST \
         -H "Authorization: token $TOKEN" \
         -d "{ \"new_owner\": \"$dst\" }" \
         "https://api.github.com/repos/syohex/$pkg/transfer"
    echo
    sleep 2
}

for p in $PACKAGES; do transfer $p; done

transfer cpp-auto-include tarsius
```

**Comment by syohex** [comment]
Done. Thank you very much

**Comment by jcs090218** [comment]
🎉  I think we can close this issue now?

**Comment by tarsius** [comment]
> Done. Thank you very much

Thank you too!

> I think we can close this issue?

There's quite a bit of work ahead of me that I would like to keep track of.

**Comment by tarsius** [comment]
@syohex Thanks so much!! :heart:

----

I overlooked one package/repository: https://github.com/syohex/emacs-company-jedi. Please transfer that one too.

**Comment by syohex** [comment]
@tarsius Done

**Comment by tarsius** [comment]
Thanks again!

If you stumble over any other packages, feel free to transfer them to the `emacsorphanage` or once I have revoked your membership to my personal account `tarsius`.

But I think we have now covered at least all packages that are available from Melpa.

(If you want to remain a maintainer of these repositories, then please let me know now, before you remove those permissions.)

**Comment by syohex** [comment]
> (If you want to remain a maintainer of these repositories, then please let me know now, before I revoke those access permissions.)

Please revoke all my permissions of those repositories.

**Comment by tarsius** [comment]
> Please revoke all my permissions of those repositories.

Done.

**Comment by tarsius** [comment]
> I could see helping with any of the `git-*`, `smeargle`, `dired-k`, maybe `anzu` and `company-jedi`.

@gonewest818 I have invited you to the organization and will give you access to these repositories once you have accepted.

**Comment by gonewest818** [comment]
thank you, I've accepted.

**Comment by tarsius** [comment]
I've given you write access to these repositories.

**Comment by jcs090218** [comment]
> I am still waiting for @syohex to reply. Anyway, I am interested maintaining these packages.

> * [zoom-window](https://github.com/syohex/emacs-zoom-window)
> * [fontawesome](https://github.com/syohex/emacs-fontawesome)
> * [sound-wav](https://github.com/syohex/emacs-sound-wav)
> * [counsel-gtags](https://github.com/syohex/emacs-counsel-gtags)
> * [helm-themes](https://github.com/syohex/emacs-helm-themes)
> * [helm-gtags](https://github.com/syohex/emacs-helm-gtags)
> * [helm-ag](https://github.com/syohex/emacs-helm-ag)

May I have the access to the repositories I mentioned above? Thanks! :D

**Comment by conao3** [comment]
From Busfactor's point of view, I think it's risky that only @tarsius has access to packages.
@purcell has full access to `emacsorphanage`, but seems to he has no time to work on `emacsorphanage`.
I don't think there is any problem if there is more than one maintainer for a certain package, but if you don't like more than one maintainer, I would like to do maintenance on the following package which the maintainer currently doesn't have.
(I have removed package related `helm` and `autocomplete` from the list because I each use alternative packages and may not be able to provide sufficient assistance.)
- codic
- easy-highlight
- emamux
- emamux-ruby-test
- evil-anzu
- evil-textobj-line
- go-add-tags
- go-direx
- go-eldoc
- go-impl
- gom-mode
- hcl-mode
- import-popwin
- jedi-eldoc
- konoha-mode
- literate-coffee-mode
- ltsv
- octicons
- perl-utils
- popup-complete
- quickrun
- reverse-theme
- sourcemap
- splitjoin
- terraform-mode
- test-more
- tora-mode

**Comment by tarsius** [comment]
@purcell and I have full access, that's good enough.

I do not intend to give individual contributors access to large number of repositories. The plan is rather to give each person access to the repositories they are actually interested in and have the time to contribute to in a meaningful way. You already have access to half a dozen packages, which together have more than 50 open issues. Wouldn't it be better to improve some of these packages before moving on to something else?

If you want access to another two or three packages, then I would be happy to grant that. But you should handpick repositories you actually want to work on.

**Comment by tarsius** [comment]
@conao3 I would also like to ask you to request my review after you have improved doc-strings. I am under the impression that you often blindly follow the recommendation of `checkdoc`, and not always for the better. For example:

```diff
 (defun ov-placeholder (ov-or-ovs)
-  "Set a placeholder feature for an overlay or a list of overlays.
+  "Set a placeholder feature for OV-OR-OVS or a list of overlays.
Each overlay deletes its string and overlay, when it is modified."
```

is not an improvement. Sure `checkdoc` is right in telling you that every argument should be mentioned by name. But *not* doing that is better than breaking the documentation as you have done here. "OV-OR-OVS" stands for "a [single] overlay or a list of overlays" so the doc-string now says "an overlay or a list of overlays or a list of overlays". Your English isn't so good and that is fine and you will get better over time, but I think that this means that you should request some help when making such changes". Thanks!

**Comment by conao3** [comment]
In special cases, if you have a better docstring suggestion, please do it in PR.
And thank you for your comment on `emacsorphanage` management. Because I've never heard of that before.
I think there are various ideas, but just in my opinion, the two of you are not enough.
I hope it doesn't end up like `core-js`, but if you think so, I will. Thanks.
