### ISSUE TITLE
(m)elpa incompatible packages (see#2824)

### ISSUE THREAD

**Issue by Reissner** [melpa/melpa#6719]
I have emacs 26.3 and the following packages cannot be installed because incompatible. 
 I personally only need the markdown mode but others may have more problems. 
I dont know whether to remove or to fix. 

first is 
aa-edit-mode       0.0.2         incompat   melpa-s... Major mode for editing AA(S_JIS Art) and .mlt file
last is 
zel                0.1.2         incompat   melpa-s... Access frecent files easily

**Comment by purcell** [comment]
The output is truncated, but those appear to say "melpa-stable". You cannot generally expect to be able to install packages using *only* MELPA stable. Instead, enable both MELPA and MELPA Stable and use `package-archive-priorities` and `package-pinned-packages` to prefer the MELPA Stable packages where desired.
