### ISSUE TITLE
auctex installation fails

### ISSUE THREAD

**Issue by Reissner** [melpa/melpa#6720]
I have emacs 26.3, new. 
when i try to install auctex from melpa, it offers 12.2.0 
During installation i receive message 
   Contacting host: elpa.gnu.org:433 
and question 
   Buffer " * http elpa.gnu.org:443*" has a running process; kill it? 
No is no choice since then nothing seems to be installed. 
Yes is ok but then auctex does not work at all: not loaded when loading .tex files. 
What went wrong?? 
Is it really http, what means *, what about the blanks, is it elpa or melpa??? 

Thanks for help.

**Comment by Reissner** [comment]
Edit: Ah another point: auctex is an available obsolete package.. 
well this is wrong indeed but may be an explanation that it is not loaded.

**Comment by purcell** [comment]
We don't host an auctex package, so this must be ELPA, I believe.
