### ISSUE TITLE
Add branch protection rule to master

### ISSUE THREAD

**Issue by riscy** [melpa/melpa#6729]
I believe `master` currently has no branch protection rules, which means someone with push access could accidentally force push to it (correct me if I'm wrong).  Can we add an empty rule to prevent this? (i.e. Settings -> Branches -> Add Rule).  Nothing additional would need to be checked off, just the rule created.

**Comment by purcell** [comment]
Yeah, that's funny: I just added a similar rule to the `ledger-mode` repo today before seeing this.

**Comment by purcell** [comment]
Done now, thanks for the prod.

**Comment by riscy** [comment]
Thanks!
