### ISSUE TITLE
Unsigned file ‘archive-contents’ at https://stable.melpa.org/packages/

### ISSUE THREAD

**Issue by pvetter** [melpa/melpa#6766]
My .emacs file has been Customized to include
 '(package-archives
   (quote
    (("gnu" . "https://elpa.gnu.org/packages/")
     ("melpa-stable" . "https://stable.melpa.org/packages/"))))

When I try to M-x package-refresh-contents, it fails with
Unsigned file ‘archive-contents’ at https://stable.melpa.org/packages/

How can I copy text out of the debugger? 
The debugger seems to make emacs rapidly occupy memory until it is forced exit with kill -9 $PID
Debugger seemed to hang emacs so I attach a screenshot:

![emacs-Debugger-MELPA-Screenshot_20200320_170144](https://user-images.githubusercontent.com/3491876/77150492-f980da80-6ace-11ea-821a-08d5dd2628d6.png)

Thank you all.

**Comment by pvetter** [comment]
![emacs-debug-MELPA-Large](https://user-images.githubusercontent.com/3491876/77151328-a3149b80-6ad0-11ea-9ce8-cda8fd2ac3cc.png)

**Comment by milkypostman** [comment]
Emacs version?

**Comment by pvetter** [comment]
emacs 26.3  on:
1. Fedora 30   x86_64   emacs-26.3-1.fc30.src.rpm  
2. Fedora 30  self-compiled emacs.
3. Someone else tried it with same result with Ubuntu 19.10
26.3 build 2 x86_64-pc-linux-gnu GTK+ 3.24.11

Does it work for you?

**Comment by pvetter** [comment]
Also with   melpa.org/packages
Failed to download ‘melpa’ archive.

**Comment by purcell** [comment]
Have you changed `package-check-signature` from the default of `'allow-unsigned`? We don't sign our packages, so you can't set your Emacs to be strict about it.

**Comment by pvetter** [comment]
@purcell wrote:
> We don't sign our packages, so you can't set your Emacs to be strict about it.

1. MELPA does not even sign the archive-contents list?
2. Can MELPA contributors sign their packages?
3. Does ELPA sign its packages and does package-check-signature 'allow-unsigned' apply to both ELPA and MELPA?

**Comment by tarsius** [comment]
I am closing this issue because the original question (paraphrasing:) "what to do about this backtrace" has been addressed.

There are more people who would like us to sign more things and there are a few open issues about such topics, see https://github.com/melpa/melpa/issues?q=is%3Aissue+is%3Aopen+sign.
