### ISSUE TITLE
Travis check on recipe name and github name inconsistent

### ISSUE THREAD

**Issue by mtekman** [melpa/melpa#6816]
I performed the following name changes on two of my PR's

| Package | Melpa Commit  | Name (Before → Now) | Travis Passes |
|-------------|----------------|------------------------------------|-------------------|
| mtekman/elisp-depmap | [elisp-depmap](https://github.com/melpa/melpa/pull/6791/commits/1cc2fcf6dd16a4d2dc84b87da9e509b25dd21953) | package-map → elisp-depmap | [Yes](https://travis-ci.org/github/melpa/melpa/builds/672239304) |
| mtekman/org-treeusage | [org-treeusage](https://github.com/melpa/melpa/pull/6811/commits/a03a4543819aec47261af31f4361ccbea847eaee) | org-density → org-treeusage | [No](https://travis-ci.org/github/melpa/melpa/builds/672237648) |

I find this behaviour a little strange since its the same operation on both PRs.

**Comment by purcell** [comment]
Interesting. The first one fails, but doesn't exit with a non-zero code.

**Comment by mtekman** [comment]
Ah so - unrelated to the bug: should I then close both my PR's and reopen them under the correct branch names?

**Comment by purcell** [comment]
There's usually no need to close and reopen PRs: instead, amend the commits, and force-push them to update the existing PRs. Post comments on the PRs to indicate that's done. Thanks!
