### ISSUE TITLE
Packaging best practices for extensions

### ISSUE THREAD

**Issue by jethrokuan** [melpa/melpa#6833]
Hi MELPA team,

I'm the maintainer for [org-roam](https://github.com/jethrokuan/org-roam), and recently there have been a few PRs extending org-roam functionality for integration with other packages, such as `helm-bibtex`, and `org-ref`. Here are the PRs:

https://github.com/jethrokuan/org-roam/pull/437
https://github.com/jethrokuan/org-roam/pull/415

I'm at a loss as to how to get them packaged and shipped properly. Here are the options I've considered:

# 1. Shipping them with `org-roam` directly

This means including them as per normal in org-roam. The issue with this is the extension packages depend on additional packages, which are otherwise not necessary to pull in. 

# 2. Shipping them under a new package `org-roam-contrib`

This is the current approach i'm considering: placing all these extension packages into a `contrib` folder, and packaging it as a new package.

The downside, of course, is that the contrib package will be filled with new dependencies for every extension. 

# 3. Shipping them as separate packages per extension

This seems like the most straightforward method, but would lead to a proliferation of packages and more maintenance work for MELPA.

What do you think? What's the right approach here?

Regards,
Jethro

**Comment by milkypostman** [comment]
I don't think that #3 is all that much more work for MELPA maintainers. Typically package metadata (repos, paths, etc.) don't change that often so there isn't a need to update the recipe. If you go this route, it would be best to have them in their own repositories, not in the `org-roam` repo. But that is probably OK. It just saves us space not having to pull the larger repo.

I tend to think that individual repos is actually the easiest to maintain and minimizes external dependencies. @purcell will have more insight into this than me but I would guess he will concur ;)

**Comment by tarsius** [comment]
> If you go this route, it would be best to have them in their own repositories, not in the `org-roam` repo. But that is probably OK. It just saves us space not having to pull the larger repo.

I agree that having separate repositories would be best and that using a shared repository instead is okay as well, but I would like to mention another IMO more important reason why using separate repositories is nicer: It helps users who *don't* us `package.el` but install packages by cloning the respective git repositories. These users don't want any compile errors resulting from unsatisfied dependencies of the various integration libraries in the same repository.

**Comment by jethrokuan** [comment]
Thank you for your comments, we've decided to go with option 3.
