### ISSUE TITLE
info-buffer:  Package's github page returns a 404 error

### ISSUE THREAD

**Issue by dieter-wilhelm** [melpa/melpa#6860]
info-buffer:  Package's github page returns a 404 error

https://melpa.org/#/info-buffer

**Comment by purcell** [comment]
Works for me. If you're still seeing an issue, please provide details of browser etc.

**Comment by dieter-wilhelm** [comment]
I'm sorry for the false alarm, there must have be a maintenance "blackout"...

Thanks and please close this issue.
