### ISSUE TITLE
all the nlinums broke

### ISSUE THREAD

**Issue by mcandre** [melpa/melpa#6868]
The default linum getup is pretty piss, but at least nlinum used to help out back in the day. Now, my machine can't even install any of the linum MELPA packages. Are these dead or is it just my network config?

**Comment by riscy** [comment]
[nlinum is on ELPA](https://elpa.gnu.org/packages/nlinum.html) and not MELPA, if that's one of the packages you're having trouble with (which specific packages are you having trouble with? :)
