### ISSUE TITLE
Getting Started page is not a getting started page

### ISSUE THREAD

**Issue by rnkn** [melpa/melpa#6906]
The instructions on the [Getting Started](https://stable.melpa.org/#/getting-started) page are inappropriate for someone getting started with Emacs packages. It is very unlikely that a user who is getting started installing Emacs packages already understands Emacs Lisp, and so presenting such a user with blocks of Emacs Lisp code is asking them to get started with something they have little to no chance of understanding.

Also, it sows the seeds of the bad habit of pasting random Lisp into one's init rather than using Emacs's builtin `customize` interface, and so bypasses Emacs packages' error checking, which, for a new user, is asking for trouble. A user who is getting started with Emacs ought to only be adding code to their init file once they first understand that code, and have reached the limitations of Emacs's builtin option system.

The instructions also ask the user to add code that (they likely do not know) retrieves additional remote code — which now returns a 404.

I fully understand the [curse of knowledge](https://en.wikipedia.org/wiki/Curse_of_knowledge) will be at play here, so let's [compensate by overcompensating](https://sivers.org/compensate) — let's make these instructions utterly mind-numbingly simple, e.g.:

> To enable installation of packages from MELPA you will need to add it as a [Package Archive](https://www.gnu.org/software/emacs/manual/html_node/emacs/Package-Installation.html#Package-Installation). To do this type `M-x customize-option RET package-archives RET`.
>
> This will present a screen to customize the user option `package-archives`. Insert an entry with an archive name of `melpa` and URL of `https://melpa.org/packages/`. Select *Apply and Save* when you are done.

&c.

I'm happy to submit a PR?

**Comment by milkypostman** [comment]
yes a PR would be great. but I would prefer having a new section above the
current (with appropriate revisions to the latter parts as-needed) that
talks about using customize to set thus up. like having a beginner level
install, then a secondary one.

although with problems of SSL I do worry that it may not work for some
users. that is why the snippet is robust

**Comment by rnkn** [comment]
Excellent. I'll have a PR within the next week.

**Comment by tarsius** [comment]
@rnkn Do you still plan to do this?

> although with problems of SSL

By now the code no longer addresses this and we instead have two sentences talking about it.

**Comment by rnkn** [comment]
Well that year sure flew by! Sorry for the delay, I'd written a draft then accidentally dropped it as a git stash. Ugh.

Instead of a PR, I'll add this as page on the wiki, then everyone can change around wording/formatting to their heart's content, and let you guys do the final convert to HTML.

**Comment by rnkn** [comment]
Hey so I keep thinking I will get to this in some imaginary future when a bunch of other things don't take precedence. I'm closing now because I don't think that day will arrive.
