### ISSUE TITLE
Show links from `Homepage:' headers on individual package pages

### ISSUE THREAD

**Issue by cpitclaudel** [melpa/melpa#6914]
Hi there,

This is a follow up to an emacs-devel thread: https://lists.gnu.org/archive/html/emacs-devel/2020-05/msg02470.html

Currently, package pages do not show the homepage declared by the package in its header; instead, they show a link to the repo.  It would be nice to show both.

For example, this page: https://melpa.org/#/emms would point to https://www.gnu.org/software/emms/, as specified by the package's `;; Homepage: http://www.gnu.org/software/emms/` header

**Comment by purcell** [comment]
Done. Should get applied in the next build.

**Comment by cpitclaudel** [comment]
:clap: :+1:

**Comment by purcell** [comment]
Hey @milkypostman, I was tweeting about having fixed this (which is a duplicate of #5285, btw), but the changes don't appear to have propagated to the MELPA site as part of the regular build cycle. Not quite sure how that is supposed to work: any pointers?

**Comment by milkypostman** [comment]
its showing up on mine. is it stale js on your machine?

**Comment by milkypostman** [comment]
@purcell ^^^

**Comment by purcell** [comment]
Oh yeah... weird! I force-reloaded and it's okay. The cache headers look fine... I wonder if the last-modified date in April for the containing HTML page somehow causes the browser to use locally-cached JS. Sorry for the false alarm, anyway.
