### ISSUE TITLE
Unable to see melpa package

### ISSUE THREAD

**Issue by mtekman** [melpa/melpa#6919]
Hello, I am unable to see the package `org-treeusage` in melpa, despite the fact that it was merged into master a while back:

* https://github.com/melpa/melpa/blob/master/recipes/org-treeusage

and that the respository for it still exists:

* https://github.com/mtekman/org-treeusage.el

Issue originally reported by @michaelsjackson  https://github.com/mtekman/org-treeusage.el/issues/9

**Comment by michaelsjackson** [comment]
Maybe it has something to do with the .el project ending?  Anyway, here I still can not see that function.

**Comment by milkypostman** [comment]
I'll try to take a look later tonight.

**Comment by milkypostman** [comment]
the package is just called `org-treeusage` in melpa, and its there and I can see it. and I see it when I do `package-list-packages`. so I'm not sure. can you explain more what problem you're seeing?

**Comment by michaelsjackson** [comment]
The point is, after installation, can you see the function org-treeusage-mode ? Here I can not.

**Comment by milkypostman** [comment]
That is a package issue I don’t think it’s melpa related. Likely a function
is not correctly tagged with auto loads. Please reach out to the author
unless you are the author. In which case look at the generated -autoloads
file after installing and see why it’s missing.

I just logged off for the night but will see what I can do tomorrow.

**Comment by mtekman** [comment]
I am the author, and the function being called is `org-treeusage-mode` which is a minor mode.

From what I know about elisp packages, only interactive functions need to be autoloaded -- and minor-modes dont(?)

Also, I just want to point out that I am not seeing @michaelsjackson behaviour on my own machine.

**Comment by michaelsjackson** [comment]
No problem, thanks to both of you for your help, one day, I will solve it, it does not hurry now.

**Comment by mtekman** [comment]
If you share your emacs config with me, I would be quite happy to debug

**Comment by milkypostman** [comment]
Pretty sure You need the autoload tag before the minor mode definition.

There are functions you can run locally to test this but I don’t know
offhand.

**Comment by michaelsjackson** [comment]
I did not send anything yet, as my config is huuge, and before sending I would need to clean it up first.

Just checked -autoloads.el file, indeed the three functions I can see are in -autoloads, I can see exactly those and nothing else.

How many functions are in your org-treeusage-autoloads.el listed?  Also just 3 (cycle-modeforware, cycle-modebackward, cycle-cycletype) or more?

**Comment by mtekman** [comment]
@milkypostman  Good to know, I will add and test.
@michaelsjackson  There should only be those 3, but I likely need to autoload my minor mode too.
