### ISSUE TITLE
File not in package

### ISSUE THREAD

**Issue by tomoda** [melpa/melpa#6952]
In Emacs, I want to get the lsp-java package. Consequently, in Emacs I do:

M-x package-install [RET] lsp-java [RET].

After a short while I get this message:

Contacting host: melpa.milkbox.net:443
package-install-from-archive: https://melpa.milkbox.net/packages/ace-window-20200311.1025.el: Not found
Making completion list... [2 times]

Checking at Melpa I see the file not found is indeed part of the package. 
Repeating the process returns the same results.
I wonder what I need to do, to also get "ace-window-20200311.1025.el" with the downloaded package?

**Comment by milkypostman** [comment]
1. please update your settings to use `melpa.org`.
2. I think you need to sync up and pull the new metadata. calling `package-list-packages`. https://melpa.org/packages/ace-window-20200606.1259.el is there.

**Comment by tomoda** [comment]
Hi Donald Curtis,

Thank you very much for your quick reply!

Best regards

Jörg
