### ISSUE TITLE
HTTP always redirects to HTTPS / how to get melpa working on Win 

### ISSUE THREAD

**Issue by return42** [melpa/melpa#7008]
I'm using emacs on MS-Win and do not have TLS. On [getting started page](https://stable.melpa.org/#/getting-started) there is the hint::

````
Note: There are some problems using the https location with Emacs on Windows.
There is currently no known easy fix for this. You can still use MELPA by using the
non-SSL location by replacing https with http. 
````

This has worked over years for me. I made my last update in Feb this year. Today I wanted to update my packages and relaized, that this HTTP url does no longer exists / **HTTP always redirects to HTTPS** (see code block below).

**Do I have a chance to get melpa working for Win without TLS?**

**Thanks for all hints!**

````
$ curl -v http://stable.melpa.org/
*   Trying 178.128.185.1:80...
* TCP_NODELAY set
* Connected to stable.melpa.org (178.128.185.1) port 80 (#0)
> GET / HTTP/1.1
> Host: stable.melpa.org
> User-Agent: curl/7.65.3
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 301 Moved Permanently
< Server: nginx
< Date: Mon, 06 Jul 2020 16:34:28 GMT
< Content-Type: text/html
< Content-Length: 162
< Connection: keep-alive
< Location: https://stable.melpa.org/
< 
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
````

**Comment by smoeding** [comment]
Looks like MELPA decided to enforce https access only...

Unfortunately this also seems to have an impact for non-Windows users. I can't access MELPA any more using a corporate proxy.

I suspect this is due to Emacs Bug [11788](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=11788) (fixed in 26.1, not fixed in 25.2). It seems `url-http.el` doesn't use the proxy correctly when talking https.

**Comment by return42** [comment]
> I suspect this is due to Emacs Bug 11788 

I think "proxy" is a different problem .. at least from my point (I changed the title to be more precise).

Without the old HTTP workaround, **emacs is no longer usable on Win if you need packages from melpa.**

I'm asking for a solution of this problem, this could be the old HTTP workaround or better a solution to use TLS on Win in emacs.

````
gnutls.c: [1] (Emacs) GnuTLS library not found
Could not create connection to stable.melpa.org:443
````

When I install emacs on Win, I also install git which has working TLS, so my question is; is there a workaround to use TLS from git in emacs? .. or what can I do?

**Comment by smoeding** [comment]
Sorry for hijacking your issue...

My point is that I supect MELPA introduced the forced redirect just recently and this broke multiple things. Using Emacs on Windows being one of it.

**Comment by return42** [comment]
:facepalm:  I located the problem, it is sitting in front of the desktop.

In emacs-26.3 gnutls works also on MS-Win .. the problem was, that I did installed the _no-dep_ [packages](https://ftp.gnu.org/gnu/emacs/windows/emacs-26/) where GnuTLS library is not in .. I'm a idiot / sorry for the noise.

**Comment by milkypostman** [comment]
It happens. Probably good for me to know to ask this next time. Although
I’m not quite sure what it all means ;)
