### ISSUE TITLE
package "binder": advice on included package tutorial?

### ISSUE THREAD

**Issue by rnkn** [melpa/melpa#7041]
Hello,

I'm beginning the steps to add package https://github.com/rnkn/binder to MELPA. The package is a global minor mode for facilitating working with large multi-file writing projects (e.g. novels, screenplays). It stores all project data in a directory `.binder.el` file à la `.dir-locals.el`.

Given the package is somewhat complicated and aimed at non-technical users, I've included a tutorial binder project as part of the package. This project includes the top-level `.binder.el` file, as well as txt files (and a jpg) in a directory called `tutorial`.

I'm seeking advice with how to proceed with this. The immediate issue is that `package-build-current-recipe` treats the tutorial lisp file as program code and thus fails.

More generally, I'd like the new user first installing the package to have access to the tutorial. On the other hand, I'm unsure that the tutorial should stick around as part of the package forevermore. Something I'm considering is greatly simplifying the tutorial and building it into the main program, which would create a small tutorial project with `M-x binder-tutorial` or similar. But then this sacrifices documentation.

Thoughts?

**Comment by gcentauri** [comment]
I'm not a package expert by any means, but I just saw this and have a few thoughts...

  - check out the https://github.com/abo-abo/pamparam package. its got some demos installed in its docs directory which is included with the package. granted, its a bit different from your situation where the `.binder.el` file is top level in your package.
  - write a command that generates or copies the `.binder.el` file which a new user would run to "install" it. this command could also pull something from the net, similar to how `all-the-icons` has a command to install fonts.

hope this helps a bit! your binder package looks neat!

**Comment by rnkn** [comment]
@gcentauri thanks for feedback. I agree and think implementing as `binder-tutorial` command to generate the content is the way to go.

**Comment by gcentauri** [comment]
@rnkn - you could still have the `tutorial` directory as is, i think you could just include it as files for the recipe, they would get installed along with the package. then perhaps rename `.binder.el` to something like `binder-tutorial` and include that as well.  the command could just rename that `binder-tutorial` file to `.binder.el` once it is installed. seems like the main issue is getting around the build recipe error? i guess the elisp for the `.binder.el` file is simple enough it could live in the main code as well and just be written to a file like you said.
