### ISSUE TITLE
python-switch-quotes: cycle between ' and " quotes in python strings

### ISSUE THREAD

**Issue by holtzermann17** [melpa/melpa#7069]
The headline `cycle between ' and " quotes in python strings` breaks fontification in the \*Packages\* buffer.

Should it instead say `cycle between single and double quotes in python strings`?

**Comment by tarsius** [comment]
Yes. Even if `package.el` could and would be taught to handle this better, then this change should still be made for the benefit of older versions of `package.cl`, which will continue to be in use for hears. You should probably talk about this with the package author as well as the Emacs/`package.el` maintainers.
