### ISSUE TITLE
Failed to download ‘melpa’ archive: (file-error "https://stable.melpa.org/archive-contents" "Not found")

### ISSUE THREAD

**Issue by bjohas** [melpa/melpa#7125]
Hello all,

I'm getting ths error:
```
Debugger entered--Lisp error: (file-error "https://stable.melpa.org/archive-contents" "Not found")
  signal(file-error ("https://stable.melpa.org/archive-contents" "Not found"))
  package--download-one-archive(("melpa" . "https://stable.melpa.org/") "archive-contents" nil)
  package--download-and-read-archives(nil)
  package-refresh-contents()
  funcall-interactively(package-refresh-contents)
  call-interactively(package-refresh-contents record nil)
  command-execute(package-refresh-contents record)
  execute-extended-command(nil "package-refresh-contents" "p")
  funcall-interactively(execute-extended-command nil "package-refresh-contents" "p")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```
with this config
```
(require 'package)
(toggle-debug-on-error)
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/") t)
(package-initialize)
...
```
On https://melpa.org/archive-contents, using a browser, I get a 404.

Any thoughts? Is the site actually down or is there an issue with the config?

Many thanks!

**Comment by wongjoel** [comment]
I found a workaround by adding `packages/` to the end of the url so that it goes to https://melpa.org/packages/archive-contents instead.
```
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(package-initialize)
```
Not sure what the intended behaviour is though, as the Getting Started instructions on the website doesn't have `packages/` appended to the url

**Comment by bjohas** [comment]
Hi @wongjoel  - thank you so much, that is really appreciated!

So it may be an issue with the instructions or maybe something on the site has changed - maybe somebody will be able to address that.

Thanks again!

**Comment by purcell** [comment]
Sorry, this was broken by a misguided PR four days ago.
