### ISSUE TITLE
Helm is stalled, what's next?

### ISSUE THREAD

**Issue by jcs090218** [melpa/melpa#7126]
Just saw https://github.com/emacs-helm/helm/issues/2386.

Helm is one of the most important package in Emacs Community. And many users and packages are depend on it. I think is worth to brought up and discuss the next step to helm? Maybe ask for more maintainers to join, etc. 😕

**Comment by conao3** [comment]
Absolutely agree.
With helm not being updated, helm related packages have to be dealt with in a monkey patch, which is a very big impact.

Anyway, I can't think fork it and discard the current helm-related 220 packages!. ([MELPA - helm](https://melpa.org/#/?q=helm))
To prevent this problem, there is a `emacs-helm` team and we have emacsorphanage to get help from Elisp community.
I sincerely hope that we can move in a better direction...

**Comment by purcell** [comment]
As @conao3 says, there is a github organisation with 12 members to handle this, and discussion should take place there, not here.
