### ISSUE TITLE
Split pull request template's check box on build and install into two

### ISSUE THREAD

**Issue by sean-hut** [melpa/melpa#7202]
Proposal:
Split the "I've built and installed the package using the instructions
in CONTRIBUTING.org" check box in the pull request template into
two check boxes.
- "I've built the package using the instructions in CONTRIBUTING.org"
- "I've installed the package using the instructions in CONTRIBUTING.org"

Motivating example:
Pull request #7189.

Benefit:
Allow contributors to more easily and clearly communicate what steps
were successful.

**Comment by tarsius** [comment]
IMO it is better to keep things as is.

Our goal with these check boxes is to get contributors to actually do these things. Giving them greater granularity when telling us which things they *didn't do* isn't really useful. If someone is able to build but not install their package, then that's probably something they should talk about it in more detail than by simply checking or not checking a check box.
