### ISSUE TITLE
google-c-style receipt uses wrong branch name

### ISSUE THREAD

**Issue by blahgeek** [melpa/melpa#7204]
The default branch of https://github.com/google/styleguide is gh-pages. There's no *.el in master branch.

**Comment by riscy** [comment]
It looks like that repo has set `gh-pages` to its default branch (and `master` to a non-default branch).  MELPA appears to be [indexing it properly](https://melpa.org/#/google-c-style) as far as I can tell, but is there another issue?

**Comment by blahgeek** [comment]
Thanks for your reply. I am using straight.el to install packages. It seem that by default it uses the master branch. Maybe it's an issue for straight.el. I will check again later to verify.

**Comment by progfolio** [comment]
Re: straight.el 

You can override w the recipe's `:branch` keyword.
Also see https://github.com/raxod502/straight.el/pull/543

**Comment by blahgeek** [comment]
Thanks for the link. It seems that it's an issue for straight.el indeed. I'm closing this issue.
