### ISSUE TITLE
List of archived package repositories

### ISSUE THREAD

**Issue by tarsius** [melpa/melpa#7225]
The github repositories of these packages have been archived:

- [x] [better-defaults](https://github.com/technomancy/better-defaults) by @technomancy
- [x] ~~[chicken-scheme](https://github.com/dleslie/chicken-scheme.el)~~ by @dleslie
- [x] [company-org-roam](https://github.com/org-roam/company-org-roam) by @org-roam
- [x] ~~[flymake-cppcheck](https://github.com/senda-akiha/flymake-cppcheck)~~ by @senda-akiha
- [x] ~~[flymake-google-cpplint](https://github.com/senda-akiha/flymake-google-cpplint)~~ by @senda-akiha
- [ ] [flymake-phpcs](https://github.com/senda-akiha/flymake-phpcs) by @senda-akiha (required by drupal-mode) pending https://github.com/arnested/drupal-mode/issues/83
- [x] ~~[ghc](https://github.com/DanielG/ghc-mod)~~ by @DanielG
- [x] [github-issues](https://github.com/inkel/github-issues.el) by @inkel ~~(required by git-commit-insert-issue)~~
- [ ] [helm-addressbook](https://github.com/emacs-helm/helm-addressbook) by @emacs-helm
- [ ] [helm-apt](https://github.com/emacs-helm/helm-apt) by @emacs-helm
- [ ] [helm-elscreen](https://github.com/emacs-helm/helm-elscreen) by @emacs-helm
- [ ] [helm-emms](https://github.com/emacs-helm/helm-emms) by @emacs-helm
- [ ] [helm-firefox](https://github.com/emacs-helm/helm-firefox) by @emacs-helm (required by org-linkany)
- [ ] [helm-ls-git](https://github.com/emacs-helm/helm-ls-git) by @emacs-helm (required by helm)
- [ ] [helm-ls-hg](https://github.com/emacs-helm/helm-ls-hg) by @emacs-helm (required by helm)
- [ ] [helm-w3m](https://github.com/emacs-helm/helm-w3m) by @emacs-helm (required by org-linkany)
- [x] [ido-complete-space-or-hyphen](https://github.com/doitian/ido-complete-space-or-hyphen) by @doitian
- [x] [image+](https://github.com/mhayashi1120/Emacs-imagex) by @mhayashi1120 (required by evil-collection)
- [x] [intero](https://github.com/commercialhaskell/intero) by @chrisdone (required by smart-jump)
- [x] [ioccur](https://github.com/thierryvolpiatto/ioccur) by @thierryvolpiatto
- [x] [isolate](https://github.com/casouri/isolate) by @casouri
- [x] [iy-go-to-char](https://github.com/doitian/iy-go-to-char) by @doitian
- [x] ~~[love-minor-mode](https://github.com/ejmr/love-minor-mode)~~ by @ejmr
- [x] [lsp-scala](https://github.com/rossabaker/lsp-scala) by @rossabaker
- [x] [o-blog](https://github.com/renard/o-blog) by @renard
- [x] ~~[php-auto-yasnippets](https://github.com/emacs-php/php-auto-yasnippets)~~ by @emacs-php
- [x] [phpcbf](https://github.com/nishimaki10/emacs-phpcbf) by @nishimaki10
- [x] ~~[projectile-direnv](https://github.com/christianromney/projectile-direnv)~~ by @christianromney
- [x] ~~[rsense](https://github.com/m2ym/rsense)~~ by @m2ym
- [x] [scpaste](https://github.com/technomancy/scpaste) by @technomancy

----

- [x] means action taken after feedback was received
- [x] ~~strike-through~~ means removed without feedback [Note that some projects had an explicit note in the readme. So some of the affected maintainers might have replied because they felt I should have taken that into account more.]

----

We should probably remove most of these packages from Melpa. I am summoning the maintainers in case they would like to comment and/or submit a pull-request themselves to remove the respective package(s).

I have already moved a bit more than half of these packages from the Emacsmirror to the Emacsattic, leaving out those with reverse dependencies and those from the `emacs-helm` organization.

**Comment by tarsius** [comment]
tarsius mentioned on gitlab: https://gitlab.com/emacs-stuff/git-commit-insert-issue/-/issues/19 :grin:

**Comment by renard** [comment]
As mentioned on o-blog home page this project is unmaintained and archived for historical  purposes. You can remove it from MELPA.

**Comment by inkel** [comment]
> [ ] [github-issues](https://github.com/inkel/github-issues.el) by @inkel (required by git-commit-insert-issue)

Hi! You can definitely remove `github-issues` from the listing, I for sure not plan to maintain it in the near future. I don't know if that would be an issue for `git-commit-insert-issue`, though.

Thanks for the ping, @tarsius. I had completely forgotten about this little project and your mention brought a smile to my face 😺

**Comment by DarwinAwardWinner** [comment]
I'd be willing to take over maintenance of ido-complete-space-or-hyphen. On the MELPA side you would just have to change the URL to https://github.com/DarwinAwardWinner/ido-complete-space-or-hyphen.

**Comment by tarsius** [comment]
> I'd be willing to take over maintenance of ido-complete-space-or-hyphen.

Great. You would be an ideal maintainer, considering you wrote https://github.com/DarwinAwardWinner/ido-completing-read-plus.

@doitian are you okay with that as well?

**Comment by technomancy** [comment]
Both of the repositories for the projects I maintain have links to the new locations if you want to update them, but if not that's fine too.

**Comment by doitian** [comment]
> > I'd be willing to take over maintenance of ido-complete-space-or-hyphen.
> 
> 
> 
> Great. You would be an ideal maintainer, considering you wrote https://github.com/DarwinAwardWinner/ido-completing-read-plus.
> 
> 
> 
> @doitian are you okay with that as well?

Sure

**Comment by tarsius** [comment]
@doitian Thanks! One more thing: it would best if you could transfer your repository to @DarwinAwardWinner, who would have to delete his fork first. That way issue/pr numbers are not reset to 1.

**Comment by tarsius** [comment]
> Both of the repositories for the projects I maintain have links to the new locations if you want to update them, but if not that's fine too.

Done. Thanks @technomancy.

**Comment by tarsius** [comment]
`company-org-roam` has been deprecated see https://github.com/melpa/melpa/pull/7369.

**Comment by tarsius** [comment]
@inkel Thanks and you are welcome. :grinning:

**Comment by inkel** [comment]
Thank you @tarsius for taking care of it.

**Comment by DarwinAwardWinner** [comment]
> @doitian Thanks! One more thing: it would best if you could transfer your repository to @DarwinAwardWinner, who would have to delete his fork first. That way issue/pr numbers are not reset to 1.

I have deleted my repo, so I'm ready to "receive" the original repo.

**Comment by tarsius** [comment]
> I'm ready to "receive" the original repo.

It appears the repository has been received. :grinning:

**Comment by tarsius** [comment]
Done except for `flymake-phpcs` and all the `helm-*`. I'll open a new issue about the Helm packages eventually.
