### ISSUE TITLE
Putting ELisp files in 'lisp' directory?

### ISSUE THREAD

**Issue by fniessen** [melpa/melpa#7242]
Dear Milkypostman,

Can't easily find your email address, so using this to ask a question: can I put my ELisp files in a 'lisp' directory in the root directory of my project.  I just did that for Emacs-Leuven (for making it easier to sort things out with dotfiles utilities -- I can come back on this, if desired).

My question is: is that OK to put those files in the 'lisp' directory, or do they have to be located in the repo root?  Or is there some other conventional directory where they could be inserted?

Best regards, and thanks a lot for your support!
Fabrice

**Comment by tarsius** [comment]
You can put your files where ever you want but you might then have to tell Emacs about it because otherwise it won't know about it.

This doesn't really have anything to do with Melpa. There are better places to ask such questions such as the Emacs reddit and stackexchange sites.
