### ISSUE TITLE
Description not displayed for package (snow)

### ISSUE THREAD

**Issue by alphapapa** [melpa/melpa#7315]
My package `snow` was recently added to MELPA (https://melpa.org/#/snow), but its description is shown as `No description available.`  Running the function `lm-commentary` in the file returns the commentary:
```el
";;; Commentary:

;; Let it snow in Emacs!  Command `snow' displays a buffer in which it
;; snows.  The storm varies in intensity, a gentle breeze blows at
;; times, and snow accumulates on the terrain in the scene.

"
```
And AFAICT that is the function used to retrieve it, so I don't know why it would not be shown in MELPA.

Thanks for your work.

**Comment by purcell** [comment]
That's weird. Is this perhaps a regression in `package-build`, @tarsius? If I build it locally (with C-c C-c in the "snow" recipe buffer) then the readme is indeed not written, but if I call

```el
(let ((package-build-archive-dir (expand-file-name "packages" default-directory)))
  (package-build--write-pkg-readme "snow" (expand-file-name "working/snow" default-directory)))
```

then the file gets written.

**Comment by tarsius** [comment]
It appears so but I am gonna catch some sleep before looking into it.

**Comment by tarsius** [comment]
It's a done.

**Comment by alphapapa** [comment]
Thanks, Jonas.  Do I need to push an update to the package to force the package's metadata on MELPA to be updated?

**Comment by tarsius** [comment]
I'm afraid so :(

**Comment by alphapapa** [comment]
That's okay, I'm sure I can find something that needs doing in it.  Thanks.

**Comment by tarsius** [comment]
> I'm sure I can find something that needs doing in it.

Typos. There's alwasy typos.
