### ISSUE TITLE
dir file for Info manual registration not being generated (modus-themes)

### ISSUE THREAD

**Issue by protesilaos** [melpa/melpa#7322]
Hello!  Users have reported and I have confirmed that my `modus-themes` package which ships with a `modus-themes.info` file no longer get a `dir` entry. So the manual does not show up in the Info reader.  The issue seems to have been introduced on December 25 and might be related to what has already been reported about building packages.

I tried to track back all changes I made that could have possibly corrupted the `modus-themes.info` file, but could not find anything.  When I call `make recipes/modus-themes` from the root of melpa.git I get the following in the resulting tar archive:

```
 drwxr-xr-x    prot/prot          0 modus-themes-20201231.1237/
 -rw-r--r--    prot/prot        437 modus-themes-20201231.1237/modus-themes-pkg.el
 -rw-r--r--    prot/prot     124069 modus-themes-20201231.1237/modus-themes.info
 -rw-r--r--    prot/prot       2349 modus-themes-20201231.1237/modus-vivendi-theme.el
 -rw-r--r--    prot/prot     301243 modus-themes-20201231.1237/modus-themes.el
 -rw-r--r--    prot/prot       2356 modus-themes-20201231.1237/modus-operandi-theme.el
```

Whereas, say, `magit` does produce the `dir` file.

The package `rg` appears to also be affected.

Apologies in advance if this is not a MELPA issue and something that only concerns my case.

**Comment by tarsius** [comment]
I'll look into it this evening.

**Comment by tarsius** [comment]
The evening came sooner than expected and I have pushed a fix. Thanks for the report.

**Comment by protesilaos** [comment]
That was quick!  I can confirm that it worked.  Thank you for your time and efforts!
