### ISSUE TITLE
Download `dash` and `dash-functional` give 404 Not Found

### ISSUE THREAD

**Issue by dhoekstra2000** [melpa/melpa#7333]
It appears that the download for the `dash` package does not update to the latest build version but keeps sticking to `20201230.348`, even though the badge shows a newer version.

It is possible to use the `melpa.org/download/dash-xxxxxxxx.xxxx` where the xs represent the latest version on the badge, but the Emacs package manager cannot automatically download these packages.

**Comment by Alexander-Miller** [comment]
Same thing for treemacs and cfrs. The download for treemacs-evil just leads to an obsolete version.

In fact going by https://melpa.org/#/?sort=version&asc=false there is not a single package with a 2021 version.

**Comment by duianto** [comment]
Confirmed.

The main Treemacs package updates as expected, the current version is:
`treemacs-20210101.1823`

But the `treemacs-evil` package isn't being downloaded,
it's latest version is: `treemacs-evil-20200716.2041`

Even though `treemacs-evil.el`
https://github.com/Alexander-Miller/treemacs/commits/master/src/extra/treemacs-evil.el
has had two commits on Dec 27, 2020
and one on Jan 1, 2021.

**Comment by Alexander-Miller** [comment]
2021 packages are being built now, however all of treemacs' sub packages remain stuck in their old versions. Did something change in the build behavior that treemacs' same-repo packages are no longer picked up?

**Comment by tarsius** [comment]
These packages should be build again now, https://github.com/melpa/melpa/issues/7354. (Might take a few hours for the builds to actually happen.)

**Comment by duianto** [comment]
Thanks
https://melpa.org/#/treemacs-evil is now up to date with:
https://github.com/Alexander-Miller/treemacs/commits/master/src/extra/treemacs-evil.el
