### ISSUE TITLE
Treemacs addons can no longer be built

### ISSUE THREAD

**Issue by Alexander-Miller** [melpa/melpa#7354]
Treemacs keeps several [small addon packages](https://github.com/Alexander-Miller/treemacs/tree/master/src/extra) in its main repo. The recipes for them  are set up to use [only the required file](https://github.com/melpa/melpa/blob/master/recipes/treemacs-evil). 

This setup used to work just fine, however due to a recent change the package build now fails because Melpa has started checking that the file name and package name are the same, so the build fails [on this line](https://github.com/melpa/melpa/blob/master/package-build/package-build.el#L711) because it compares "treemacs-evil.el" vs "src/extra/treemacs-evil.el".

Strangely enough  building treemacs proper has no such problem even though its files are also located in a [sub directory](https://github.com/Alexander-Miller/treemacs/tree/master/src/elisp).

**Comment by tarsius** [comment]
Thanks for the report.

Fixed by https://github.com/melpa/package-build/commit/4ca24cb7143eb49365b8546f518ef4b857b9c253.

**Comment by purcell** [comment]
Nice, thanks @tarsius
