### ISSUE TITLE
Official mirror for melpa stable doesn't provide the stable versions of packages

### ISSUE THREAD

**Issue by natrys** [melpa/melpa#7374]
The API endpoint for the stable version of melpa mirror listed as "official" in the readme, seems to be returning package versions of normal melpa, not the stable one.

Basically I expect these two endpoints to return same data, but only the latter is correct.

```
http://www.mirrorservice.org/sites/stable.melpa.org/packages/archive-contents
http://stable.melpa.org/packages/archive-contents
```

**Comment by purcell** [comment]
Interesting. I haven't checked this since we set it up a couple of years ago, but it used to work. We moved servers and re-jigged the config there at some point, so I wonder if perhaps there's an issue with our rsync setup. Will take a look when I get chance - thanks for the heads-up.

**Comment by kwvanderlinde** [comment]
Any updates on this? The situation appears to be unchanged so far.

**Comment by purcell** [comment]
Hmm, okay, it looks like we used to have 2 rsync daemons, one for each domain. Now we have a single one, with two named rsync resources. I'll need to get in touch with the mirrorservice folks to ask them to update things on their end.

**Comment by milkypostman** [comment]
thanks for doing this Steve.

**Comment by purcell** [comment]
I sent an update request to the mirrorservice team, I'll report back here when I know more.

**Comment by purcell** [comment]
I believe this is now resolved, at least based on the availability of resources like

https://www.mirrorservice.org/sites/stable.melpa.org/packages/a-1.0.0.el

**Comment by kwvanderlinde** [comment]
Thanks @purcell ! Everything looks good now when rsync'ing from mirrorservice which is going to be really handy!

**Comment by milkypostman** [comment]
will try to take a look in the next few days.

**Comment by andrecbarros** [comment]
Perhaps, the documentation should be updated, it works with

rsync -avz --progress --delete rsync://melpa.org/packages-stable/ melpa_stable/

Cheers

**Comment by milkypostman** [comment]
@andrecbarros I looked all over for where this is even documented and it seems like it's only in this pull request?

**Comment by tarsius** [comment]
I couldn't find any existing documentation either.
