### ISSUE TITLE
Remove the twitter widget from melpa.org?

### ISSUE THREAD

**Issue by minad** [melpa/melpa#7377]
* It is unnecessary
* It seems to breaks always
* Why send data to Twitter?

EDIT: Maybe also remove Google Analytics on the go? But I don't want to sound too much like RMS here... ;)

**Comment by minad** [comment]
As an alternative - what about adding some log which shows the updated packages instead, similar to http://hackage.haskell.org/packages/recent?

**Comment by purcell** [comment]
I agree it's not working great right now but I'm not in a hurry to remove it. The problem currently is that the free zapier integration which tweets out package updates (based on an RSS feed on the site) keeps hitting its limit, so that makes the updates feed a little useless. This can be fixed - or, indeed, replaced - but it also serves the purpose of broadcasting announcements or retweets. The twitter widget is a very convenient way to include them.

I'm sympathetic to the privacy argument, though browsers can trivially block social media and tracking javascript.

**Comment by minad** [comment]
> I'm sympathetic to the privacy argument, though browsers can trivially block social media and tracking javascript.

I would not say it is trivial, since you have to adjust these settings per page and most people don't adjust all their settings. I wonder how people are surfing in the web without an ad blocker for example. But it seems there are people who do otherwise there wouldn't have to be any ads ;) I would just prefer if sites like melpa do the "right" thing.

> I agree it's not working great right now but I'm not in a hurry to remove it.

Yes there is no hurry. My proposal goes more in the direction - do what requires the least work for the maintainers. Do not spend time on fixing some zapier integration or fix problems with some rate limits. Just kick it out! ;)

> This can be fixed - or, indeed, replaced - but it also serves the purpose of broadcasting announcements or retweets. The twitter widget is a very convenient way to include them.

I think the twitter account would be even more useful if you do not clutter it with package updates and reserve it solely for *important* announcements, whatever these may be.

But I don't want to berate you here and steal your time, it just annoyed me when I looked at the melpa site the last time to check for some package builds, so I thought I should mention it. Keep up the good work with melpa! :+1:

**Comment by purcell** [comment]
> I think the twitter account would be even more useful if you do not clutter it with package updates and reserve it solely for _important_ announcements, whatever these may be.

Well hey, I know for a fact that very many people follow the Twitter account to keep tabs on new and updated packages. But yeah, it's hard to have good visibility for both occasional important announcements and a constant stream of updates.

In any case, I've removed both Google Analytics and the Twitter widget. I don't think we refer to the Analytics stats enough for them provide actionable insights. The changes should get automatically applied in the next few hours.

**Comment by minad** [comment]
Thank you @purcell!
