### ISSUE TITLE
update only upon commits that change the *.el file

### ISSUE THREAD

**Issue by Boruch-Baum** [melpa/melpa#7392]
IIUC, melpa monitors 'fetchers' in order to know when to update a package. In the case of git repositories, melpa seems to check for new commits. However, a new commit could have no bearing on the package being monitored, for instance, updates to a repository's documentation files or CI.

So, if I'm understanding how the process works, you could reduce bandwidth for all concerned by checking the files modified by the new git commit(s) and only update when the actual package files change.

**Comment by purcell** [comment]
What we do is pull new changes - which is inevitably going to be necessary to see the changes - then rebuild the package using the listed files. This latter step is trivial, and the former is what takes all the time. So either I don't quite understand what you're suggesting, or there's no easy win to be had here.

**Comment by Boruch-Baum** [comment]
OK. Just thought it might be helpful.
