### ISSUE TITLE
Description not displayed for package per-buffer-theme

### ISSUE THREAD

**Issue by inigoserna** [melpa/melpa#7401]
Hi,

I just noted that there is not description/summary shown for package my `per-buffer-theme`.
I think it was displayed a couple of months ago.

`lm-synopsis` returns the correct text.

Thanks

**Comment by purcell** [comment]
How about `lm-commentary`? That's what `package-build` uses. See also #7398 maybe.

**Comment by purcell** [comment]
Seems to be working now...?

**Comment by inigoserna** [comment]
Yes!, it works now.
But I don't understand why. I've been doing some tests but haven't changed anything.
Anyway, thanks for your help and interest, and keep rocking!
Thanks a lot.

**Comment by purcell** [comment]
There were some related `package-build.el` fixes, so I suspect they resolved this.
