### ISSUE TITLE
Delete company-lsp package?

### ISSUE THREAD

**Issue by yyoncho** [melpa/melpa#7461]
This package is deprecated and no longer works with lsp-mode. Also, the author is unreachable. At the same time, there are users who still install it and break their config. Is it possible to be deleted?

**Comment by purcell** [comment]
Done, thanks

**Comment by scmbradley** [comment]
Is there an alternative for using company with lsp?

**Comment by tototoshi** [comment]
@scmbradley https://github.com/scalameta/metals/issues/2641#issuecomment-812546564
