### ISSUE TITLE
Request: Removing ein from melpa-stable

### ISSUE THREAD

**Issue by dickmao** [melpa/melpa#7479]
If we could somehow delete [/mnt/store/melpa/working/ein](https://stable.melpa.org/#/ein), then rather than [fetching new tags](https://github.com/melpa/package-build/blob/d8ec8ddf5e39b61e9338de9a778633b7e01854cd/package-build.el#L250-L251), it would presumably [clone from scratch](https://github.com/melpa/package-build/blob/d8ec8ddf5e39b61e9338de9a778633b7e01854cd/package-build.el#L255-L256) the repo, which [no longer fields any tags](https://github.com/millejoh/emacs-ipython-notebook/tags), thus granting ein sweet release.

**Comment by tarsius** [comment]
@millejoh why were the tags removed? Do you want to remove this from melpa-stable and if so why?

**Comment by tarsius** [comment]
@millejoh It seems something has gone wrong in your repository. It appears you have accidentally deleted the tags.

> which no longer fields any tags, thus granting ein sweet release.

If there are no tags then no new releases will be made available on Melpa-Stable. 

It would be nice if that were fixed upstream, but aside from pinging them one more time, I don't see how we can help with that here.
