### ISSUE TITLE
Ask contributors to stick around for CI to complete

### ISSUE THREAD

**Issue by tarsius** [melpa/melpa#7486]
@purcell @riscy What about adding something like this at the end of the pr template:

> [After submitting this, please wait for the CI to complete and if it reports problems, then please try to fix them.]

Suggestions for better wording?

Also I've been thinking we should

```diff
-[Please confirm with `x`:]
+<!--Please confirm with `x`:-->
```

**Comment by riscy** [comment]
One possible rewording: `<!-- After submitting, please fix any problems the CI reports -->`.  At first I was going to say this seems obvious to me, but not everyone will have experience with this and I've noticed a few PRs left in a broken-build state.

> Also I've been thinking we should ...

Agreed. :)

**Comment by tarsius** [comment]
Done.
