### ISSUE TITLE
Determine list of "golden" packages.

### ISSUE THREAD

**Issue by milkypostman** [melpa/melpa#7492]
I would like community suggestions for a *small* subset of packages (2-5?) that can be used to check that a PR works properly, including functional changes to `package-build`. These would be packages that indicate that everything is going well or that as a community we want to make sure always build with MELPA.

- evil
- magit

**Comment by tarsius** [comment]
[Last time you called them "unique".](https://github.com/melpa/melpa/issues/6478). :grinning: 

But yes, I agree we should do this.

Whenever we would run the "check the modified packages" test if only there weren't only zero such packages, then we could instead build these few packages.

**Comment by purcell** [comment]
Including high-profile packages as above makes sense, but we probably want packages that use a variety of fetchers and `:files` patterns, also some which use `-pkg.el` files. (`magit` qualifies for the latter.) As mentioned elsewhere, though, I think these checks might well belong in CI for the `package-build` repo instead.

**Comment by milkypostman** [comment]
LOL. ok. I guess we need to setup CI there.....

**Comment by milkypostman** [comment]
Duplicate of #6478
