### ISSUE TITLE
version-to-list: Invalid version syntax: `20210328.643^M': 

### ISSUE THREAD

**Issue by ShuguangSun** [melpa/melpa#7515]
When I run `package-build-current-recipe` in a recipe, it messages the error "version-to-list: Invalid version syntax: `20210328.643^M' which looks like an additional carrage return (^M).

In GNU Emacs 28.0.50 (build 1, x86_64-w64-mingw32)
 of 2021-03-31 built on 
Repository revision: 515378434a44b9979e8c8a6e04203695095bdc40
Repository branch: feature/native-comp
Windowing system distributor 'Microsoft Corp.', version 10.0.19042
System Description: Microsoft Windows 10 Enterprise (v10.0.2009.19042.867)

**Comment by purcell** [comment]
Which recipe?

**Comment by ShuguangSun** [comment]
Any one. For example, elx, "version-to-list: Invalid version syntax: `20210228.2103^M'

``` elisp
;; Please check the following package descriptor.
;; If the correct package description or dependencies are missing,
;; then the source .el file is likely malformed, and should be fixed.
(elx .
     [(20210228 2103)
      ((emacs
        (25 1)))
      "extract information from Emacs Lisp libraries" single
      ((:commit . "de9d42c86fc3e71239492f64bf4ed7325b056363")
       (:authors
        ("Jonas Bernoulli" . "jonas@bernoul.li"))
       (:maintainer "Jonas Bernoulli" . "jonas@bernoul.li")
       (:keywords "docs" "libraries" "packages")
       (:url . "https://github.com/emacscollective/elx"))])
```

**Comment by purcell** [comment]
Okay, thanks, so a couple more quick questions to help narrow this down:

- Does it only happen when you select "y" to _install_ the freshly-built package?
- Does it also happen when you build a package that comes with a `-pkg.el` file in its repo, e.g. `magit`?
  - If not, what encoding does the freshly-built `.el` file (under `melpa/packages`) have, and does the `;; Package-Version` field in that file look weird if you view it with `whitespace-mode` enabled?

Sorry for the questions, but I don't have a Windows machine on which to try this myself.

**Comment by ShuguangSun** [comment]
> Does it only happen when you select "y" to _install_ the freshly-built package?

Yes. 

> Does it also happen when you build a package that comes with a `-pkg.el` file in its repo, e.g. `magit`?

No.

>     * If not, what encoding does the freshly-built `.el` file (under `melpa/packages`) have, and does the `;; Package-Version` field in that file look weird if you view it with `whitespace-mode` enabled?

The `buffer-file-coding-system` of the freshly-build `.el` file is `prefer-utf-8-dos`.
The error comes from `(or (lm-header "package-version") (lm-header "version"))` from `package-buffer-info` called by `package-install-from-buffer`, which results a "^M". 
I add `(print buffer-file-coding-system)` to `package-buffer-info`, it print `no-conversion`.

**Comment by purcell** [comment]
Thanks for all the details. Not sure exactly how to reproduce this without a windows box: I've tried setting the preferred coding system to utf-8-dos locally, but that doesn't affect anything. I'm guessing that the `[MELPA]/working/package-name/` git clones have `.el` files with carriage returns, as a result of cloning them on a Windows machine?

**Comment by tarsius** [comment]
Whatever the issue may be, it it is not related to how we distribute packages here on Melpa. You will probably have more luck getting help with this if you ask somewhere other Emacs+Windows users hang out.
