### ISSUE TITLE
What to do about TLS support failing?

### ISSUE THREAD

**Issue by SKelem** [melpa/melpa#7521]
I'm running emacs 26.3 on Ubuntu 20.10.
When I run the TLS support test (from https://melpa.org/#/getting-started), I get:
```
M-x eww RET https://wikipedia.org
eww: Symbol’s value as variable is void: cl-struct-url-tags
```
Any idea on how to fix this?
I also tried: 
```
% apt-file search libssl | grep libssl-dev
libssl-dev: /usr/lib/x86_64-linux-gnu/libssl.a
libssl-dev: /usr/lib/x86_64-linux-gnu/libssl.so
```

**Comment by purcell** [comment]
> M-x eww RET https://wikipedia.org
> eww: Symbol’s value as variable is void: cl-struct-url-tags

I know we list that command as a test, but the error message you're getting doesn't look related to TLS at all. It looks more like a broken installation. Try the same command with a site that serves plain http, and see if you get the same error.
