### ISSUE TITLE
Download statistics are stuck?

### ISSUE THREAD

**Issue by minad** [melpa/melpa#7524]

**Comment by minad** [comment]
Btw, MELPA seems to be faster recently. Has something been changed?

**Comment by purcell** [comment]
Hmm, good find: access logs are empty, disk appears to be full. Will report back.

**Comment by purcell** [comment]
> Btw, MELPA seems to be faster recently. Has something been changed?

Not to my knowledge, but also not sure what/when your basis for comparison is.

**Comment by purcell** [comment]
Noting the biggest checkout dirs on the server here:
```
101168	iscroll
109788	eldoc-stan
109792	company-stan
109792	flycheck-stan
109792	stan-mode
109792	stan-snippets
116000	ligo-mode
117816	ac-html-bootstrap
118768	scad-mode
119036	cfengine-code-style
120616	kivy-mode
124852	libgit
134260	organize-imports-java
149300	spiral
153116	language-detection
154708	call-graph
163364	python-mode
163464	equake
168372	protobuf-mode
170484	thrift
186248	sekka
269724	ansible
282380	cmake-mode
322160	lsp-p4
441128	fuel
475240	mgmtconfig-mode
602416	erlang
642496	nemerle
847588	eri
872340	agda2-mode
872356	annotation
1001040	mozc
```

**Comment by purcell** [comment]
Looks like maybe 3 lost days of download history. I'm running a `git gc` on all the git working directories, which is something we still don't routinely do. That is freeing up enough space that everything should resume now, but a more complete strategy will be needed.

**Comment by purcell** [comment]
For the record:

Disk size is 50GB
Logs are 11GB
SQLite download info extracted from logs is 5.2GB
Working directories are 18GB (down by 4.1GB as a result of `git gc`)
Packages (non-Stable) are only around 600MB.

**Comment by minad** [comment]
Thank you @purcell! What about dropping huge repositories? I know this is a long standing issue.

1. Drop large repositories from MELPA builds (disable temporarily, notify maintainers that emacs package must be extracted to separate repository)
2. Introduce repository size limit (50M)? I find that already fairly large, but things will grow over time. Magit for example is 27M. So some shallow cloning strategy is needed in the long term (as proposed before in #5361)? Regarding the repository size limit it may make sense to discuss this during package inclusion (Probably you already do that?). For example if someone proposes an elisp package which is part of a large repository (e.g. major mode as part of programming language repository like nemerle).

**Comment by purcell** [comment]
>     1. Drop large repositories from MELPA builds (disable temporarily, notify maintainers that emacs package must be extracted to separate repository)
>     2\. Introduce repository size limit (50M)? I find that already fairly large, but things will grow over time.

Yeah, #5361 is about that topic, but these specific steps would involve a lot of coordination with third parties, so they're not the first on the list. I've started switching builds to partial clones today, so I'll probably wait and see what further steps are required: I expect that will help quite a lot already.

**Comment by purcell** [comment]
I've taken the liberty of closing this because I'm pretty certain it's resolved, but ping me if you feel that the stats still aren't changing in the next day or so.

**Comment by minad** [comment]
> Yeah, #5361 is about that topic, but these specific steps would involve a lot of coordination with third parties, so they're not the first on the list. I've started switching builds to partial clones today, so I'll probably wait and see what further steps are required: I expect that will help quite a lot already.

Sure, everything has been discussed already many times here. And I assume you are aware of all the implications. So I hope I don't bother you when repeating some things.

I appreciate the quick fix (partial clones, great!) and also the fix of the download statistics. Not that I consider those important, but a full disk seems fairly serious ;)

**Comment by purcell** [comment]
> So I hope I don't bother you when repeating some things.

Nope, that's cool, I appreciate the input. :+1:
