### ISSUE TITLE
melpa integration with gentoo portage package manager no longer works here...

### ISSUE THREAD

**Issue by CaptainBloodz** [melpa/melpa#7533]
Executing
emerge -p world

throws
 *   elisp: EAPI 5 not supported
 *      *) die "${ECLASS}: EAPI ${EAPI:-0} not supported" ;;
for each melpa sourced installed package.

Updating isn't possible anymore.

Is there any way to fix this?

**Comment by purcell** [comment]
Completely lacking in context for this, sorry. You should file an issue with whoever wrote the Portage integration: this doesn't appear to be a MELPA issue at all.

**Comment by CaptainBloodz** [comment]
not match of a context, indeed.
Many things have improved regarding melpa integration in gentoo.
Sorry for the noise.
Thks
