### ISSUE TITLE
evil-numbers: unmaintained, policy for taking ownership?

### ISSUE THREAD

**Issue by ideasman42** [melpa/melpa#7559]
It seems this package is no longer maintained.

- Sent an email to the author over 2 weeks ago to ask if the package is maintained without response.
- Submitted a pull request for a simple warning fix 24 days ago, without response.

Is there any issues with submitting a PR that points to my own fork of this repo?

I have no big plans for the package besides:

- Basic maintenance, keep up with changes in Emacs
- Feature parity with VIM (fixing https://github.com/cofi/evil-numbers/issues/7 for example)

**Comment by purcell** [comment]
Not opposed to reassigning the authoritative repo in principle, given your efforts so far, and the apparent total lack of github activity from the author.

I see from that issue that two other authors have fixed it: perhaps the best future maintainer might even be someone else. How about you open a further issue on the upstream repo to discuss this topic, and CC other contributors? This way you can get them to submit fresh PRs/fixes etc. against your fork in due course.

**Comment by purcell** [comment]
Thanks, good work. I see there was even https://github.com/juliapath/evil-numbers/issues/3 about getting that fork into MELPA, potentially under a different name.

**Comment by juliapath** [comment]
I'd be fine if my repo was to replace cofi/evil-numbers. I contacted cofi a few times and even got an answer once, but not anymore to my followup. Of course I could use a new name for the package if that was preferred, but I'd rather not if I don't have to.

**Comment by purcell** [comment]
Done now, thanks!
