### ISSUE TITLE
multi-mode, mmm-mode, and similar packages

### ISSUE THREAD

**Issue by lassik** [melpa/melpa#7564]
We have a [`scheme-c-mode`](https://github.com/chicken-contrib/scheme-c-mode) package to be added MELPA but it depends on `multi-mode` to get multiple major modes in the same buffer. `multi-mode` is not on ELPA or MELPA; it originates [here](http://www.loveshack.ukfsn.org/emacs/). MELPA has [`mmm-mode`](https://github.com/purcell/mmm-mode) for the same purpose. What should we do - add `multi-mode` to MELPA as well, or rewrite `scheme-c-mode` to use `mmm-mode`?

I've never worked with multiple major modes, so I'm not qualified to make the technical decision; hoping someone with more experience could advise.

**Comment by purcell** [comment]
I mean, that scheme-c-mode repo has been archived, so I'm not sure we should be adding that to MELPA, so perhaps this question is moot.

**Comment by tarsius** [comment]
IMO it would be okay to add `multi-mode` in addition. Both have been around for a long time and are still being maintained.

If you want to release a package that depends on `multi-mode` to Melpa, then you would first have to open a pull-request to add the dependency.
