### ISSUE TITLE
The source and home links differ for MELPA hide-lines package

### ISSUE THREAD

**Issue by pierre-rouleau** [melpa/melpa#7568]
Although the MELPA home link points to an earlier version of the code, the code distributed is the older one.

The MELPA hide-lines package source code link is pointing to https://github.com/emacsorphanage/hide-lines which corresponds to the original code published in EmacsWiki (at https://www.emacswiki.org/emacs/hide-lines.el) and is an older copy of the code.

The newer copy, which provides more commands, is identified in the home page link:  https://github.com/vapniks/hide-lines

There's a bit of consistency cleanup to do here.   Let me know if I can help.

**Comment by purcell** [comment]
Done, thanks.
