### ISSUE TITLE
melpa.org is empty here, normal ?

### ISSUE THREAD

**Issue by danrobi11** [melpa/melpa#7571]
> To browse available packages, check out the [archive index page](https://melpa.org/)

We cant search for packages. The website is empty. Normal ?

![melpa blank](https://user-images.githubusercontent.com/48020114/118191138-1fbfb300-b412-11eb-9469-80a5a44c3031.png)

**Comment by purcell** [comment]
It's empty if you have disabled javascript.

**Comment by danrobi11** [comment]
@purcell Weird, the js on my end is enabled. Otherwise I couldnt logout of github.

**Comment by danrobi11** [comment]
@purcell 

Ok I've found the issue. Im blocking cdnjs.cloudflare.com at the hosts level. 

Now I wonder why cdnjs.cloudflare is needed on melpa.org ?!

**Comment by purcell** [comment]
I think we're serving our JS straight from a CDN rather than copy it into our repo. We don't have sufficient complexity to warrant npm or bundlers.

**Comment by danrobi11** [comment]
@purcell 

Ok Thank you for the support. Closing
