### ISSUE TITLE
Package archives with subdirectories

### ISSUE THREAD

**Issue by doublep** [melpa/melpa#7575]
I see in the `README.md` that *"Any file specified at any path in the repository is copied to the root of the package"*. For a package I would like to use subdirectories and have asked if it was supported by Emacs: https://lists.gnu.org/archive/html/emacs-devel/2021-05/msg00616.html. According to one of the top developers, it is supported.

However, for MELPA I don't see a way to achieve this, also not from a brief investigation of the source code. Documentation says: *"More complex options are available, submit an Issue if the specified package requires more complex file specification."*. So, here it is.

**Comment by purcell** [comment]
Usually you would write `:files (:defaults "docs")` to include the default files plus the entire intact subdirectory "docs". Does that help?

**Comment by doublep** [comment]
Partially yes, as directory now ends in the archive. The problem, now, is that excludes inside this directory are ignored: I tried to explicitly exclude unwanted files, but it didn't change anything. As far as I can see from the sources, there is just a `copy-directory` call, so excludes are not discarded and matched files are also never deleted afterwards. In my package the directory contains both source files (which shouldn't be copied) and the actual resource files...

**Comment by purcell** [comment]
You can only `:exclude` files that have been added via a glob, and the list is expanded and filtered from left to right, so IIRC you need something like the following:

```
:files (:defaults ("docs" "docs/*") (:exclude "docs/not-this" "docs/not-that"))
```

**Comment by doublep** [comment]
Thank you, now it works as wanted. I presume the format of cons cell is (SUBDIR FILE-PATTERNS...) and files are copied to given subdirectory in the package's tarball. At least it looks like that from brief testing. Maybe a few words about this could be added to the documentation.

**Comment by purcell** [comment]
Yes, exactly. Better documentation would be good... :-)  Glad you got it working.

**Comment by purcell** [comment]
I tried to clarify this a litte in the README.
