### ISSUE TITLE
Magit package needs to be rebuild

### ISSUE THREAD

**Issue by tarsius** [melpa/melpa#7591]
@purcell or @milkypostman please recreate the `magit-3.0.0` package. I did not update the Melpa recipe for `magit` soon enough, resulting in that package containing `magit-section.el` even though that is distributed as a separate package and specified as a dependency of `magit`.

**Comment by milkypostman** [comment]
Done.  Verified that the magit-3.0.0 build doesn't have `Magit-section.el`.

**Comment by tarsius** [comment]
Thanks!
