### ISSUE TITLE
Guidance for 'package-requires' 

### ISSUE THREAD

**Issue by Boruch-Baum** [melpa/melpa#7598]
In the past, I've managed to submit packages to melpa and use the `package-requires` directive, but now I'm working on updating a seemingly neglected package [noaa.el](https://github.com/thomp/noaa/pull/5) for which package lint is giving me a *lot* of output, and I haven't a clue how to proceed. A web-search hasn't produced any guidance or explanation , not even in @alphapapa's guidebook. In the following output, the first line is the existing `package-requires` and the rest are my notes / attempt based upon `package-lint` output.

```
;; Package-Requires: ((request "0.2.0") (cl-lib "0.5") (emacs "24") (dash "2.14.1"))

;;                   ((emacs "24.3") (cl-macs "") (defvar-local) (read-only-mode))
;;                   ((emacs "24.4") (subr-x "") (string-blank-p))
;;                   ((emacs "24.5") (cl-extra ""))
;;                   ((emacs "25.1") (parse-iso8601-time-string))
;;                   ((emacs "27.1") (json-parse-string))
```

A *best* response would be a pointer to a URL explaining the format and usage. That way it could be discoverable by others and not hidden here in a github issue. I'm frustrated that my web searches turned up nothing; it's difficult to believe there's no documentation *anywhere*.

**Comment by alphapapa** [comment]
https://www.gnu.org/software/emacs/manual/html_node/elisp/Library-Headers.html

**Comment by Boruch-Baum** [comment]
Thanks.
