### ISSUE TITLE
Failed to download ‘melpa-stable’ archive.

### ISSUE THREAD

**Issue by ertpoi** [melpa/melpa#7619]
I am getting this error when trying to refresh packages from today morning. I have melpa-stable in my init.el

```lisp
(add-to-list 'package-archives '("melpa-stable" . "https://stable.melpa.org/packages/") t)
```

Is this an issue with the server or with me??

**Comment by purcell** [comment]
Issue is on your side, sorry. Most likely your Emacs doesn't have fully working SSL support/config. Perhaps post more information about the Emacs you're using?

**Comment by ertpoi** [comment]
I am using `"GNU Emacs 26.1 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.5)
 of 2021-01-31, modified by Debian"`

**Comment by ertpoi** [comment]
I compiled emacs 27.2., and problem solved (seems to be a problem with 26.)

**Comment by purcell** [comment]
With 26.2 and earlier, there was a GNUTLS issue which prevented it from working with many modern TLS configurations.
