### ISSUE TITLE
Update a package?

### ISSUE THREAD

**Issue by mtekman** [melpa/melpa#7626]
Hi, the melpa build  (https://github.com/melpa/melpa/blob/master/recipes/smithers)  for my package (https://gitlab.com/mtekman/smithers.el/) seems to build on an outdated version `20210531.2232`, but there has been commits since [2021-06-01](https://gitlab.com/mtekman/smithers.el/-/blob/master/smithers.el) which seem to have gone ignored for a long time now.

Do I need to make a new PR to trigger an update?

**Comment by aplaice** [comment]
I think that this is a matter of different time-zones. Your latest commit was at 12:32 am GMT+0200 on 1 June, which corresponds to 22:32 GMT+0000 on 31 May, which is the timestamp of the latest MELPA build!

If you click on the "source code" button on `smithers`'s [MELPA page](https://melpa.org/#/smithers), you can see that it links to the latest commit.

**Comment by mtekman** [comment]
Oh gosh - how silly of me :laughing: 

Thank you!
