### ISSUE TITLE
matlab-mode in MELPA stable?

### ISSUE THREAD

**Issue by wyphan** [melpa/melpa#7639]
I noticed that the `matlab-mode` package is available to install from MELPA bleeding-edge but not MELPA stable repo. Is there a particular reason why this is the case?

Otherwise, how can I have both MELPA bleeding-edge and MELPA stable repos to coexist in my `.emacs` file without breaking Emacs?

Any help would be appreciated.

**Comment by wasamasa** [comment]
The Git repository does not use tags, so MELPA stable cannot create tagged releases. Consider contacting upstream about creating and pushing version number tags.

**Comment by tarsius** [comment]
> Consider contacting upstream about creating and pushing version number tags.

This is the way forward. Nothing to be done here. Closing.
