### ISSUE TITLE
Cannot doen load melpa.  Melpa  or melpa-stable 

### ISSUE THREAD

**Issue by worikgh** [melpa/melpa#7641]
This is not a duplicate of 7238 as far as I can tell
I have `debug-on-error` set to `t` and it does not halt on a error

The configuration.  I get exactly the same results using `http`

```
(require 'package)                                                                                                                                                       
(setq package-archives                                                                                                                                                   
      '(("GNU ELPA"     . "https://elpa.gnu.org/packages/")                                                                                                              
        ("MELPA Stable" . "https://stable.melpa.org/packages/")                                                                                                          
        ("MELPA"        . "https://melpa.org/packages/"))                                                                                                                
      package-archive-priorities                                                                                                                                         
      '(("MELPA Stable" . 10)                                                                                                                                            
        ("GNU ELPA"     . 5)                                                                                                                                             
        ("MELPA"        . 0)))                                                                                                                                           
(package-initialize)                                                                                                                                                     
```

The `*Messages*`  on running `package-refresh-contents`

```
Importing package-keyring.gpg...done
Contacting host: elpa.gnu.org:443
Failed to download ‘GNU ELPA’ archive.
Contacting host: stable.melpa.org:443
Failed to download ‘MELPA Stable’ archive.
Contacting host: melpa.org:443
Failed to download ‘MELPA’ archive.
```

Running on a Raspberry PI 4
```
$ cat /etc/issue
Raspbian GNU/Linux 10
```

`GNU Emacs 26.1 (build 2, arm-unknown-linux-gnueabihf, GTK+ Version 3.24.5) of 2021-02-07, modified by Debian`

The machine is connected to the Internet and has no difficulties loading other URLs.

Using `eww` I can download some other pages from `http` but not `https`.

* `http://example.com` but not `https://example.com`
* `http://google.com` but not `https://google.com`

**Comment by worikgh** [comment]
Here is the thing:

My emacs does not talk https.

`http://melpa.org/` is redirected to `https://melpa.org/`

There is no melpa for my version of emacs.  That is quite a serious bug???

**Comment by worikgh** [comment]
This command changes things:
```
(setq gnutls-algorithm-priority "NORMAL:-VERS-TLS1.3")
```

Now I get no errors.  It silently does its thing.  But `package-list-packages` lists no packages from `melpa`.  

I am looking for the `rust*` packages (https://github.com/brotzeit/rustic/issues/260) but they are not there.

```
(require 'package)                                                                                                                                                       
(require 'gnutls)                                                                                                                                                        
(setq gnutls-algorithm-priority "NORMAL:-VERS-TLS1.3")                                                                                                                   
(setq package-archives                                                                                                                                                   
      '(("GNU ELPA"     . "https://elpa.gnu.org/packages/")                                                                                                              
        ("MELPA Stable" . "https://stable.melpa.org/packages/")                                                                                                          
        ("MELPA"        . "https://melpa.org/packages/"))                                                                                                                
      package-archive-priorities                                                                                                                                         
      '(("MELPA Stable" . 10)                                                                                                                                            
        ("GNU ELPA"     . 5)                                                                                                                                             
        ("MELPA"        . 0)))                                                                                                                                           
(package-initialize)                                                                                                                                                     
(package-refresh-contents)                                                                                                                                               
```

**Comment by alphapapa** [comment]
You're having a problem with your Emacs build and configuration.  This doesn't indicate a problem with MELPA.  Posting here and expecting the MELPA maintainers to help you solve this isn't fair to them.  Please use a more appropriate place to ask for general help with Emacs, like old.reddit.com/r/emacs, IRC, etc.

**Comment by worikgh** [comment]
`You're having a problem with your Emacs build and configuration.` Is a good reply

This is a vanilla build of emacs.  Fresh install.  The fact that (once I fixed the TLS problem) loading packages fails *silently* indicates this is a MELPA problem. 

Accusing strangers on the Internet of being unfair is a way of never hearing about problems.  Be nice.

**Comment by purcell** [comment]
Okay, I think we can all manage a slightly more patient tone here. We are among Emacs friends. :-)

> This is a vanilla build of emacs. Fresh install. The fact that (once I fixed the TLS problem) loading packages fails _silently_ indicates this is a MELPA problem.

Emacs 26.1 (and 26.2 IIRC) and earlier had a bug that stopped those versions working with modern SSL setups. This means that those versions don't work out-of-the-box with MELPA - but neither do they work with ELPA over HTTPS. Regarding out-of-the-box SSL compatibility, we have had to choose between using a secure SSL config, or maintaining support for Emacsen released over 2 years ago.

Now, as far as I remember, it's usually sufficient to use that `gnutls-algorithm-priority` workaround you tried in those affected Emacs versions, but you have to refresh the package list again afterwards. Could you confirm that you tried that and still failed to see packages?

GNU ELPA still allows plain HTTP. We decided (as a result of user demand) to only support SSL access. This is reasonable if there are workarounds such as that above, but obviously it means that Emacsen built without any SSL support will not work with MELPA. Such builds would be very unusual, though.

**Comment by purcell** [comment]
P.S. It's also quite possible that we need to add more info about this specific issue to our "getting started" / readme docs.

**Comment by alphapapa** [comment]
> This is a vanilla build of emacs. Fresh install. The fact that (once I fixed the TLS problem) loading packages fails _silently_ indicates this is a MELPA problem.
> 
> Accusing strangers on the Internet of being unfair is a way of never hearing about problems. Be nice.

You're using a version of Emacs that's 3 years old and 4 releases behind.  If you searched the Web for the issue you're having, you'd find that this is not the first time that we've heard about it.  Other users have reported it and been given solutions in various places on the Web (if I had a dollar for every time I saw this posted on r/emacs...).  But instead, you accuse MELPA of being broken.

It's not fair to expect them to give you personal tech support on their bug tracker for a years-old issue with far-outdated software.  It's especially not fair for you to come here without, apparently, having done a Web search first (if you did, you didn't say so, which would be your omission).  You could have asked on Reddit, the emacs-help mailing list, IRC, etc, so that numerous people could help you and other users could learn from the answers.  Instead, you're expecting them to spend their limited free time that they could be spending to improve MELPA to do help you individually.  That isn't nice of you.  

Now I'll refer you to [ESR's guide](http://catb.org/~esr/faqs/smart-questions.html) and note that Steve is a very patient fellow,  generous even to a fault.  You're lucky to have him as your guide.

**Comment by worikgh** [comment]
Golly.  You really do not like users reporting bugs!

BTW the magic incantation is: `(setq gnutls-algorithm-priority "NORMAL:-VERS-TLS1.3")` early in the configuration.

Please desist from personal attacks on users reporting bugs.  I know it is very hard for a expert to hear the same problems from users over and over again.  It seems obvious to you, but not to us.  Not because we are stupid, or cannot do a web search.  I have had a issue using melpa.  I did search extensively, eventually I found the magic incantation needed.  But the place to report issues with MELPA is MELPA.  Not some forums on social media sites!  

I am using a OS I downloaded from the Raspberry PI folks that is less then six months old.  This is the version of emacs provided.  Many thousands of users will be having this problem.  

I do suggest that it would be a good idea to have a guide for emacs 26 users, but you do what you want.

I never accused MELPA of being broken.  Even if MELPA were broken, it would not be a accusation! There is a bug.  The bug happens to be in emacs, bug it manifests itself as a bug in MELPA.

**Comment by worikgh** [comment]
> Now, as far as I remember, it's usually sufficient to use that `gnutls-algorithm-priority` workaround you tried in those affected Emacs versions, but you have to refresh the package list again afterwards. Could you confirm that you tried that and still failed to see packages?

`gnutls-algorithm-priority`?  I reported that it resulted in silent failure.  I am happy to try a different incantation of that if it would be useful.

As I mentioned to your college I am coming to this from a vanilla Raspberry PI install, so there are plenty of people with this software who may try out emacs as a IDE (for rustr in my case, using `rustic` which is what bought me here) who will fall away at this hurdle.  

Anything I can do to help.

**Comment by alphapapa** [comment]
> Golly. You really do not like users reporting bugs!

I don't understand how you could reach that conclusion from reading what I wrote.  Please consider reading my messages again.  

> Please desist from personal attacks on users reporting bugs. 

It's not a personal attack to ask you to respect the MELPA maintainers' time and use a more appropriate forum for asking for Emacs tech support.  I don't think I can make that plea any more clearly and politely than I have, so I'll just quote you and leave it at that: "Be nice."

**Comment by tarsius** [comment]
I've added a note to the Getting Started page. (There's a delay before it goes online.)

**Comment by purcell** [comment]
Thanks @tarsius, that should make things a lot clearer.
