### ISSUE TITLE
ql's repository has disappeared

### ISSUE THREAD

**Issue by tarsius** [melpa/melpa#7646]
`ql`'s upstream repository has disappeared along with a few other of Ian's repositories for packages (aws, githorg, vc-browse) that are not in Melpa but are mirrored on the Emacsmirror.

@ieure Could you please tell us a bit more about this? Thanks!

**Comment by ieure** [comment]
I no longer want to use GitHub for anything, so I'm in the process of winding down my account as much as possible.  As part of that, I went through all my repos and deleted 100+ of them.  Anything that got deleted is something I haven't used/supported/maintained in years, and in the case of githorg, I don't think it even really worked properly.  I didn't realize that they were in MELPA at all.

Probably the best option at this point is to move them from emacsmirror into emacsorphanage.

The other repos of mine that are in MELPA will be moving to GitLab, and I'll be submitting PRs here for them.

**Comment by tarsius** [comment]
Thanks for the information!

> Probably the best option at this point is to move them from emacsmirror into emacsorphanage.

I'll move them to the emacsattic, which is what I usually do for packages that aren't on melpa and that no other packages depend on either. Moving something to the orphanage doesn't remove it from the mirror, on the contrary, the orphanage serves as a new, hopefully temporary upstream; from which it is then mirrored.

> The other repos of mine that are in MELPA will be moving to GitLab, and I'll be submitting PRs here for them.

That includes `ql`, right?

**Comment by ieure** [comment]
> > The other repos of mine that are in MELPA will be moving to GitLab, and I'll be submitting PRs here for them.
> 
> That includes `ql`, right?

No, I don't use Quod Libet anymore.

**Comment by tarsius** [comment]
Done moving them to the attic.
