### ISSUE TITLE
MELPA cannot load full content

### ISSUE THREAD

**Issue by linhtch90** [melpa/melpa#7659]
When I go to home page of MELPA, the website just showed this

![image](https://user-images.githubusercontent.com/67230802/126995680-52c888f3-4a7c-4fab-888d-6e629acd9b30.png)

**Comment by alphapapa** [comment]
Works for me.

**Comment by manuel-uberti** [comment]
Sometimes it happens to me as well, but usually a page refresh is enough. I tend to blame my internet connection in cases such as this.
