### ISSUE TITLE
Remove flymake-proselint

### ISSUE THREAD

**Issue by manuel-uberti** [melpa/melpa#7681]
My [flymake-proselint](https://github.com/manuel-uberti/flymake-proselint) package is soon to appear on GNU ELPA. For context, check [here](https://lists.gnu.org/archive/html/emacs-devel/2021-08/msg00287.html).

I share @milkypostman's [view](https://github.com/melpa/melpa/pull/7640#issuecomment-874097233) so I'd like to remove the package from MELPA. Do you want me to open a PR or is it something a MELPA maintainer can do?

Thank you.

**Comment by riscy** [comment]
That commit closes this issue -- I think opening a PR like you just did is the best way.

**Comment by manuel-uberti** [comment]
Awesome, thank you!
