### ISSUE TITLE
Download counters stuck?

### ISSUE THREAD

**Issue by alphapapa** [melpa/melpa#7703]
@milkypostman FYI, it appears that the download counters are stuck.

**Comment by milkypostman** [comment]
yeah, the process for calculating counters appeared to be stopped. I'm not sure what would have caused this. It exited with code `0` which should mean docker restarts the process. I will keep an eye on it for a few days and then close out this issue.

FYI it last ran on August 19th. Thanks for reporting.

**Comment by shg** [comment]
The counter seems to have stopped updating a few days ago.

**Comment by milkypostman** [comment]
Yeah, sorry about this. We ended up running out of space but I've increased the size again.
