### ISSUE TITLE
request to remove package

### ISSUE THREAD

**Issue by xahlee** [melpa/melpa#7755]
hi melpa team, may I request to remove my packages?

* xah-fly-keys
* xah-css-mode
* xah-elisp-mode
* xah-find
* xah-get-thing
* xah-lookup
* xah-math-input
* xah-reformat-code
* xah-replace-pairs
* xahk-mode

I hope to have my own website as repo. Thank you guys for years of support.

**Comment by htgoebel** [comment]
> I hope to have my own website as repo.

@xahlee  I'd like to use `package` to mange this extension. What's the URL at your website to be added to `package-archives`?
