### ISSUE TITLE
Way to pass options to makeinfo?

### ISSUE THREAD

**Issue by rnkn** [melpa/melpa#7761]
I know this will likely be consider sacrilege, but I quite like how info files look (within Emacs) when generated with `makeinfo --paragraph-indent=none`.

I understand the current `makeinfo` process is hardcoded with only the output `-o` path, but would it be nice to be able to pass options with a recipe?

Or is that opening things up too much for problems?

**Comment by akirak** [comment]
Hello @rnkn, 

I think you can produce the info file for yourself and commit it to your repository. If there is an existing info file in the designated location, package-build doesn't run makeinfo. See the following code in `package-build.el`:

```emacs-lisp
(unless (file-exists-p info)
                    ;; If the info file is located in a subdirectory
                    ;; and contains relative includes, then it is
                    ;; necessary to run makeinfo in the subdirectory.
                    (with-demoted-errors "Error: %S"
                      (package-build--run-process
                       (file-name-directory src) nil
                       "makeinfo" src "-o" info))
                    (package-build--message "Created %s" info))
```

**Comment by rnkn** [comment]
I guess I just like the cleanliness of a single .texi file... Ideally `makeinfo` could read options from within the .texi file, but it seems that it does not.

cf. `(info "(texinfo) makeinfo options")` 😕

**Comment by akirak** [comment]
`--paragraph-indent` seems to be more of a personal preference. You probably wish to apply the option to all files, don't you?  And you already can. You can regenerate info files of all install packages that have .texi files on your machine.

**Comment by rnkn** [comment]
No this is just for generating the docs for my own packages.

**Comment by akirak** [comment]
I don't think they would support the option, but good luck!
