### ISSUE TITLE
consider removing package stock-ticker

### ISSUE THREAD

**Issue by Boruch-Baum** [melpa/melpa#7766]
1. The package doesn't work
2. The author hasn't responded to ANY issues EVER for the package, back to year 2016
3. The underlying API (yahoo finance) seems to have been updated many times since the code was written
4. The current incarnation of the underlying API seems to be subscription-based

**Comment by tarsius** [comment]
https://github.com/beacoder/stock-tracker

> The author hasn't responded to ANY issues EVER for the package, back to year 2016

There also was only ever *one* issue opened by anyone but him and that's the one you opened on the same day as you opened this issue.

From that issue (https://github.com/beacoder/stock-tracker/issues/3):

> Could it be that the data is being picked up for a China-version of he US stock instead of the actual direct prices on the US stock exchanges?

That doesn't answer your question fully, I suppose, but the readme contains:

> =stock-tracker= is a simple [[https://money.163.com/stock/][Netease Stock (网易股票)]] interface for Emacs.

Removing the package seems more than a bit premature.

Have you tried contacting him by mail?

**Comment by Boruch-Baum** [comment]
On 2021-11-06 13:32, Jonas Bernoulli wrote:
>    [1]https://github.com/beacoder/stock-tracker
>    ...
>    Removing the package seems more than a bit premature.

Just as long as MELPA is aware and up-to-date with it, I'm fine.

>    Have you tried contacting him by mail?

No. I expected submitting the github issue to do that.

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by tarsius** [comment]
Some people only visit the github webpage sporadically and have chosen to not receive any notifications from github per email. So we have to try to make contact by email.

I don't think there isn't anything that should be done here, so I am closing this.
