### ISSUE TITLE
consider removing package stock-tracker

### ISSUE THREAD

**Issue by Boruch-Baum** [melpa/melpa#7767]
ref: https://github.com/beacoder/stock-tracker/issues/3

I may be jumping the gun on this one a bit. The package functions, but reports garbage data (tested only for US stocks). My guess is that the underlying API reports a Chinese pass-through version of US stocks instead of the actual US exchange prices. BTW, this isn't unique to China; USA regulations require a similar pass-through for investing in foreign companies. If my guess is correct, it could be sufficient to just alter the package documentation to reflect that the package is for domestic Chinese use only.

**Comment by tarsius** [comment]
See #7766.
