### ISSUE TITLE
Advice on package split, possible rename?

### ISSUE THREAD

**Issue by bdarcus** [melpa/melpa#7773]
I maintain the bibtex-actions MELPA package.

I would like to do two things, which I think I should do at the same time. Before I put together the PRs, is this reasonable?

## What I want to do

In order of priority:

1. Split the package
2. rename the repo etc

## Details

The two new recipes would be for the mode-based frontends, and so would allow me to have separate package-requires lines (and autoload commands) for them.

The name change is because the package now handles file formats beyond bibtex; namely JSON, and because I should soon be removing the bibtex-completion dependency, and so want to clearly distinguish it.

## Strategy

My thought is to:

1. update the bibtex-actions recipe to point to the latest commit
2. change the repo and all files and symbol names accordingly, and add three new MELPA recipes, with some transition period, after which the original recipe would be removed. For the MELPA recipes, the main package would then be a subset of elisp files, and would add two new recipes for the remainder..

So in the end, the `bibtex-actions` recipe would become:

- `newname` (minimal dependencies)
- `newname-org` (Org 9.5, newname, embark, citeproc, etc.)
- `newname-latex` (reftex, newname, etc.)

**Comment by ErnestDong** [comment]
Could any tell me how to find the old bibtex-actions on Melpa now?

**Comment by tarsius** [comment]
> Could any tell me how to find the old bibtex-actions on Melpa now?

You cannot do that anymore now. The package is now named `citar`. If you use it under the old name in your configuration, then you have to adjust that.
