### ISSUE TITLE
Change package repo

### ISSUE THREAD

**Issue by joostkremers** [melpa/melpa#7786]
I have a package on Melpa, [`visual-fill-column`](https://github.com/joostkremers/visual-fill-column), that is currently hosted on Github. I would like to move it to another forge (Codeberg.org to be precise). I'm wondering, though, if this could have any negative effects for users of the package (in particular, will their installs be updated automatically if I push a commit to the new forge).

And if I do decide to go ahead with it, how would I go about it?

TIA

**Comment by tarsius** [comment]
You just have to adjust the Melpa recipe and open a pull-request.

**Comment by tarsius** [comment]
I expect we'll see a pull-request soonish. :smiley:
