### ISSUE TITLE
tsc and tree-sitter 1 version behind

### ISSUE THREAD

**Issue by wyuenho** [melpa/melpa#7821]
On stable.melpa, tsc and tree-sitter seems to be 1 version behind for 2 days, is the build bot stuck?

**Comment by milkypostman** [comment]
I'm wondering if it's because the `version-regexp` is set for these. Is there a reason for that?

The bot isn't stuck as far as I can tell.

**Comment by milkypostman** [comment]
I tried removing `version-regexp` from these and they worked. why it works at all is a mystery to me.

**Comment by milkypostman** [comment]
f07a741 fixes things. there is a minor bug in `package-build` and I'll file an issue or send a PR there.

**Comment by milkypostman** [comment]
Also, thanks for the report.
