### ISSUE TITLE
how to test package in sandbox

### ISSUE THREAD

**Issue by mooseyboots** [melpa/melpa#7824]
hi melpa, 

i'm putting together a PR for a package, and trying to make my schtick look spiffy.

contributing.org suggests:

```
You can optionally run a sandboxed Emacs in which locally-built packages will be available for installation along with those already in MELPA:

EMACS_COMMAND=/path/to/emacs make sandbox INSTALL=<NAME>
```
but it's not clear to me how to actually do so. when i run the above, substituting for my emacs binary and package name, i get this error:

`make: *** No rule to make target 'sandbox'.  Stop.`

am i missing something here?

**Comment by akirak** [comment]
Hello @mooseyboots,

I have never run the sandbox command, but are you sure you did run make at the root of the repository? Apparently, `sandbox` target exists in the Makefile.

**Comment by mooseyboots** [comment]
thx for the heads up, it wasn't clear to me where to run the command.

the correct place to run the command is in the root of the (locally cloned) MELPA repo.
