### ISSUE TITLE
does melpa generate loaddefs.el or do I have to do it myself in the package source code?

### ISSUE THREAD

**Issue by Trevoke** [melpa/melpa#7827]
Hi! Question is in the title. Couldn't find the answer anywhere that I looked.

**Comment by milkypostman** [comment]
Are you talking about generating `autoload` statements? If that's correct, then it's done automatically by `package.el` after the package gets installed. Roughly speaking, `package.el` uses some standard way of processing the `.el` file of a package and generates the `pkgname-autoloads.el` file. You can look at wherever the ELPA files are stored and every package automatically has an autoloads file.

I believe that if the package already has an autoloads file then this process is skipped but I think that's discouraged and it's really unnecessary.

Also, I don't know the exact details on how Emacs determines what to put in the autoloads file but I know putting `;;;###autoload` before a function definition causes that function to be added to the autoloads file.

Shorter answer: MELPA doesn't do it and all you need to do is annotate the correct functions for autoload and once it's installed the autoloads file will get generated.

**Comment by Trevoke** [comment]
Okay great, thank you. I had a hard time parsing the emacs documentation around that.

**Comment by milkypostman** [comment]
It’s not just you. I have mostly cribbed the info from others examples. The documentation is sparse in general. 

Glad it helped.
