### ISSUE TITLE
Build process stuck, packages not updated?

### ISSUE THREAD

**Issue by minad** [melpa/melpa#7838]
I updated the Marginalia package yesterday (over 24 hours ago) but the MELPA package has still not been updated. Is there an issue on the MELPA build server?

**Comment by nbarrientos** [comment]
Another data point:

https://melpa.org/#/all-the-icons got a new build on the 25th:

(from the build log)

```
...
Copying files (->) and directories (=>)
  from /mnt/store/melpa/working/all-the-icons/
  to /tmp/all-the-icons5B6BvO/all-the-icons-20211225.506
    all-the-icons-faces.el -> all-the-icons-faces.el
    all-the-icons.el -> all-the-icons.el
    data => data
Created all-the-icons-20211225.506.tar containing:
...
```

However the version available from MELPA is still `20211108.7` (the previous one).

**Comment by milkypostman** [comment]
thanks for the report, looking in to it

**Comment by milkypostman** [comment]
Thank you for the report, here is the summary.

We have a process that periodically (every 5 minutes) scans all the packages and creates an updated `archive-contents` file. This has the benefit of catching new builds before the whole re-building process completes.

Now, I can't say I know much at all about Docker. Somehow the "syncer" process got hosed. It was just completely frozen. I had to forcibly remove the container and restart it. But that does seem to have unwedged the process.

I will think of a better way to be pinged about the server status.

**Comment by victorolinasc** [comment]
Not sure if related to this but getting 404 on all packages it seems...

![image](https://user-images.githubusercontent.com/376386/147490687-319825e2-dd92-49a4-803e-9959280a1133.png)

**Comment by nbarrientos** [comment]
Thanks for taking a look! You guys should seriously consider accepting sponsorship via GitHub or others.
@milkypostman @riscy

**Comment by milkypostman** [comment]
@nbarrientos I will probably setup a patreon in the next few months to help with server costs. But it's complicated to do so. 

In summary I did realize that after all, we did run out of storage on the server again. To avoid this problem I am upgrading the storage system to isolate things and also give us more space.
