### ISSUE TITLE
Does visible-buffer support for idle-highlight-mode make this package obsolete?

### ISSUE THREAD

**Issue by ideasman42** [melpa/melpa#7875]
Hi, I've been updating idle-highlight mode which now supports multiple visible buffers: https://gitlab.com/ideasman42/emacs-idle-highlight-mode see `idle-highlight-visible-buffers`.

For reference both packages:
- https://melpa.org/#/idle-highlight-in-visible-buffers-mode
- https://melpa.org/#/idle-highlight-mode

Seeing as both packages provide similar functionality.

- Would it be reasonable to say it makes this package obsolete (should melpa contain both for example?).
- Or are there reasons to keep both?

**Comment by milkypostman** [comment]
Our policy has typically been to not remove redundant packages, but to avoid accepting new packages that duplicate existing package functionality without significant reason.

My suggestion would be to reach out to @ignacy and see if they're still using and maintaining their package. Despite it not being updated for a few years, there may be people using it and unless the original author says "don't use my package, go use ____ instead cause if this breaks I'm not going to fix it" then I'd just leave the package in MELPA.

I also understand this could be confusing to some users having to decide between packages but I think (at least right now) it's better not to break existing users.

**Comment by ignacy** [comment]
Yeah, sure if it does the same thing already and it will keep doing it in the future we can remove https://melpa.org/#/idle-highlight-in-visible-buffers-mode from the list.

**Comment by ideasman42** [comment]
@ignacy yes, this functionality will be supported.

Note that part of the reason for this task is that `idle-highlight-in-visible-buffers-mode` looks to be unmaintained:

- https://github.com/ignacy/idle-highlight-in-visible-buffers-mode/issues/2 - no reply (since 2018), seems l like a fundamental bug.
- https://github.com/ignacy/idle-highlight-in-visible-buffers-mode/issues/1 - no reply (since 2019).

**Comment by tamwile** [comment]
It is still findable on Melpa.
