### ISSUE TITLE
Broken version strings in some OCaml/merlin related packages

### ISSUE THREAD

**Issue by sheijk** [melpa/melpa#7946]
The version strings of some OCaml/merlin packages cannot be parsed correctly and produce invalid json output. They use a format like 4.4.413 or 4.4.412 for [their releases](https://github.com/ocaml/merlin/releases) which Melpa parses as 4.4.-4.413 (not the negative number).

The packages use -413/-412 postfixes as markers for the OCaml releases they're supposed to be used with (4.13/4.12). 

Affected packages can be found [here](https://stable.melpa.org/#/?q=merlin), also see the version string Melpa produced which contains a negative number (4.4.-4.413).

See also [this bug report for Nix](https://github.com/nix-community/emacs-overlay/issues/178), and [this workaround](https://github.com/NixOS/nixpkgs/pull/154066).

**Comment by purcell** [comment]
> and produce invalid json output

What do you mean by this? Presumably just that _wrong_ version numbers appear in the JSON, not that the JSON is invalid.

> They use a format like 4.4.413 or 4.4.412

Not quite: they look like `v4.4-413`. The versions are parsed by `version-to-list`, for which `4.4-413` looks like a kind of numbered pre-release of `4.4`, hence the negative number. There's not a lot we can do in this case, because fixing this up would require providing a programmable transformation of the original string prior to parsing, and that's unlikely to be something worth us tweaking the MELPA build machinery for.

**Comment by sheijk** [comment]
> > and produce invalid json output
> 
> What do you mean by this? Presumably just that _wrong_ version numbers appear in the JSON, not that the JSON is invalid.

Yes, the version numbers are not as expected.

> Not quite: they look like `v4.4-413`. The versions are parsed by `version-to-list`, for which `4.4-413` looks like a kind of numbered pre-release of `4.4`, hence the negative number. 

I see, changing an Emacs function or Melpa due to this is probably not ideal. I think there is some motion to use a more compatible versioning scheme by the package already.

I'm not sure I follow your explanation of the behavior, though. If "4.4-413" would produce `(4 4 -413)` I'd consider that reasonable but it's producing an extra minus four: `(4 4 -4 413)`. The documentation of version-regexp-alist seems to indicate "4.4-413" is at least not an expected input. Even "4.4alpha3.1beta" gets parsed, again not sure if that's intended, either. I had a look at the source code of version-to-list but it's not obvious what the intent would be here.

**Comment by purcell** [comment]
`-4` is a magic number that connotes something like `snapshot`, `git` or `cvs` according the docs for `version-to-list`.

**Comment by purcell** [comment]
So see the corresponding entry in the version regexp var here:
```
version-regexp-alist is a variable defined in ‘subr.el’.

Its value is
(("^[-._+ ]?snapshot$" . -4)
 ("^[-._+]$" . -4)
 ("^[-._+ ]?\\(cvs\\|git\\|bzr\\|svn\\|hg\\|darcs\\)$" . -4)
 ("^[-._+ ]?unknown$" . -4)
 ("^[-._+ ]?alpha$" . -3)
 ("^[-._+ ]?beta$" . -2)
 ("^[-._+ ]?\\(pre\\|rc\\)$" . -1))
```

**Comment by purcell** [comment]
(Not saying it's useful or correct in any way, of course!)

**Comment by sheijk** [comment]
The Merlin maintainers decided to keep it as is ocaml/merlin#1442. So I guess this issue should get closed, too?
