### ISSUE TITLE
feat(or question): why not add `Readme.org/Readme.md` when building Emacs packages

### ISSUE THREAD

**Issue by younger-1** [melpa/melpa#8076]
When installing packages, the packages from `elpa` will bundle with `Readme.org/Readme.md` while those from `melpa` not.

I notice this when I want to refer to info page of `use-package` (from `melpa`) and it told me that "TODO. For now, see ‘README.md’." but I could not find local file of `readme.md` after doing a `C-x C-f`.  While referring to `vertico` (from `elpa`), it shipped with `readme` file which could be useful.

BYW, comparing https://melpa.org/#/use-package and https://elpa.gnu.org/packages/vertico.html, it may more useful to include in the readme file in package's description page.

**Comment by milkypostman** [comment]
This has been discussed before. Most recently in https://github.com/melpa/melpa/issues/7178
