### ISSUE TITLE
Unmantained packages

### ISSUE THREAD

**Issue by manuel-uberti** [melpa/melpa#8115]
Hi,

I'd like to remove, or move somewhere else like the Emacs Orphanage, the following packages of mine:

- https://github.com/manuel-uberti/doneburn-theme
- https://github.com/manuel-uberti/goto-last-point
- https://github.com/manuel-uberti/slow-keys

They are unmantained. Also, FWIW, whatever new package I might develop it will appear on SourceHut, not on GitHub.

**Comment by milkypostman** [comment]
Do you want to discuss things, move them, or just remove them?

You can send a PR to remove the packages.

I do recognize that maybe `goto-last-point` may have a few dependencies. I'm not sure the best way to hand that.

Anyways, I didn't want to leave you hanging here. I thought maybe we support SourceHut now but maybe I'm misremembering.
