### ISSUE TITLE
Failed to install `tide`

### ISSUE THREAD

**Issue by ndrewtl** [melpa/melpa#8117]
[Tide](https://github.com/ananthakumaran/tide) appears to have a broken dependency

```
Error (use-package): Failed to install tide: https://melpa.org/packages/typescript-mode-20220703.1052.tar: Not found Disable showing Disable logging
Error (use-package): Cannot load tide Disable showing Disable logging
```

**Comment by tarsius** [comment]
As far as I know only the latest build is kept on the server. Do `M-x package-refresh-contents` and then the client and server should agree on what is available.
