### ISSUE TITLE
Some packages missing from archive.json

### ISSUE THREAD

**Issue by progfolio** [melpa/melpa#8153]
Not sure if this is intended or not.
The following packages have recipes in the `recipes` directory, but do not show up in archive.json:

- magit-p4
- magit-stgit
- malancholy-theme
- org-present-remote

Thus, these package do not show up when searching on melpa.org.

**Comment by milkypostman** [comment]
Hrm, I would send pull requests where we can. Are these packages we should remove?

**Comment by tarsius** [comment]
> They all have malformed "Package-Requires" metadata in their package headers:
> org-present-remote
> (string symbol) instead of (symbol string) pair for "web" dependency

@duncan-bayne please fix that. Thanks!

> Both magit packages are in the orphanage.

I've fixed those.

**Comment by duncan-bayne** [comment]
Jonas Bernoulli ***@***.***> writes:

>  They all have malformed "Package-Requires" metadata in their package headers:
>  org-present-remote
>  (string symbol) instead of (symbol string) pair for "web" dependency
>
> @duncan-bayne please fix that. Thanks!

I've raised a TODO here:

https://todo.sr.ht/~duncan-bayne/org-present-remote/1

... and will fix ASAP.  Thanks for the heads-up :)

--
Duncan Bayne
+61 420 817 082 | https://duncan.bayne.id.au/

I usually check my mail every 24 - 48 hours.  If there's something
urgent going on, please send me an SMS or call me.

**Comment by riscy** [comment]
For what it's worth, I'm now checking for this during reviews.

**Comment by duncan-bayne** [comment]
Fixed - apologies for the delay.

**Comment by progfolio** [comment]
Looks like all of the packages I mentioned are now listed properly and this is being checked during reviews.
The only other improvement I can think of is adding some sort of alert to the build system if a package is updated in a way which breaks the dependency declaration (if it doesn't already exist, I haven't checked.)
