### ISSUE TITLE
What to do if package-name is taken?

### ISSUE THREAD

**Issue by xaderfos** [melpa/melpa#8155]
Sorry, I'm sure this is probable naive or obvious, but I have been maintaining a major mode that I always wanted to push to melpa one fine day but in the meantime someone else pushed their own take on the mode with the exact same name and now I guess I just cannot do anything about it?

Do I need to come up with a new name for my mode?
What about the discoverability of it if it is not in the form of 'language-here'-mode?

Sorry for posting an issue for this if not appropriate, I could not figure out how else to contact anyone.

**Comment by milkypostman** [comment]
In the past people have renamed their package or they have merged their changes with the existing mode.

**Comment by akirak** [comment]
@xaderfos There are some examples such as `js2-mode`, `jsonian-mode`, etc. which are alternatives to builtin/well-known libraries.
