### ISSUE TITLE
Requests timing out

### ISSUE THREAD

**Issue by wyuenho** [melpa/melpa#8162]
Melpa has been really slow to load today and connection often times out, is someone monitoring the service?

**Comment by milkypostman** [comment]
Is it still slow? It's loading fine for me.

We don't have an SLO or get pages.

**Comment by bk138** [comment]
Same here. Am based in Germany. Let me know if I can provide any diagnostics.

**Comment by milkypostman** [comment]
https://downforeveryoneorjustme.com/melpa.org

Seems like it's something on your end. 

Hosted in the US.

Is it just consistently slow?

**Comment by bk138** [comment]
> Seems like it's something on your end.

Indeed. Just switched over to mobile Internet and it works now. Must be my landline ISP. OK to close this issue from my side.
