### ISSUE TITLE
per-buffer-theme cannot be build

### ISSUE THREAD

**Issue by tarsius** [melpa/melpa#8182]
I am reporting this here because issues are not enabled on the upstream repository. I also have no account there and creating an account and getting up to speed with hg to report this issue would be a bit much to ask.

Because of the second of these typos in the header, this package cannot be build and is missing from Melpa:

```diff
@@ -1,12 +1,12 @@
 ;;; per-buffer-theme.el --- Change theme and font according to buffer name or major mode.  -*- lexical-binding:t -*-
 
-;; Copyright (C) 2015-20 Free Software Foundation, Inc.
+;; Copyright (C) 2015-2021 Free Software Foundation, Inc.
 
 ;; Author: Iñigo Serna <inigoserna@gmx.com>
 ;; URL: https://hg.serna.eu/emacs/per-buffer-theme
 ;; Version: 2.1
 ;; Keywords: themes
-;; Package-Requires: ((emacs "25.1")
+;; Package-Requires: ((emacs "25.1"))
 
 ;; This file is not part of GNU Emacs.
```

Please fix that and also the compile warnings:

```
per-buffer-theme.el:138:9: Warning: global/dynamic var `pbt~timer' lacks a
    prefix

In pbt~advice-function:
per-buffer-theme.el:207:46: Warning: Unused lexical argument `norecord'
```

The first of these warnings is actually about a bigger issue: You use `per-buffer-theme/` as the prefix or public symbols and `pbt~` for private symbols. This should be `per-buffer-theme-` and `per-buffer-theme--`. Nowadays we would not add this package to Melpa because of that. Please consider following the conventions.

**Comment by progfolio** [comment]
I assume @inigoserna has been contacted about this?

**Comment by tarsius** [comment]
Errr... that was the intention...

**Comment by inigoserna** [comment]
Sorry, I hadn't received any notification regarding this issue until @progfolio mentioned me. I'm not a github user.
Building issues should be solved by now.
I will modify package symbols to adapt to conventions tomorrow.
Thanks for the warning and excuse me again for the late response.

**Comment by tarsius** [comment]
> Sorry, I hadn't received any notification regarding this issue until @progfolio mentioned me. 

Not your fault. There was no way for you to know about this until you got summoned.

**Comment by tarsius** [comment]
Thanks!
