### ISSUE TITLE
Streamline the build process

### ISSUE THREAD

**Issue by purcell** [melpa/melpa#821]
(Adding this issue as a placeholder for ongoing discussion and improvements.)

Rebuilding each unchanged package currently requires around 6 seconds. Now we've reached 1,000 packages, that means a build cycle time of around 2 hours.

A couple of initial ideas:
- For any given package, if its repo, recipe & package-build.el are unchanged, we can skip any parsing / tarring steps etc. So we could keep a hash of the related files plus package-build.
- We could run "quick" and "full" builds at different intervals, where "quick" builds would exclude packages for which the previous MELPA version was (for example) over a year ago.

**Comment by alphapapa** [comment]
Is this still relevant?  If so, would doing the hash-storing and checking belong in package-build.el or in the Makefile or...?

**Comment by purcell** [comment]
Leaning on `make` would be helpful here, but also not very practical currently because the update steps are built into `package-build`, the functions in which mostly run the show.

**Comment by alphapapa** [comment]
Yeah, I looked at the Makefile and couldn't see an obvious way to do it, although since I'm so unfamiliar with it I'm not really qualified to say.  :)

**Comment by APIPLM** [comment]
@tarsius  Thanks. The build process always like gets the latest release of source files of the package, and the repo is in the receipt file from  [Melpa ](https://github.com/melpa/melpa), then run throughout the process.  The receipt file of Melpa does not have the version information, it is pretty hard to do extra actions like the issue https://github.com/nashamri/spacemacs-theme/pull/199 mentioned.

**Comment by tarsius** [comment]
@APIPLM I accidentally linked the wrong issue. This is completely unrelated.

**Comment by tarsius** [comment]
For parallel builds, we have been leaning on `make` for a long time now.
