### ISSUE TITLE
Async package wrongly tagged to 3.8.8 whereas the last tag is 1.9.7

### ISSUE THREAD

**Issue by thierryvolpiatto** [melpa/melpa#8217]
Hello, I wrongly pushed a 3.8.8 tag to Async (https://github.com/jwiegley/emacs-async) but the last tag is 1.9.7, could you remove the 3.8.8 from Melpa stable (https://stable.melpa.org/#/async)?
Thanks.

See Issue https://github.com/jwiegley/emacs-async/issues/155

**Comment by milkypostman** [comment]
I deleted the tag and removed the package. It will take a bit but everything should fix itself. Will check tomorrow morning.

**Comment by thierryvolpiatto** [comment]
Donald Curtis ***@***.***> writes:

> I deleted the tag and removed the package. It will take a bit but everything should fix itself. Will check tomorrow morning.

Great, thanks.

> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.*Message ID: ***@***.***>


-- 
Thierry

**Comment by milkypostman** [comment]
Everything looks good on the website. Thanks!
