### ISSUE TITLE
Melpa down?

### ISSUE THREAD

**Issue by DanielRichtmann** [melpa/melpa#8231]
This may not be the correct place, but it appears that melpa is down. If this issue helps that someone that can do something about it finds out earlier, it was worth it.

**Comment by milkypostman** [comment]
Thanks. I'll have a look.

**Comment by milkypostman** [comment]
I had to restart the server. There was some issue on the host and I'm not really sure what it was. The server itself was running fine and was still building packages. However, nothing could get to the server.

I've added an alert to get an email after 5m of downtime in the future. Thanks for the report and sorry for the inconvenience.
