### ISSUE TITLE
helm-gitignore is recognized as incompat

### ISSUE THREAD

**Issue by conao3** [melpa/melpa#8247]
![image](https://user-images.githubusercontent.com/4703128/199180406-2578e13c-ddc4-406f-92c6-f4491e7d4ddb.png)

Currentry, [helm-gitignore](https://melpa.org/#/helm-gitignore) is recognized as `incompat` by package.el.
Maybe `gitignore-mode` renames to [git-mode](https://melpa.org/#/git-modes)...?

Anyway, just I want to notify this issue. Thanks.

**Comment by tarsius** [comment]
https://github.com/jupl/helm-gitignore/pull/6

**Comment by tarsius** [comment]
Melpa now gets this from the orphanage.
