### ISSUE TITLE
EricCrosson archived his packages

### ISSUE THREAD

**Issue by tarsius** [melpa/melpa#8253]
@EricCrosson you have archived the repositories of your Emacs packages, which are distributed on Melpa. I am contacting you here because issues are closed on archived repositories.

Have you moved these repositories? Are these packages still potentially useful to some users? Or should they be removed from Melpa?

**Comment by EricCrosson** [comment]
Hi @tarsius,

I have not moved these repositories, I only archived them to indicate that I am no longer actively maintaining them. These packages are still potentially useful to some users, including myself, but future development may make more sense in forks.

**Comment by EricCrosson** [comment]
Thanks for laying out these options, @tarsius. I will take a look at each package I've uploaded to melpa and handle it on a case-by-case basis. I have a feeling most will go to the orphanage. Is there anything to the process, other than transferring the repository from my user to the organization?

**Comment by tarsius** [comment]
> Is there anything to the process, other than transferring the repository from my user to the organization?

You will have to transfer it to my personal account, because it is not possible to transfer to an organization you are not a member of. (Doesn't make sense because you also do not have access to my personal account; but it is what it is.) I will then transfer it from there to the orphanage.

The Melpa recipe also has to be updated, but I'll take care of that.

**Comment by EricCrosson** [comment]
I transferred two repositories and unarchived the other two

**Comment by tarsius** [comment]
Thanks!
