### ISSUE TITLE
Don't pin melpa/.github repository

### ISSUE THREAD

**Issue by tarsius** [melpa/melpa#8265]
It doesn't make sense to pin `melpa/.github` at https://github.com/melpa. It is a metadata repository that is irrelevant to most people. People who want to visit it anyway, can do so by clicking on the respective entry in the "regular" list of repositories right below.

Very minor I know, but I was hoping that one of the only two people who can fix it, @milkypostman and @purcell, would do so eventually. That still hasn't happened, so I am sending you this note.

**Comment by tarsius** [comment]
Friendly ping!

On a similar note, should we really pin #8216? It's not like this comes up all the time and/or we plan to do anything about it any time soon. Putting the spotlight on it, just increases the odds that we end up having to invest time doing something that we would rather delay until we ourselves conclude that is the right thing to do *and* that we have the time and motivation to do it.

**Comment by tarsius** [comment]
Looking through some open issues...
@milkypostman @purcell I don't care *much* about this but could you please spare a few clicks to get this done soon? Or if you disagree, close this issue.

**Comment by milkypostman** [comment]
This is fixed now. But just a heads up that these were auto selected by Github and I solved by forcibly pinning only melpa and package-build.

**Comment by tarsius** [comment]
Yeah, I figured it was pinned automatically.

Thanks!
