### ISSUE TITLE
RSS feed in Stable points to melpa.org instead of stable.melpa.org

### ISSUE THREAD

**Issue by louis77** [melpa/melpa#8275]
As can be seen in https://stable.melpa.org/updates.rss:

<img width="654" alt="Bildschirm­foto 2022-11-15 um 23 44 41" src="https://user-images.githubusercontent.com/1240462/202041437-b398570e-3ac0-4629-8513-435757a3ef7e.png">

**Comment by milkypostman** [comment]
Should be fixed by https://github.com/melpa/melpa/commit/275d4234e587f6e19d0c0701e02749886a31f4e9
