### ISSUE TITLE
The service is down?

### ISSUE THREAD

**Issue by dimitarvp** [melpa/melpa#8311]
I tried from two networks and melpa.org does not seem to be there. Various down detectors confirm it.

What's going on? Can we rely on it coming back soon-ish?

**Comment by averageflow** [comment]
I'm also experiencing issues since yesterday evening (Amsterdam time).
Some deployment went wrong ? Also saw "0 packages" for a while.. very weird

**Comment by louis77** [comment]
Same here from different DNS incl. 8.8.8.8, 9.9.9.9 etc.

**Comment by milkypostman** [comment]
Thanks for the report. I'm investigating.

**Comment by milkypostman** [comment]
I checked logs and it looks like our host was having some network issues. I suspect I may need to restart our host if this persists. I'll leave this bug open until this evening CST and see how things go.
