### ISSUE TITLE
editorconfig not installable from MELPA using M-x package-install

### ISSUE THREAD

**Issue by glyn** [melpa/melpa#8331]
The editorconfig plugin is [listed](https://melpa.org/#/editorconfig) in MELPA, but when I try installing it:
```
M-x package-install
editorconfig
```
emacs prompts me to complete the package name to one of the following:
* editorconfig-charset-extras
* editorconfig-domain-specific
* editorconfig-custom-majormode
* editorconfig-generate

`M-x list-packages` shows these packages are coming from MELPA:
<img width="982" alt="Screenshot 2022-12-21 at 11 53 06" src="https://user-images.githubusercontent.com/94953/208899344-8b9f8094-1e65-4d2a-96dc-1cce0ffa568b.png">

I tried running `M-x package-refresh-contents`, but the package still wasn't found.

I am running emacs 28.2 (build 1, aarch64-apple-darwin21.1.0, NS appkit-2113.00 Version 12.0.1 (Build 21A559))
 of 2022-09-12 on macOS 12.6.1 on a Macbook Air M1.

See also [editorconfig issue 284](https://github.com/editorconfig/editorconfig-emacs/issues/284) where this problem was initially discussed.

**Comment by glyn** [comment]
Update: I searched further down the list of packages (`M-x package-list-packages`) and found editorconfig and was then able to install it. Uninstalling it then reproduced the above problem behaviour *except* that editorconfig now appears in the correct position in the list - just before editor-config-charset-extras. So the problem still exists, but at least I now have a way of installing editorconfig.

**Comment by milkypostman** [comment]
Hey @glyn I just went to my Emacs, version 28.2, and I installed `emacsclient` from the list. So I'm not sure how to reproduce this. I deleted, then re-installed, and still no error.

Maybe it's been resolved?

**Comment by glyn** [comment]
@milkypostman This issue relates to `editorconfig`, not `emacsclient`.

**Comment by milkypostman** [comment]
Sorry, this is what i meant.

**Comment by glyn** [comment]
Oh I see. I can install from the list, but not using `M-x packages-install`. I am assuming this is a problem with melpa rather than a basic bug in emacs, but I could be wrong.

**Comment by milkypostman** [comment]
Oh I see. Sorry I misread the bug. Let me try that. 

Actually it sounds more like a bug with package.el to me.

**Comment by akirak** [comment]
`editorconfig` package is available in the archive contents: https://melpa.org/packages/archive-contents. Hope it helps.

**Comment by glyn** [comment]
@akirak Thanks. I'll change the title of this bug to make it clearer.

**Comment by milkypostman** [comment]
The code for `package-install` has the following logic,

```
     (package--archives-initialize)
     (list (intern (completing-read
                    "Install package: "
                    (delq nil
                          (mapcar (lambda (elt)
                                    (unless (package-installed-p (car elt))
                                      (symbol-name (car elt))))
                                  package-archive-contents))
                    nil t))
           nil)))
```

And so if the package is already installed, it won't show up with `package-install`.

I think this is working as intended.

**Comment by glyn** [comment]
I tried reproducing again and I cannot. I think I must have had two different versions of editorconfig installed at the same time, so deleting one left the other around and produced the expected behaviour. Apologies for wasting everyone's time.

**Comment by milkypostman** [comment]
@glyn Very likely if you went to `package-list-packages` indeed there were two versions listed. One was installed, and other was a newer version. It makes it look like the package is not installed and was indeed confusing to me at first too.

**Comment by glyn** [comment]
Yes, I think the fact that the list of packages isn't simply sorted by package name is the most confusing part. One has to keep searching further than expected to find installed packages.
