### ISSUE TITLE
Does not work correctly in Russia

### ISSUE THREAD

**Issue by pank-su** [melpa/melpa#8397]
I can't download packages and website (melpa.org and stable.melpa.org) does not show package without VPN.

![image](https://user-images.githubusercontent.com/49202787/218050232-ebc30af2-843f-496d-8c3d-a3d28f06af6e.png)
![image](https://user-images.githubusercontent.com/49202787/218050517-9adbb1b8-46bc-44fd-99a9-7c4cbb3842ab.png)

With VPN:

![image](https://user-images.githubusercontent.com/49202787/218050722-9d0aa4a1-7a52-4ab9-90b1-a6f1bdda93b1.png)
![image](https://user-images.githubusercontent.com/49202787/218051944-548449c2-52be-4676-a0a1-d1c11ef74c9b.png)

**Comment by LewWadoo** [comment]
I use a mirror as a workaround:
```emacs-lisp
("melpa" . "http://mirrors.tuna.tsinghua.edu.cn/elpa/melpa/")
```
