### ISSUE TITLE
Request to take over maintenance of org-noter

### ISSUE THREAD

**Issue by petermao** [melpa/melpa#8413]
@dmitrym0 and I would like to take over maintenance of @weirdNox's [org-noter](https://github.com/weirdNox/org-noter) package.

- The last commit from the author (Gonçalo Santos) is dated November 10, 2019.
- I have tried to contact GS via email (December 7, 2022).
- Dmitry opened https://github.com/weirdNox/org-noter/issues/173 on January 31, 2023.
- We have heard no word from him, so I believe at this point, we fall under the "author is unresponsive" category in https://github.com/melpa/melpa/wiki/Unmaintained-Packages-and-Forks.

The package did need some attention.  Two others (@c1-g and @ahmed-shariff) made significant improvements since GS's last commit; however, the code was a not fully functional where they left off.  Dmitry and I have done a lot of work to debug the code, introduce CI tests, and refactor the note insertion code.  We believe that at this point, our forks of the code (which we periodically merge) are stable, maintain the original flavor of org-noter, and bring in some features that would benefit users.

 As for our credibility/community involvement/elisp chops -- Dmitry is the author/maintainer of [org-hyperscheduler](https://github.com/dmitrym0/org-hyperscheduler), and I am the author/maintainer of [look-mode](https://github.com/petermao/look-mode).  In addition, I recently made contributions to [num3-mode on ELPA](https://elpa.gnu.org/packages/num3-mode.html).

My fork of org-noter: https://github.com/petermao/org-noter
Dmitry's fork: https://github.com/dmitrym0/org-noter-plus

Presently, my fork is 20 commits ahead -- mostly changes impelled by flycheck.

**Comment by tarsius** [comment]
Seems like a good course of action to me. @riscy?

Was this ever part of `org-contrib`, i.e., of Org itself before those contributed libraries were split into the separate `org-contrib` repository and package? If so, you should probably also bring this on the Org mailing list.

**Comment by tarsius** [comment]
(And sorry for not replying earlier.)

**Comment by petermao** [comment]
I don't think this was/is part of `org-contrib`.  Is it worth mentioning the pending change of maintainership, or would that just be spam on that mailing list?

**Comment by tarsius** [comment]
No, I don't think that would be considered spam. Maybe it would spark someone's interest and you would gain a co-maintainer. The Org maintainers themselves might not comment though, but that doesn't mean they consider it useless noise.

**Comment by riscy** [comment]
Yes, apologies for the delay (I'm usually over in the pull requests tab and don't look here as often).  Thank you @petermao for the thoughtful write-up; I'm totally on board with this. :)

**Comment by petermao** [comment]
Thanks, Jonas & Chris.  Dmitry and I will make a PR soon.  I'll also let the Org maintainers know about the change.

**Comment by petermao** [comment]
closed with acceptance of PR #8445
