### ISSUE TITLE
Badge does not update

### ISSUE THREAD

**Issue by laishulu** [melpa/melpa#8422]
https://melpa.org/#/sis

Badge does not update to the latest version.

Build log says:
```
Package: sis
Fetcher: github
Source:  https://github.com/laishulu/emacs-smart-input-source.git

Updating /mnt/store/melpa/working/sis/
Checking out b1f8e11fe40d13bcaf554635aed005415968853d
Searching for program: No such file or directory, convert
```

**Comment by tarsius** [comment]
@milkypostman I forgot to ask you to install `imagemagick`, when I [changed](https://github.com/melpa/package-build/commit/c68ffb3616fd344bc425390a6d1d3561856ce6db) `package-build` to use that to generate the badges, instead of relying on an external service. Could you please do that now? Thanks!

**Comment by milkypostman** [comment]
OK, should be good to go now.

I upgraded nginx while I was at it and we're now using a more modern Debian for building. Stable. Hopefully that doesn't mess anything up.

**Comment by tarsius** [comment]
Thanks!
