### ISSUE TITLE
Proposed advice for package-compute-transaction does not fix the problem

### ISSUE THREAD

**Issue by wolfmanx** [melpa/melpa#8461]
In section *Dependency order is reversed* at

https://github.com/melpa/melpa/blob/6205f77bbb6c3a44146110f2a0e293cdf4280228/html/partials/getting-started.html#L137

A piece of advice is shown, which is supposed to fix a problem with `package-compute-transaction` in Emacs 24.

With multiple dependencies, this advice does not work correctly. With the following advice, the dependency order comes out exactly as in later versions of package.el:

```elisp
  (defadvice package-compute-transaction
      (around package-compute-transaction-fix activate)
    "Fix order of requirements."
    (let ((package-list (ad-get-arg 0)))
      (let (package-list)
        (ad-set-args 0 (list nil  (ad-get-arg 1)))
        ad-do-it)
      (dolist (elt (nreverse ad-return-value))
        (setq package-list (cons elt (delq elt package-list))))
      (setq ad-return-value package-list))))
```

BTW,  that is not the only problem with old Emacsen. In pursuing the goal to have a single `package-user-dir` with byte code in version sub-directories for all the versions of Emacs that I still encounter during Administration (23.4, 24.3, 24.5, 25.2, 26.3, 27.1)  I found quite some issues that can be fully back-ported with defadvice and a couple of compatibility definitions . See [package-compat](https://almost-un.org/selpa/#/package-compat).

**Comment by tarsius** [comment]
> See [package-compat](https://almost-un.org/selpa/#/package-compat).

There's also [`package-fixes`](https://git.savannah.gnu.org/cgit/emacs/elpa.git/log/?h=externals/package-fixes) in the GNU Elpa repository. It never got released and with every passing year it becomes less important to do so. But if you care enough about this, then I think it would be better to get that releases (by bumping the `Version` library header to something greater than `0`), than to write another compatibility package in the same spirit. If you have other improvements/backports, then suggest merging those as well.

On the other hand, IMO, the time has come to stop supporting Emacs releases that are so ancient, they don't even come with `package.el` built in.

**Comment by wolfmanx** [comment]
If I had any say in the matter of the installed Emacs version on the machines I must support for a living, I would wholeheartedly agree with you. Alas, my voice doesn't count. :cry: 

If a feature may be of common interest, I will invest the extra effort to make it work beyond my specific use cases (as I did with the Mercurial patch). However, I usually do not have the resources to get caught up in a lengthy review process.

When I started looking into `package.el`, I used the above mentioned advice. Expecting I would end up with a working solution, it did cost me quite some time to realize that the order of dependencies is not corrected at all by simply reversing the result. After spending some time to fix that, I found, that  the compilation for the depending packages still failed, since  the dependencies were not activated.

So, replacing the misleading advice for `package-compute-transaction` with a correct solution will help out the next guy who tries to do this without completely tumbling in the dark. Maybe even removing all mention of old things is helpful in not getting anybody's hope up too high. :smile:

I did look at [package-fixes](https://git.savannah.gnu.org/cgit/emacs/elpa.git/log/?h=externals/package-fixes)  and the first thing I noticed is that it uses  `-*- lexical-binding: t; -*-`, which means it won't load in Emacs 23.4. It also provides only a bare minimum of fixes (e.g, it does not back-port the `no-byte-compile: t` file local variable). My solution needs a lot of monkey patching, which I don't think is ever going to be accepted in a reviewed package. This patching, however, is necessary to make the final goal in`package-version-dir.el` not only possible but actually useful -- to get a distributable `package-user-dir` without unnecessarily byte-compiled -PKG.el files:

    ┌ elpa
    └┬ the-package-date.time
     ├─ the-package.el
     ├─ the-package-pkg.el
     ├┬ 23.4
     │└─ the-package.elc
     ├┬ 26.3
     │└─ the-package.elc
     └┬ 27.1
      └─ the-package.elc

I only wrote this package, since all I found were questions about how to do it with `package.el`, but not a single feasible solution.

I don't necessarily wish to advertise my packages, I only need a distribution mechanism for various Emacs Lisp packages in my daily work  (among other things, I need to control that http is still supported). I started my own home brew distribution system with Emacs 18/19/20 and it is entirely idiomatic. After noticing the advent of user-emacs-directory around v22, I basically ignored it until I finally decided 3 weeks ago to run a melpa clone to henceforth experience the eternal sunshine of the spotless mind. :smile: 

I know, that my use case is quite esoteric, which is why I do not offer things like the [minimal compatibility patch](https://github.com/wolfmanx/melpa/commit/6ac02bb500c49fc9a57dbe8a20ae3232f0131d9c) to make `package-build.el` run on Emacs 25 again as I saw it recently officially declared unsupported. However, for me it is still faster to slap in the definitions for `if-let*` and `when-let*`, so I don't have to go through a full OS update for my bionic server with Emacs 25.2 which happens to house my melpa instance.

**Comment by tarsius** [comment]
> So, replacing the misleading advice for package-compute-transaction with a correct solution will help out the next guy who tries to do this without completely tumbling in the dark. Maybe even removing all mention of old things is helpful in not getting anybody's hope up too high. 

Could you please open a pr for that?

For what it's worth I've made a push to maybe get `package` itself on GNU ELPA: https://lists.gnu.org/archive/html/emacs-devel/2023-03/msg00995.html.

**Comment by wolfmanx** [comment]
> Could you please open a pr for that?

I will.

**Comment by wolfmanx** [comment]
> For what it's worth I've made a push to maybe get `package` itself on GNU ELPA: https://lists.gnu.org/archive/html/emacs-devel/2023-03/msg00995.html

It seems like a good idea (since that is, what I basically did :wink:) ... so I have read into that thread, and my first impression notes are:

Having `package` available on ELPA for older Emacsen will definitely require most if not all the compatibility definitions (not most of the advice though) that I have collected in [package-compat.el](https://almost-un.org/kallithea/public/unorg-init/files/e0c4d1b88b5702f09eba287045277a9c1f029c1c/.emacs.def/compat/package-compat.el).

This is caused by the chicken-and-egg bootstrap problem, that any non-backward-compatible augmentation to the package.el functionality must be handled **before any other package** is activated. That's why I had to prepare an entire `early-init.el` with its own compatibility definitions to search for and load the `package` augmentation package.

This also means that for `package` other packages like `compat` -- which again relies on `seq` -- are not entirely useful as dependencies, since you would basically reproduce a considerable part of the `package` functionality (necessarily) without or with a minimal set of compatibility definitions anyway before finally activating the augmented `package` and have it do the full-fledged thing. It also complicates the installation process (marginally), since the dependencies and `package` will have to be installed twice (the second time with the enhanced version of `package` activated).

This unavoidable bootstrap process for `package` is basically beyond the capabilities of an everyday Emacs user.

The actual solution to the problem would have been to establish a stable `package` core from the get go without any perceived modern traits that is able to bootstrap itself from a package. And this is still the correct solution, since 10 years from, when all the incorrigible Emacs version have died out, the remaining elder citizens will all be able to bootstrap that latest and greatest `package` as package.

I actually provide
-  an ancient package.el,
-  the compatibility definitions to give old Emacsen modern package functionality,
-  and the **backward-incompatible** version sub-dir enhancement

as a single package that is activated before `package-init` is called (since it would not make any sense otherwise). On my lonely last Emacs 23.4 instance I had to do a manual initial download, but on all other versions (24.3, 24.4, 25.2, 26.3, 27.1) the bootstrap process went flawlessly with a simple `(package-install 'package-compat)` followed by deleting the package and doing another `(package-install 'package-compat)` (this time with all the bells-and-whistle extensions activated).

So it might still be a good idea to inspect my working solution, before getting lost in theory and finally running into all the same dead ends as I did.

One contributor said, that it was impossible to correct the mistakes of the past, which I find very strange, since I have been playing this game with Emacs since version 18. Each new version brought on a host of incompatibilities, that were  very simple, albeit in some cases very ugly, to correct. E.g.:

```elisp
;; (progn (forward-line 1) (snip-insert "el_compat.with-demoted-errors-f" t t "el" " --key skip_for_update") (insert "\n"))
(eval-and-compile
  ;; what a mess ... 23.4 - 26.x
  ;; `with-demoted-errors' fails, if it has a mandatory argument `format',
  ;; `macroexpand' is used, so the expected failure does not show up in *Messages*,
  ;; who wants to see obsolete warnings?
  (unless (fboundp 'with-demoted-errors-f)
    (if (and (fboundp 'with-demoted-errors)
             (not (ignore-errors (macroexpand '(with-demoted-errors)))))
        (defalias 'with-demoted-errors-f 'with-demoted-errors)
      (defmacro with-demoted-errors-f (format &rest body)
        (declare (debug t) (indent 1))
        `(,(if (fboundp 'condition-case-unless-debug)
               'condition-case-unless-debug
             'condition-case-no-debug)
          err
          (progn ,@body)
          (error (message ,format err))))))
  (unless (fboundp 'ignore-errors-verbose)
    (defmacro ignore-errors-verbose (&rest body)
      (declare (debug t) (indent 0))
      `(with-demoted-errors-f "error: %s (ignored)" ,@body)))
  (unless (get 'lexical-binding 'safe-local-variable)
    (put 'lexical-binding 'safe-local-variable 'booleanp))
  (defalias 'symbol-tag-pp-to-string
    #'(lambda (o &optional e n) (pp-to-string o))))
```

 I just recently got rid of all the FSF Emacs/Xemacs compatibility stuff I had been dragging along for 2 or 3 decades :joy: 
 
And then there is the adjacent problem of `emacs` version dependencies (instead of more accurate feature dependencies). Just to be able to load some packages in Emacs 23.4, I had to prepare an Emacs version spoofing facility to fake the Emacs version to 24.4, which I will probably need for other packages that claim not to work with older Emacsen. :wink:
