### ISSUE TITLE
Something wrong with melpa.org and stable.melpa.org

### ISSUE THREAD

**Issue by doublep** [melpa/melpa#8515]
I released package Logview 0.16.1 yesterday. However, the release is still not on `stable.melpa.org`. I tried investigating a bit and found a lot of confusing results.

Page https://melpa.org/#/logview ("unstable") currently shows an old version 20221206.1843, but new 2023... on the badge. In Emacs package manager (`package-list-packages`) the new 2023... is indeed available.

Page https://stable.melpa.org/#/logview also shows old 0.16, but new 0.16.1 in the badge. However, in Emacs package manager (`package-list-packages`) the new 0.16.1 is *not* available.

If you go to https://melpa.org/#/?sort=version&asc=false (sorted by versions in descending order), it claims that the latest versions are from 27.04, not 29.04 as one would expect.

So, something is definitely not correct.

**Comment by milkypostman** [comment]
I think something may be outputting incorrect JSON data,

```
# make html/archive.json
 • Updating packages/archive-contents ...
 • Building html/archive.json ...
Bad JSON object key: nil
make: *** [Makefile:103: html/archive.json] Error 255
```

**Comment by milkypostman** [comment]
One example is,

```
((auto-complete (1 3 1)) (flycheck-dmd-dub (0 7))) "Auto Completion source for dcd for GNU Emacs" single ((:commit . "56d9817159acdebdbb3d5499c7e9379d29af0cd4") (:authors (nil . "<atila.neves@gmail.com>")) (:maintainers (nil . "<atila.neves@gmail.com>")) (:maintainer nil . "<atila.neves@gmail.com>") (:keywords "languages") (:url . "http://github.com/atilaneves/ac-dcd"))])
```

atilaneves/ac-dcd package is creating maintainers and [authors with a nil field](https://github.com/atilaneves/ac-dcd/blob/56d9817159acdebdbb3d5499c7e9379d29af0cd4/ac-dcd.el#L3), but the JSON dump function doesn't understand this.

@tarsius I can try to fix this later (sorry I am with family right now) but for now it means our website will be out of date.

**Comment by tarsius** [comment]
spending the weekend with family too

**Comment by milkypostman** [comment]
Thanks Jonas!
