### ISSUE TITLE
Melpa and Melpa Stable are not updating elixir-mode

### ISSUE THREAD

**Issue by victorolinasc** [melpa/melpa#8593]
Hi people! 

I'm one of the maintainers of  `elixir-mode`. I see that the recipes are okay, but versions are not updating. For example, MELPA is currently in version 20221017.2044 but last commit is from February/2023. 

![image](https://github.com/melpa/melpa/assets/376386/4afe937c-0acf-451c-9ed5-f6033c9e10a1)

Stable is **also not picking up last versions**. I've tagged 2.4.0 and 2.4.1 this week but it is not building somehow. 

![image](https://github.com/melpa/melpa/assets/376386/ad1192cf-f8ab-401f-a693-a523fbddcd01)

I know it is not an issue here, but it seems that NonGNU is ALSO not updating :)

Is there anything I can do on my end to help debug?

Sorry to bother here... but couldn't find any other place for information. 

Thanks for your awesome work!

**Comment by milkypostman** [comment]
Thanks for the report. I will have a look. 

We've had some occasional build snafus so may just need a nudge.

**Comment by milkypostman** [comment]
@tarsius I think there is something wrong with syncing, likely related to the "only check something out once" change.

Hard to find examples but my current repro is that if I go into a working directory and get a detached branch at an old commit, making the recipe doesn't update the repro as I would expect, and the revision we get is the old one.

**Comment by milkypostman** [comment]
Actually the repro is just that for some reason it doesn't want to check out the latest version from head when I do,

```
make recipes/elixir-mode
```

The output is,

```
> make recipes/elixir-mode
 • Building package elixir-mode ...
Package: elixir-mode
Fetcher: github
Source:  https://github.com/elixir-editors/emacs-elixir.git

Updating /mnt/store/melpa/working/elixir-mode/
Checking out 4974ff9a83daf50f2f03dc0d6d00871296e088b0
Copying files (->) and directories (=>)
  from /mnt/store/melpa/working/elixir-mode/
  to /tmp/elixir-modegQsr9G/elixir-mode-20221017.2044
    elixir-format.el -> elixir-format.el
    elixir-mode.el -> elixir-mode.el
    elixir-smie.el -> elixir-smie.el
Created elixir-mode-20221017.2044.tar containing:
  elixir-mode-20221017.2044/
  elixir-mode-20221017.2044/elixir-format.el
  elixir-mode-20221017.2044/elixir-mode-pkg.el
  elixir-mode-20221017.2044/elixir-mode.el
  elixir-mode-20221017.2044/elixir-smie.el
Built elixir-mode in 0.999s, finished at 2023-06-15T01:07:27+0000
 ✓ Success:
4.0K -rw-r--r-- 1 root root 284 Jun 15 01:07 packages/elixir-mode-20221017.2044.entry
 72K -rw-r--r-- 1 root root 70K Jun 15 01:07 packages/elixir-mode-20221017.2044.tar
```

**Comment by milkypostman** [comment]
I just deleted the `elixir-mode` directory and re-created, and for some reason it's still using the 2022-10-17 commit.

Oh, @victorolinasc is this because you didn't actually touch any of the lisp files in the newer commits?

**Comment by milkypostman** [comment]
I see. @victorolinasc , the versioning is based on the last time one of the package files was updated.

- `elixir-mode.el` was last updated Oct 17, 2022
- `elixir-smie.el` and `elixir-format.el` were a long time before that.

So I think this is all working as intended.

**Comment by victorolinasc** [comment]
@milkypostman thanks a lot for all your support! Maybe this should be documented somewhere? I could try and open a PR if that is welcome.

Thanks a lot!
