### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by MathieuDutSik** [melpa/melpa#8618]
I want to use MELPA for installing Emacs related software. I do the following on emacs 28.2:
`M-x package-install [RET] lsp-mode [RET]`
and I get following error
https://melpa.org/packages/markdown-mode-20211022.55.el: Not found

So, it seems that the MELPA database is not consistent.

**Comment by milkypostman** [comment]
I think you need to sync your local package info. The current version of LSP mode is 20230625 and I verified the website and archive-contents both list that version.

**Comment by MathieuDutSik** [comment]
> I think you need to sync your local package info. The current version of LSP mode is 20230625 and I verified the website and archive-contents both list that version.

Ok, thanks I found the way. I did `package-refresh-contents` and then it worked.
Possibly it would be nice to suggest doing a refresh if such an error occurs.
