### ISSUE TITLE
2023 Server Upgrade Tracking Bug

### ISSUE THREAD

**Issue by milkypostman** [melpa/melpa#8632]
Filing an issue here to track anything related to upgrading the server.

I am currently running two instances of MELPA. I will be migrating the DNS records soon and this will require generating a new SSL certificate.

**Comment by milkypostman** [comment]
just posted a tweet: https://twitter.com/melpa_emacs/status/1677090973791166466?s=20

Going to switch IPs now. Should be seamless but we'll see :)

**Comment by milkypostman** [comment]
Just FYI: DNS TTL is 15 minutes.

**Comment by milkypostman** [comment]
Site seems to be doing well. Transition has happened.

**Comment by milkypostman** [comment]
I've turned off the old server. I will leave it for the hour. Then delete it and clean things up.

**Comment by jcs090218** [comment]
Is the migration still going on? 🤔  Keep getting the error:

```
error in process sentinel: Error retrieving: http://melpa.org/packages/archive-contents "incomprehensible buffer"
```

**Comment by milkypostman** [comment]
I haven't heard of any other problems and so by now I'd expect many reports if we were broken. 

Which eMacs version and what's the repro steps?

Can you try removing your elpa directory and starting from scratch?

**Comment by jcs090218** [comment]
Oh, okay. I guess the new IP is blocked by the [Malwarebytes](https://www.malwarebytes.com/) for some reason. 🤔 Adding it to allow list solves the issue.

**Comment by milkypostman** [comment]
Ah great to hear. No idea what that is.

**Comment by petermao** [comment]
Not sure if this is related, but the [website](https://melpa.org/#/) "downloads" odometer is stuck at 325,767,881.

**Comment by purcell** [comment]
Maybe the logprocessor service is not running on the new machine? I'm not actually sure how the services are configured on the new host.

**Comment by milkypostman** [comment]
oh this was due to my forgetting to actually fix the python path in the logprocessor run script. 4d787fbfd3b555a637cae7c5b352900ffd1f5eaa should fix this. will take a while. Will check in later today.

**Comment by milkypostman** [comment]
OK. It now says 325,894,326. So I think we're good. Thanks for reporting.

**Comment by milkypostman** [comment]
alright. this bug is done.
