### ISSUE TITLE
"invalid-read-syntax" when loading autoloads generated by package-unpack for MELPA package

### ISSUE THREAD

**Issue by QiangF** [melpa/melpa#8686]
Emacs version is 29.1, one such package is unicad, the backtrace is

    Debugger entered--Lisp error: (invalid-read-syntax "#" 22 34)
      read(#<buffer  *load*-765405>)
      eval-buffer(#<buffer  *load*-765405> nil "/home/q/.emacs.d/elpa/unicad-20200914.1500/unicad-autoloads.el" nil t)  ; Reading at buffer position 734
      load-with-code-conversion("/home/q/.emacs.d/elpa/unicad-20200914.1500/unicad-autoloads.el" "/home/q/.emacs.d/elpa/unicad-20200914.1500/unicad-autoloads.el" nil t)
      #<subr load>("/home/q/.emacs.d/elpa/unicad-20200914.1500/unicad-autoloads" nil t nil nil)
      apply(#<subr load> ("/home/q/.emacs.d/elpa/unicad-20200914.1500/unicad-autoloads" nil t))
      load("/home/q/.emacs.d/elpa/unicad-20200914.1500/unicad-autoloads" nil t)
      package-activate-1(#s(package-desc :name unicad :version (20200914 1500) :summary "An elisp port of Mozilla Universal Charset Auto Detector" :reqs ((emacs (24)) (nadvice (0 3))) :kind nil :archive nil :dir "/home/q/.emacs.d/elpa/unicad-20200914.1500" :extras ((:url . "https://github.com/ukari/unicad") (:keywords "i18n") (:maintainer "Qichen Huang" . "unicad.el@gmail.com") (:maintainers ("Qichen Huang" . "unicad.el@gmail.com")) (:authors ("Qichen Huang" . "unicad.el@gmail.com")) (:commit . "a5fd4e326a0607acc3776c11f41826e60b6486c6")) :signed nil) :reload :deps)
      package-unpack(#s(package-desc :name unicad :version (20200914 1500) :summary "An elisp port of Mozilla Universal Charset Auto Detector" :reqs ((emacs (24)) (nadvice (0 3))) :kind tar :archive "melpa" :dir nil :extras ((:commit . "a5fd4e326a0607acc3776c11f41826e60b6486c6") (:authors ("Qichen Huang" . "unicad.el@gmail.com")) (:maintainers ("Qichen Huang" . "unicad.el@gmail.com")) (:maintainer "Qichen Huang" . "unicad.el@gmail.com") (:keywords "i18n") (:url . "https://github.com/ukari/unicad")) :signed nil))
      #f(compiled-function () #<bytecode 0x7e51e71e0911ba8>)()
      package--with-response-buffer-1("http://mirrors.bfsu.edu.cn/elpa/melpa/" #f(compiled-function () #<bytecode 0x7e51e71e0911ba8>) :file "unicad-20200914.1500.tar" :async nil :error-function #f(compiled-function () #<bytecode 0x198000153e91>) :noerror nil)
      package-install-from-archive(#s(package-desc :name unicad :version (20200914 1500) :summary "An elisp port of Mozilla Universal Charset Auto Detector" :reqs ((emacs (24)) (nadvice (0 3))) :kind tar :archive "melpa" :dir nil :extras ((:commit . "a5fd4e326a0607acc3776c11f41826e60b6486c6") (:authors ("Qichen Huang" . "unicad.el@gmail.com")) (:maintainers ("Qichen Huang" . "unicad.el@gmail.com")) (:maintainer "Qichen Huang" . "unicad.el@gmail.com") (:keywords "i18n") (:url . "https://github.com/ukari/unicad")) :signed nil))
      mapc(package-install-from-archive (#s(package-desc :name unicad :version (20200914 1500) :summary "An elisp port of Mozilla Universal Charset Auto Detector" :reqs ((emacs (24)) (nadvice (0 3))) :kind tar :archive "melpa" :dir nil :extras ((:commit . "a5fd4e326a0607acc3776c11f41826e60b6486c6") (:authors ("Qichen Huang" . "unicad.el@gmail.com")) (:maintainers ("Qichen Huang" . "unicad.el@gmail.com")) (:maintainer "Qichen Huang" . "unicad.el@gmail.com") (:keywords "i18n") (:url . "https://github.com/ukari/unicad")) :signed nil)))
      package-download-transaction((#s(package-desc :name unicad :version (20200914 1500) :summary "An elisp port of Mozilla Universal Charset Auto Detector" :reqs ((emacs (24)) (nadvice (0 3))) :kind tar :archive "melpa" :dir nil :extras ((:commit . "a5fd4e326a0607acc3776c11f41826e60b6486c6") (:authors ("Qichen Huang" . "unicad.el@gmail.com")) (:maintainers ("Qichen Huang" . "unicad.el@gmail.com")) (:maintainer "Qichen Huang" . "unicad.el@gmail.com") (:keywords "i18n") (:url . "https://github.com/ukari/unicad")) :signed nil)))
      package-install(unicad)

Related files: https://gist.github.com/QiangF/61b2e3173cabde9bca8afdba5a9d56db

**Comment by tarsius** [comment]
Since `<PACKAGE>-autoload.el` are generated by `package.el`, from code in `<PACKAGE>.el`, the tools by used by MELPA to build a package for `<PACKAGE>`, most likely is not involved in this at all. (Yes, that is a lot of "package" :grin:.) This is therefore a support request about something unrelated and since nobody answered by now, I am closing this.
