### ISSUE TITLE
Notice: download stats might be temporarily incorrect

### ISSUE THREAD

**Issue by purcell** [melpa/melpa#8708]
I'm doing some work behind the scenes to change how we maintain our download stats, and they're not currently getting updated on the server as a result. I'll fix this in the next few days, apologies for any disruption!

/cc @milkypostman @riscy @tarsius

**Comment by purcell** [comment]
Some background... This is mostly an indulgence on my part: I'm trying out switching from our 7.5GB + 1.4GB sqlite databases full of download stats (which have admittedly been just fine) to using parquet files containing the downloads for each original logfile. Those files can then be queried en-masse using duckdb, quickly, without any separate database store on disk. My theory is that it will save space, and there's no need to do clever normalisation when we insert things — you simply rip the downloads out of each web server log file into parquet, then query flexibly later. Basically a fun experiment. If the results suck for unforeseen reasons then I'll walk this back.

**Comment by purcell** [comment]
Okay, this is live and updating again now, every half hour:

* Stable: 1.3GB logs => 111M parquet files (~1800), saves 1.3GB
* Regular: 11GB logs => 1.9GB parquet files (~3600), saves 5.5GB

Querying takes about a minute for regular MELPA, a bit longer than I hoped, but it's pretty efficient. I might consider merging some of the historical logs together by month or year, so that there are fewer resulting parquet files to scan, which I think would speed things up.

What's nice is that if the parquet files disappear, the stats will backfill automatically, so they are disposable as long as we keep the logs around.

**Comment by purcell** [comment]
TBH, for our current querying use case it would be equivalent (and even more space efficient) if we just wrote a JSON summary of download counts for each logfile, then summed them up (which, again, would be quite easy using duckdb). Where the parquet files would help would be deduplication – which isn't necessary now anyway – or summarising by time bucket of package version.

**Comment by purcell** [comment]
I did that latter change too, so storage is *way* down, and totals are faster. I wrote a README in the logprocessor dir to explain the shenanigans there: https://github.com/melpa/melpa/blob/master/docker/logprocessor/README.md

**Comment by milkypostman** [comment]
Really cool stuff Steve. Thanks!

**Comment by shg** [comment]
It seems that the DLs have not been counted up for about 2 weeks.

**Comment by milkypostman** [comment]
Fixed.
