### ISSUE TITLE
leaf isn't updated: shows commit fce337 on Aug 3, instead of 466e12 on Aug 3

### ISSUE THREAD

**Issue by jf** [melpa/melpa#8771]
as per subject. I'm not entirely certain about the update mechanism; but given my reading of `Automatic updates - new commits result in new packages` on melpa.org, I'm expecting MELPA to have picked up the later [466e12](https://github.com/conao3/leaf.el/commit/466e12a4161fdee53bca60a786a460b4680255f1) already by now. Is there any documentation regarding how updates are detected / managed?

**Comment by akirak** [comment]
@jf That must be because those newer commits are only documentation updates; MELPA ignores commits that don't change source code.

**Comment by jf** [comment]
I see! that makes sense. Thank you!

**Comment by akirak** [comment]
@jf Could you close this issue?

**Comment by jf** [comment]
sure. My apologies.
