### ISSUE TITLE
the download odometer is not working

### ISSUE THREAD

**Issue by petermao** [melpa/melpa#8777]
not a huge problem, I just noticed that the DL number for dash is starting to look very familiar.

**Comment by milkypostman** [comment]
Thanks for filing. I'm wondering if this is related to changes @purcell made recently. I'll have a look tomorrow evening if he doesn't swoop in first.

**Comment by milkypostman** [comment]
Can you verify that things are better now? I think the process wasn't running.

**Comment by milkypostman** [comment]
Verified that things are working on our end. Watched the web logs go by and the totals updated.

**Comment by purcell** [comment]
Hmm, sorry, I wonder if I left it stopped after the last round of tweaking a few weeks back. Thanks for checking, @milkypostman.
