### ISSUE TITLE
[largely Eldev-specific] how to distribute different package versions that require different Emacs versions

### ISSUE THREAD

**Issue by doublep** [melpa/melpa#8825]
I'd like to drop support for old Emacs versions from Eldev, but don't want to break it for downstream users. I.e. (especially for CI) I'd prefer that Eldev would still be able to bootstrap itself on Emacs 24.4 and up, just like now, and then perform the usual commands, like testing the project. For that I'd envision that the bootstrap script would simply install different packages — 1.8 (1.x) if executed on an ancient Emacs and 2.0 (2.x) if executed on, say, Emacs 27+.

Some brief testing of Emacs package system suggest that it is not able (as always) to cope with that. I.e. even if package archive would provide two versions of the same package, one running on given Emacs version, one requiring a later version, Emacs is not able to pick a proper version. The test was: I created a local PA with package X 1.0 without any dependencies at all, and X 2.0 requiring Emacs 29. Emacs 28 still couldn't install X from it, complaining that it required Emacs 29, even though it could install X 1.0. Oh well...

So, the question of if it is possible to make MELPA provide two versions of a package seems pointless anyway.

The only other solution I could think of would be to clone recipe for Eldev as e.g. `eldev-v1` and fix it to certain branch, while leaving the "normal" recipe track `master`. And then make the bootstrap script install either `eldev` on newer Emacs or `eldev-v1` if executed on old versions.

What do you think about it? Or can you think of a better solution?

**Comment by tarsius** [comment]
So when a few users got upset that Magit 2.0 didn't behave exactly like Magit 1.4, I setup a separate package archive for the old version.

To do that clone the Melpa repository, adjust the recipe of your package and build it. Copy the relevant files to your webpage and add instructions on how to add that archive and on how to pin that package to that archive (if *think* the latter is possible).

**Comment by doublep** [comment]
That doesn't quite apply in my case. It is typically used in CI (e.g. with GitHub actions), to test with various Emacs versions supported by the project. E.g. Magit currently works on Emacs 25+, so hypothetically would run CI tests on Emacs 25-29. If latest version of Eldev no longer supports Emacs 25, it cannot be installed for that CI run.

Eldev is bootstrapped by a small shell script that installs latest available stable version of the package from MELPA. This means that either I need to support Emacs 24.4 and up sort of forever, or change bootstrapping procedure somehow. I want it to stay fully automatic, so that users don't need to configure anything or pin packages to archives — especially on CI (which implies non-interactive use) users wouldn't even have control over that.

It seems that there are three ugly (and not all working) options:

1. Use MELPA for latest Eldev, use a different PA if Emacs is too old (this is basically what you have proposed; in principle, bootstrapping script is "smart enough" to switch like that);
2. Have MELPA provide packages `eldev` (latest version) and `eldev-1` (latest release in branch 1.x). This is what I proposed initially.
3. Have MELPA provide at least two different versions — this is apparently pointless, as Emacs cannot correctly handle such setup anyway.

Would you consider option 2 (requires changes on MELPA side), or should I go with 1?

**Comment by tarsius** [comment]
>     2. Have MELPA provide packages `eldev` (latest version) and `eldev-1` (latest release in branch 1.x). This is what I proposed initially.

I go to great lengths to ensure that all features are only provided by a single package in Melpa (and the Emacsmirror). If we added `eldev-1`, then I would have to add all kinds of special-cases to `package-build.el` (and `emir.el`), and eventually I would have to turn to those special-cases into proper support for "multiple-versions of the same package". This would be a lot of work, and while for this package in particular it might makes sense, this is not something that we would want to allow for just any package. So I would be implementing all this for this one package (and maybe some similar CI packages).

I'm afraid I don't have the time and motivation to do that.

> Would you consider option 2 (requires changes on MELPA side), or should I go with 1?
>
> Use MELPA for latest Eldev, use a different PA if Emacs is too old (this is basically what you have proposed; in principle, bootstrapping script is "smart enough" to switch like that);

Yes please do that. I also expect that it much less work to do it there.
