### ISSUE TITLE
Package-Requires syntax for alternative requirements

### ISSUE THREAD

**Issue by Boruch-Baum** [melpa/melpa#8830]
I'm updating  a package to support alternative backends: either mpv.el or empv.el. How do I reflect that in the "Package-Requires:" header? Can I just use a simple 'or' in the list?

**Comment by tarsius** [comment]
Unfortunately `package.el` does not support that. If you care a lot about this feature, you should bring it up on the emacs-devel mailing list, but do some research first; most likely this has been discussed before.
