### ISSUE TITLE
`tuhdo/xwidgete` repo does not exist

### ISSUE THREAD

**Issue by ayys** [melpa/melpa#8891]
I am trying to compile melpa and I found that the repo for [xwidgete](https://github.com/melpa/melpa/blame/master/recipes/xwidgete) i.e. http://github.com/tuhdo/xwidgete does not exist anymore. 

I can create a PR to either update the repo location or remove the recipe if that is what's needed.

**Comment by ayys** [comment]
I can see the `xwidgete` package on melpa though, so idk if I am just doing something wrong here.

**Comment by ayys** [comment]
Uh oh, both [recipes/srefactor](https://github.com/melpa/melpa/blob/master/recipes/srefactor) and [recipes/stickyfunc-enhance](https://github.com/melpa/melpa/blob/master/recipes/stickyfunc-enhance) do not exist either because they both belong to `tuhdo` user and that user does not exist on GitHub anymore.

**Comment by ayys** [comment]
I am guessing melpa.org servers have a cache of these repos so they can build fine.

**Comment by tarsius** [comment]
Please contact the author by email and ask them whether they are now publishing repositories elsewhere and what they think should happen to the packages on Melpa.

**Comment by tarsius** [comment]
For now I have updated the recipes to get these packages from the [emacsattic](https://github.com/emacsattic).

**Comment by ayys** [comment]
Thanks for the response. I'll contact them and report back.

**Comment by ayys** [comment]
@tarsius Ok this is super weird, the account @tuhdo is back on github now. Maybe it was banned for a while?
I hope the author can respond here with what happened.

**Comment by tuhdo** [comment]
@ayys yes, it was banned for almost a week because some suspicious login attempt. It took a week for Github support to response and resolve the case.

**Comment by ayys** [comment]
I'm glad it's resolved and things are back to normal. Cheers. I'm closing this issue now.
