### ISSUE TITLE
req-package's repository has been archived

### ISSUE THREAD

**Issue by tarsius** [melpa/melpa#8895]
@edvorg has archived https://github.com/edvorg/req-package, without adding a message about that to the readme. Because that also means that no new issues can be opened in that repository, I am opening one here instead.

@edvorg, why did you archive this package? Does it not work anymore, or do you just personally not use it anymore and thus don't want to maintain it anymore? What should happen to this package on Melpa?

**Comment by edvorg** [comment]
@tarsius I'm sorry I was not aware that this was a rule for archiving repos. Yes, I'm not working on this project for a long time and not feeling like doing so in the future, because moved on to work on other things and I'm not even using emacs these days.

I could un-archive the repo and push a note into readme before archiving it again. Is it a free format or there is some template that I should use?

I'm not sure what should happen to package on melpa tho, please advise 🙏🏻

**Comment by tarsius** [comment]
If you think that there's a good chance that this still works and has users, then we could move it to the [Emacs orphanage](https://github.com/emacsorphanage). That way its team can take care of handing it over to a new maintainer, in the event that someone volunteers. We would also look at user contributions.

If you want to do that, just transfer the repository to my personal account (@tarsius). That's necessary because you don't have the rights to transfer to @emacsorphanage directly. If you do, tell me about it here because there is only an email notification, which expires after one day, so I am likely to miss that.

**Comment by edvorg** [comment]
@tarsius alright, request sent, please kindly check 🙏🏻

**Comment by tarsius** [comment]
Ahhhh! I haven't clicked the link fast enough. Please initiate another transfer. Sorry about that!

**Comment by tarsius** [comment]
@edvorg Friendly ping!

**Comment by edvorg** [comment]
Hi Jonas, just clicked the abort button, but seems like it needs time to process this action so that I could try to send a new transfer request again

**Comment by edvorg** [comment]
Hello @tarsius , I have made a new transfer request, please have a look

**Comment by tarsius** [comment]
Thanks! I've accepted and moved it to the orphanage. I still have to update Melpa and the Emacsmirror.
