### ISSUE TITLE
benchmark-init-el maintainer appears to have disappeared

### ISSUE THREAD

**Issue by chaosemer** [melpa/melpa#8906]
[benchmark-init-el](https://github.com/dholm/benchmark-init-el)'s maintainer has stopped responding to PRs or issues. There are currently two PRs open that are about ensuring benchmark-init-el builds cleanly on recent Emacs. One was opened six months ago, the other was openned one month ago and both have gotten no replies. I also tried to reach out to the maintainer via email listed on GitHub (dholmster@gmail.com) on January 4th and have gotten no reply and the website listed on GitHub (http://www.dholm.com/) appears to be down. I couldn't figure out any other way to contact the current maintainer @dholm.

Since this is one of the top packages on MELPA (78th percentile), I think there should be an active maintainer. Changes like making sure to run on Emacs 30 and fixing byte compile warnings should getting merged. I would be ok taking over maintenance if that helps.

Also tagging @purcell who was successful in getting @dholm to reply in a [previous PR](https://github.com/dholm/benchmark-init-el/pull/16).

**Comment by tarsius** [comment]
See https://github.com/melpa/melpa/wiki/Unmaintained-Packages-and-Forks. Based on your description of the outstanding issues, I think the bar for pointing Melpa at a fork has not been met (yet?).

**Comment by chaosemer** [comment]
Thanks for the pointer. Also, last night @dholm did merge the Emacs 30 necessary PRs. This is now unneeded.
