### ISSUE TITLE
Package 4clojure seems 'secondarily' hijacked

### ISSUE THREAD

**Issue by Boruch-Baum** [melpa/melpa#8921]
I can't really figure out exactly what package 4clojure was originally meant to do. It seems that the intent was to interface to a Q&A website for the clojure language. However, that website, [www.4clojure.com](www.4clojure.com) seems to now be a Vietnamese-language site that aggregates Android games.

The package seems to have originally been added to MELPA in year 2013 (#1061) and was re-hosted in year 2019/2020 (#6555)

Some of the people who seem to have been involved are: @losingkeys, @macavirus, @abend.

**Comment by arcli** [comment]
This is correct. The 4clojure package now serves no purpose since 4clojure.com has been retired.

**Comment by tarsius** [comment]
Given the name "foreclosure", this was to be expected. :grin:
