### ISSUE TITLE
Symbol’s function definition is void: package--prepare-dependencies

### ISSUE THREAD

**Issue by nameiwillforget** [melpa/melpa#8929]
I'm sorry if this is an error on my part. I was trying to contribute my first MELPA package and while testing the build as in the Contribution guide using `package-build-create-package` I encountered an error:
```
• Building package avy-act-on-distance (from https://gitlab.com/nameiwillforget/avy-act-on-distance)...
Updating /home/alex/projects/MELPA/melpa/working/avy-act-on-distance/
Checking out ff4554fa5507134dfcd23a2badbc56a106e8535b
if: Symbol’s function definition is void: package--prepare-dependencies
```
Is this because the syntax of my `.el` file or my recipe is wrong? The recipe is
```
(avy-act-on-distance
 :fetcher git
 :url "https://gitlab.com/nameiwillforget/avy-act-on-distance")
```
And the beginning of the `.el` file is
```
;;; avy-act-on-distance.el --- Commands that let avy act from a distance  -*- lexical-binding: t; -*-

;; Copyright (C) 2024  Alexander Prähauser

;; Author: Alexander Prähauser <ahprae@protonmail.com>
;; Package-Requires: ((avy "0.5.0") (back-button "0.6.8"))
;; Version: 1.0
;; Keywords: tools, convenience
;; URL: https://gitlab.com/nameiwillforget/avy-act-on-distance
```

**Comment by nameiwillforget** [comment]
Alright, I tried to build a recipe for a package I've already installed from melpa and got the same error. I also tried to clone melpa again and to build a recipe from there, but I got the same `package--prepare-dependencies is missing` error. I tried to google `package--prepare-dependencies` but found no results. What is going on?

**Comment by tarsius** [comment]
It's-a merged.

**Comment by purcell** [comment]
Thanks @tarsius! 🙏
