### ISSUE TITLE
readline-complete's repository has been archived

### ISSUE THREAD

**Issue by tarsius** [melpa/melpa#8945]
@monsanto has archived https://github.com/monsanto/readline-complete.el, without adding a message about that to the readme. Because that also means that no new issues can be opened in that repository, I am opening one here instead.

@monsanto, why did you archive this package? Does it not work anymore, or do you just personally not use it anymore and thus don't want to maintain it anymore? What should happen to this package on Melpa?

**Comment by monsanto** [comment]
@tarsius I just archived it because I'm busy with other things in life and didn't want anyone to get the expectation that I was going to work on it anymore. I wrote RLC ~12 years ago as part of my personal emacs configuration and only put it on GH when it was more-or-less done--note that there have only been 16 commits in the history of the project, most of them just me merging random stuff.

I don't mind reopening it if that makes you feel better about having it on melpa, but my involvement would just be to merge whatever PRs people on a "yeah, that looks OK" basis.

**Comment by Boruch-Baum** [comment]
I don't have package `readline-complete` installed (this is the first I've heard of it), yet have several forms of auto-complete in all my shell/term buffer variants (emacs 29).

Using \emacs -Q, M-x `shell` gives me tab completion in a \*Completions\* buffer. M-x `term` gives the completions as in a terminal.

In my 'tricked out' emacs -nw, M-x `shell` gives me completions using a popup menu, in the style of `company` back-ends. I don't know what feature or package is performing the completions. I poked around MELPA and found that there exists a package [emacs-native-shell-complete](https://melpa.org/#/company-native-complete) that seems to perform this feature without the `company`-style popups, but I don't have that package installed either.

**Comment by tarsius** [comment]
@monsanto Keeping the repository open doesn't necessarily imply that you will keep on improving a project. You might occasionally get feature requests that you have to decline, which you have to decline. You could reduce the likelihood of that happening too often, by adding a note about "maintenance mode" to the readme.

I would appreciate it if you could reopen and then manage as you outlined. Alternatively you could also transfer it to the [Emacsorphanage](https://github.com/emacsorphanage), where I (with a little help from some others), do this work for ~100 packages. Of course that's a lot, so I prefer if authors keep doing the little maintenance work that their aging packages still cause.

@Boruch-Baum I am aware there are alternatives. That's not really the question here. (Besides, I find the anti-NIH of this package intriguing.)

**Comment by Boruch-Baum** [comment]
On 2024-03-04 02:21, Jonas Bernoulli wrote:
>    ***@***.*** I am aware there are alternatives. That's not really
>    the question here.

OK.

>    (Besides, I find the anti-NIH of this package intriguing.)

I'm now intrigued to know what "NIH" means!

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by monsanto** [comment]
OK, I'll reopen it.

**Comment by tarsius** [comment]
Thanks!
