### ISSUE TITLE
Latest update of cc-isearch-menu builds but is not distributed

### ISSUE THREAD

**Issue by kickingvegas** [melpa/melpa#8946]
An update of cc-isearch-menu successfully builds according to the build log. (cc-isearch-menu-20240302.21)
However, on the MELPA page it shows that 20240221.742 is the current version. When I try to install it I get an error message saying that

package--with-response-buffer-1: http://melpa.org/packages/cc-isearch-menu-20240221.742.tar: Not found

https://melpa.org/#/cc-isearch-menu

Please provide guidance.

**Comment by linuxmetel** [comment]
[https://melpa.org/#/company](company) cannot be downloaded, neither.

**Comment by kickingvegas** [comment]
As of Sat Mar  2 10:43:35 2024, cc-isearch-menu package is consistent with build log, allowing for install of `cc-isearch-menu-20240302.21.tar`. That said, issue still remains that updating a package repo does not fully update its distribution on MELPA, as corroborated by @linuxmetel.

**Comment by kickingvegas** [comment]
Hello @tarsius! Thanks for the input. To clarify, I think this might be an intermittent issue, where updating a repo (in this case `cc-isearch-menu` to v1.1.0) will:

1.  Trigger a build and be successful at building its artifacts (e.g. `cc-isearch-menu-20240302.21.tar`)
2.  However the artifacts of that build are not distributed so that is available in Emacs via `package-list`.
    -   What is listed on <https://melpa.org/#/cc-isearch-menu> is `cc-isearch-menu-20240221.742.tar`
    -   Updating the package from Emacs at that time will result in a error with this warning message:
        
            package--with-response-buffer-1: http://melpa.org/packages/cc-isearch-menu-20240221.742.tar: Not found

Perhaps there is some latency, but it seemed like nearly a day had passed with the build artifact not being available, so I tried to induce a subsequent update by updating the `README.org` which also did not work. A later change to `cc-isearch-menu.el` (v1.2.0) did apparently work.

Good to know that only files included in the tarball will trigger a new snapshot.

Hopefully this provides more clarity and thanks again!

**Comment by tarsius** [comment]
> I tried to induce a subsequent update by updating the `README.org` which also did not work.

`README.org` is not included in the tarball, so what I just said applies:

> Not[e] that Melpa only builds a new snapshot if a file that would be included in the tarball is actually modified (and only up to the latest commit that touches such a file).


>    -   Updating the package from Emacs at that time will result in a error with this warning message:
>       
>            package--with-response-buffer-1: http://melpa.org/packages/cc-isearch-menu-20240221.742.tar: Not found

You need to `M-x package-refresh-contents`. The current version of that file contains:

```
 (cc-isearch-menu . [(20240304 1917) ((emacs (29 1))) "A Transient menu for isearch" tar ((:commit . "4b983f518485380604167401387fe0128fb9e0af") (:authors ("Charles Choi" . "kickingvegas@gmail.com")) (:maintainers ("Charles Choi" . "kickingvegas@gmail.com")) (:maintainer "Charles Choi" . "kickingvegas@gmail.com") (:keywords "wp") (:url . "https://github.com/kickingvegas/cc-isearch-men"))])
```

**Comment by kickingvegas** [comment]
@tarsius Understood about the README.org not being included as a build trigger.

I did actually try to call `package-refresh-contents` which still didn't help things at the time. That said, I'll close this issue and be on the lookout if this happens again.
