### ISSUE TITLE
Missing package archives for packages: devdocs, modus themes

### ISSUE THREAD

**Issue by aboualiaa** [melpa/melpa#8948]
specifically these links:

https://melpa.org/packages/modus-themes-20240227.715.tar
https://melpa.org/packages/devdocs-20231127.1905.tar

the archives are not found.

**Comment by linuxmetel** [comment]
maybe same issue: #8946

**Comment by jacobHclarkson** [comment]
I am also getting 404s for these packages:

- https://melpa.org/packages/rust-mode-20240301.229.tar
- https://melpa.org/packages/org-rich-yank-20240201.921.tar
- https://melpa.org/packages/company-20240301.346.tar
- https://melpa.org/packages/devdocs-20231127.1905.tar
- https://melpa.org/packages/company-20240301.346.tar
- https://melpa.org/packages/company-20240301.346.tar
- https://melpa.org/packages/company-20240301.346.tar
- https://melpa.org/packages/company-20240301.346.tar
- https://melpa.org/packages/company-20240301.346.tar

**Comment by milkypostman** [comment]
Company is at 20240302.1508 right now. Digging into why the website is not correct.

**Comment by milkypostman** [comment]
Something failed with syncing due to this error,

```
Assertion failed: (plist-get plist :repo), (:fetcher codeberg :url "https://codeberg.org/ashton314/nordic-night")
```

**Comment by milkypostman** [comment]
Looks like 2d0973e00821f06bf7ad427df4bae008ab0519f3 broke the build.

It should be fixed now.

**Comment by milkypostman** [comment]
cc: @tarsius for visibility

**Comment by tarsius** [comment]
So from the above I gather, this mistake in one receive broke building all packages. :scream:

I'll have to teach `package-build.el` to continue after an error like that.

**Comment by milkypostman** [comment]
It's actually building archive-contents that broke.

**Comment by aboualiaa** [comment]
@milkypostman Thank you! How long does the website need to recover?

**Comment by tarsius** [comment]
> It's actually building archive-contents that broke.

I'll look into that part then. :grinning: 

Note to self: also check if the faulty commit was auto-generated by emir.

**Comment by tarsius** [comment]
> It's actually building archive-contents that broke.

Fixed.

> Note to self: also check if the faulty commit was auto-generated by emir.

The mistake was not automated.
