### ISSUE TITLE
Tarballs for packages built(?) on/around February 29th are 404'ing

### ISSUE THREAD

**Issue by squid-lee** [melpa/melpa#8949]
I went to upgrade emacs packages today, and got 404s on the tarball for a few of them:

http://melpa.org/packages/yaml-pro-20240229.602.tar / https://melpa.org/#/yaml-pro
http://melpa.org/packages/rust-mode-20240301.229.tar / https://melpa.org/#/rust-mode

It may not be leap year related though:
https://melpa.org/#/org-rich-yank / https://melpa.org/packages/org-rich-yank-20240201.921.tar gives me a 404

**Comment by milkypostman** [comment]
see #8948
