### ISSUE TITLE
Fuco1 archived two old packages

### ISSUE THREAD

**Issue by tarsius** [melpa/melpa#8973]
@Fuco1, I've noticed that you have archived these two packages

- [x] https://github.com/Fuco1/ETable
- [x] https://github.com/Fuco1/neon-mode

without adding a note about why you are doing that. Since you are using Markdown in you readmes, I recommend you use a `> [!NOTE]` as described at https://github.com/orgs/community/discussions/16925. Please briefly explain why you are archiving the repository. Might it nevertheless still be of interest to others?

And please let us know here explicitly, whether these packages should be removed from Melpa.

**Comment by Fuco1** [comment]
I think ETable wasn't ever used by anyone and it's not really finished, even though it is somewhat usable.  neon-mode technically works fine, I guess I can unarchive it. I'm doing a cleanup now going through all the thousands of open issues on my packages trying to respond / fix bugs that I neglected lately.

I will add a note to ETable.

**Comment by Fuco1** [comment]
Done.  Should I make a PR removing ETable?

**Comment by tarsius** [comment]
Thanks!

> Should I make a PR removing ETable?

I've just removed it myself.
