### ISSUE TITLE
Dunn archived an old package 

### ISSUE THREAD

**Issue by tarsius** [melpa/melpa#8982]
@dunn, I've noticed that you have archived this package

- [ ] https://github.com/dunn/homebrew-mode

without adding a note about why you are doing that. Since you are using Markdown in you readmes, I recommend you use a `> [!NOTE]` as described at https://github.com/orgs/community/discussions/16925. Please briefly explain why you are archiving the repository. Might it nevertheless still be of interest to others?

And please let us know here explicitly, whether these packages should be removed from Melpa.

**Comment by dunn** [comment]
oh, i'd forgotten that was even in melpa.

i don't use it anymore, and haven't maintained it for years; given how much homebrew has changed since, i would be surprised if it works anymore.

so yes, unless anyone else still uses it and wants to take over maintenance, it should be removed.

**Comment by tarsius** [comment]
Thanks. Makes sense.

I've removed the recipe.

**Comment by dunn** [comment]
thank you!
