### ISSUE TITLE
Question about Versioning in Texinfo Documents

### ISSUE THREAD

**Issue by yewscion** [melpa/melpa#9046]
Hello!

Sorry if this is answered somewhere, but I've been unable to find it if it is. I currently have my emacs lisp repos versioned the same way as everything else, using a version.texi.in file that replaces a macro with the version defined in my configure.ac file. However, this does not work when using MELPA to process the texinfo files, as the configure script is never run.

Is there a way to utilize my current setup with the MELPA repo style recipe, or do I need to look into some kind of preprocessing in order to do that? Currently, my docs are simply never built, as they always error.

Thanks for Your time!

**Comment by milkypostman** [comment]
Sorry for the delayed response.

We don't currently support running any code on the server to preprocess versions or anything like that. Our versioning is also based on commit date and time.

I'd suggest checking out the MELPA repo and experiment with building your package and see what package it produces.
