### ISSUE TITLE
Remove or replace j-mode with a fork

### ISSUE THREAD

**Issue by Stebalien** [melpa/melpa#9055]
`j-mode` is currently re-defining the built-in `if-let` macro, breaking any other package that uses it.

PR to fix (https://github.com/zellio/j-mode/pull/26) has been open for two years, but the project hasn't seen any movement in a while.

cc @zellio are you still interested in maintaining this package?
cc @LdBeth I see you seem to be maintaining a fork and have expressed interest in maintaining this project (https://github.com/zellio/j-mode/issues/28).

**Comment by zellio** [comment]
This probably needs to be rewritten at some point, the code is old and unloved but I've merged the 29 fix

**Comment by Stebalien** [comment]
Ah, thank you!

**Comment by Stebalien** [comment]
(but I would check-in with @LdBeth if you're interested in a co-maintainer).
