### ISSUE TITLE
Cannot download package from melpa

### ISSUE THREAD

**Issue by webloginwu** [melpa/melpa#9069]
Error message:

Failed to download ‘(melpa . https://melpa.org/packages/)’ archive.
I use below settings

`(require 'package)
(add-to-list 'package-archives '(("melpa" . "https://melpa.org/packages/")
                                 ("melpa-stable" . "https://stable.melpa.org/packages/") 
                                 ("gnu" . "https://elpa.gnu.org/packages/")
                                 )
             t)
(package-initialize)`
1. elpa works
curl -L https://elpa.gnu.org/packages/
2. but melpa don't work

curl -L https://melpa.org/packages/
```
<html>
  <head>
    <title>Package Listing</title>
    <meta http-equiv="refresh" content="5; url=/" />
  </head>
  <body>
    <h1>Package Listing</h1>
    <p>
      Please see the <a href="/">main page</a> for a full package
      listing. You will be redirected automatically.
    </p>
  </body>
</html>
```

**Comment by alphapapa** [comment]
MELPA is working fine.  You likely have a connection problem, especially if you are behind a government-enforced firewall.

Regardless of that, this is not a useful bug report.  See http://catb.org/~esr/faqs/smart-questions.html for how to ask for help in an effective way.

**Comment by webloginwu** [comment]
@alphapapa 
finally I found the root cause, 
I check the value of variable package-archives using C-h v
It is:
```
Value:
(("gnu" . "http://elpa.gnu.org/packages/")
 ("nongnu" . "http://elpa.nongnu.org/nongnu/")
 (("melpa" . "https://melpa.org/packages/")
  ("gnu" . "https://elpa.gnu.org/packages/")))

Original value was 
(("gnu" . "http://elpa.gnu.org/packages/")
 ("nongnu" . "http://elpa.nongnu.org/nongnu/"))
```
it is not right.
