### ISSUE TITLE
the connection has timed out

### ISSUE THREAD

**Issue by wemotions** [melpa/melpa#9072]
I can't access the MELPA website (https://melpa.org/#/). When I try to access the site, the browser reports that it is impossible to establish a connection to the server. The problem has been observed for several days and only from the network 91.108.28.0/28.
Please review the configurations and any potential blockages affecting the website to restore access.

Browser message:  The server at melpa.org is taking too long respond

![image](https://github.com/melpa/melpa/assets/93228239/eded0c3c-9b3d-4f11-9760-be1450fe0df5)

**Comment by milkypostman** [comment]
https://downforeveryoneorjustme.com/melpa.org says all is well. 

Are you behind a firewall or something? Did you run some scripts against the server recently to get throttled?

**Comment by wemotions** [comment]
Access to the site has been restored.
Thank you for creating the action.
