### ISSUE TITLE
latest version of helm package (helm-20240624.615) is broken

### ISSUE THREAD

**Issue by lwiechec** [melpa/melpa#9077]
It looks like the [MELPA recipe](https://github.com/melpa/melpa/blob/master/recipes/helm) is excluding `helm-lib.el` which contains function `helm-local-directory-files` that is used in other calls, including opening files and listing directories.

**Comment by thierryvolpiatto** [comment]
Thanks @tarsius . The Melpa recipe haven't changed since years, it excludes helm-lib and others because it uses as dependency helm-core package which contains itself these files (helm-lib, helm-core..). So I hardly see how it wouldn't work.

**Comment by tarsius** [comment]
@lwiechec maybe you have accidentally removed `helm-core` and need to reinstall it.

**Comment by lwiechec** [comment]
@thierryvolpiatto @tarsius thank you and apologies - I should've checked more thoroughly.
