### ISSUE TITLE
markdown-mode incompatible with RHEL8 standard emacs

### ISSUE THREAD

**Issue by jlqibm** [melpa/melpa#9120]
Some of us use RHEL8 in our work life, which still packages emacs-26.  Unfortunately, elpa doesn't package markdown-mode, and both melpa and melpa-stable package versions of markdown-mode that require at least emacs-27.

Is it possible to get the older version 2.5 of markdown-mode packaged to be available as an alternative?

**Comment by milkypostman** [comment]
Sorry but I think you'd need to manually install this to fix your problem.

We have discussed maintaining old versions but the main MELPA repo is for unstable bleeding edge versions and stable is best effort. 

I'm not sure that package.el even would allow multiple versions in the repo.

Im sorry I don't have a better answer for the RHEL8 users.
