### ISSUE TITLE
Failed to download 'melpa' archive

### ISSUE THREAD

**Issue by Strelok2013** [melpa/melpa#9145]
What it says in the title, I can't seem to download the melpa archive. I've tried the gnutls fix and using http instead of https.
Running emacs with -Q and running eval-buffer on the code below works.

init.el:
```
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org.packages/") t)

(package-refresh-contents t)
```

I'm running on void linux and I installed emacs using the package manager xbps.

**Comment by milkypostman** [comment]
`melpa.org.packages/` is not correct. It should be `melpa.org/packages/`

You can copy the snippet from it getting started page: https://melpa.org/#/getting-started

**Comment by Strelok2013** [comment]
Its always a typo like this that breaks things. Thank you for catching that :)
