### ISSUE TITLE
New `-pkg.el` header causing `lisp-data-mode` undefined in CI for older versions of Emacs?

### ISSUE THREAD

**Issue by greghendershott** [melpa/melpa#9193]
Although I'm still trying to understand, exactly, I think this recent change:

https://github.com/melpa/melpa/commit/abb5177f6dd6a181fa24654778ff9f440f1964e7#diff-c0fbc288d4e9bf23854f53311d59620842f0870d0c443ced778504e44e681d50R1023

is the cause of errors I'm suddenly getting like this:

https://github.com/greghendershott/racket-mode/actions/runs/11093543327/job/30819952750#step:6:26

when running CI on older versions of Emacs.

(I test my package against older version of both Emacs and the Racket language.)

---

As a mitigation, probably my CI script "just" needs to `--eval` some `defalias` of `lisp-data-mode` to `normal-mode`.

So I'll work on that.

And I understand the `mode:` portion of the new header is probably very convenient for people who inspect/edit `-pkg.el` files all day.

So... maybe this issue is just a heads-up --- that the change will cause some breakage that probably wasn't expected --- and should be closed. But I wanted to point it out, especially in case you see some other/better approach.

**Comment by greghendershott** [comment]
p.s. I thought I'd made a GitHub link directly to the line in that commit, but apparently I didn't.

It's the change at line 1022 in the new `package-build.el`:

```elisp
      (insert
       ";; -*- mode: lisp-data; no-byte-compile: t; lexical-binding: nil -*-\n")
```

**Comment by greghendershott** [comment]
For me, [so far this works](https://github.com/greghendershott/racket-mode/commit/8d2d63a5a410ad560c55335356cb1d4e947a2b01): `defalias` of `lisp-data-mode` to `emacs-lisp-mode` (not to `normal-mode`, 25.1 doesn't like that).

Again, probably you can/should just close this issue -- but hopefully it can help anyone else doing CI against older versions of Emacs.

**Comment by tarsius** [comment]
Thanks for letting me know!

It will take a few hour for all packages to be rebuild.

**Comment by greghendershott** [comment]
Oh! That was more than I expected. Thank you for that (as well as all your contributions to seemingly every corner of the Emacs ecosystem :smile:).
