### ISSUE TITLE
Package archive not updated

### ISSUE THREAD

**Issue by sarg** [melpa/melpa#9196]
Latest version reported on the site is [20240928.843](https://melpa.org/packages/anki-editor-20240928.843.tar), however today is 20240930 and there were new packages added since then. Build status tooltip shows that latest build was 2 hr ago.

Specifically,  this package is still not present in the list: https://github.com/melpa/melpa/commit/f7db042667dbf2870758d16367ba99589b0fe920

**Comment by tarsius** [comment]
On it, though because locally `archive-contents` is updated as expected, and I cannot get my hands on any logs from `make summarise`, where I believe the error occurs, the debugging is somewhat difficult.

**Comment by tarsius** [comment]
Due to the value of `:maintainer` being malformatted, the `json` (a requirement of `summarise`) hangs. (I did not run `summarise` locally, because that also depends on the `html` target, which needs `erb`, which I so far avoided installing locally.

In a few hours we'll now if this did the trick.
