### ISSUE TITLE
RFC: Consolidating Casual Packages on MELPA

### ISSUE THREAD

**Issue by kickingvegas** [melpa/melpa#9199]
I am currently considering a proposal to consolidate the current set of Casual packages (now at 13) into four packages for distribution on MELPA. 

Details of this proposal can be found at https://github.com/kickingvegas/casual-suite/discussions/50#discussioncomment-10814717

This will require changes to the Casual recipes on MELPA, the bulk of which will be removing them and using the recipe key `:old-names` to support redirects.

This issue is a request for comment (if any) on this proposal from MELPA's perspective, particularly with regards to feasibility and possible concerns that I have not considered.

Thanks and best regards -

Charles

**Comment by tarsius** [comment]
It's getting late, so a proper response will have to wait until tomorrow, but since I have spend the last few hours responding to "RFCs", some very quick feedback.

@minad's comment sounds pretty much exactly like what I would have suggested. Your response sounds ... well, quite a bit more verbose :grinning:. And like agree with his suggestions but additionally work out some details. I'll have to study that properly -- after I get some sleep. :sleeping:

**Comment by tarsius** [comment]
> Less user effort in installing a multitude of packages.

I appreciate that. As someone who installs packages by cloning repositories (with the help of my [`borg`](https://github.com/emacscollective/borg)) I wasn't happy about having to clone so many repositories. I would have preferred the less aggressive split you are now suggesting, but wasn't sufficiently inconvenienced to actually urge you to do that.

> The current set of Casual packages superseded by `casual` shall be obsoleted and removed on MELPA upon publication of the new `casual` package on MELPA.

You could also use transient (ha!) packages, as I do for "friends of `emacsql`", see https://melpa.org/#/?q=emacsql and follow links to learn the implementation details.

I see you are already planning something similar to that:

> (4) The new `casual` package shall provide a means of removing the packages it supersedes.
> (5) Superseded packages that are still installed shall issue a warning message to upgrade to the new `casual` package.

The main difference seems to be that you intend to remove the "superseded packages that issue warnings" early on. Your approach won't help users who don't update frequently enough and thus miss the window when they would get to see those warnings with your approach. (Of course we don't want to keep the transient packages around forever, so some people are bound to miss the warnings (though you plan to tackle that with (4) it seems). I'll probably keep the transient `emacsql-*` packages around for another two months or so.)

**Comment by kickingvegas** [comment]
[Decision made](https://github.com/kickingvegas/casual-suite/discussions/50#discussioncomment-10939491) to move forward with consolidation plan. 

PR #9218 submitted to add `casual` package to MELPA.
