### ISSUE TITLE
should emacs-slack be orphaned?

### ISSUE THREAD

**Issue by ag91** [melpa/melpa#9226]
The author added a deprecation note on their package: https://github.com/yuya373/emacs-slack.
Is the usual procedure to move the package to the orphanage?

I am maintaining a fork for myself which attempts to fix some of the major issues that were reported on their repository: https://github.com/ag91/emacs-slack

I would be happy to forward my changes after testing them on my side so that others could benefit, 
although I have not yet refreshed README and docs (so far I have mostly used the fork myself)

**Comment by tarsius** [comment]
> Is the usual procedure to move the package to the orphanage?

Yes, see https://github.com/melpa/melpa/wiki/Unmaintained-Packages-and-Forks. (Well, it doesn't actually mention the orphanage, but it does mention what should be tried first.)

**Comment by ag91** [comment]
thanks @tarsius for your suggestion, I contacted the maintainer and he just created an organization and added me as a member. That is the best outcome I think :)

**Comment by tarsius** [comment]
I've updated the Melpa recipe.
