### ISSUE TITLE
Unpublish use-package and friends?

### ISSUE THREAD

**Issue by wyuenho** [melpa/melpa#9238]
use-package is now being developed in Emacs core and published on Elpa, the version on Github in which the Melpa recipes pull from has not been tagged or updated for over 1.5 years, meanwhile 2 new versions have been published on Elpa. This means anyone using Melpa instead of Stable Melpa cannot get the latest use-package from Elpa as the date version is shadowing the semver. Should we remove them from Melpa or do something else instead? cc @jwiegley

Affected packages:

- https://melpa.org/#/bind-chord
- https://melpa.org/#/bind-key
- https://melpa.org/#/use-package
- https://melpa.org/#/use-package-chords
- https://melpa.org/#/use-package-ensure-system-package

**Comment by jwiegley** [comment]
Yes, we should remove from Melpa. All active development on use-package now happens within Emacs core, not externally anymore.

**Comment by wyuenho** [comment]
@jwiegley I notice except bind-key and use-package, the other package are not published on Elpa, what should we do with them?

**Comment by jwiegley** [comment]
Hi @wyuenho, can you please rephrase? I didn't understand. Both bind-key and use-package are in Emacs now, and should be removed from Melpa.

**Comment by wyuenho** [comment]
[bind-chord](https://melpa.org/#/bind-chord), [use-package-chords](https://melpa.org/#/use-package-chords) and [use-package-ensure-system-package](https://melpa.org/#/use-package-ensure-system-package) are all published as separate packages on Melpa, they are all pointing to the `use-package` Github repo, but these 3 packages are no where to be found on Elpa, and the Github repo hasn't been updated for years. What's the status with these packages?

**Comment by jwiegley** [comment]
I'm not aware of their status: they were created by others, and I have never used them.

**Comment by wyuenho** [comment]
Ok, let me ask in a different way. What is the status of the [use-package github repo](https://github.com/jwiegley/use-package)? The [Elpa package metadata](https://elpa.gnu.org/packages/use-package.html), is still pointing to the Github repo, but clearly that's not where the latest development is done. Is this just a matter of you forgetting to change the URL package metadata for the `use-package` in Emacs core, and bind-chord, use-package-chord and use-package-ensure-system-package should be considered abandoned and thus move to [emacsorphanage](https://github.com/emacsorphanage)?

**Comment by jwiegley** [comment]
I didn't manage the integration of use-package into Emacs core, so whoever did didn't update it to remove the GitHub page. This all happens by volunteers, I simply haven't deleted the GitHub repository (in case anyone wished to post issues there, for example).

Whether those packages are abandoned now or not, I have no idea. That would require reaching out to the authors to see if they are still intending to maintain them.

**Comment by purcell** [comment]
Hey folks, I've removed `bind-key`, `use-package` and `use-package-ensure-system-package` from MELPA because they are all unambiguously available on ELPA and _not_ developed in that GitHub repo (`use-package-ensure-system-package` is contained in the `use-package` package in ELPA).

As for `bind-chord` and `use-package-chords`, I've kept the recipes, still pointing at the apparently-defunct `use-package` GitHub repo, but perhaps @waymondo would like to extract them to one or two separate repos? It's a bit weird having this mix of non-maintained and maintained code in the same repo.

**Comment by waymondo** [comment]
yeah, i think it makes sense to move `bind-chord` and `use-package-chords` to their own repo now that `use-package` is in emacs core. i will take care of this in the coming week when i get some time and report back here with a PR to update the MELPA references to it.

**Comment by purcell** [comment]
Thanks @waymondo :)

**Comment by waymondo** [comment]
just opened [this](https://github.com/melpa/melpa/pull/9244). i _think_ that's all that's required? lmk if not

**Comment by tarsius** [comment]
> just opened [this](https://github.com/melpa/melpa/pull/9244). i _think_ that's all that's required? lmk if not

Looks good, merged.

Good timing too. I was dealing with these packages in the Emacsmirror just now, and realized I would have to wait for you to update the original repository. Then I came here and saw `waymondo commented 1 minute ago`. :grinning:

**Comment by waymondo** [comment]
my ears were burning as they say!

**Comment by wyuenho** [comment]
I just checked `use-package-ensure-system-package`, it appears it requires `system-package`, which doesn't seem to be developed on Gitlab anymore. The [version on Elpa](https://elpa.gnu.org/packages/system-packages.html) is more recent than [the one on Melpa](https://melpa.org/#/system-packages), which means Melpa's crazy datetime version is shadowing it too. Should we remove it from Melpa as well?

**Comment by wyuenho** [comment]
Thanks everyone!
