### ISSUE TITLE
Make melpa.org a more responsive website?

### ISSUE THREAD

**Issue by jpggithub** [melpa/melpa#9248]
I find melpa.org not very convenient when I read it with my smartphone.
Perhaps the website could be more responsive by adding the following line to the header of each page?

```
<meta name="viewport" content="width=device-width, initial-scale=1.0" >
```
source : https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Responsive_Design#the_viewport_meta_tag

**Comment by purcell** [comment]
Good idea, thanks — I've pushed this and the site should rebuild with the change within the next few hours.
