### ISSUE TITLE
wanderlust 20241111.2133 fails when trying to load a file called 'luna'. Version 20241111.934 works ok

### ISSUE THREAD

**Issue by antoniocorbi** [melpa/melpa#9255]
Hi!

After upgrading today to wanderlust 20241111.2133 if fails to start saying it can't open a file called 'luna' (I can see some (require 'luna) in elmo files).

In another computer I've got still installed wanderlust 20241111.934 and it works ok.

I'm using emacs 29.4 on NixOS 24.11.

**Comment by milkypostman** [comment]
Have you tried reaching out to the wanderlust developer? Looks like it's been abandoned but I'd start at https://github.com/emacsmirror/wanderlust. I'd take a look at the history of that repo.

**Comment by tarsius** [comment]
That's fixed now, but it will take an hour or two for Melpa to get around to building a new package.

**Comment by TanukiMa** [comment]
> Hi!
> 
> After upgrading today to wanderlust 20241111.2133 if fails to start saying it can't open a file called 'luna' (I can see some (require 'luna) in elmo files).
> 
> In another computer I've got still installed wanderlust 20241111.934 and it works ok.
> 
> I'm using emacs 29.4 on NixOS 24.11.

luna.el is included in the flim package.

After reinstalling the flim package, Wanderlust started up successfully in my environment.

M-x package-reinstall flim

**Comment by antoniocorbi** [comment]
> That's fixed now, but it will take an hour or two for Melpa to get around to building a new package.

Bit late, sorry. As you say it does work now.
