### ISSUE TITLE
wanderlust-20241125.2206 fails to install

### ISSUE THREAD

**Issue by antoniocorbi** [melpa/melpa#9259]
Hi,

After the last update to wanderlust trying to install from zero wanderlust-20241125.2206 produces this error:

`package-built-in-p: Lisp nesting exceeds ‘max-lisp-eval-depth’: 1601`

Definitely something is happening to this package after previous update couldn't find 'luna' file and now this.

**Comment by tarsius** [comment]
That's fixed now, but it will take an hour or two for Melpa to get around to building a new package.
