### ISSUE TITLE
`emacsmirror/semi` is too old

### ISSUE THREAD

**Issue by jian-lin** [melpa/melpa#9292]
Currently, the newest commit of upstream `semi` is on [2024-06-06][1].  However, the newest upstream commit of `emacsmirror/semi` is on 2016-08-16.
![image](https://github.com/user-attachments/assets/c7d3caa1-c472-4426-b5a3-457fc7dddaae)

CC @tarsius

[1]: https://github.com/wanderlust/semi/commit/85a52b899ac89be504d9e38d8d406bba98f4b0b3

**Comment by tarsius** [comment]
Thanks for the report!

I've changed the default branch for `semi` on the Emacsmirror to `master`, the up-to-date branch. It will take a few hours for Melpa to pick that up.
