### ISSUE TITLE
Lint package & check for dependencies

### ISSUE THREAD

**Issue by dotemacs** [melpa/melpa#952]
I'm posting this here as I'm not sure where would be the best to discuss this.

I've submitted a few packages and every time I do a bit of head scratching to see if the package conforms to the required format: valid header, closing comment... 

I don't know if you considered it or if I'm just missing it, but how about a Make task or just adding it to the 'recipe/package-name' task, something that checks the formatting of the package and if the dependancies are there?

If this exists and I've not spotted it, then I apologise. 

If you've considered this and decided to go without it, can you point me at the discussion if it's available online?

If this is not in MELPA, I'd like to add it.

Thank you for your time

**Comment by purcell** [comment]
With the advent of package-lint etc., I don't think this is an outstanding MELPA issue.
